### ISSUE TITLE
VSCode: Autocomplete for Astro.* APIs.

### ISSUE THREAD

**Issue by matthewp** [snowpackjs/astro#1026]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Autocomplete doesn't work for `Astro.*`.

### Steps to Reproduce

Should work in both frontmatter script area and in the template.

**Comment by IanVS** [comment]
I believe this is closed by https://github.com/snowpackjs/astro/pull/1068.

**Comment by matthewp** [comment]
Thanks!
