### ISSUE TITLE
Module scripts src relative path not prefixed by `.` is not correctly rewritten during build

### ISSUE THREAD

**Issue by kevinkassimo** [snowpackjs/astro#104]
For

https://github.com/snowpackjs/astro/blob/d2337e70239137700447dd46d5bd70de38a0a8ae/examples/snowpack/astro/components/Nav.astro#L351

If you replace it with `<script type="module" src="docsearch.js"></script>`, the source path would not be rewritten and kept as `docsearch.js`, thus making the output page not able to load this script.

This is due to

https://github.com/snowpackjs/astro/blob/d2337e70239137700447dd46d5bd70de38a0a8ae/src/compiler/transform/module-scripts.ts#L29

and thus would miss relative paths without `.` prefix and not performing the rewrite (technically I believe only `/path-absolute` paths should be ignored). To fix this, probably we can do

```ts
if (!src || src.startsWith('/')) {
```

(I had a local branch for this that seems working, but since the project could not be forked I could not make the PR I'll just leave my investigations here)

**Comment by drwpow** [comment]
This seems like the same root issue as #96, I believe? Even though it’s a bit different as the JS gets bundled, I think they both address the core issue, which is _how much do users expect us to transform?_ Or worded another way: _when do users want us to rewrite their imports?_

This is a tricky question we may either need an API for, or some more clear ruling on.

**Comment by drwpow** [comment]
Oh but that said, this issue being more about the `.` itself is still a bug we should address. Just trying to point out the overlap.
