### ISSUE TITLE
VSCode: Move vscode extension + tools to another repo

### ISSUE THREAD

**Issue by matthewp** [snowpackjs/astro#1069]
### Background & Motivation

We've started breaking apart the monorepo a little bit and keeping core things in /astro and moving non-core things to their own repo. This makes the issue tracker easier to view and maintain.

Additionally it's hard to develop the vscode extension in this monorepo because the tools are not listed as workspaces. This is because it interferes with publishing the extension.

### Proposed Solution

Move the extension and language service to their own repository and track issues there.

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by jasikpark** [comment]
The pattern I've seen is: move alpha project out of monorepo for quick iteration and then merge back into the monorepo when it's more stable, ex: the docs project and maybe(?) the prettier plugin. 

I think improving the experience spent working on the vscode extension is definitely important though, so if we need to move it to it's own repo to do that, we should!

**Comment by matthewp** [comment]
Yeah this is about being able to develop the plugin without special knowledge since it doesn't work in this monorepo. Will only move if the flow can be improved.

**Comment by jasikpark** [comment]
Closed by #1230
