### ISSUE TITLE
🐛 BUG: Uploading Astro's dist folder to something other then the servers root doesn't load the CSS styles

### ISSUE THREAD

**Issue by markteekman** [snowpackjs/astro#1073]
### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I uploaded an Astro project to https://markteekman.nl/accessible-astro-strarter/ and it didn't show any CSS styling. Got to talking in the support channel on Discord with JSH and Astro's looking at the root folder for the _astro folder with the CSS, so at https://markteekman.nl/_astro, while it should be looking at www.markteekman.nl/accessible-astro-strarter/_astro.

Some extra content from JSH:

> I can't find any really good solution as of now. Using ${Astro.site}style/global.css sort of works, but you have to comment out the site in the config for development. It also ONLY works for explicitly set URLs, meaning when you write CSS in a .astro components, it won't work. This should be looked into, I'd suggest. For now, your best bet would be to either create a subdomain at accessible-astro.markteekman.nl if you can or write a script to rewrite all /_astro/ paths to /your-url/_astro.

I fixed it for now with his suggestion of using a subdomain 🙂 

### Steps to Reproduce

1. `npm build`
2. Deploying contents of `dist` on server via FTP on a subpage (example: https://mydomain.com/astro-is-cool/
5. No CSS styles are loaded because the stylesheet is looking for https://mydomain/.com/_astro instead of https://mydomain.com/astro-is-cool/_astro

**Comment by matthewp** [comment]
+1, we should support this.

**Comment by drwpow** [comment]
I think there are probably 2 ways to solve this: either you set `buildOptions.site` to `https://mydomain.com/astro-is-cool/` or we add another config value that gets prefixes onto every path, e.g. `buildOptions.baseDir = 'astro-is-cool/'`. Does anyone have a strong preference between the two?

**Comment by jasikpark** [comment]
I like the idea of allowing that setting to be `URL | string` so that the reccomended way to config is with a URL constructor, but you can also just pass a string - 

```js
export default {
site: { 
  pathname: "/hello-world",
},
```

Which I suppose is a long way of saying #2 😆

**Comment by markteekman** [comment]
@drwpow Either options sound good! Also like the idea of @jasikpark, but here is where the knowledge on the topic fails me a bit.. 😅

**Comment by drwpow** [comment]
This is related to https://github.com/snowpackjs/astro/issues/963, and more than likely solved by accepting that. But the bug is still valid.

**Comment by FredKSchott** [comment]
Thanks for the report! We believe that this has been fixed in astro v0.21, going out today. Let us know if you can still reproduce the issue after updating to v0.21 and we'll be happy to take a look.
