### ISSUE TITLE
🐛 BUG: [build] src/pages/<filename>.astro: could not find ...

### ISSUE THREAD

**Issue by coelmay** [snowpackjs/astro#1101]
### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

When using [ImageKit tranforms](https://docs.imagekit.io/features/image-transformations) with a comma in an `<img srcset="">` build will fail however does not fail when used in a `<source srcset="">`.

Possibly related to https://github.com/snowpackjs/astro/issues/1071.

```html
<!--
  Fails:
  [build] src/pages/<filename>.astro: could not find "main_img.jpg"
-->
<img
  src="/placeholder.jpg"
  srcset="http://cdn.example.com/my-products/tr:w-600,q-80/product-1/main_img.jpg 600w,
    http://cdn.example.com/my-products/tr:w-800,q-80/product-1/main_img.jpg 800w"
>
```

```html
<!-- Works -->
<picture>
  <source
    src="/placeholder.jpg"
    srcset="http://cdn.example.com/my-products/tr:w-600,q-80/product-1/main_img.jpg 600w,
      http://cdn.example.com/my-products/tr:w-800,q-80/product-1/main_img.jpg 800w"
  >
</picture>
```

See expanded list of examples: https://github.com/coelmay/astro-image-bug/blob/main/src/pages/index.astro

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. git clone https://github.com/coelmay/astro-image-bug/
3. npm run build
4. [build] src/pages/<filename>.astro: could not find ...

### Link to Minimal Reproducible Example (Optional)

https://github.com/coelmay/astro-image-bug

**Comment by jasikpark** [comment]
Does it still work when the picture element has an img inside of it?

**Comment by coelmay** [comment]
This fails
```html
<picture>
<img
  src="/placeholder.jpg"
  srcset="http://cdn.example.com/my-products/tr:w-600,q-80/product-1/main_img.jpg 600w,
    http://cdn.example.com/my-products/tr:w-800,q-80/product-1/main_img.jpg 800w"
>
</picture>
```

**Comment by matthewp** [comment]
The srcset logic is here: https://github.com/snowpackjs/astro/blob/a4a7685be1bddea80883a17dae0492ad941aa59e/packages/astro/src/build.ts#L314-L323

I think this is likely where the bug is occuring. If someone wants to create a test and fix, a test should be added here: https://github.com/snowpackjs/astro/blob/23b0d2d345312eb072998d043fe84a5addbd6c04/packages/astro/test/astro-assets.test.js#L10

I think this is probably not super hard to replicate and fix, would make a great contribution!

**Comment by coelmay** [comment]
How about something like this:

```javascript
// Create Regular Expression for splitting
// Take into account srcset may us 800w, or 1.5x 
// I'm not a RegExp expert, so there is possible a better way
const srcsetRgx = new RegExp(/\ \d+(?:\.\d+)?[wx],?/)

// Split and filter out empty entry
const sources = srcset.split(srcsetRgx).filter((el) => el === "")
```

So if the srcset was 
```html
<img srcset="http://cdn.example.com/my-products/product-1/main_img.jpg?tr=w-600,q-80 600w,
http://cdn.example.com/my-products/product-1/main_img.jpg?tr=w-800,q-80 800w">
```
or
```html
<img srcset="http://cdn.example.com/my-products/product-1/main_img.jpg?tr=w-600,q-80 1.5x,
http://cdn.example.com/my-products/product-1/main_img.jpg?tr=w-800,q-80 2x">
```
or
```html
<img srcset="/my-products/product-1/main_img.jpg?tr=w-600,q-80 1.5x,
/my-products/product-1/main_img.jpg?tr=w-800,q-80 2x">
```
or even a combination of **w** and **x** (who would use that?)
```html
<img srcset="http://cdn.example.com/my-products/product-1/main_img.jpg?tr=w-600,q-80 600w,
http://cdn.example.com/my-products/product-1/main_img.jpg?tr=w-800,q-80 2x">
```
an array of URLs would get returned (plus one empty one, hence the filter)
```javascript
[
  "http://cdn.example.com/my-products/product-1/main_img.jpg?tr=w-600,q-80",
  "http://cdn.example.com/my-products/product-1/main_img.jpg?tr=w-800,q-80"
]
```

**Comment by matthewp** [comment]
@coelmay it sounds like you know a lot about srcset, would love a PR to fix this if you have the time!

**Comment by coelmay** [comment]
> @coelmay it sounds like you know a lot about srcset, would love a PR to fix this if you have the time!

🤣🤣🤣🤣🤣🤣🤣 I don't know much about anything really. I'm simply a curious fellow.

What I came up with in the end is in https://gist.github.com/coelmay/67cb4ec689282fc299585bc8c7feaa34 with tests (this doesn't necessarily adhere to [4.8.4.3.9 Parsing a srcset attribute](https://html.spec.whatwg.org/multipage/images.html#parsing-a-srcset-attribute)) but reworking the code you posted above would look something like
```javascript
$('img[srcset]').each((_i, el) => { 
    const srcsetRegex = new RegExp(/\ \d+(?:\.\d+)?[wx],?/);
    const mutliURLRegex = new RegExp(/,(?:\ ?)(?=\/|https?)/);
    
    const srcset = $(el).attr('srcset') || ''; 
    
    let sources = srcset.split(srcsetRegex).filter((el) => el !== "");
    let srces = [];
    sources.map((el) => el.split(mutliURLRegex).forEach((el) => srces.push(el.trim())));

    for (const src of srces) { 
      if (!isRemoteOrEmbedded(src)) { 
        pageDeps.images.add(getDistPath(src, { astroConfig, srcPath })); 
      } 
    } 
});
```
I don't believe this is ideal.

If I knew how the whole PR thing worked I'd happily add this, but I don't. More than happy for someone who does to take this snippet and create a PR should they think viable.

**Comment by coelmay** [comment]
Thanks @jasikpark.

I'd like to propose a spec compliant parser instead of my (upon reflection) somewhat flawed attempt.

[srcset-parse](https://github.com/molefrog/srcset-parse) is one such library I found. It is written to ES2015 standard so don't know how that works in context of Astro as a whole.

**Comment by coelmay** [comment]
Was unable to get `srcset-parse` to integrate in local builds, so used the relevant portion of code and regex to get the functionality required (attribution given naturally.)

**Comment by coelmay** [comment]
I've tried and I've tried and I've tried again, but I am unable to get a working solution to this with [`srcset-parse`](https://github.com/molefrog/srcset-parse). Always get `error: parse is not a function`.
Have no idea about ts. Hopefully someone can get something to work some day.
Will just make sure no URLs with commas are used until that day (if it does.)

**Comment by jasikpark** [comment]
Want to publish your attempts as a branch on a fork so we can maybe help you out? Sounds like a failing import in that case...

**Comment by coelmay** [comment]
> Want to publish your attempts as a branch on a fork so we can maybe help you out? Sounds like a failing import in that case...

Deleted everything in disgust/frustration.

**Comment by jasikpark** [comment]
oh well, we'll sort it out eventually hopefully..

**Comment by pointout** [comment]
For me also ```<picture><source srcset=...``` didn't work. In both img and source the first ressource in srcset is wiped out. This occures in astro version above 0.20.8. In dev mode all works as expected. also in 0.20.12.
