### ISSUE TITLE
📘 DOC: Add Gatsby to Comparing section in docs

### ISSUE THREAD

**Issue by kaushalyap** [snowpackjs/astro#1103]
Astro is compared to the lot of libraries [here](https://docs.astro.build/comparing-astro-vs-other-tools). But Gatsby is not mentioned there. AFAIK only difference is Gatsby tied to the React  while Astro not.  Astro claim to have partial hydration, Gatsby also eventually have partial hydration when React have [Suspense](https://github.com/facebook/react/issues/13206). Other than that Gatsby have following features that I think Astro currently do not have.

- Image optimization
- Fast page navigation with [Link](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-link/)
- Resource pre-fetching
- Per route code splitting
- Inlining Critical CSS
- Plugins

**Comment by jasikpark** [comment]
Gatsby is now in the comparison docs here: https://docs.astro.build/comparing-astro-vs-other-tools/
