### ISSUE TITLE
🐛 BUG: Cannot import from root directory

### ISSUE THREAD

**Issue by lhermann** [snowpackjs/astro#1117]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Importing files from the root or top level directory throws a 'Could not find' error.

```
[executing astro] CompileError: Could not find "/test.js"
    at load (file:///Users/lhermann/htdocs/astro-import-bug/node_modules/astro/dist/runtime.js:217:16)
    at async Server.<anonymous> (file:///Users/lhermann/htdocs/astro-import-bug/node_modules/astro/dist/dev.js:21:20) {
  start: { line: 16, column: 11, character: 481 },
  end: { line: 16, column: 11, character: 481 },
  filename: '/Users/lhermann/htdocs/astro-import-bug/src/pages/index.astro',
  frame: '14: // https://docs.astro.build/core-concepts/astro-components/\n' +
    '15: \n' +
    "16: import '../test.js'\n" +
    '               ^\n' +
    "17: import '../../test.js'\n" +
    '18: ---'
}
```

Check out the following test setup: https://github.com/lhermann/astro-import-bug/blob/master/src/pages/index.astro

I tried importing it with absolute path (`/test.js`) and relative path (`../../test.js`)

<img width="427" alt="image" src="https://user-images.githubusercontent.com/2800117/129476280-1fea1da3-825a-48e9-973b-81da36dbd03e.png">

(I don't know if this is intended behavior, couldn't find anything about it in the docs.)

### Steps to Reproduce

1. `clone https://github.com/lhermann/astro-import-bug.git`
2. `npm install`
3. `npm start`

Error: `CompileError: Could not find "/test.js"`

Expected: Should be able to import files from root directory

### Link to Minimal Reproducible Example (Optional)

https://github.com/lhermann/astro-import-bug

**Comment by jasikpark** [comment]
try adding a 
```
// snowpack.config.js
export default = {
  workspaceRoot: "../..",
};
```
to your project

**Comment by tony-sull** [comment]
Astro is only responsible for processing and bundling files under `src` so you really do want any of your source code to live there

I can't find the PR now, but I was pretty sure there was a change a little while ago to make sure that imports are always coming from inside the `src` directory

The Supported Imports docs mention thst Astro only processes files under `src`, but I could see adding a note there to clarify if importing files outside `src` isn't supported 👍

**Comment by lhermann** [comment]
@tony-sull thank you for clarifying. I was hoping to import my firebase config json file from the root directory. What do you suggest as best practice in this case?

**Comment by matthewp** [comment]
You can specify a different `src:` option in your config: https://github.com/snowpackjs/astro/blob/latest/packages/astro/src/@types/config.ts#L17

So you could make your root folder the src folder and then you can import anything in the project. Warning here as this means you can import any file in the project, which is probably not what you want. You can also set an alternative mount folder via a snowpack config: https://www.snowpack.dev/reference/configuration#mount

But again, this will mount a folder. Can you move the firebase config to a subfolder? Putting stuff in a `config/` is common. Then you could mount that folder only.

Going to close as there doesn't seem to be a bug here, but happy to keep discussing.

**Comment by lhermann** [comment]
Thank you @matthewp. I tried to use snowpack mount but couldn't wrap my mind around it and get it to work.

After much trial and error I ended up writing a simple importer JS file like so:
``` js
import config from '../config.json'

export default {
  ...config,
}
```
