### ISSUE TITLE
🐛 BUG: if naming your import props then it doesn't load your file

### ISSUE THREAD

**Issue by dan-1s** [snowpackjs/astro#1126]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

In astro file: if you name your import `props` it will not load your imported data.

### Steps to Reproduce

1. `npm init astro`
2. `npm install`
3. create `src/pages/data.js` file with `export default { data: "some-data" };`
4. in `src/pages/index.astro`  import the file using `import props from ./data.js`

Expected `props` to hold `{ data: "some-data" }` or a message/warning that `props` is reserved by Astro :)
Actual: `props` is an empty object {}

**Comment by jasikpark** [comment]
This would be good to fix - I've run into a similar problem where I've been able to render a component as 
```astro
<span {...props}><slot/></span>
```
rather than `Astro.props` due to that variable shadowing.

**Comment by matthewp** [comment]
Fixed by #1433
