### ISSUE TITLE
RFC Call: August 17, 2021

### ISSUE THREAD

**Issue by drwpow** [snowpackjs/astro#1139]
## When/Where

- 2p EDT, 11a PDT
- On Discord, #events channel

## Agenda

https://github.com/snowpackjs/astro/issues?q=is%3Aopen+is%3Aissue+label%3Arfc-discuss
Want to see something discussed? Comment below and we can add a tag

- https://github.com/snowpackjs/astro/issues/1077
- https://github.com/snowpackjs/astro/issues/612
- https://github.com/snowpackjs/astro/issues/1119
- https://github.com/snowpackjs/astro/issues/1013
- https://github.com/snowpackjs/astro/issues/1097

**Comment by matthewp** [comment]
@drwpow #958 still needs work, it was previously discussed but I need to come up with some answers to the questions raised last time, can we remove it from the agenda?

**Comment by drwpow** [comment]
@matthewp yup was just about to ask you about that one—I couldn’t remember if it needed more discussion or work. Removed!

**Comment by FredKSchott** [comment]
Can we discuss https://github.com/snowpackjs/astro/issues/708 ?

**Comment by drwpow** [comment]
Ah sorry @FredKSchott didn’t see this during the call. Will add for next week’s meeting.

**Comment by FredKSchott** [comment]
np! you hit time perfectly, we can throw it on the schedule for next week

**Comment by FredKSchott** [comment]
assume this issue is safe to close now! can you spin up next weeks as well?

**Comment by drwpow** [comment]
Opened a new one: https://github.com/snowpackjs/astro/issues/1144.

Do we close old ones (https://github.com/snowpackjs/astro/issues/1003)?

**Comment by FredKSchott** [comment]
We should! Nice, 2 closed issues for the price of one
