### ISSUE TITLE
🐛 BUG: \n in Markdown codeblocks is interpreted as actual newline

### ISSUE THREAD

**Issue by MarcusOtter** [snowpackjs/astro#1147]
### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

While editing the `markdown.content.md` in the docs site I found this:

| Input | Output | Expected |
| ----- | ------- | ---------- |
| ![image](https://user-images.githubusercontent.com/35617441/129829956-e2b9c801-6f83-4cf7-9934-9d0982873cf5.png) | ![image](https://user-images.githubusercontent.com/35617441/129830097-337d85f1-34a8-4e65-b73a-2ebe39d8257b.png) | ![image](https://user-images.githubusercontent.com/35617441/129830142-b618fbef-2408-4106-b654-fa1b7a77951a.png) |

This is wrong because everything entered in code blocks should be considered raw text.

Current workaround:
![image](https://user-images.githubusercontent.com/35617441/129830179-798a47ce-6fee-4a85-be05-ae4a3dd82c26.png)

### Steps to Reproduce

1. Build the docs
2. Open any of the markdown pages and insert the the input seen above
3. See output

**Comment by FredKSchott** [comment]
Thanks for the report! We believe that this has been fixed in astro v0.21, going out today. Let us know if you can still reproduce the issue after updating to v0.21 and we'll be happy to take a look.
