### ISSUE TITLE
🐛 BUG: Tags will be deleted instead of moved to `<head>` if `<head>` not present

### ISSUE THREAD

**Issue by Tc-001** [snowpackjs/astro#1154]
### What package manager are you using?

npm

### What operating system are you using?

linux

### Describe the Bug

Any tag that is supposed to be moved to the head goes missing instead if `<head>` element is not explicitly defined

### Steps to Reproduce

1. Create the following astro file as a page:
```astro
<style>
  p {
    color: blue;
  }
</style>
<p>test</p>
```
2. Notice it not adding the styles
3. Replace it with
```astro
<head></head>

<style>
  p {
    color: blue;
  }
</style>
<p>test</p>
```
4. Notice it now adding the styles

Also seems to happen with HMR scripts and alike

The most noticeable example is the astro error page, which now appears with no styling no matter the project (just trigger an error in 0.19 and observe it)

**Comment by Tc-001** [comment]
This also happens on nested components if the top-level one dies not have `<head />`

**Comment by FredKSchott** [comment]
I think we can call this a "fixed in new compiler" bug, since @natemoo-re and I have been talking about removing all of the clever "no html"/"no head"/"no body" quirks mode features from the new compiler

@drwpow have you started a new label to categorize compiler issues?

**Comment by drwpow** [comment]
> @drwpow have you started a new label to categorize compiler issues?

No but that’s a good call. Will do that now.

**Comment by natemoo-re** [comment]
Confirming that this is fixed in the `astro@next` preview!

Will put this in our milestone to be closed when that release is stable.
