### ISSUE TITLE
🐛 BUG: `:global()` will not be properly removed if additional selectors applied

### ISSUE THREAD

**Issue by Tc-001** [snowpackjs/astro#1155]
### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

When a `:global(foo)` is succeeded by any character/selector that is not a `space`, the final compilation will include the closing bracket `)`

### Steps to Reproduce

1. `npm init astro` using any template
2. replace `index.astro` with:
```astro
<head></head>

<style>
  p {
    color: red;
  }
  :global(foo):hover {
    background-color: red
  }
</style>

<p>test</p>
```
> P.S. `<head>` is requiered, see #1154 

3. using `<p>` as the reference, find the stylesheet in the devtools
4. Observe the 2nd CSS statement:
```css
foo):hover {
  background-color: red
}
```
Notice the not-removed bracket where the `:global(foo)` was before

**Comment by tony-sull** [comment]
I think this may actually be by design in Astro right now.  I haven't actually seen that syntax used before but just tried it in Svelte's REPL and they do support it, may be worth an RFC to add support for that in Astro if nothing else :+1:

**Comment by Tc-001** [comment]
1. It was working in 0.18
2. Here is sass code that will generate the bugged CSS
```sass
	:global(body[data="dark"])
		.when-light
			display: none
		.when-dark
			display: block
```
It will show/hide a scoped component based on a globally defined theme

**Comment by Tc-001** [comment]
Although looking at it it *shouldn't* generate a bugged css based on my previous obervations, this is the real-world scenario where I encountered it

**Comment by drwpow** [comment]
This is a bug for sure, but I’m having a tough time deciding if `:global(body).when-light` is a syntax error. I think it should be? In which case we should just throw an error.

As a temporary workaround, it’s worth noting that `body` is a special tag that will never be scoped (because it’s always unique) so you should be able to omit `:global()` for all body selectors (but this doesn’t apply to `body .foo`, a child selector, since that technically may be scoped).

Overall, though, we‘d love improvements to all of the following:

1. This bug specifically (throwing syntax error)
2. Adding [more test cases here](https://github.com/snowpackjs/astro/blob/main/packages/astro/test/astro-scoped-styles.test.js)
3. Expanding docs section / examples on `:global()` selector scope?

**Comment by drwpow** [comment]
> but just tried it in Svelte's REPL and they do support it

Ah missed this part. If there’s precedent for it, then I’m in favor of supporting it too. I just want to be consistent.

**Comment by Tc-001** [comment]
For me at least `:global` means "leve it as is, do not apply any scoping for elements within me". So it should be theoretically applied to any element/elements where scoping would usually take place.
Thus, because `div .content p` is valid css, `:global` should be able to apply in any arrangement (`div :global(.content) p`, `:global(div .content) p`, `div .content :global(p)`, etc.)

Of course that could add some completely, so I'm not against removing at and adding a syntax error if it's not sustainable

**Comment by drwpow** [comment]
Added a test + fix here: https://github.com/snowpackjs/astro/pull/1162

**Comment by Tc-001** [comment]
There still seems to an issue with `:global(.foo) .bar` being compiled as `.foo.bar` instead of `.foo .bar`

```astro
<style>
    :global(.foo) .bar {color: red;}
</style>
```
will output
```html
<style type="text/css">.foo.bar {color: red;}</style>
```

I can probably submit a PR later tonight or sometime tomorrow, as it doesn't seem that difficult to track down (famous last words lol)

**Comment by Tc-001** [comment]
@drwpow I think I found an issue with 
https://github.com/snowpackjs/astro/blob/d51e0f4fef5a19eb82c2e02c41578bd908b39720/packages/astro/src/compiler/transform/postcss-scoped-styles/index.ts#L18-L20

where it will remove a whitepace where it should not
Input: `div:not(.foo) .bar`
Output: `div:not(.foo).bar`

I don't know the best way to approach this, as the commit seems to be in place to fix another issue
