### ISSUE TITLE
🐛 BUG: Typo in the latest blog post

### ISSUE THREAD

**Issue by bLaCkwEw** [snowpackjs/astro#1156]
### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

There is a typo in the latest blog post detailing the 0.19 release.

I believe it's supposed to say *"100%"* but it's actually *"1005"* instead.
![Screenshot_2021-08-18_21-21-44](https://user-images.githubusercontent.com/35146970/129953952-8a2a083a-d90b-42d4-8a74-20f44cb0a0f9.png)

### Steps to Reproduce

See https://astro.build/blog/astro-019#open-collective towards the bottom of the section.

**Comment by tony-sull** [comment]
Thanks for catching this!  Just filed #1157 to fix that

**Comment by FredKSchott** [comment]
haha thank you both! 1005 funds??? sounds like a dream come true

**Comment by FredKSchott** [comment]
Thanks both!
