### ISSUE TITLE
📘 DOC: Replace VuePress with VitePress in Astro vs. X

### ISSUE THREAD

**Issue by yyx990803** [snowpackjs/astro#1159]
First of all, great work on Astro! I stumbled upon a comparison vs VuePress in the docs. Since VuePress v1 is a bit outdated, I want to suggest updating the comparison to target [VitePress](https://vitepress.vuejs.org/) instead.

VitePress is the spiritual successor to VuePress. It replaces VuePress' Vue 2 + webpack internals with Vue 3 + Vite, and adds a number of production improvements. Most notably, it supports mixing Vue components in markdown with partial hydration (for the markdown part). It loads a lightweight Vue application upfront in return for faster, SPA-style subsequent navigations.

[Vite's docs](https://vitejs.dev/) is built with VitePress, we are also in the process of rebuilding the Vue documentation with VitePress.

Also note that although the default theme is designed for documentation, both VuePress and VitePress actually support arbitrary custom themes using Vue. As an example, the [Vue blog](https://blog.vuejs.org/) is built with VitePress and a custom blog theme.

**Comment by FredKSchott** [comment]
exciting stuff! Just saw your performance numbers on Twitter, looks super promising.

These comparisons mainly exist for users who are looking to compare Astro to existing solutions. Vitepress downloads seem small (esp. compared to Vuepress) and it doesn't look like Vitepress is claiming to be ready for production usage yet. For ex, messages like this at the top of the README:

> 🔥 Note this is early WIP! Currently the focus is on making Vite stable and feature complete first. It is not recommended to use this for anything serious yet.

For now, I'm happy to add a note to the Vuepress section about Vitepress as the more modern alternative on the way. And then once Vitepress is considered more stable / production ready we can look into switching the section over entirely.

**Comment by yyx990803** [comment]
Sounds good. It'll probably reach stable status after we are done with the new Vue docs.

**Comment by FredKSchott** [comment]
VitePress added in https://github.com/snowpackjs/astro/commit/a79b6db152075793d8604e05073df3d1b292a418, will close this issue for now but feel free to ping again once VitePress v1.0 is ready
