### ISSUE TITLE
🐛 BUG: Astro incorrectly adds a class to every selector when importing via @use or @import in SCSS

### ISSUE THREAD

**Issue by RafidMuhymin** [snowpackjs/astro#1168]
### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

When using the @use or the @import syntax to import an SCSS file inside a style tag in a layout file, Astro incorrectly adds a class to every style present in the stylesheet. As a result, no style gets applied to any element. The class that Astro adds to every selector is the class it adds to the container element of the slot component.

If you aren't using a layout then every element present inside the body tag on your page and their children will have the same class added. And that class will be added to every selector inside the style tags.

### Steps to Reproduce

Create a Layout.astro file like below:
```astro
<html lang="en">
<head>
    <style lang="scss">
      @import "../path/to/style.scss";
    </style>
</head>
<body>
    <main id="root">
      <slot></slot>
    </main> 
</body>
</html>
```

Then add styles to the style.scss file:

```scss
// To quickly add enough class I have included the @tailwind directives
@tailwind base;
@tailwind components;
@tailwind utilities;
```

Then if you look inside the generated styles in the browser, you style tags should look something like the attached file below.
[astro.txt](https://github.com/snowpackjs/astro/files/7016399/astro.txt)

**Comment by FredKSchott** [comment]
Thanks for the report! We believe that this has been fixed in astro v0.21, going out today. Let us know if you can still reproduce the issue after updating to v0.21 and we'll be happy to take a look.
