### ISSUE TITLE
🐛 BUG: `Astro.resolve()` fails if `buildOptions.site` includes a path

### ISSUE THREAD

**Issue by simonwiles** [snowpackjs/astro#1171]
### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

If I add a path / subfolder to my site url at `buildOptions.site`, `Astro.resolve()` fails to find anything.

To be honest, all I want is a way to reference an image that can work both at `localhost:3000/` for dev purposes and at a subfolder (e.g. https://simonwiles.github.io/my-astro-project) when the project it built.  Is there a best practice here?  Nothing I've tried has worked so far (`Astro.resolve()`, composing a relative path using `Astro.site`, composing an absolute path using `Astro.site`) so I'm post-processing my built files with `sed` at the moment (I'm having to do this anyway because of #968).

**Edit:** I *am* able to get something that works if I place my image in the `public/` folder and use `src={Astro.site.href + 'path/from/public/folder/image.png'}`, which is workable for my immediate needs (and better than using `sed` :)) -- but that's really irrelevant to this bug report.

### Steps to Reproduce

1. `npm init astro` (generic template, then `npm install` etc.)
2. Copy the `logo.svg` to the `src/` folder
3. Change the `src` attribute on the main image in `pages/index.astro` to `{Astro.resolve("../logo.svg")}`
4. `npm run build` -- all is well
5. Change the `buildOptions.site` key in `astro.config.mjs` to (e.g.) http://localhost/astro-project
6. `npm run build` -- build fails `[build] file:///path/to/project/src/pages/index.astro: could not find "logo.svg"

**Comment by FredKSchott** [comment]
Thanks for the report! We believe that this has been fixed in astro v0.21, going out today. Let us know if you can still reproduce the issue after updating to v0.21 and we'll be happy to take a look.
