### ISSUE TITLE
🐛 BUG: Can't use <script setup> with Vue 3

### ISSUE THREAD

**Issue by Miguelklappes** [snowpackjs/astro#1190]
### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

I can't use the [<script setup>](https://v3.vuejs.org/api/sfc-script-setup.html#sfc-script-setup) syntax with Vue 3, therefore I am not able to take advantage of some features of this framework.

### Steps to Reproduce

1. yarn create astro -- --template framework-vue
2. yarn && yarn dev
2. Edit Vue component and use <script setup> syntax
3. Wait for it to work and it doesn't
4. The errors are the usual _Vue warn_ that happens when you forgot to return something in the setup() function, but here I am using `<script setup>`, thus properties are always exposed. I expected `<script setup>` to work as usual.

`[Vue warn]: Property "count" was accessed during render but is not defined on instance.`

### Link to Minimal Reproducible Example (Optional)

https://github.com/Miguelklappes/astro-test

**Comment by FredKSchott** [comment]
Thanks for the report! We believe that this has been fixed in astro v0.21, going out today. Let us know if you can still reproduce the issue after updating to v0.21 and we'll be happy to take a look.
