### ISSUE TITLE
💡 RFC: [@astro/markdown-support] Accessible markdown footnotes

### ISSUE THREAD

**Issue by robinmetral** [snowpackjs/astro#1191]
### Background & Motivation

Footnotes using `remark-footnotes` (built into `@astrojs/markdown-support`) are [not accessible](https://github.com/remarkjs/remark-footnotes/issues/6) with our current version of rehype:

https://github.com/snowpackjs/astro/blob/d51e0f4fef5a19eb82c2e02c41578bd908b39720/packages/markdown-support/package.json#L30

I  asked about this in `remark-footnotes` https://github.com/remarkjs/remark-footnotes/issues/6, and it turns out that this has already been addressed a few months ago in [`mdast-util-to-hast@11.0.0`](https://github.com/syntax-tree/mdast-util-to-hast/releases/tag/11.0.0), which in turn was upgraded in [`remark-rehype@9.0.0`](https://github.com/remarkjs/remark-rehype/releases/tag/9.0.0) 🎉 

### Possible solutions

Upgrade to `remark/rehype@9.0.0`. We'll need to verify any breaking changes.

> I've opened an issue for visibility, but I'll make a PR for this! I've been looking for an excuse to contriobute to Astro 🤗 

### Alternatives considered

None.

### Risks, downsides, and/or tradeoffs

Only good things ❤️ 

### Open Questions

None.

### Detailed Design

- go through the detailed changelogs
- upgrade the packages
- thoroughly test
- 🚢 

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by drwpow** [comment]
I’ll let @matthewp give his opinion, but this seems like a pretty easy win to me. I’m not aware of a reason why we would want to stay on the current version (but cc-ing @matthewp to double-check)
