### ISSUE TITLE
🐛 BUG: HTML videos won't load locally in Safari

### ISSUE THREAD

**Issue by patrickhill** [snowpackjs/astro#1193]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Videos won't load on Safari in localhost. I believe this is because the local server is sending assets with a 200 status when they should be using 206. 

reference: https://stackoverflow.com/questions/32996396/safari-9-0-can-not-play-mp4-video-on-the-storage-server/32998689#32998689

### Steps to Reproduce

1. `npm init astro` using template generic
2. npm install
3. npm start
4. add a video to the index file
5. open localhost in safari
6. video won't load, safari reports an error for the asset

**Comment by matthewp** [comment]
Very interesting, this is technically a snowpack issue but its ok to post it here. Is there a particular header that tells us when we need to return 206? I'll do some research, just curious here if you happen to know.

**Comment by patrickhill** [comment]
I'm not really sure. From what I can understand, it looks like videos download in partial chunks so they use the Range request header. When the partial data finishes, it gives the 206 partial content success status.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/206

**Comment by natemoo-re** [comment]
Thanks for raising this! I'm not sure if this is fixed in `astro@next` by our move to Vite, but I am cleaning up the `compiler-v2` issues and this is definitely an upstream issue.

If this still isn't fixed in `astro@next`, I'd suggest opening an issue on https://github.com/vitejs/vite!
