### ISSUE TITLE
🐛 BUG: Astro doesn't build web workers while running `astro build`, but it does build them while running `astro dev`

### ISSUE THREAD

**Issue by okikio** [snowpackjs/astro#1195]
### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

Astro doesn't build web workers while running `astro build`, but it does build them while running `astro dev`.

My astro config is 
```ts
export default {
  // projectRoot: '.',     // Where to resolve all URLs relative to. Useful if you have a monorepo project.
  // pages: './src/pages', // Path to Astro components, pages, and data
  // dist: './dist',       // When running `astro build`, path to final static output
  // public: './public',   // A folder of static files Astro will copy to the root. Useful for favicons, images, and other files that don’t need processing.
  buildOptions: {
    // site: 'http://example.com',           // Your public domain, e.g.: https://my-site.dev/. Used to generate sitemaps and canonical URLs.
    sitemap: true,         // Generate sitemap (set to "false" to disable)
  },
  devOptions: {
    // hostname: 'localhost',  // The hostname to run the dev server on. 
    // port: 3000,             // The port to run the dev server on.
    // tailwindConfig: '',     // Path to tailwind.config.js if used, e.g. './tailwind.config.js'
  },
  renderers: [
    "@astrojs/renderer-solid"
  ],
};
```

My snowpack config is,
```ts
// Snowpack Configuration File
// See all supported options: https://www.snowpack.dev/reference/configuration

/** @type {import("snowpack").SnowpackUserConfig } */
export default {
  // exclude: ["typescript"],
  optimize: {
    bundle: true,
    minify: true,
    keepNames: true,
    target: 'es2020',
  },
  mount: {
    /* ... */
  },
  plugins: [
    /* ... */
  ],
  packageOptions: {
    /* ... */
    polyfillNode: true
  },
  devOptions: {
    /* ... */
  },
  buildOptions: {
    /* ... */
  },
};
```

### Steps to Reproduce

1. `npm init astro` using template `framework-solid`
2. `mkdir public`
3. Create a typescript file in the `public` folder, that is supposed to be the web worker, e.g. `public/web-worker.ts`
```ts
// public/web-worker.ts
console.log("This was logged from the web-worker")
```
4. Then go to the `src/components/Counter.tsx` file, and include a 
```ts
// ...
new Worker(new URL("/web-worker.js", import.meta.url), {
    type: "module",
    name: "web-worker"
})
```
inside the default function, something like this,
```ts
import { createSignal, onMount } from 'solid-js';

/** */
export default function SolidCounter({ children }) {
  const [count, setCount] = createSignal(0);
  const add = () => setCount(count() + 1);
  const subtract = () => setCount(count() - 1);

  new Worker(new URL("/web-worker.js", import.meta.url), {
      type: "module",
      name: "web-worker"
  })

  return (
    <>
      <div class="counter">
        <button onClick={subtract}>-</button>
        <pre>{count()}</pre>
        <button onClick={add}>+</button>
      </div>
      <div class="children">{children}</div>
    </>
  );
}
```
5. `astro dev` (this should work)
> _**Note**: you have to open http://localhost:3000 in the browser for the error to appear._
6. Now run `astro build` (this will build, but the `web-worker.js` file will be missing, even though it was there in `astro dev` )

**Comment by matthewp** [comment]
Thanks for bringing this up! I'm curious how Next.js and others handle this.

**Comment by drwpow** [comment]
This is something I can’t say will be fixed with the new compiler for sure, but there’s a small possibility. At least, we should mark this as something to double-check.

**Comment by okikio** [comment]
The problem here is the inconsistent behavior between `astro dev` and `astro build`, this issue can be fixed without the new compiler. `astro dev` is actually able to compile web workers, I think this comes from snowpack, but when it comes to `astro build` it doesn't compile the Web worker.

**Comment by okikio** [comment]
After some more investigating I've found that the problem is actually the fact that on `astro dev` typescript files in the `public` directory are compiled to js, while on `astro build` they are not

**Comment by matthewp** [comment]
Even if TypeScript files were compiled, they would not be built during the build (bundled) so it's very likely they would not work anyways. I think there's likely a need to tell the build step that there are extra entrypoints that it won't find through the normal page scanning. @drwpow is probably right that the new compiler might fix this (if it doesn't it should be fixed there).

**Comment by okikio** [comment]
But it wouldn't need to be bundled all that is needed is for the file to be compiled, even if it isn't bundled together, right now the

**Comment by matthewp** [comment]
The core issue here is that the build isn't aware that this file exists. The reason it gets compiled in dev and not build is that the browser sends requests for files in dev and in the build there is no browser; instead we scan pages to find files to build and we don't detect this one. So to Drew's point, the new compiler rewrite includes a new page scanner which might pick this up.

**Comment by okikio** [comment]
Oh, OK 👍

**Comment by matthewp** [comment]
Hi @okikio, this should be working now in `next` which we are releasing today! Let me know if you find otherwise and we can reopen.
