### ISSUE TITLE
💡 RFC: Non constant page sizes in pagination

### ISSUE THREAD

**Issue by kaleidawave** [snowpackjs/astro#1203]
### Background & Motivation

I have the following design for a layout items:

![image](https://user-images.githubusercontent.com/26967284/130483862-80716659-838d-400f-9e98-6c16681a1446.png)

To do this I need a page with five items on the first page and six items on latter pages.

The current `pageSize` item on [`paginate`](https://docs.astro.build/reference/api-reference#paginate) is fixed. e.g I can either have pages of 5 items or pages of 6 items: `paginate(allPokemon, { pageSize: 5 /* or 6 */ });` not a mix.

I don't think there is a current way to do this using the current collections api

### Possible solutions

There could be a overload. If `pageSize` is `typeof pageSize === "object" && Symbol.iterator in pageSize` then could use a iterator to generate page sizes. 

For my problem I would use:

```js
const firstFiveThenSixes = {
  first: false,
  next() {
    if (this.first) {
      return {value: 6, done: false};
    } else {
      this.first = true;
      return {value: 5, done: false};
    }
  },
  [Symbol.iterator]: function () {return this;}
};

return paginate(items, { pageSize: firstFiveThenSixes  })
```

I think the current paginate function could be adapted to use this. I don't think any changes would be needed to any other apis. 

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [X] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
This feels like a pretty advanced use-case that I don't think the core team is able to prioritize. 

I'm happy to leave it here to collect feedback from the community, and to move this forward it will need a champion who would be willing to implement this if approved.

**Comment by jasikpark** [comment]
So is this RFC asking for support for custom pagination functions, where you can define your own iterator? What's stopping this from happening today without changes to astro?

**Comment by jasikpark** [comment]
In theory, you could simply take https://github.com/snowpackjs/astro/blob/74372a7d269882fe8bbcbf02a85a79296d58668f/packages/astro/src/build/paginate.ts and put in an importable package with the code changes you want!

`import { non-constant-paginate } from "@kaleidawave/non-constant-paginate";` 😆

**Comment by FredKSchott** [comment]
Ah, great call! paginate is just a helper to create pages, so you can build your own paginate function! 

Closing since that's definitely the way to support an advanced use case like this

**Comment by jasikpark** [comment]
That file is actually kind of confusing since it seems the function is called create paginate function which doesn't make a lot of sense to me as to how it actually works.￼

**Comment by FredKSchott** [comment]
internally, we have to create the `paginate()` function that we send to any page that asks for it. It's a different function for each page. Agreed its not the most clear.
