### ISSUE TITLE
🐛 BUG: Astro.resolve() doesn't work inside of components

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#1211]
### What package manager are you using?

yarn

### What operating system are you using?

mac

### Describe the Bug

It appears that Astro components cannot use `Astro.resolve()` inside of components, since the resolver will always run relative to the page and not the component. Because components can show up on many pages, this renders the feature unusable in components in most projects.

Astro.resolve() does appear to work inside of pages.

@matthewp mind prioritizing a fix for this?

### Steps to Reproduce

1. `npm init astro` using template portfolio
2. Go to https://github.com/snowpackjs/astro/blob/main/examples/portfolio/src/components/MainHead.astro
3. Update the `link[href]` attribute to use `Astro.resolve()`, on a file relative to the component (you may need to create a CSS file inside of your src directory, somewhere like "src/styles/index.css".
4. Run `yarn build`
5. Notice that the build fails because on at least one page, the relative path will not work.

**Comment by jasikpark** [comment]
I have very much experienced this when trying to use this feature
