### ISSUE TITLE
🐛 BUG: odd behaviour when adding `head` related element onto page/layout if imported layout included `head`

### ISSUE THREAD

**Issue by KivalEvan** [snowpackjs/astro#1219]
### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

If Inner layout or page import the Outer layout containing `head`, and Inner layout or page adds any `head` related element such as `link`, `meta`, and `title`, the `<!DOCTYPE html>` will be removed from the page.

If the layout contain a component with `style`, and Inner layout or page adds external stylesheet link, it will duplicate the component's style link to the top along with the added stylesheet link. (this only happen in `dev` but not on `build`, and I don't know the implication)

Unrelated but also related: if external stylesheet link is used in component, it will still compile and output the duplicate stylesheet link from head within the element; but `<!DOCTYPE html>` is not removed. (again, only happen in `dev`)

I believe this should've either thrown an error or a warning.

### Steps to Reproduce

1. Create an empty Astro project.
2. In `/public/`, create 2 `.css` files containing anything. (`style1.css` and `style2.css` as example)
```css
/* example, change color for another stylesheet */
div {
    color: blue;
}
```
3. Create `Test` component containing `<style>`. (optional but still related)
4. Create `Outer` layout containing empty HTML with `<slot />` in body, head only link to the first stylesheet.
```astro
<!DOCTYPE html>
<html lang="en">
<head>
    <title>test title</title>
    <link rel="stylesheet" href="/style1.css" />
</head>
<body>
    <slot />
</body>
</html>
```
5. Create `Inner` layout import outer layout and link to the second stylesheet.
```astro
---
import Outer from './Outer.astro';
import Test from '../components/Test.astro';
---
<link rel="stylesheet" href="/style2.css" />
<Outer>
    <slot />
    <Test />
</Outer>
```
6. Create a page using Inner layout.
```astro
---
import Inner from '../layouts/Inner.astro';
---
<Inner>
    <div>Test Site</div>
</Inner>
```
7. `npm run dev` or `npm run build`, no error was thrown but the output is described above.

Swap the `link` in `Inner` layout to page (and change `Inner` to `Outer` layout) for similar result.
This can be done with `meta` and `title`.

**Comment by matthewp** [comment]
Thanks for posting! I'm finding (5) a little confusing:

```astro
---
import Outer from './Outer.astro';
import Test from '../components/Test.astro';
---
<link rel="stylesheet" href="/style2.css" />
<Outer>
    <slot />
    <Test />
</Outer>
```

Given that Outer contains your doctype, html tag, head, etc. it seems like you should be rendering something like:

```html
<link rel="stylesheet" href="/style2.css">
<!DOCTYPE html>
<html lang="en">
...
```

But I'm fairly certain this is not what you want. Don't you want to put your link tag in a slot used by Outer?

**Comment by KivalEvan** [comment]
I didn't think putting it outside slot would still work, which is quite strange when it doesn't throw any error and causes side effect. I initially thought this can work but it shouldn't be.

**Comment by KivalEvan** [comment]
Another information to add now that you enlighten me a bit, ordering does seem to matter so putting it outside of slot at the bottom will be placed at the end of `body`. That stops `<!DOCTYPE html>` from getting deleted.

**Comment by matthewp** [comment]
That's because `Outer` is the owner of the `<body>`, if you put something after the body and not in the slot that Outer provides it will not go in the body. When using a layout component like you are doing you'll want to put all of your content within slots.
