### ISSUE TITLE
🐛 BUG: .well-known directory ignored during build

### ISSUE THREAD

**Issue by linux-china** [snowpackjs/astro#1238]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I have .well-known directory in public,  but it's ignored during build.  `.well-known` directory is very important for some cases.   https://en.wikipedia.org/wiki/List_of_/.well-known/_services_offered_by_webservers

### Steps to Reproduce

1.   Create .well-known directory in public
2.  Create a hello.txt file in public/.well-known directory 
3.  Run 'npm run build'
4.  `.well-known` not found in dist directory

**Comment by FredKSchott** [comment]
Thanks for the report! We believe that this has been fixed in astro v0.21, going out today. Let us know if you can still reproduce the issue after updating to v0.21 and we'll be happy to take a look.
