### ISSUE TITLE
🐛 BUG: Astro `0.20.0` breaks tailwind

### ISSUE THREAD

**Issue by builtbyproxy** [snowpackjs/astro#1256]
### What package manager are you using?

yarn

### What operating system are you using?

mac

### Describe the Bug

If you create a new astro project it will not allow you to import/use tailwind as described [here](https://docs.astro.build/guides/styling#-tailwind)

If I go to my `package.json` and downgrade from version `0.20.0` (in my case `0.20.3`), to `0.19.4` (the latest v19), it will load tailwind as intended. 

### Steps to Reproduce

1. `yarn create astro tailwind-test --template starter`
2. Select `react`
3. `yarn dev`
4. Cancel server
5. Follow these steps [here](https://docs.astro.build/guides/styling#-tailwind)
6. Replace the body contents of your `index.astro` file with: 
```
    <div class="bg-red-500">
        Hello BG Red
    </div>
```
7. `yarn && npx astro dev --reload --verbose`
8. refresh page, no tailwind in effect (background red)
9. downgrade `astro` in your `package.json` to `0.19.4`
10. `yarn && npx astro dev --reload --verbose`
11. refresh page, tailwind is in effect

**Comment by builtbyproxy** [comment]
My random thought is, if you look at the latest release notes, it's version `0.19` as of August 18, 2021. It seems odd, I'd get version `0.20` in the `init` phase if it's not live?

**Comment by jasikpark** [comment]
Does `yarm create astro --template with-tailwindcss` work for you? do we simply need to update the tailwind docs a bit?

**Comment by jasikpark** [comment]
> My random thought is, if you look at the [latest release notes](https://astro.build/blog/astro-019), it's version `0.19` as of August 18, 2021. It seems odd, I'd get version `0.20` in the `init` phase if it's not live? 

Latest is actually `0.20.3`, it just didn't get a blog post, I suppose. https://github.com/snowpackjs/astro/releases/tag/astro%400.20.3

**Comment by LuziferSenpai** [comment]
> Does `yarm create astro --template with-tailwindcss` work for you? do we simply need to update the tailwind docs a bit?
> 
> https://github.com/snowpackjs/astro/tree/main/examples/with-tailwindcss

Yea, so I wrote this in Discord in the support Channel already, but I tested the template and it works with Astro 18, but not with Astro 20.

**Comment by RodyGL** [comment]
As of **v0.0.20**, astro [won't process public files](https://github.com/snowpackjs/astro/releases/tag/astro%400.20.0).

In order to tailwindcss to work you need to move your css file inside **src** folder:

```
src
-- styles
    -- global.css
  -- pages
    -- index.astro
```

**_index.astro_**
`<link rel="stylesheet" href={Astro.resolve('../styles/global.css')} />`

**Comment by builtbyproxy** [comment]
I've used the above initial steps: 

<details>
  <summary>Initial Steps</summary>

 	  1. `yarn create astro tailwind-test --template starter`
	  2. Select `react`
	  3. `yarn dev`
	  4. Cancel server
	  5. Follow these steps [here](https://docs.astro.build/guides/styling#-tailwind)
	  6. Replace the body contents of your `index.astro` file with: 
	  ```
	      <div class="bg-red-500">
	          Hello BG Red
	      </div>
	  ```
	  7. `yarn && npx astro dev --reload --verbose`
	  8. refresh page, no tailwind in effect (background red)
</details>


and then from there tried: 

9. Fix file structure
```
	  src
	  -- styles
	      -- global.css
	    -- pages
	      -- index.astro
```
10. Fix index import
```
	<link rel="stylesheet" href={Astro.resolve('../styles/global.css')} />
```

I can confirm that has fixed tailwind for version 20 of Astro, I feel like a gumby 😂 I did move the files but didn't update the import 🤦

I've proposed a slight change to the documentation to follow up on this for others but if you've got other plans for the change, do what you will 😂
https://github.com/snowpackjs/astro/pull/1262

**Comment by Ridingst** [comment]
Thanks @RodyGL I've spent 3 hours looking for this issue.

**Comment by jasikpark** [comment]
> I've used the above initial steps: 
> 
> 
> 
> <details>
> 
>   <summary>Initial Steps</summary>
> 
> 
> 
>  	  1. `yarn create astro tailwind-test --template starter`
> 
> 	  2. Select `react`
> 
> 	  3. `yarn dev`
> 
> 	  4. Cancel server
> 
> 	  5. Follow these steps [here](https://docs.astro.build/guides/styling#-tailwind)
> 
> 	  6. Replace the body contents of your `index.astro` file with: 
> 
> 	  ```
> 
> 	      <div class="bg-red-500">
> 
> 	          Hello BG Red
> 
> 	      </div>
> 
> 	  ```
> 
> 	  7. `yarn && npx astro dev --reload --verbose`
> 
> 	  8. refresh page, no tailwind in effect (background red)
> 
> </details>
> 
> 
> 
> 
> 
> and then from there tried: 
> 
> 
> 
> 9. Fix file structure
> 
> ```
> 
> 	  src
> 
> 	  -- styles
> 
> 	      -- global.css
> 
> 	    -- pages
> 
> 	      -- index.astro
> 
> ```
> 
> 10. Fix index import
> 
> ```
> 
> 	<link rel="stylesheet" href={Astro.resolve('../styles/global.css')} />
> 
> ```
> 
> 
> 
> I can confirm that has fixed tailwind for version 20 of Astro, I feel like a gumby 😂 I did move the files but didn't update the import 🤦
> 
> 
> 
> I've proposed a slight change to the documentation to follow up on this for others but if you've got other plans for the change, do what you will 😂
> 
> ##### PR: https://github.com/snowpackjs/astro/pull/1262
> 
> 

Since that worked for you, I'll close the issue, since it sounds like your docs PR contains the solution
