### ISSUE TITLE
📘 DOC: Collections page is a 404

### ISSUE THREAD

**Issue by josh-collinsworth** [snowpackjs/astro#1258]
From the [API reference page](https://docs.astro.build/reference/api-referenc), under the `Astro.fetchContent()` heading, there's an Astro Collections link, that goes to `https://docs.astro.build/core-concepts/collections`. However, clicking this link results in a 404, and the page does not seem to exist in GitHub.

Would suggest/request either stubbing out the page, or removing the sentence and link.

**Comment by manigandham** [comment]
The Collections API was removed with version v0.19 
https://github.com/snowpackjs/astro/releases/tag/astro%400.19.0
