### ISSUE TITLE
📘 DOC: `lang` prop for `<Prism />` component

### ISSUE THREAD

**Issue by WaltzingPenguin** [snowpackjs/astro#1261]
The `<Prism />` component requires a language to be passed to it in order to function and the documentation does not even mention its existence.  If you leave it off, Astro does provide a warning `Prism.astro: No language provided.`, but guesswork is required to fix it.

**Comment by sarah11918** [comment]
Thanks for this, and good catch! I've submitted a pull request to update the documentation! https://github.com/snowpackjs/astro/pull/1264

**Comment by matthewp** [comment]
Thanks for taking care of this @sarah11918 !
