### ISSUE TITLE
🐛 BUG: Firebase Firestore "error loading dynamically imported module"

### ISSUE THREAD

**Issue by jthegedus** [snowpackjs/astro#1263]
### What package manager are you using?

npm

### What operating system are you using?

PopOS (Ubuntu)

### Describe the Bug

Importing Firestore into a Svelte component throws a `TypeError: error loading dynamically imported module` error and breaks the component.

Originally discussed in other issue https://github.com/snowpackjs/astro/issues/1016

### Steps to Reproduce

1. `npm init astro`. Choose skeleton with Svelte.js as the framework.
2. `npm i`
3. `npm i firebase`
4. Import Firebase in `src/components/svelteCounter.svelte`
	```diff
	+import { initializeApp, getApps } from "firebase/app";
	+import { getFirestore, doc, onSnapshot, setDoc } from "firebase/firestore";
	let count = 0;
	```
5. `npm run start`
6. Error is shown in browser console and Counter does not work.

	```
	Loading failed for the module with source “node:process”.
	Uncaught (in promise) TypeError: error loading dynamically imported module
	Loading failed for the module with source “http://localhost:3000/_snowpack/pkg/@firebase.webchannel-wrapper.v0.5.1.js”.
	```

### Link to Minimal Reproducible Example (Optional)

https://github.com/jthegedus/astro-firebase-bug-reproduction

**Comment by natemoo-re** [comment]
Looks like this is fixed in `astro@next` as we'd hoped! Please take a look at [this reproduction](https://stackblitz.com/edit/github-7qtycp?file=src%2Fcomponents%2FSvelteCounter.svelte). Let us know if you run into any more issues!

**Comment by jthegedus** [comment]
Will take a look thanks

**Comment by jthegedus** [comment]
This does indeed close the reported issue, thanks.
