### ISSUE TITLE
Requiring npm packages via require() should be supported in the frontmatter

### ISSUE THREAD

**Issue by RafidMuhymin** [snowpackjs/astro#1265]
### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

Currently, require() can't be used inside the frontmatter. We must use ESM imports to import a package. But it limits the packages that we can import. Because snowpack supports importing limited types of files. And it's also not possible for it to support each and every kind of file type (I think). So, we can't import packages like sharp, imagetools-core, requirejs etc. It's preventing us from achieving various tasks.

### Steps to Reproduce

Astro should add support for require() in the Astro frontmatter. Adding new Astro APIs and build APIs should provide a workaround to achieve the desired task but it may limit the things we can achieve.

**Comment by jasikpark** [comment]
Do you have an example of a package that isn't working for you? I believe snowpack natively supports importing CJS modules with ESM syntax 🤔

**Comment by RafidMuhymin** [comment]
@jasikpark sharp, imagetools-core, requirejs, etc.

**Comment by FredKSchott** [comment]
I think we're drawing a hard line at not supporting `require()` inside of frontmatter. CJS and ESM are two different module systems, and Node.js is doing its best to not mix and match.

What might make sense is not BLOCKING your ability to require, using https://nodejs.org/api/module.html#module_module_createrequire_filename. I don't think that we're currently blocking this.
