### ISSUE TITLE
🐛 BUG: ld+json script tags are not parsed

### ISSUE THREAD

**Issue by flowforfrank** [snowpackjs/astro#1266]
### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

`script` tags with an `application/ld+json` type are not parsed, eg.:

**Example**:

```jsx
<script type="application/ld+json">
    {JSON.stringify({
        '@context' : 'https://schema.org',
        '@type' : 'WebSite',
        'name' : websiteName,
        'url' : websiteURL
    })}
</script>
```

**Expected output:**

```jsx
<script type="application/ld+json">
    {
        "@context" : "https://schema.org",
        "@type" : "WebSite",
        "name" : "Google",
        "url" : "https://google.com"
    }
</script>
```

**Actual output:**

```jsx
<script type="application/ld+json">
    {JSON.stringify({
        '@context' : 'https://schema.org',
        '@type' : 'WebSite',
        'name' : websiteName,
        'url' : websiteURL
    })}
</script>
```

The following solutions are also not working:

```astro
---
const websiteSchema = JSON.stringify({
    '@context' : 'https://schema.org',
    '@type' : 'WebSite',
    'name' : websiteName,
    'url' : websiteURL
});
---

<script type="application/ld+json">{websiteSchema}</script>

<!-- or -->

<script type="application/ld+json">
    {
        '@context' : 'https://schema.org',
        '@type' : 'WebSite',
        'name' : {websiteName} <!-- using jsx expressions -->
        'url' : `${websiteURL}` <!-- using string interpolation -->
    }
</script>
```

### Steps to Reproduce

1. `npm init astro`
2.  Add a `script` tag to an `astro` component with a type of `application/ld+json`
3. Try to resolve a variable inside the schema markup
5. The variables are not parsed, they are outputted as is. See examples above.

**Comment by jasikpark** [comment]
You might be interested in https://github.com/snowpackjs/astro/issues/1107, since it's a similar usecase. Does a fully static json-ld tag work? Can you pull the js tags into the content variable?

```astro
---
const { interpolatedVar } = Astro.props;
let data = `
<script type="json+ld">
data data data 😆 ${interpolatedVar}
</script>`;
---
{data}
```

**Comment by flowforfrank** [comment]
Yes, this does seem to fix the issue for now. Thank you @jasikpark for the quick one.

**Comment by outbackStack** [comment]
@jasikpark 

You suggestion was was working on `astro": "^0.23.0"` until I updated to `"astro": "^1.0.0-beta.41",`. Is there a new way to parsed the variables in the script tags?

I've tried all the directives on this guide and none of them work.
https://docs.astro.build/en/reference/directives-reference/#script--style-directives

**Comment by flowforfrank** [comment]
For future reference, this can be achieved in the following way with the latest version of Astro (v4.6.1 at the time of writing):

```astro
---
const schema = `
    {
        "@context": "https://schema.org",
        "@type": "WebSite"
    }
`
---

<script type="application/ld+json" set:html={schema} />
