### ISSUE TITLE
RFC Call: Sept 14, 2021

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#1278]
> **NOTE:** No RFC call on September 7th: many of the core team members are taking some much needed time off for the long weekend. We'll be back again September 14!

## Agenda: 

- https://github.com/snowpackjs/astro/issues/1350: @matthewp 
- https://github.com/snowpackjs/astro/issues/1301: @jonathantneal

**Comment by jasikpark** [comment]
Perhaps @jonathantneal's proposal for programmatic access to slots? #1301!

**Comment by drwpow** [comment]
Possibly https://github.com/snowpackjs/astro/issues/1349?
