### ISSUE TITLE
🐛 BUG: Current page on the sidebar is not highlighted

### ISSUE THREAD

**Issue by chenxsan** [snowpackjs/astro#1307]
### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

![image](https://user-images.githubusercontent.com/1091472/132087561-f3beeb93-01eb-4f59-97d8-3af7e78499d6.png)

As you can see from the screenshot above, I'm at page https://docs.astro.build/getting-started, but the `aria-current` value is `false` instead of `page`. I've tried the latest code under the `docs` directory, nothing wrong. So I'm not sure what's going on here.

### Steps to Reproduce

Just open the doc https://docs.astro.build/getting-started.

**Comment by jasikpark** [comment]
Fixed by #1299

**Comment by jasikpark** [comment]
You can view the fix at https://next.docs.astro.build/getting-started!

**Comment by chenxsan** [comment]
@jasikpark Awesome! Glad it's fixed.
