### ISSUE TITLE
💡 RFC: dynamic component

### ISSUE THREAD

**Issue by raph5** [snowpackjs/astro#1318]
### Background & Motivation

I am creating a web site managed by a headless CMS. And after a few api calls i have an object like this :
```js
const data = {
  landingPage: {
    components: [
      {component: "banner", props: {logo: "lorem ipsum"}},
      {component: "textSection", props: {title: "lorem ipsum !", text: "lorem ipsum..."}},
    ]
  },
  otherPage: {...},
}
```
I solved the pagination problem by following the doc's pagination guide (:ok_hand:). But now i have to dynamically put the right components (that i previously made) with the right props in each pages.

And i dont find a native way to do that.

### Proposed Solution

to solve this problem i made a `DynamicComponent.astro` component :
```js
---
const { component, componentName, propertys={} } = Astro.props;

const textProps = Object.keys(propertys).map(p => `${p}="${propertys[p]}"`).join(' ');
---

{ component.__render(`<${componentName} ${textProps} />`) }
```

But it would be better to have a native astro solution

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by jasikpark** [comment]
@jonathantneal this feels like some shenanigans you've been up to with your shapeshifting span 😆

I'd say couldn't you just do something like

```astro
---
import Banner from "./Banner.astro";
import TextSection from "./TextSection.astro";

const { componentName, passedThroughProps={} } = Astro.props;
---

{ 
	// This is an immediately invoked function that contains a switch statement, 
	// so you can match against different things!
	(()=> {
		switch (componentName) {
			case: "banner": return <Banner {...passedThroughProps}/>;
			case: "textSection": return <TextSection {...passedThroughProps}/>;
			// default: return some default component
	})()
}
```

**Comment by raph5** [comment]
ok thank's
