### ISSUE TITLE
🐛 BUG: `Astro.site` should resolve to `localhost:PORT` when on dev server, even if `site` is set in `astro.config.mjs`

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro#1319]
### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

You can see in `astro/docs` that `Astro.site` resolves to `https://docs.astro.build/` when running the dev server, rather than `localhost:3000`, which is what I would expect `Astro.site` to resolve to, similar to [Hugo](https://gohugo.io/documentation/)

### Steps to Reproduce

1. clone astro project
2. `yarn`
3. `yarn build`
4. `yarn workspace docs start`
5. Print out  `console.debug(Astro.site)`:
```js
URL {
  href: 'https://docs.astro.build/',
  origin: 'https://docs.astro.build',
  protocol: 'https:',
  username: '',
  password: '',
  host: 'docs.astro.build',
  hostname: 'docs.astro.build',
  port: '',
  pathname: '/',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
```

`console.debug(Astro.site.toString())` => `https://docs.astro.build/`

@chenxsan [sorted out](https://github.com/snowpackjs/astro/pull/1308#issuecomment-913109189) that it's probably set in https://github.com/snowpackjs/astro/blob/main/packages/astro/src/runtime.ts#L93

**Comment by matthewp** [comment]
This was fixed via https://github.com/snowpackjs/astro/pull/1387
