### ISSUE TITLE
🐛 BUG: Svelte hydration/hmr

### ISSUE THREAD

**Issue by JBTurtlin** [snowpackjs/astro#1321]
### What package manager are you using?

npm

### What operating system are you using?

Linux (Ubuntu 20.04 on WSL2)

### Describe the Bug

I get the following error in dev using the default svelte starter:

![svelte_hmr_bug](https://user-images.githubusercontent.com/28937963/132137264-05669685-4a40-4a45-bf9e-a032135ae467.png)

Ostensibly an hmr issue as npm run preview works fine.  

### Steps to Reproduce

1. `npm init astro` using template <Starter KIt (Generic)>
2. Select Svelte
3. npm i && npm start
4. Scroll down to SvelteCounter

**Comment by jasikpark** [comment]
Do you get the same error with my reproduction of that? https://codesandbox.io/s/github/jasikpark/astro-1321-reproduction && https://6ukce.sse.codesandbox.io/?

**Comment by JBTurtlin** [comment]
Both those links work fine.  I noticed you used yarn and so I tried that locally and that did the trick, no error.  Went back to npm (v7.22.0) as a sanity check and getting the error,  I also tried rolling back to npm v6.14.15 but no luck.  I couldn't find anyone else having the same problem so maybe it's an oddity with npm and my particular dev environment.  I can use yarn in the meantime, cheers.

**Comment by jasikpark** [comment]
Well, I'd like to find out if there *is* a problem with npm + astro, but I'm glad it's working for you!

**Comment by JBTurtlin** [comment]
Sorry, I jumped the gun on this.  The issue is that very rarely everthing works fine.  Unfortunately that also means I can't reproduce the bug.  I figured I should reopen in case someone else encounters it.

**Comment by matthewp** [comment]
Just created a new project and I'm not able to recreate. Happy to reopen if you're able to continue getting this to happen or if others are getting the problem as well.
