### ISSUE TITLE
📘 DOC: Add codesandbox.io links for starter templates!

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro#1327]
Codesandbox supports creating a sandbox from a git repo, so it'd be great to add a link to each example's readme that lets you get started on codesandbox with it! This would be great for creating reproductions of issues as well!

- https://codesandbox.io/docs/importing
- https://github.com/snowpackjs/astro/tree/main/examples/minimal becomes https://githubbox.com/snowpackjs/astro/tree/main/examples/minimal

It'd also be great to add a dropdown to the `getting-started` page on docs! "Select from one of these starters, and we'll open a new codesandbox based on it in a new tab!

**Comment by jasikpark** [comment]
Right here: https://next.docs.astro.build/getting-started#example-projects

**Comment by jasikpark** [comment]
:eyes: https://codesandbox.io/docs/importing#import-using-remark-codesandbox seems perfect:

https://github.com/kevin940726/remark-codesandbox

**Comment by aFuzzyBear** [comment]
I had it the vast majority of the templates working and deployed with gitpod and codesandbox, with badges on the example page for one click deployment, tbh I need to get that back up and done properly but the leg work is already done bud

**Comment by jasikpark** [comment]
I suppose this issue has been appeased partially by adding StackBlitz embeds to the repo readmes: https://github.com/snowpackjs/astro/tree/main/examples/blog and also by implementing <astro.new> [internet archive](https://web.archive.org/web/20211117232109/https://astro.new/)
