### ISSUE TITLE
Prepare for sponsorship

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#1330]
If all goes well, we should have some exciting news to share later this week: Astro's secured its first major sponsorship! I won't spoil the surprise just yet, but we need to do some work this week to prepare for the announcement. Here's a list of what needs to get done this week to successfully launch the sponsorship:

- [x] prepare sponsors logos/avatars placement on our repo README
- [x] prepare sponsors logos/avatars placement on our homepage
- [x] prepare sponsors logo placement on our docs sidebar
- [x] Add "Deploy with Netlify" buttons on all GitHub starter template READMEs
- [x] Move our starter "themes" out of the "examples/" monorepo directory and into their own repos 
    - required for "Deploy with XXX" button to work
    - mark those repos as "template" in github
    - note: can we maintain these repos as copies from the monorepo? Or, should these 4-5 all-in-one starter templates 
- [x] update links: https://next.docs.astro.build/themes
- [x] Blog post
- [x] Get hosted demos for every theme
- [x] Move Astro hosting from Vercel to Netlify (partially done, in progress)

Follow up work:

- [ ] decide where themes are maintained, long-term

**Comment by jasikpark** [comment]
> note: can we maintain these repos as copies from the monorepo? Or, should these 4-5 all-in-one starter templates (note: different from examples) be moved out into individual repos for the long-term?

Maybe they can be maintained as git submodules? though I suppose that doesn't truly help anything.. if only helpful as a way of linking them all in one central structure.

**Comment by FredKSchott** [comment]
Yea, I've heard that git submodules can be more trouble than they're worth.

Previously I think the team would be worried about moving these examples out of the monorepo because we'd lose the ability to test them. But, now that we're comfortable with GH Actions I think we could create an even better test suite by having these live separately. We constantly miss configuration/package.json bugs due to our monorepo hiding dependency issues.

**Comment by jasikpark** [comment]
It'll be nice if we can have all of them deployed as static sites so that people can easily click away into the demo!

**Comment by FredKSchott** [comment]
> It'll be nice if we can have all of them deployed as static sites so that people can easily click away into the demo!

💯💯💯

**Comment by FredKSchott** [comment]
Made some good progress here! All thats remaining are logo placements.

Note that themes have now been broken off into a new Astro organization (better late than never!). Right now we maintain them in both places, so pretty soon we'll need to make a decision about where they should live, long-term.

**Comment by FredKSchott** [comment]
@drwpow if you have any time this week, it would be great if you could tackle the logo placement on the homepage + README + docs site.

**Comment by jasikpark** [comment]
This should be completed by #1317!

**Comment by FredKSchott** [comment]
Done as of last week! Thanks @drwpow for the last minute help. 
/cc @jlengstorf
