### ISSUE TITLE
🐛 BUG: Astro website fails to deploy using Node v16.8.0

### ISSUE THREAD

**Issue by jgil-r** [snowpackjs/astro#1333]
### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

Astro docs state that I can use node v16.0.0 or higher (using v16.8.0), but still  fails to deploy on Netlify. 

### Steps to Reproduce

5:15:16 PM: Installing NPM modules using Yarn version 1.22.10
5:15:17 PM: yarn install v1.22.10
5:15:17 PM: [1/4] Resolving packages...
5:15:18 PM: [2/4] Fetching packages...
5:15:23 PM: error astro@0.20.4: The engine "node" is incompatible with this module. Expected version "^12.20.0 || ^14.13.1 || >=16.0.0". Got "12.18.0"
5:15:23 PM: error Found incompatible module.
5:15:23 PM: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
5:15:23 PM: Error during Yarn install
5:15:23 PM: Build was terminated: Build script returned non-zero exit code: 1
5:15:23 PM: Creating deploy upload records
5:15:23 PM: Failing build: Failed to build site
5:15:23 PM: Failed during stage 'building site': Build script returned non-zero exit code: 1
5:15:24 PM: Finished processing build request in 34.760320402s

**Comment by jgil-r** [comment]
Adding `node` to `.nvmrc` fixed it.

**Comment by jasikpark** [comment]
Did it need to be `node v16.8.0`? I'll make a PR to the [docs](https://docs.astro.build/guides/deploy#netlify) to update.

**Comment by jasikpark** [comment]
done: https://github.com/snowpackjs/astro/pull/1337

**Comment by jgil-r** [comment]
> Did it need to be `node v16.8.0`? I'll make a PR to the [docs](https://docs.astro.build/guides/deploy#netlify) to update.

I just have `node` in `.nvimrc` file, which would be `v16.9.0`
