### ISSUE TITLE
💡 RFC: process the content inside script

### ISSUE THREAD

**Issue by chenxsan** [snowpackjs/astro#1348]
### Background & Motivation

Here's the script in a `index.astro` file:

```
<script type="module">
  import copy from 'clipboard-copy'
  document.addEventListener('click', () => {
    copy(123);
  });
</script>
```
It won't work at the moment with an error:

> Uncaught TypeError: Failed to resolve module specifier "clipboard-copy". Relative references must start with either "/", "./", or "../".

As far as I know, the code would work fine with snowpack - correct me if I was wrong as I just conclude it from the snowpack documentation.

### Possible solutions

I'm not quite sure of how snowpack works, maybe process the script first so we can take advantage of the npm packages? I know it's possible to import that `copy` from an ESM version on CDN, but I would prefer to manage those packages in my `package.json`.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [X] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
Yes! see this similar RFC where we are tracking this in the new compiler: https://github.com/snowpackjs/astro/issues/997
