### ISSUE TITLE
🐛 BUG: astro dev crashing on JSX expression syntax error

### ISSUE THREAD

**Issue by Volper212** [snowpackjs/astro#1352]
### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

I'm using node version v16.6.1, which is a version that exits the process on unhandled rejections. I think that might be the problem

### Steps to Reproduce

1. `npm init astro` (`Enter` all the way)
2. `npm i`
3. `echo "{}" > src/pages/index.astro`
4. `npm run dev`
5. Open `localhost:3000` in the browser
6. Dev server crashed
![image](https://user-images.githubusercontent.com/47470991/132947389-da5849e6-646e-4b02-afac-071a315bf90a.png)
Expected behavior: server continues running, shows error in the browser.

Steps 1-3 can be skipped by just cloning the minimal reproducible example

### Link to Minimal Reproducible Example (Optional)

https://github.com/Volper212/astro-bug-report

**Comment by natemoo-re** [comment]
Confirming that this is fixed in the new compiler. Empty expressions are no longer treated as errors, so the dev process definitely won't crash. [See REPL link](https://astro.build/play#eyJpbm1lbW9yeTovL21vZGVsL3NyYy9wYWdlcy9QYWdlLmFzdHJvIjoie30ifQ==)

**Comment by jasikpark** [comment]
> Confirming that this is fixed in the new compiler. Empty expressions are no longer treated as errors, so the dev process definitely won't crash. [See REPL link](https://astro.build/play#eyJpbm1lbW9yeTovL21vZGVsL3NyYy9wYWdlcy9QYWdlLmFzdHJvIjoie30ifQ==)

Is that outputting correctly? I'm seeing `}` output in the REPL link but I would expect ``, aka an empty component to be output.
