### ISSUE TITLE
🐛 BUG: WASM Compiler REPL renders <title> element to page in the preview pane 

### ISSUE THREAD

**Issue by matsdahlin** [snowpackjs/astro#1362]
### What package manager are you using?

https://astro.build/play

### What operating system are you using?

Mac

### Describe the Bug

When using a variable `{someVariable}` inside the `<title>` tags, anything added _after_ the variable gets rendered to the page in the REPL preview pane:

![astro-wasm-repl](https://user-images.githubusercontent.com/337696/133223755-f9ec0bae-49b3-4ec5-a76d-1e48b8e22373.png)

### Steps to Reproduce

1. go to https://astro.build/play
2. type in any text _after_ the {name} variable inside the <title> tags
3. Error! The text after the variable use is getting rendered to the preview pane

**Comment by FredKSchott** [comment]
<img width="1021" alt="Screen Shot 2021-09-14 at 2 42 23 PM" src="https://user-images.githubusercontent.com/622227/133337896-9695114b-edfa-4201-adae-2b5acb1da893.png">

wierdddddd
