### ISSUE TITLE
🐛 BUG: dev mode fails to init svelte components

### ISSUE THREAD

**Issue by pointout** [snowpackjs/astro#1365]
### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

When using a (simple) svelte component to an astro component, there is an "Failed to init component"-error in dev mode. Building and previewing the page that includes the components works.

### Steps to Reproduce

1. `npm init astro` using template starter
2. create a svelte component
3. include the svelte component into a astro component or astro page
4. start `npx astro dev` and open page in the browser
5. The page shows an error overlay. In my case: `
Failed to init component <ExchangeRates> SvelteComponentDev@http://localhost:3300/_snowpack/pkg/svelte.internal.v3.42.5.js:1821:13
ExchangeRates@http://localhost:3300/_astro/src/components/catalog/ExchangeRates.svelte.js:72:3
createProxiedComponent@http://localhost:3300/_snowpack/pkg/svelte-hmr.runtime.hot-api-esm.v0.13.5.js:242:9
ProxyComponent@http://localhost:3300/_snowpack/pkg/svelte-hmr.runtime.hot-api-esm.v0.13.5.js:482:42
Proxy<ExchangeRates>@http://localhost:3300/_snowpack/pkg/svelte-hmr.runtime.hot-api-esm.v0.13.5.js:581:11
create_fragment@http://localhost:3300/_snowpack/pkg/@astrojs.renderer-svelte.client.v0.1.1.js:77:21
init@http://localhost:3300/_snowpack/pkg/svelte.internal.v3.42.5.js:1647:35
Wrapper@http://localhost:3300/_snowpack/pkg/@astrojs.renderer-svelte.client.v0.1.1.js:160:7
client/<@http://localhost:3300/_snowpack/pkg/@astrojs.renderer-svelte.client.v0.1.1.js:167:7
@http://localhost:3300/de/katalog/kategorie/kunst/:7:39
onLoad@http://localhost:3300/_astro_frontend/hydrate/load.js:7:12
async*@http://localhost:3300/de/katalog/kategorie/kunst/:4:6
`
``
The browser console shows: `[HMR][Svelte] Unrecoverable error in <ExchangeRates>: next update will trigger a full reload svelte-hmr.runtime.hot-api-esm.v0.13.5.js:256:11
    logError svelte-hmr.runtime.hot-api-esm.v0.13.5.js:256
    Proxy<ExchangeRates> svelte-hmr.runtime.hot-api-esm.v0.13.5.js:612
    create_fragment @astrojs.renderer-svelte.client.v0.1.1.js:77
    init svelte.internal.v3.42.5.js:1647
    Wrapper @astrojs.renderer-svelte.client.v0.1.1.js:160
    client @astrojs.renderer-svelte.client.v0.1.1.js:167
    <anonym> (index):7
    onLoad load.ts:12
    <anonym> `

6. Building and previewing the page works as expected.

The svelte component only fetches data from an api and writes them into the localStorage.

**Comment by pointout** [comment]
Update to Astro 0.20.7 didn't solve the issue.

**Comment by pointout** [comment]
Maybe in 0.20.7 this is solved. Just reloaded the pages are shown without error in dev mode. I will watch and close the issue, if there is no error in near future.

**Comment by pointout** [comment]
Looks good since Update to 0.20.7 - I close this.

**Comment by mzaini30** [comment]
How to fix it? I still get that error.

**Comment by pointout** [comment]
I updated to 0.20.7 and did a reload in Firefox. In chromebased browsers I had to reload the page for several times. Don't know why, but in the end it woked there also.
