### ISSUE TITLE
🐛 BUG: Astro.props is null [astro-compiler-next]

### ISSUE THREAD

**Issue by jonathantneal** [snowpackjs/astro#1367]
### What package manager are you using?

browser

### What operating system are you using?

Mac

### Describe the Bug

Using https://astro.build/play, if I don’t pass any props to a component — `<Component />` — then `Astro.props` is `null`, which throws when I use a spread in that component — `const { name = "Component" } = Astro.props`.

### Steps to Reproduce

1. Goto https://astro.build/play
2. Add a component.
3. Change `const name = "Component"` to `const { name = "Component" } = Astro.props`
4. Add `<Component />` to `Page.astro`.
5. TypeError! Right side of assignment cannot be destructured.

### Link to Minimal Reproducible Example (Optional)

https://astro.build/play

**Comment by natemoo-re** [comment]
Closed in https://github.com/snowpackjs/astro-compiler-next/pull/19
