### ISSUE TITLE
RFC Call: 28 Sep 2021

### ISSUE THREAD

**Issue by drwpow** [snowpackjs/astro#1369]
### Agenda

* https://github.com/snowpackjs/astro/issues/1349
* https://github.com/snowpackjs/astro/issues/1305

**Comment by FredKSchott** [comment]
> From @natemoo-re, in Discord:
> Hey everyone! There are some big changes to Astro in flight right now, so rather than having our usual RFC call, we wanted to give everyone the opportunity to ask some questions and get direct answers from the core team regarding yesterday's big announcements.

Regular RFC call will resume next week, on Sept. 28!

**Comment by jonathantneal** [comment]
Possibly https://github.com/snowpackjs/astro/issues/1450 ?

**Comment by matthewp** [comment]
Successful RFC call!
