### ISSUE TITLE
🐛 BUG: misleading error message if unexpected text exists in top-level <html> element

### ISSUE THREAD

**Issue by amagee** [snowpackjs/astro#1373]
### What package manager are you using?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

If I mistakenly put some text directly inside my `<html>` tag in an `.astro` component, then the dev process gives an output like 

```
[parse-error] [61:179]: Expected ')'
```

and viewing the resulting page in the browser gives an output like

```
SyntaxError: [61:179]: Expected ')'
```

To reproduce the issue, a `<body>` tag is also necessary.

So the following `.astro` page will exhibit the issue:

```
---
---
<html lang="en">
  some stuff
  <body>
    123
  </body>
</html>
```

but this one will not:

```
---
---
<html lang="en">
  some stuff
</html>
```

### Steps to Reproduce

1. `npm init astro` using any template
2. Place the following in the `index.astro` file:

```
---
---
<html lang="en">
  some stuff
  <body>
    123
  </body>
</html>
```

3. Error! as mentioned above. Desired behaviour: either a working page saying "some stuff 123", or an error message correctly describing the problem.

**Comment by coelmay** [comment]
When doing `astro build` on this code the result is
```
SyntaxError: [61:196]: Expected ')'
    at file:///Volumes/500GBSSD/projects/astro/bad-text/src/pages/index.astro
    ...
    at parseFunctionBody (/Volumes/500GBSSD/projects/astro/bad-text/node_modules/meriyah/dist/meriyah.umd.js:3875:21)
```
I cannot find an error message matching this format in the astro codebase though in `meriyah.umd.js` there is
```
const errorMessages = {
    // other messages
    [23]: "Expected '%0'",
    // more messages
}
```
While Astro doesn't use meriyah directly (that I can find) snowpack does in [ssr-loader/transform.ts](https://github.com/snowpackjs/snowpack/blob/91da2b6af73bc7c639e3e94a6cf7010cd0e1e14a/snowpack/src/ssr-loader/transform.ts#L9)

**Comment by natemoo-re** [comment]
This is fixed in the new compiler! We'll just print out the HTML you give us. [See REPL link](https://astro.build/play#eyJpbm1lbW9yeTovL21vZGVsL3NyYy9wYWdlcy9QYWdlLmFzdHJvIjoiLS0tXG4tLS1cbjxodG1sIGxhbmc9XCJlblwiPlxuICBzb21lIHN0dWZmXG4gIDxib2R5PlxuICAgIDEyM1xuICA8L2JvZHk+XG48L2h0bWw+IiwiaW5tZW1vcnk6Ly9tb2RlbC9zcmMvY29tcG9uZW50cy9Db21wb25lbnQuYXN0cm8iOiI8aDE+SGVsbG8gPHNsb3QgLz48L2gxPiJ9).
