### ISSUE TITLE
🐛 BUG: buildOptions.baseUrl not honored in snowpack.config.mjs

### ISSUE THREAD

**Issue by dylanspurgin** [snowpackjs/astro#1378]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

My project is being deployed to a subdirectory so I need the path to the css in the template `<link>` element to be relative. Reading through the docs, it appears that snowpack supports this with [buildOptions.baseUrl](https://www.snowpack.dev/reference/configuration#buildoptionsbaseurl) and that [Astro supports configuring Snowpack using snowpack.config.mjs](https://docs.astro.build/reference/configuration-reference#snowpack-config) but I cannot seem to get this to work.

No matter what configuration I throw at it, my stylesheet link always starts with a forward slash:
`<link rel="stylesheet" href="/_astro/index-Z2gNdb6.css" type="text/css">`

### Steps to Reproduce

1. `npm init astro` using template Minimal
2. Add a `style` section to `src/pages/index.astro` with any single css rule so it will create a `<link>` tag for importing the stylesheet in the build.
3. Add `snowpack.config.mjs`:
```javascript
export default {
    plugins: [],
    buildOptions: {
        baseUrl: '.' // Also tried '/prefix'
    }
};
```
4. `npm run build`
5. Path to stylesheet in `/dist/index.html` is not prefixed with the value of `buildOptions.baseUrl`

**Comment by coelmay** [comment]
Have you tried setting the `buildOptions.site` in `astro.config.mjs`?
https://github.com/snowpackjs/astro/blob/ad2962fdacb23589db5e33789aba82e8bde836ce/packages/astro/src/%40types/config.ts#L52-L53

**Comment by dylanspurgin** [comment]
I had indeed tried various values for `buildOptions.site` in my project and I tried it again just now in the scaffolded Minimal project as well and it does not change the output of the `<link>` href in `dist/index.html`.

**Comment by dylantrooien** [comment]
Same issue.
tried
snowpack mount options,
projectRoot, site, baseUrl Settings

**Comment by matthewp** [comment]
Yep, this is a known issue: https://github.com/snowpackjs/astro/issues/968. If you have details that are covered in that issue, please add them there. Thanks!
