### ISSUE TITLE
CSS output dir📘 DOC: 

### ISSUE THREAD

**Issue by PaulieScanlon** [snowpackjs/astro#1386]
Hi folks! I'm having a small problem deploying to GitHub pages.

I have some styles in a component and all is well and working locally and when i run a build i can see the `xyz.css` in `dist/_astro` however, It would appear as though GitHub pages doesn't like dir names that included underscores.

If i manually change the dir name and reference in `index.html` to `astro/xyz.css` everything works fine when deployed.

Is there anything in the config options that will allow me to change the name of the dir where the compiled css lives? E.g somewhere in snowpack could i change this output dir to `css` or something similar and would that get applied correctly as the path to the css in `index.html`?

GitHub pages doesn't like this:
```
mysite.github.io/_astro/xyz.css
```

But it does work if i do either of the following:

```
mysite.github.io/astro/xyz.css
mysite.github.io/css/xyz.css
```

**Comment by PaulieScanlon** [comment]
Looks like this is what i'm looking for: 

https://docs.astro.build/guides/deploy#github-pages

**Comment by Tahmeed-programmer** [comment]
> Looks like this is what i'm looking for:
> 
> https://docs.astro.build/guides/deploy#github-pages

the page doesnt exist and i am facing similar issues, how do I resolve it?

**Comment by PaulieScanlon** [comment]
Hmm. Good question. That was 2 years ago. I can't even remember what I did this morning.

Here's the repo, which did work but I have deployed it for 2 years.

https://github.com/PaulieScanlon/pauliescanlon.github.io

**Comment by Tahmeed-programmer** [comment]
> Hmm. Good question. That was 2 years ago. I can't even remember what I did this morning.
> 
> Here's the repo, which did work but I haven't deployed it for 2 years.
> 
> https://github.com/PaulieScanlon/pauliescanlon.github.io

appreciate ur reply, i also noticed another issue which is when i add "./astro" then my files start working. Let me xplain my process , i first build my astro pages by setting the base in the config as lawyer1 as that is where i will be copying my files to. after its built i copy the contents of that dist folder to a file called lawyer1 which is a repo under my github pages. but then the path "lawyer1/astro" causes issue and the path "./astro" doesnt , why ?
