### ISSUE TITLE
🐛 BUG: Building large amount of pages fails with "too many files open"

### ISSUE THREAD

**Issue by kometbomb** [snowpackjs/astro#1389]
### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

When building a large count of pages (e.g. /pages/[1-10000].html) the build script fails with "EMFILE: too many files open".

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. create a route and getStaticPaths() that outputs e.g. page slugs from 1 to 10000
3. `npm run build`
5. build throws `EMFILE: too many open files` after optimizing the CSS

### Link to Minimal Reproducible Example (Optional)

https://github.com/kometbomb/astro-file-handle-bug

### Fix

https://github.com/kometbomb/astro/pull/1

**Comment by kometbomb** [comment]
Pushed a working fix here: https://github.com/kometbomb/astro/pull/1

I was unable to reopen the original PR so I'll just leave this here to avoid further confusion.

**Comment by jasikpark** [comment]
this reminds me that https://github.com/tc39/proposal-weakrefs exists 😁 though it's probably not pertinent

**Comment by kometbomb** [comment]
I agree that quite often when there is a long running JS script you run into that kind of problems with the GC not triggering soon enough. But in this case, I think even with weak refs it could be that the writeFile() call takes long enough that the previous promises have time to also call writeFile() until there are too many handles open. So, doing each job "synchronously" solves that problem. Now that I think about it, I am not sure if the close() call is needed.

**Comment by matthewp** [comment]
Thanks for submitting a fix for this!
