### ISSUE TITLE
RFC: Explore alternative `props` API

### ISSUE THREAD

**Issue by natemoo-re** [snowpackjs/astro#139]
Currently, `.astro` files expose component `props` in [the Svelte-style](https://svelte.dev/tutorial/default-values), using the `export` keyword. While this might be familiar to Svelte users, it does overload a keyword that JavaScript uses for other purposes. Any other ideas that might make sense here? (Note: we might stay with what we have! Just wanted to open the floor for suggestions.)

> This is a pretty confusing/surprising API. Typically `export` provides data to other modules, but this inverts that. I’m not sure I have a better solution in mind, but I’ll think on it if there’s interest on the Astro team.

_Originally posted by @eyelidlessness in https://github.com/snowpackjs/astro/pull/137#discussion_r622414775_

**Comment by Aurelius333** [comment]
Vue's new experimental [`<script setup>` syntax](https://github.com/vuejs/rfcs/pull/227) uses a function `defineProps` for declaring props. Maybe something like that would be nicer in TypeScript compared to casting `Astro.props as Props`.

Vue example:
```html
<script setup lang="ts">
  import { defineProps } from 'vue';

  const props = defineProps<{
    foo: string;
    bar?: number;
  }>();
</script>
```

**Comment by jasikpark** [comment]
Why not just have the same api, but choose an acceptable "keyword" for props like `prop default hello = "hello world"` instead of `export default hello = "hello world"` and exports can be used to expose data from components?

**Comment by romaricpascal** [comment]
Following down that trail, a [label](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/label) could avoid introducing a new keywoard. A bit like what Svelte does to identify reactive expressions with `$:`

```js
prop: let showTitle = false;
```

**Comment by FredKSchott** [comment]
RFC Call Consensus: move forward with the `A. The Nate approach` as outlined above, with smaller details (ex: `Astro.props` vs. `Astro.defineProps`) to be discussed and resolved separately.

**Comment by Aurelius333** [comment]
I just realized that if `Astro.props` is given the type `any`, I think you can write
```ts
const props: Props = Astro.props
```
instead of
```ts
const props = Astro.props as Props
```
. It’s a small difference, but it feels better to me than using a type cast. 

With that in mind, I think `Astro.props` is better than my `Astro.defineProps` suggestion, even in TypeScript. (Vue also has other reasons for using `defineProps` that don’t apply to Astro.)

**Comment by FredKSchott** [comment]
yup, agreed that both forms should be supported.
