### ISSUE TITLE
🐛 BUG: React.PureComponent not supported from top-level

### ISSUE THREAD

**Issue by KMarshland** [snowpackjs/astro#1400]
### What package manager are you using?

npm

### What operating system are you using?

Mac (catalina)

### Describe the Bug

When rendering a react component from an astro page, it does not recognize that the react renderer will work, throwing the error:

```
Error: No renderer found for StaticComponent! Did you forget to add a renderer to your Astro config?
```

It works if I make the component inherit from `React.Component` rather than `React.PureComponent`, or if I have a wrapper component that does so and simply renders the original component. 

Presumably, in checking which render to use, it checks if a component inherits from React.Component but not React.PureComponent. I'd be happy to make this my first PR if someone can point me toward a file to look at!

### Steps to Reproduce

A simple example is as follows. In `page.astro`:
```
---
import StaticComponent from '../components/static_component.jsx';

---

<body>
<StaticComponent />
</body>
```

The component looks like:
```
import React from 'react';

export default class StaticComponent extends React.PureComponent {

    render() {
        return (
            <div>
                <h1>Static component</h1>
            </div>
        )
    }

}
```

**Comment by matthewp** [comment]
Very interesting! I think I have an idea what causes this, going to take a look.

**Comment by matthewp** [comment]
PR submitted: #1467
