### ISSUE TITLE
Add workspaceRoot/node_modules to sass includePaths

### ISSUE THREAD

**Issue by chee** [snowpackjs/astro#1426]
### Background & Motivation

I'm working with a component system in a monorepo, and i want to build an example app in there using astro. When I do an npm install in the root all the components are available in the root's node_modules directory, and this works fine for JavaScript because of node's module resolution system but not for sass.

### Possible solutions

It would be nice if the snowpack `workspaceRoot` was included in [the sass includePaths](https://github.com/snowpackjs/astro/blob/74372a7d269882fe8bbcbf02a85a79296d58668f/packages/astro/src/compiler/transform/styles.ts#L88-L101)

#### config

a way to customize the includePaths

#### emulate node modules resolution system

keep doing `findUp` until you find a `node_modules` that contains a path matching the imported file, or you hit `/`

#### do nothing

i can install every component, and all of their sass dependencies (and all of their dependencies) in my project, and that will work too.

### Risks, downsides, and/or tradeoffs

maybe complexity

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by lunelson** [comment]
For advanced Sass use-cases it would be great if the entire Sass options API were exposed somewhere, along with a "prepend" option similar to what sass-loader does in webpack. This is critical for globally configuring modules in Sass 4.x+

**Comment by matthewp** [comment]
I'm going to mark this as blocked, as I don't think we'll change it before the `next` branch is merged. I'm uncertain how Vite does workspaces, but assuming it supports them, we can add support for this behavior (which seems correct to me) either in that branch or after it is merged.

**Comment by natemoo-re** [comment]
In `astro@next` which has now been promoted to our `main` branch, we use Vite's built-in plugin pipeline to transform any Sass. You should be able to configure these options through Vite, but if they're missing this feature we might be able to contribute a fix upstream!

**Comment by FredKSchott** [comment]
Thanks for the report! We believe that this has been fixed in astro v0.21, going out today. Let us know if you can still reproduce the issue after updating to v0.21 and we'll be happy to take a look.

**Comment by chee** [comment]
thank-you :heart:, i look forward to trying it on Monday.
