### ISSUE TITLE
 'node:url' from origin 'http://localhost:3000'  CORS Error

### ISSUE THREAD

**Issue by amancoder28** [snowpackjs/astro#1428]
### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

Access to script at 'node:url' from origin 'http://localhost:3000' has been blocked by CORS policy: Cross origin requests are only supported for protocol schemes: http, data, chrome, chrome-extension, chrome-untrusted, https.

I'm using astro with svelte and sanity content platform .

I have got a cors error.

### Steps to Reproduce

1. `npm init astro`
2. yarn add @sanity/client
3. ```
`const fetchTuts = async () => {
		const query = `*[_type == "daily"] { 
				title, description, image{
					asset->{
						url
					}
				}
			}`;

		await sanity
			.fetch(query)
			.then((data) => tuts.concat(data))
			.catch((err) => console.error(err));
	};

	onMount(fetchTuts);`
```

**Comment by matthewp** [comment]
Can you provide a full reproduction (either a codesandbox or a repo we can clone). You should not be attempting to load `node:url` in a client-side component, which is the only scenario in which CORS could come into play.

Going to close for now as I don't think there's a bug here, but happy to reopen if you can provide a reproduction. Thanks!
