### ISSUE TITLE
🐛 BUG: devOptions.hmr = false not respected in config

### ISSUE THREAD

**Issue by sh1nryu** [snowpackjs/astro#1449]
### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Setting `devOptions: { hmr: false }` doesn't disable esm-hmr. Tried adding this option in both snowpack.config.mjs as well as astro.config.mjs, to no avail.

### Steps to Reproduce

1. `npm init astro` using template <any>, with svelte-renderer.
2. Add a 'snowpack.config.mjs' with 'devOptions: { hmr: false }'
3. Within index.astro, add a Svelte component (within this component, call a javascript module in the onMount svelte lifecycle method).
4. Make a change in the js module called in the Svelte component, or the Svelte component itself. 
5. If hmr: false was in effect, whole page should reload as a result of a change in the Svelte component or the nested module, but it does not (Svelte's onMount lifecycle method did not re-run).

**Comment by matthewp** [comment]
This will likely not be fixed in 0.20, but in 0.21 Astro will use Vite, which you can disable HMR like this: https://vitejs.dev/config/#server-hmr

**Comment by natemoo-re** [comment]
Thanks for the report! As @matthewp outlined above, Vite's HMR can be disabled using that new option.

Please feel free to open a new issue if you run into any problems in `astro@0.21.0` and up.
