### ISSUE TITLE
🐛 BUG: Apostrophe in Astro file inline function eval as string even in JSX

### ISSUE THREAD

**Issue by Chrissdroid** [snowpackjs/astro#1478]
### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

```astro
---
const arr = [1,2,3,4]
---
<ul>
  {arr.map(item => (
    <li>{item} - L'aventure commence ici</li>
  ))}
</ul>
```
In the following exemple, Astro will treat the apostrophe in the sentence `L'aventure commence ici` as a start of a string even if it's an JSX (type of) expression

Adding another apostrophe at the end remove the error at runtime and leave both apostrophe in the resulting HTML

It can be avoided by changing the apostrophe as his HTML equivalent `&#039` but i don't consider that as a real "fix"

Maybe this case is affecting more than only the inline function (like the conditional && syntax)

### Steps to Reproduce

1. `npm init astro` using default template
2. Inside the HTML part of a .astro file, write JSX expression inside a Expression Syntax
3. In the JSX add an apostrophe inside the tag
4. Watch Astro goes crazy as it can't evaluate the content of HTML section of the .astro file

### Link to Minimal Reproducible Example (Optional)

https://astro.build/play#eyJpbm1lbW9yeTovL21vZGVsL3NyYy9wYWdlcy9QYWdlLmFzdHJvIjoiLS0tXG5jb25zdCBhcnIgPSBbMSwgMiwgMywgNF1cbi0tLVxuPGh0bWwgbGFuZz1cImVuXCI+XG4gIDxoZWFkPlxuICAgIDxtZXRhIGNoYXJzZXQ9XCJVVEYtOFwiPlxuICAgIDx0aXRsZT5Bc3RybyBQbGF5Z3JvdW5kPC90aXRsZT5cbiAgPC9oZWFkPlxuICA8Ym9keT5cbiAgICB7YXJyLm1hcChpdGVtID0+IChcbiAgICAgIDxzcGFuIGxhbmc9XCJmclwiPntpdGVtfSAtIEwnYXZlbnR1cmUgQ29tbWVuY2UgaWNpPC9zcGFuPlxuICAgICkpfVxuXG4gICAgPCEtLSBQb3RlbnRpYWwgRml4ICMxIC0tPlxuICAgIDwhLS0gQWRkaW5nIGFub3RoZXIgYXBvc3Ryb3BoZSAtLT5cbiAgICB7YXJyLm1hcChpdGVtID0+IChcbiAgICAgIDxzcGFuIGxhbmc9XCJmclwiPntpdGVtfSAtIEwnYXZlbnR1cmUgQ29tbWVuY2UgaWNpJzwvc3Bhbj5cbiAgICApKX1cblxuICAgIDwhLS0gUG90ZW50aWFsIEZpeCAjMiAtLT5cbiAgICA8IS0tIFdyYXBpbmcgaXQgaW4gYSBzdHJpbmcgZXhwcmVzc2lvbiAtLT5cbiAgICB7YXJyLm1hcChpdGVtID0+IChcbiAgICAgIDxzcGFuIGxhbmc9XCJmclwiPntpdGVtfSAtIHtcIkwnYXZlbnR1cmUgQ29tbWVuY2UgaWNpXCJ9PC9zcGFuPlxuICAgICkpfVxuXG4gICAgPCEtLSBQb3RlbnRpYWwgRml4ICMzIC0tPlxuICAgIDwhLS0gRXNjYXBpbmcgY2hhcmFjdGVyIC0tPlxuICAgIHthcnIubWFwKGl0ZW0gPT4gKFxuICAgICAgPHNwYW4gbGFuZz1cImZyXCI+e2l0ZW19IC0gTCYjMDM5YXZlbnR1cmUgQ29tbWVuY2UgaWNpPC9zcGFuPlxuICAgICkpfVxuICA8L2JvZHk+XG48L2h0bWw+XG4ifQ==

**Comment by jasikpark** [comment]
Is that only the case inside an expression, like a map for example? it's not a problem otherwise, right?

**Comment by matthewp** [comment]
Looks like this is still causing a problem: https://stackblitz.com/edit/github-gybs4c?file=src%2Fpages%2Findex.astro&on=stackblitz

**Comment by natemoo-re** [comment]
Thanks for the ping @matthewp! I think I know the fix here, I'll take a look.
