### ISSUE TITLE
🐛 BUG: `content.url` missing from standalone markdown pages

### ISSUE THREAD

**Issue by innermatrix** [snowpackjs/astro#1603]
### What package manager are you using?

npm

### What operating system are you using?

macOS

### Describe the Bug

`content.url` is missing from markdown pages rendered via a standalone `md` file in `src/pages` (as opposed to those rendered via a component using `fetchRequest`). 

### Steps to Reproduce

1. `npm init astro` using any template
2. Add `src/pages/demo.md` with `layout: ../components/TestComponent.astro`
3. Add `src/components/TestComponent.astro` with `<Debug {content}/>`
4. Render (`dev` or `build`)

* Expected: `content` includes `url` per [documentation](https://docs.astro.build/guides/markdown-content/)
* Seen: no `content.url`

See `demo.md` in MWE

### Link to Minimal Reproducible Example (Optional)

https://stackblitz.com/edit/astro-p713a1

**Comment by matthewp** [comment]
Thanks for submitting! I just changed your repro to use `next` and it works! Going to close, expect this to be fixed in 0.21.

**Comment by dheerajvs** [comment]
@matthewp This bug seems to occurring again when tested using astro v1.0.0-beta.44.
`content.url` is missing when using Markdown layouts.

Repro example: https://stackblitz.com/edit/astro-tis5v6
