### ISSUE TITLE
🐛 BUG: Error Message Suppressed By Child Render Error When Header Left Out Of Docs Template

### ISSUE THREAD

**Issue by JacobMGEvans** [snowpackjs/astro#1640]
### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Error Message Suppressed By Child Render Error When Header Left Out Of Docs Template

I had thought that the left panel could render without a root header, the error response I received was a bit unintuitive to the root cause.
![image](https://user-images.githubusercontent.com/27247160/138522527-dbf79a07-2e5f-4c1a-be54-7e47a24a562c.png)

### Steps to Reproduce

PR that fixes the "children" error: https://github.com/OpenSourceRaidGuild/tutorial-quest/pull/21/files

**Comment by matthewp** [comment]
Thanks!

**Comment by matthewp** [comment]
For anyone taking this issue, apply the fix linked above into our docs template.

**Comment by matthewp** [comment]
Fixed by https://github.com/snowpackjs/astro/pull/1734
