### ISSUE TITLE
🐛 BUG: Error when evaluating SSR module / module is not defined on fresh @next

### ISSUE THREAD

**Issue by hans-d** [snowpackjs/astro#1682]
### What package manager are you using?

npm

### What operating system are you using?

linux docker

### Describe the Bug

fresh barebone/manual install of astro@next--compiler, with basic page results in errors

### Steps to Reproduce

1. running in docker container 'node:latest' without anything extra installed in the image. Current PWD is shared and current working dir within the container.
2. `npm init --yes`
3. `npm install astro@next--compiler --save`
```
  "dependencies": {
    "astro": "^0.0.0-compiler-202192719637"
  }
```
4. add page as per https://github.com/snowpackjs/astro/blob/next/docs/src/pages/installation.md
5. `astro dev`

```
07:53 PM [astro] Server started                               1908ms
07:53 PM [astro] Local: http://0.0.0.0:3000
7:53:28 PM [vite] Error when evaluating SSR module /node_modules/react/index.js?v=627d6032:
ReferenceError: module is not defined
    at /node_modules/react/index.js?v=627d6032:6:3
    at instantiateModule (/blog/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:66511:15)
7:53:28 PM [vite] Error when evaluating SSR module @astrojs/renderer-react/server.js:
ReferenceError: module is not defined
    at /node_modules/react/index.js?v=627d6032:4:3
    at instantiateModule (/blog/node_modules/astro/vendor/vite/dist/node/chunks/dep-35df7f96.js:66511:15)
07:53 PM [astro] 500 /                                        744ms
07:53 PM [astro] 404 /favicon.ico                             0ms
```

**Comment by natemoo-re** [comment]
Interesting... Try a fresh install of the renderers as well, just to be sure? These deps should be automatically bumped by our release script but I suspect that's where this problem is.

```
npm i @astrojs/renderer-{react,preact,vue,svelte}@0.0.0-compiler-202192719637
```

**Comment by hans-d** [comment]
That manual interventions seems to resolve it now indeed.

NB: bumping to the latest next--compiler (202192918241) results now in a `Not Found - GET https://registry.npmjs.org/astro/-/astro-0.0.0-compiler-202192918241.tgz - Not found`

**Comment by hans-d** [comment]
seems resolved as well with astro@next...
