### ISSUE TITLE
🐛 BUG: Using `srcset` on image where source URL resolves to empty/undefined causes build to crash

### ISSUE THREAD

**Issue by dnbo** [snowpackjs/astro#1687]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

If you use `srcset` on an `<img>`-tag in an Astro component with variables that resolve to `undefined`, the `astro build` will crash with an error message

`[build] file:///~/src/pages/index.astro: could not find file "/_astro/src/pages/undefined".`

The error message itself is very unclear and it's hard to track down what component causes the issue.

Repro code (should work in any Astro component):
`<img srcset={`${image.versionOne} 1x, ${image.versionTwo} 2x`}>`

### Steps to Reproduce

1. `<img srcset={`${image.versionOne} 1x, ${image.versionTwo} 2x`}>` in any Astro component
2. Run `astro build`

**Comment by matthewp** [comment]
Thanks!

**Comment by FredKSchott** [comment]
Thanks for the report! We believe that this has been fixed in astro v0.21, going out today. Let us know if you can still reproduce the issue after updating to v0.21 and we'll be happy to take a look.
