### ISSUE TITLE
🐛 BUG: Assets in `src/` do not get build in `astro@next`

### ISSUE THREAD

**Issue by bobaekang** [snowpackjs/astro#1715]
### What package manager are you using?

npm

### What operating system are you using?

Windows (WSL 1)

### Describe the Bug

Using `Astro.resolve()`  to import CSS stylesheet or JS script fails because the build output includes neither the assets nor the valid paths for those (missing) assets for the corresponding attrs.

Here's an example source:

```astro
---
---
<html lang="en">

<head>
	<meta charset="utf-8" />
	<link rel="icon" type="image/x-icon" href="/favicon.ico" />
	<meta name="viewport" content="width=device-width" />

	<!-- SEE LINES BELOW -->
	<link rel="stylesheet" href={Astro.resolve('../style.css')} type="text/css" />
	<script src={Astro.resolve('../script.js')} />
	<!-- SEE LINES ABOVE-->

	<title>Welcome to Astro</title>
</head>

<body>
	<h1>Welcome to <a href="https://astro.build/">Astro</a></h1>
</body>

</html>

```

And here's the build output:

```html
<html lang="en"><head>
	<meta charset="utf-8">
	<link rel="icon" type="image/x-icon" href="/favicon.ico">
	<meta name="viewport" content="width=device-width">

	<!-- SEE LINES BELOW -->
	<link rel="stylesheet" href="/home/bobaekang/sandbox/astro-test/src/style.css" type="text/css">
	<script src="/home/bobaekang/sandbox/astro-test/src/script.js"></script>
	<!-- SEE LINES ABOVE-->

	<title>Welcome to Astro</title>
</head>

<body>
	<h1>Welcome to <a href="https://astro.build/">Astro</a></h1>
</body></html>
```

Here's the screenshot of CLI output for running `npm run build`:

![image](https://user-images.githubusercontent.com/22449454/139562643-9b1a009d-d54a-4c44-8580-185df71d59e9.png)

In contrast, `Astro.resolve()` works with dev server.

### Steps to Reproduce

1. `npm init astro` using template minimal
2. `npm install astro@next --compiler`
3. Create `/src/style.css` and `/src/script.js` files
4. Add `<link rel="stylesheet" href={Astro.resolve('../style.css')} type="text/css" />` and `<script src={Astro.resolve('../script.js')} />` to `/src/pages/index.astro`
5. `npm run build`
6. Error! Describe what went wrong (and what was expected instead)...

**Comment by matthewp** [comment]
I updated the issue description to reflect the larger issue here. I'm working on this problem this week.

**Comment by matthewp** [comment]
Note to self, test out this: https://github.com/snowpackjs/astro/issues/1711

**Comment by bobaekang** [comment]
@matthewp I'd appreciate if there's been any update on this issue. Thank you!

**Comment by tusamni** [comment]
> @matthewp I'd appreciate if there's been any update on this issue. Thank you!

He's been posting updates in Discord. I believe he's got it working locally, should be included in the upcoming 0.21.0-next.3 release.

**Comment by jasikpark** [comment]
This is being worked on in #1786

**Comment by matthewp** [comment]
Yep, PR is up, just getting last tests passing and then some reviews.
