### ISSUE TITLE
🐛 BUG: Astro-lit slot conflict

### ISSUE THREAD

**Issue by yinonov** [snowpackjs/astro#1717]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Astro slot conflicts with lit component slot -
when trying to assign nodes to a lit component named slot, astro doesn't render those nodes, probably due to its own slotting feature.

is it really safe to adopt custom element preserved attribute name (slot)?

p.s. default slots are rendered as expected

### Steps to Reproduce

1. using the `renderer-lit` example
2. add named slot to `Counter` component template
3. nest content within the `my-counter` tag in `index.astro` and project it to the newly created named slot
5. content will not render to the page, not even to light tree

### Link to Minimal Reproducible Example (Optional)

https://stackblitz.com/edit/github-l5nmfq-jgp6nr?file=src/pages/index.astro

**Comment by matthewp** [comment]
Thanks for the repro!
