### ISSUE TITLE
RFC Call - 11/2/2021

### ISSUE THREAD

**Issue by matthewp** [snowpackjs/astro#1723]
# Agenda

1. https://github.com/snowpackjs/astro/issues/1618
   - @innermatrix
   - Summary: Allow more control over where assets are built that live in the config.src folder.
   - Context/Reason: Revisit earlier discussions on whether page-specific files live and see if there's a solution to this problem.
1. https://github.com/snowpackjs/astro/issues/1720
   - @yinonov
   - Summary: Import 3rd party Lit components without `export tagName` requirement.
   - Context/Reason: @natemoo-re submitted a PR to remove the tagName requirement.
1. https://github.com/snowpackjs/astro/issues/1694
   - @AsyncBanana 
   - Summary: Allow preprocessing of .astro files to enable custom syntax like Pug (similar to what svelte-preprocess allows).
   - Context/Reason: To unblock the RFC so that the submitter can create a full proposal.

If there is something else you would like to discuss, please mention it here.

**Comment by aFuzzyBear** [comment]
Hi Matt, I was wondering if we could include issue #1618 for discussion if time permits, I would also be willing to champion this as well if needed.

**Comment by matthewp** [comment]
Yep! Let's talk about it.

**Comment by matthewp** [comment]
Great call everyone!
