### ISSUE TITLE
🐛 BUG: descendant combinator not locally scoped

### ISSUE THREAD

**Issue by IanVS** [snowpackjs/astro#1724]
### What package manager are you using?

npm and yarn

### What operating system are you using?

mac, codesandbox

### Describe the Bug

I upgraded from Astro 0.18.9 to 0.20.12, and found that some of my styles have been broken.  Specifically, I found a case where I was using a descendant combinator, and the first classname was scoped correctly, but the second was treated as global.  It seems to have something to do with the use of a pseudo-selector (`:nth-child(even)` in my case) as well.  Adding a direct descendant selector (>) results in the correct local scoping.

### Steps to Reproduce

See codesandbox.

### Link to Minimal Reproducible Example (Optional)

https://codesandbox.io/s/astro-1724-i4l7h?file=/src/components/Feature.astro

**Comment by IanVS** [comment]
I tried to add a failing test to `astro-scoped-styles.test.js`, but it looks like that file is no longer in the repo.  If it were, this would be a failing test case:

```
'.class:nth-child(even) .class2': `.class.${className}:nth-child(even) .class2.${className}`
```

```
        ++.class.astro-abcd1234:nth-child(even)·.class2.astro-abcd1234    (Expected)
        --.class.astro-abcd1234:nth-child(even).class2                    (Actual)
```

**Comment by natemoo-re** [comment]
Thanks for the repro and a thorough test case. We're obviously in the middle of a big reorganization—I apologize for the mess!

I have good news—this is fixed in the new compiler, released under `astro@next`. See [working reproduction](https://stackblitz.com/edit/github-t3hheb?file=src%2Fcomponents%2FFeature.astro).
