### ISSUE TITLE
🐛 BUG: Vite options like server cause errors

### ISSUE THREAD

**Issue by hans-d** [snowpackjs/astro#1755]
### What package manager are you using?

npm

### What operating system are you using?

linux

### Describe the Bug

Using `vite` options like `server` causes ```[vite] Error when evaluating SSR module /node_modules/react/index.js:
ReferenceError: module is not defined
    at /node_modules/react/index.js:6:3
    at instantiateModule (/home/projects/github-zxz9ec/node_modules/astro/vendor/vite/dist/node/chunks/```

Seems like the additional options provided here are not deep merged with the other options set in the code at https://github.com/snowpackjs/astro/blob/next/packages/astro/src/core/create-vite.ts

### Steps to Reproduce

1. use starter template
2. add ```  vite: {
    server: {
      hmr: {
        clientPort: 8091,
      },
    },
  },``` to astro.config.mjs
3. watch it fail on 'npm run dev'

### Link to Minimal Reproducible Example (Optional)

https://stackblitz.com/edit/github-zxz9ec?file=astro.config.mjs

**Comment by drwpow** [comment]
Was able to easily replicate this. Hopefully #1768 fixes this! Took a look and `vite.mergeConfig` should be deeply-merging everything. I think it was just some of our own code that was interfering.

**Comment by hans-d** [comment]
confirmed
