### ISSUE TITLE
💡 RFC: Zero specificity scoping

### ISSUE THREAD

**Issue by natemoo-re** [snowpackjs/astro#1762]
### Background & Motivation

I would like Astro to respect the specificity with which styles are authored. Basically, Astro should scope styles in a way that does not introduce additional specificity.

### Example

Given the following CSS file and Astro component, I would expect the `.title` element to be `red` since it was authored with a specificity of `0/1/1` but the Astro component defines `blue` with a specificity of `0/0/1`. 

Currently the output depends on the order the styles are loaded, meaning the `.title` element will always be `blue` since component styles always come after. [See reproduction](https://stackblitz.com/edit/github-deysv8?file=src%2Fcomponents%2FDemo.astro).

**external.css**
```css
/* more specific */
h1.title {
  color: red;
}
```

**file.astro**
```astro
<h1 class="title">Hello world!</h1>

<style>
  /* less specific */
  h1 {
    color: blue;
  }
</style>
```

### Possible solutions

Rather than generating class-based selectors like `h1.astro-XXXXXXXX`, we should use the [`:where()`](https://caniuse.com/mdn-css_selectors_where) selector to avoid introducing additional specificity for our `.astro-XXXXXXXX` class.

### Alternatives considered

None

### Risks, downsides, and/or tradeoffs

Even though `:where()` is supported in all evergreen browsers, users may want to support legacy browsers. We could potentially support a config toggle, differential style loading, `@supports` flags, or just make it clear what our browser compatibility table is.

### Open Questions

None

### Detailed Design

Update the compiler to append `:where(.astro-XXXXXXXX)` rather than `.astro-XXXXXXXX`.

```css
/* BEFORE: specificity of 0/1/1 */
h1.astro-XXXXXXXX {}

/* AFTER: specificity of 0/0/1 */
h1:where(.astro-XXXXXXXX) {}
```

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by jonathantneal** [comment]
Great idea, @natemoo-re! Big +1 from me.

Does Astro support a [browserslist](https://github.com/browserslist/browserslist) configuration? If so, could this be used to determine whether `:where` can be used?

I also support the idea of a config toggle, if it is necessary.

**Comment by natemoo-re** [comment]
@jonathantneal Implementing **browserslist** support to control this feature is a great idea!

**Comment by matthewp** [comment]
Given the caniuse table, I think this is safe for us to use. Seems like a good idea to me.

**Comment by natemoo-re** [comment]
Added the `rfc-discuss` label, hopeful we can chat about it this week!

**Comment by drwpow** [comment]
I’m +1 to using `:where()` in general and +1 to single-specificity styling in general.

I think the biggest risk to this is **deterministic ordering.** I think we’d have to make sure styles always get loaded in a specific order, especially when bundling, otherwise the `:where()` in components won’t work. This mainly affects components who have no determined ordering, and based on how they are arranged/bundled in the application, style output could look very differently.

**Comment by drwpow** [comment]
### RFC Call 2021-11-16 Notes

- Q: How could older browsers be supported? A: possibly `browserslist` as suggested [in this comment](https://github.com/snowpackjs/astro/issues/1762#issuecomment-962664528)

**Comment by matthewp** [comment]
I think we need to define what style scoping is supposed to mean before we proceed with this type of proposal. If it is supposed to mean "this always wins over external" then we need to enforce that to the extent that is possible (using `!important` on all declarations for example). If it is supposed to mean something more loose, great! Let's define it and then something like this could be done.
