### ISSUE TITLE
🐛 BUG: Query parameter in the URL return an 404 error

### ISSUE THREAD

**Issue by lakano** [snowpackjs/astro#1795]
### What package manager are you using?

npm

### What operating system are you using?

Fedora Linux 35

### Describe the Bug

If you try to uses parameters in the URLs (eg: « localhost:3000/my-list?page=2 » ), astro ( npm run dev / npm run preview ) return a 404 error.

Even if Astro don't use theses parameters, this should be simply ignored. You can quickly fix that into the packages/astro/src/core/dev/index.ts in the handleRequest function like that:

```
before:
    let pathname = req.url || '/'; // original request
after:
    let pathname = (req.url || '/').split('?')[0]; // original request
```
EDIT: This fix worked inside .next1 but no more in next3 version, surely because req.url is used elsewhere. A quick fix could be done like that:
```
before:
    let pathname = req.url || '/'; // original request
after:
    req.url = req.url?.split('?')[0]
    let pathname = req.url || '/'; // original request
```

Regards

### Steps to Reproduce

1. Use any template and add in the URL « ?whatever »

**Comment by natemoo-re** [comment]
Thanks! This is definitely a bug to be fixed before `0.21.0` goes out.
