### ISSUE TITLE
🐛 BUG: Tailwind CSS breaks after saving file on astro@next

### ISSUE THREAD

**Issue by tusamni** [snowpackjs/astro#1810]
### What package manager are you using?

np

### What operating system are you using?

Windows 11

### Describe the Bug

When running the [official Tailwind example](https://github.com/snowpackjs/astro/tree/main/examples/with-tailwindcss) on Windows 11, the link to the CSS will break after saving any file.

Running `npm run dev` creates:
`<link rel="stylesheet" type="text/css" href="/C:/Users/erik/Downloads/sites/tailwind/examples/with-tailwindcss/src/styles/global.css">`

After saving any file:
`<link rel="stylesheet" type="text/css" href="http://localhost:3000/:/Users/erik/Downloads/sites/tailwind/examples/with-tailwindcss/src/styles/global.css?t=1636731599194">`

Note that the drive letter gets removed.

### Steps to Reproduce

1. `clone https://github.com/snowpackjs/astro.git astro`
2. `cd examples/with-tailwindcss`
3. `npm install`
4. `npm run dev`
5. Make a change to `src/pages/index.astro`
6. CSS will break after saving change

**Comment by jonathantneal** [comment]
Pinging @drwpow for review. This looks like either a pathing issue or a `URL` issue.

@tusamni, do you expect to see a domain like `localhost` when you access a drive?

e.g.
```
file://localhost/etc/fstab
```

— from https://en.wikipedia.org/wiki/File_URI_scheme#Windows

**Comment by tusamni** [comment]
Not usually?

I'm no expert here, but I would have assumed the path would have just been http://localhost:3000/image/path/etc

**Comment by tusamni** [comment]
Might it be related to this? https://github.com/vitejs/vite/issues/735

**Comment by tusamni** [comment]
This seems to be fixed with 0.21.0-next.11
