### ISSUE TITLE
🐛 BUG: sass file compiled as scss

### ISSUE THREAD

**Issue by Olyno** [snowpackjs/astro#1813]
### What package manager are you using?

yarn

### What operating system are you using?

Linux

### Describe the Bug

It looks like vite is compiling ``sass`` files as ``scss`` file, and so it creates a syntax error:
```
Error: Expected newline.
  ╷                                                 
1 │ .element {                                       
  │          ^                                     
  ╵                                                  
  src/styles/m_gumgame.sass 1:10  root stylesheet
````

### Steps to Reproduce

1. Clone [this repository](https://github.com/Olyno/astro-sass-issue)
2. ``yarn`` or ``npm i``
3. ``yarn build`` or ``npm run build``

### Link to Minimal Reproducible Example (Optional)

https://github.com/Olyno/astro-sass-issue

**Comment by drwpow** [comment]
Good news! This has been fixed in the latest branch. But this behavior was missing from our tests. Added tests in #1919 to ensure this doesn’t regress.
