### ISSUE TITLE
🐛 BUG: Cannot find module 'preact' - Theme toggle in documentation example not working

### ISSUE THREAD

**Issue by borisv** [snowpackjs/astro#1817]
### What version of `astro` are you using?

0.21.0

### What package manager are you using?

npm

### What operating system are you using?

WSL2

### Describe the Bug

When initializing and installing astro@next.3 with the documentation example, as well as loading preact with 
npm i @astrojs/renderer-preact@next in VSCode Problems I get a

```Cannot find module 'preact'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?```

Same goes for module 'react'.  
Same messages come in Stackblitz.  

-> Regarding 'preact': When doing npm run dev the theme toggle in the right sidebar behaves kind of funky after each new page load (one needs to switch between different device views to get the icon highlighted and functional).   
I tried in dev and with build in preview - getting identical behaviour in both- and I kind of find no reason for this.   
This isn't new behaviour, it has been actually has been present in next.1, next.2 and next.3

-> Regarding 'react': Neither Search nor Language select get rendered in dev or build.

If you reproduce this using stackblitz you need to open it in 'New Window', if you are local the bug will already be visible when you go to localhost:3000

Even though it is already there with a fresh load, to reproduce the actual behaviour, click on a link in the sidebar  
-> the toggle for dark is not highlighted and not operational   
-> in DevTools switch on device you and choose a device that takes the toggle out of view  and then switch the toggle switch back into view   
-> the dark mode toggle is highlighted and operational

### Link to Minimal Reproducible Example

https://stackblitz.com/github/snowpackjs/astro/tree/main/examples/docs?file=package.json&on=stackblitz

**Comment by jonathantneal** [comment]
I’m not seeing this in v0.21.0-next.7 at your link. Are you still seeing this?

**Comment by borisv** [comment]
Yes, if on stackblitz I go into /src/components and open any .tsx file in any of the subfolders there
-> any preact or react import has a wavy underline indicating that the respective module could not be found (ALT-F8)
-> in the browser preview window the function according to every one of these imports is not available

Tried in Chrome Dev as well as Brave Dev

For me the error message "Cannot find module 'preact/hooks'. Did you mean to set the 'moduleResolution' option to 'node', or to add aliases to the 'paths' option?" seems to indicate that the tsconfig.json gets ignored or the path gets _interupted_ otherwise.

**Comment by borisv** [comment]
While not seeing it working in next.7 I now see it almost working in next.12, since the dependency install of the preact module is no longer called in package.json.
-> at least seems to make preact available

But now apart from the toggle component still not working across page loads I get in ThemeToggleBotton.tsx a greyed out import { useState, useEffect } from 'preact/hooks' reporting
-> 'Cannot find module preact/hooks'

**Comment by FredKSchott** [comment]
Confirmed fixed in latest `next` version
