### ISSUE TITLE
🐛 BUG: dev server doesn't reload the page when i update a asvelte component

### ISSUE THREAD

**Issue by potros** [snowpackjs/astro#1823]
### What version of `astro` are you using?

0.0.21

### What package manager are you using?

npm

### What operating system are you using?

windows

### Describe the Bug

dev server doesn't reload the page when i update a asvelte component

### Link to Minimal Reproducible Example

https://astro.new/starter?on=stackblitz

**Comment by natemoo-re** [comment]
Closing as a duplicate of https://github.com/snowpackjs/astro/issues/1824
