### ISSUE TITLE
🐛 BUG: HMR not working when renderers are installed

### ISSUE THREAD

**Issue by borisv** [snowpackjs/astro#1824]
### What version of `astro` are you using?

0.21.0

### What package manager are you using?

npm

### What operating system are you using?

WSL2

### Describe the Bug

HMR shows inconsistent behaviour across the different ways of installs.

Using one of the example templates directly inside the mono-repo locally   
->HMR doesn't kick in with changes

Using npm init astro@next choosing starter WITHOUT any renderer  
->HMR DOES kick in with changes

Using npm init astro@next choosing starter WITH any renderer (installed Svelte for instance with npm i @astrojs/renderer-svelte@next)
->HMR DOES NOT kick in with changes

Using one of the example templates via https://astro.new/next  
->HMR DOES NOT in with changes

This complicate things further: When using stackblitz there is NO renderer explicitly called, but anyway HMR DOES NOT work

So HMR not kicking in at first seems to be a thing AS SOON AS renderers are involved. But HMR kicking in WITHOUT any renderer involved is only working with npm init astro@next locally.

An possibly unrelated aside: When using npm init astro@next   
->package.json DOES NOT contain the link to 0.21.0   
->npm i astro@next.3 needs to be used explicitly

### Link to Minimal Reproducible Example

https://stackblitz.com/github/snowpackjs/astro/tree/main/examples/starter?file=package.json&on=stackblitz

**Comment by hans-d** [comment]
Noticed some of this behaviour as well, on linux. (https://discord.com/channels/830184174198718474/845451724738265138/907741764163604501)

**Comment by dayvista** [comment]
Experienced this as well while running v0.21.0-next.3 with the Svelte renderer on Mac OS Monterey v12.0.1.

**Comment by christian-fuss** [comment]
Despite my limited knowledge of astro and vite so far, I tried to investigate a bit, maybe it is helpful:

- the server sends a custom "astro.reload" event via WebSocket to the client
- the client receives it and dispatches it to the listeners
- for pure HTML changes I assume the hmr.ts/js should handle it by calling morphdom
- but in my case the import.meta.hot guard in that file is undefined and thus the handler is never called
- I assume the import.meta.hot should be set/defined in development mode but I don't know who,why,when this should happen and why it is not set in my case but obviously for many users it seems to be ok.

My test scenario is based on `npm init astro@next && npm i -D astro@next && npm install && npm run start` running in WSL2.

**Comment by christian-fuss** [comment]
> npm init astro@next



> Using npm init astro@next choosing starter WITHOUT any renderer
> ->HMR DOES kick in with changes

At least it is consistently NOT working. If you check your package.json when doing `npm init astro@next`, you will see that the starter still references the 0.20.12 version, which is now latest. There HMR is working. if you call a `npm install astro@next` after using the starter, you really will have a @next version, but then HMR is not working.

For simply trying it, without the obstacles of local machines, you can reproduce this bug also on Stackblitz with the minimal next starter: https://astro.new/minimal@next?on=stackblitz

**Comment by christian-fuss** [comment]
I think I found the reason, why nothing HMRs: When reading up on SSR/client:only rendering I stumbled over one point in the Astro docs: "All ESM modules include a import.meta property. Astro adds import[dot]meta[dot]env through Snowpack." :bulb: ESM modules contain it, but when debugging I did not only not see the import.meta.hot, but there was also no import.meta. I was obviously not using ESM modules. Now I just added "type": "module" to my package.json and voila HMR works. I have not checked yet, what this does to my production build, because there I definitely want CJS because I am targeting old mobile browsers.

**Comment by natemoo-re** [comment]
Update based on @christian-fuss's investigation! I was able to narrow down the issue and determined that we had a Vite configuration setting that was excluding any files inside of `astro` from being processed, which meant that `import.meta.hot` would always be `undefined`.

By fixing this (PR shortly), HMR should be working again!

**Comment by natemoo-re** [comment]
See https://github.com/snowpackjs/astro/pull/1858
