### ISSUE TITLE
🐛 BUG: Comments in jsx astro syntax not working

### ISSUE THREAD

**Issue by schlichtanders** [snowpackjs/astro#1832]
### What version of `astro` are you using?

0.20.12

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

it is [documented](https://docs.astro.build/core-concepts/astro-components/#comparing-astro-versus-jsx) that astro supports comments in html style within inline jsx-like html

while this would be really nice to have, it does not work for me. Here a failing minimal example
```astro
---
const boolean = true;
---
{boolean ? 
    <div>
    <!-- comment -->
    hello
    </div>
: null }
```
It fails with
```
𝘅 Expected ":" but found "}"

     3 | ---
     4 | {boolean ? 
   > 5 |     <div>
       |          ^
     6 |     <!-- comment -->
     7 |     hello
     8 |     </div>

(node:4417) UnhandledPromiseRejectionWarning: Error: Unable to compile expression
    at compileExpression (file:///home/.../node_modules/astro/dist/compiler/codegen/index.js:223:11)
    at async Object.enter (file:///home/.../node_modules/astro/dist/compiler/codegen/index.js:479:24)
    at async AsyncWalker.visit (file:///home/.../node_modules/estree-walker/src/async.js:49:5)
    at async AsyncWalker.visit (file:///home/.../node_modules/estree-walker/src/async.js:86:6)
    at async AsyncWalker.visit (file:///home/.../node_modules/estree-walker/src/async.js:79:14)
    at async asyncWalk (file:///home/.../node_modules/estree-walker/src/index.js:34:9)
```

comment on astro.new: Neither stackblitz, nor codeinsandbox works for me (tried minimal version, stackblitz never shows anything, codeinsandbox shows the wrong thing...)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wi9leu-csbc4q?file=src/pages/index.astro

**Comment by vineryap** [comment]
I don't think it the documentation mentioned about supporting comment inside the jsx syntax on astro file.
On the comparison table it only showing the difference of "Comment Style".
But maybe this can be requested as a feature :)

**Comment by natemoo-re** [comment]
[This works](https://stackblitz.com/edit/github-4hv1xd?file=src%2Fpages%2Findex.astro) exactly like you want! The problem is that you need to wrap your elements with `()` in order for Astro to render them as a single fragment.

```astro
---
const boolean = true;
---
{boolean ? (
    <div>
    <!-- comment -->
    hello
    </div>
) : null }
```

**Comment by schlichtanders** [comment]
thank you very much. I actually tried the parantheses version, however as stackblitz didn't work for me, I just tried it in my astro version, where your code indeed throws the error
```
𝘅 Expected ")" but found "}"

     3 | ---
     4 | {boolean ? (
   > 5 |     <div>
       |          ^
     6 |     <!-- comment -->
```
(error only in old astro version 0.20.12)

I now checked with someone else whether stackblitz works for them, and indeed, so  apparently it is my browser. With a fresh chromium installation I could make it work and replicate that the comments work for the most recent astro version.

Thank you very much and my excuses for the noise.
