### ISSUE TITLE
🐛 BUG: Vue scoped styles applied globally during build step

### ISSUE THREAD

**Issue by Destiner** [snowpackjs/astro#1844]
### What version of `astro` are you using?

0.21.0-next.3

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

During dev step, scoped styles in Vue SFCs applied correctly (only to the elements inside the component). During build step, however, scoped styles are applied globally (i.e. to any matching element across the entire app).

In reproduction example, I added a scoped style to `Counter` `<button>`s. On stackblitz, it works as expected. It also works correctly, if you run `astro dev`. But if you run `astro build`, the scoped style will also apply to the button outside of the `Counter` component.

<details>
<summary>Here's how it looks if you build the example</summary>
<img width="1435" alt="Screenshot 2021-11-16 at 15 41 16" src="https://user-images.githubusercontent.com/4247901/141987148-d44a7bb3-3330-4406-a33d-a19c19654184.png">
</details>

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-qpj6s2

**Comment by nezzard** [comment]
Have the same probmel.
Problem in  client:visible, not in scoped styles
