### ISSUE TITLE
🐛 BUG: ENOENT: no such file or directory on src/pages/index.astro 

### ISSUE THREAD

**Issue by smakinson** [snowpackjs/astro#1848]
### What version of `astro` are you using?

0.21.0-next.4

### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

In next.3 & next.4 (haven't tried pre those) I see:

`ENOENT: no such file or directory on src/pages/index.astro `

The full path to the project has a directory with a space in the name. If I move the project outside that path so that no spaces are in the path I no longer see the error.

NOTE: The space is replaced with %20 in the full path in the error message I see.
NOTE: The example URL is not relevant as I don't think this can be reproduced in the same way on stackblitz.

### Link to Minimal Reproducible Example

https://stackblitz.com/github/snowpackjs/astro/tree/latest/examples/minimal?on=stackblitz

**Comment by jonathantneal** [comment]
I am unable to replicate this. Could it be because your example uses Astro v0.20 but the report is for v0.21?

Working in v0.21: https://stackblitz.com/edit/github-yozzvi?file=package.json&on=stackblitz

**Comment by smakinson** [comment]
@jonathantneal The project was started without Vite and I have come back to it here & there to try moving to the Vite compiler. I came back to it yesterday at next.3 and saw this issue. I then tried `next.4` & `next.5`, package.json has:

```
"@astrojs/renderer-vue": "^0.2.0-next.1",
"astro": "^0.21.0-next.5",
```

I run `astro dev` and goto `http://localhost:8080` and in the browser I see a 500 error and a message similar to this:

`ENOENT: no such file or directory, open '/Users/shawn/projects/clients/Some%20Directory/Repos/theproject/theproject-astro/src/pages/index.astro'`

**Comment by smakinson** [comment]
I upped to `"astro": "^0.21.0"` and so far this is no longer happening. I'll close this and if it returns I'll reopen.
