### ISSUE TITLE
v0.21 Bug Bash

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#1860]
## Prioritized for v0.21
- [X] BUG: buildOptions.site errors
- [x] BUG:`HMR` broken! (@natemoo-re)
    - Fix: https://github.com/snowpackjs/astro/pull/1858
- [x] BUG: https://github.com/snowpackjs/astro/issues/1844 (@matthewp)
    - (from Nate in Discord:  JS is not loaded either?)
    - Fix: https://github.com/snowpackjs/astro/pull/1868 
- [x] BUG: `Error: [getStaticPaths] route pattern matched, but no matching static path found. (/)` (@FredKSchott)
    - Fix: https://github.com/snowpackjs/astro/pull/1865
- [x] BUG: bad toString warning  (@jonathantneal)
    - Reason: Unrelated check earlier in code throws before the _right_ error can surface.
    - Fix: https://github.com/snowpackjs/astro/pull/1849
- [ ] BUG: `1 high severity vulnerability` on install (@jonathantneal)
    - Fix: https://github.com/snowpackjs/astro/pull/1867
- [ ] BUG: Many dependencies out of date or no longer used (@jonathantneal)
    - Fix: https://github.com/snowpackjs/astro/pull/1867 (will address both ☝️)
- [x] BUG: `npm init` breaks with some flag usage (@FredKSchott)
    - Reason: npm changed default behavior in a breaking way
    - Fix: https://github.com/snowpackjs/astro/pull/1862
- [x] BUG: Custom elements stopped working (@jonathantneal)
    - Reason: Any tag with a dash accidentally started requiring a renderer after a recent change.
    - Fix: https://github.com/snowpackjs/astro/pull/1854
- [ ] BUG: Old-school Sass syntax not working
    - Reason: 
- [ ] BUG: compiler does not gracefully handle top-level `style` combined with `Layout` component (claimed by @natemoo-re)
    - see: https://stackblitz.com/edit/github-fefvl9?file=src/pages/index.astro

## Nice to Have
- [ ] BUG: [console error and web error do not match](https://discord.com/channels/830184174198718474/854024247286169630/910285385416994866) (@matthewp)
    - Reason: Panics console log themselves and then we capture and send another bug to the browser.
    ```astro
    ---
    let foo;
    
    export function ohno() {
    
    }
    ---
    <div>testing</div>
    ```
    - Research: The panic error comes from Go directly. We could override their wasm glue code and not console.log the panics if that's desired.
- [ ] BUG: Can't run tests on some mac machines
    - Reason: `$$createMetadata is not defined` (@matthewp)
- [ ] BUG: `export default getStaticPaths() {` causes compiler error
    - Reason: Compiler can't report bad JS?
- [x] BUG: [can't print a module namespace that doesn't have toString()](https://discord.com/channels/830184174198718474/854024247286169630/910287316067680317)
    - Reason: 
    - Fix: https://github.com/snowpackjs/astro/pull/1849
- [ ] BUG: [`TypeError: __vite_ssr_import_1__ is not a function`](https://discord.com/channels/830184174198718474/854024247286169630/910286555514540032)
    - Reason: Might be fixed by #1875 
- [ ] BUG: [imports must go at top of file](https://discord.com/channels/830184174198718474/854024247286169630/910285779249541150)
    - Reason: Compiler issue
    - Issue: https://github.com/snowpackjs/astro/issues/1880
- [ ] BUG: When running Astro in an empty directory: `no such file or directory, scandir '/.../src/pages/'`
    - Reason: 
- [ ] Update vite (@FredKSchott)
    - Fix: https://github.com/snowpackjs/astro/pull/1866
- [x] Do we support CSS modules?
- [X] BUG: [error message with double negative wording](https://discord.com/channels/830184174198718474/854024247286169630/910286847912058921)
    - Reason: `{ms}` is becoming `ms()`  in the compiler
    - Fix: N/A - too odd of a bug. Fine to address later

**Comment by jonathantneal** [comment]
Closing this in favor of individual issues.
