### ISSUE TITLE
🐛 BUG: <Markdown> components with inlined html parsed wrongly 

### ISSUE THREAD

**Issue by schlichtanders** [snowpackjs/astro#1877]
### What version of `astro` are you using?

0.20.12

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

While standard markdown files work seamlessly, when using the same markdown code within in <Markdown> tag, line breaks are inserted every time inline html is used. 

I think this is due to wrong rendering. paragraphs are inserted wrongly.

At least for me that makes <Markdown> component unusable unfortunately and I switched everywhere to pure html because of this.

I would love to see Markdown component having the very same support like MD files (or more).

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-wxdcbn?file=src%2Fpages%2Findex.astro&on=stackblitz

**Comment by jonathantneal** [comment]
Yes, I can confirm the text should render like this:

```
This is a sentence go to
```



And instead it is rendering like this:

```
This is a

sentence

go to
```

This does seem like a bug, unless the Markdown parser we use has explicitly different expectations.

**Comment by natemoo-re** [comment]
This is fixed in the new compiler (released under `astro@next`). [See reproduction](https://stackblitz.com/edit/github-wxdcbn-k1fxnf?file=src%2Fpages%2Findex.astro&on=stackblitz).
