### ISSUE TITLE
Error on Windows after creating new project

### ISSUE THREAD

**Issue by itsMapleLeaf** [snowpackjs/astro#188]
I get this error when I try to run the start or build script:
```
Error [ERR_UNSUPPORTED_ESM_URL_SCHEME]: Only file and data URLs are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
 ERROR  Command failed with exit code 1.
```
If it helps, running Windows 10 with PowerShell, but it looks like a path handling issue

My workaround for now is using WSL

EDIT: I noticed that the astro version in the new project was at `0.0.9`. I updated it to `0.0.12`, but the error still happens.

**Comment by matthewp** [comment]
Thanks @itsMapleLeaf, we've made a lot of progress on Windows and it seems to be working fine now. Please upgrade to the latest and retry. Thanks for being an early adopter!
