### ISSUE TITLE
Compiler not gracefully handling top-level styles in <Layout>

### ISSUE THREAD

**Issue by jonathantneal** [snowpackjs/astro#1887]
https://stackblitz.com/edit/github-fefvl9?file=src/pages/index.astro

**Comment by natemoo-re** [comment]
Reported on Discord. See https://stackblitz.com/edit/github-fefvl9?file=src/pages/index.astro

**Comment by natemoo-re** [comment]
See https://github.com/snowpackjs/astro-compiler-next/pull/154

**Comment by jonathantneal** [comment]
Resolved by https://github.com/snowpackjs/astro-compiler-next/pull/154
