### ISSUE TITLE
🐛 BUG: define:vars finds a dom element, does not use var from frontmatter

### ISSUE THREAD

**Issue by IanVS** [snowpackjs/astro#1893]
### What version of `astro` are you using?

0.21.0-next.7

### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

I was trying to use the new `define:vars` syntax on a `<script>`, and found some strange behavior.  

The largest issue is that using the syntax does not seem to make my variable from frontmatter available in my script, but rather tries to find a dom element with an id matching the name of the variable (see the provided stackblitz).

I'm not sure if it's related or another issue, but I also find that I need to restart my dev server in order for changes to apply, refreshing the page is not enough, there seems to be some aggressive caching going on.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-fefvl9-lvja8c?devtoolsheight=33&file=src/pages/index.astro

**Comment by natemoo-re** [comment]
Here [it is working](https://stackblitz.com/edit/github-fefvl9-6cjdnb?devtoolsheight=33&file=src/pages/index.astro). `define:vars` expects an object. 
```astro
<script type="module" hoist define:vars={{ answer }}>
  console.log('The answer in the script is', answer);
</script>
```
