### ISSUE TITLE
pnpm support

### ISSUE THREAD

**Issue by itsMapleLeaf** [snowpackjs/astro#190]
Trying to use pnpm in an Astro project, I get errors of missing packages that I'm not even using:
```
(node:5647) UnhandledPromiseRejectionWarning: Error: Package "preact-render-to-string" not found. Have you installed it?
```
When I install that, it'll say the same thing about Svelte packages.

At the moment, it seems like Astro relies on packages being hoisted, ergo, the default behavior of npm and Yarn 1. That's not the case with pnpm:

![image](https://user-images.githubusercontent.com/19603573/117553206-ba388480-b015-11eb-9e85-e04a636e2d69.png)

**Comment by FredKSchott** [comment]
Moving to #342 so that we can discuss which solution we want to go with.
