### ISSUE TITLE
🐛 BUG: Components in Markdown not well supported via fetchContent

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#1900]
### What version of `astro` are you using?

0.21.0-next.8

### What package manager are you using?

yarn

### What operating system are you using?

mac

### Describe the Bug

When using `Astro.fetchContent()` Components-in-Markdown don't seem to work as expected. You can see this in the new `www` branch, where some `.astro` files couldn't be converted to `.md` files due to this issue. 

I didn't have time to create an isolated test case (had to actually write the blog post :) but I'm happy to walk through this with anyone who can't reproduce.

To reproduce, try converting any of the `.astro` files to `.md`. Alternatively, you can try to use the `Note` component in any existing `.md` blog post. Instead of using the `Note`  component output in the final HTML, I saw a lower-case `<note>` HTML component on the page.

### Link to Minimal Reproducible Example

https://github.com/snowpackjs/astro/tree/new-www-blog/www/src/pages/blog

**Comment by natemoo-re** [comment]
Fixed! Docs to follow
