### ISSUE TITLE
Possible race condition during file output

### ISSUE THREAD

**Issue by kevinkassimo** [snowpackjs/astro#192]
Seems that using the main branch's `astro.mjs` for building a simple project (simply create a simple `index.astro` and use a `Counter.tsx` React component under `<Counter:idle />`) could potentially trigger a race condition of output files.

Occasionally (running a few times. If the bundle is present, delete the whole `dist` folder and try again. I usually hit this bug in 1 out of 4 attempts) the react-dom bundle could not be found in the `dist/` folder, rendering the build broken. However, rerunning the build command could have a very high chance of writing the bundle back to `dist/`. It is unclear what is going on, but very likely a race condition is happening that does not wait for the file to be fully written before the command exits.

**Comment by matthewp** [comment]
Hey @kevinkassimo, I tried to reproduce but haven't been able to. It's possible we've fixed this in the time since you filed. Would you mind trying again and letting me know what you see?

**Comment by matthewp** [comment]
This seems pretty related: https://github.com/snowpackjs/astro/issues/468
