### ISSUE TITLE
🐛 BUG:  {items.map} render problem in table element

### ISSUE THREAD

**Issue by linux-china** [snowpackjs/astro#1939]
### What version of `astro` are you using?

0.21.0

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I have a Pets.astro component with following code: 

```astro
---
const items = ["Dog", "Cat", "Platipus"];
---

<table>
    <tr>
        <td>Name</td>
    </tr>
    {items.map(item => (
    <tr>
        <td>{item}</td>
    </tr>
    ))}
</table>
```

After render,  the html  rendered by {items.map} is not in right place.  

```html
<tr>
    <td>Dog</td>
</tr><tr>
    <td>Cat</td>
</tr><tr>
    <td>Platipus</td>
</tr>

<table>
    <tbody><tr>
        <th scope="col">Name</th>
    </tr>

    </tbody></table>
```

Is it a bug of astro-compiler? 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-r3fqpr-xb1rwf?file=src/pages/index.astro

**Comment by natemoo-re** [comment]
Thanks for the bug report! Yes, this is likely an issue with our compiler. ☺️
I'm going to take a look at this now.
