### ISSUE TITLE
📘 DOC: Broken link to astro configuration API

### ISSUE THREAD

**Issue by fossilx** [snowpackjs/astro#1941]
The configuration reference page currently links to a non-existent file on github.

Current link: 
`https://github.com/snowpackjs/astro/blob/latest/packages/astro/src/@types/config.ts`

I think the correct link should now be: (points directly to `AstroUserConfig`)
`https://github.com/snowpackjs/astro/blob/latest/packages/astro/src/@types/astro.ts#L48`

**Comment by natemoo-re** [comment]
Good catch! If you have a moment, we'd love a PR to fix this!
