### ISSUE TITLE
🐛 BUG: `404.astro` is being built to `/dist/404/index.html` in v0.21

### ISSUE THREAD

**Issue by tony-sull** [snowpackjs/astro#1944]
### What version of `astro` are you using?

0.21.0

### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

In v0.20, `pages/404.astro` would be built to `/dist/404.html`.  In v0.21 it's built in `/dist/404/index.html`

I know I just saw a PR that recently added this functionality into v0.20 and now I can't find it again, but it looks like this may have been lost in the v0.21 update

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-7cpedu

**Comment by natemoo-re** [comment]
Uh oh, good catch—thanks @tony-sull! Hopefully a quick fix.

**Comment by coelmay** [comment]
Related to this I believe @natemoo-re, when using a layout which contains `<style global>`, the `404.html` references the stylesheet incorrectly e.g
```html
<link rel="stylesheet" href="../assets/index.84cdbce3.css">
```
https://github.com/coelmay/status-code-pages-bug has a demonstration (including `dist`.)

Have found this same behaviour when using `Astro.resolve` in `404.astro` to reference a Tailwind CSS `global.css`
```html
<link rel="stylesheet" href={Astro.resolve("../styles/global.css")}>
```
which I have demonstrated in https://github.com/coelmay/astro-resolve-stylesheet-404-issue (including `dist`.)
