### ISSUE TITLE
🐛 BUG: Markdown image alt error when using double quotes

### ISSUE THREAD

**Issue by JuanM04** [snowpackjs/astro#1951]
### What version of `astro` are you using?

0.21.0

### What package manager are you using?

yarn

### What operating system are you using?

Fedora 35

### Describe the Bug

When I declare an image inside a Markdown file like this:

```md
![Person saying "hello"](person.png)
```

It throws this error:

```
Unable to parse

<p><img src="person.png" alt="Person saying "hello""></p>
                             ^
```

### Link to Minimal Reproducible Example

https://codesandbox.io/s/astro-markdown-alt-img-jldil

**Comment by JuanM04** [comment]
Ok, after some research, I found out it isn't a Markdown problem but a problem inside the new compiler.

Having an Astro file like this:

```astro
<div>
  <img src="/my-image.png" alt="A person saying &#x22;hello&#x22;" />
</div>
```

will compile to this:

```html
<div>
  <img src="/my-image.png" alt="A person saying "hello"" />
</div>
```

Also, `&#x22;` is the escaped character that remark uses - that's why I stumbled upon this

**Comment by natemoo-re** [comment]
Awesome investigation! Thanks so much for narrowing this down. We'll start working on a fix.

**Comment by natemoo-re** [comment]
Pushed a fix for this in https://github.com/snowpackjs/astro-compiler/pull/160, hopefully able to merge it soon!
