### ISSUE TITLE
🐛 BUG: `client:only` component doesn’t detect renderer in 0.21

### ISSUE THREAD

**Issue by delucis** [snowpackjs/astro#1958]
### What version of `astro` are you using?

0.21.0

### What package manager are you using?

npm (7.24.1)

### What operating system are you using?

macOS (12.0.1)

### Describe the Bug

With 0.20.x, I was using a `client:only` Preact component with just that renderer configured:

```js
// astro.config.mjs
export default {
  renderers: ['@astrojs/renderer-preact'],
};
```

After upgrading to 0.21.0, I get a 500 Error:

```
Using the `client:only` hydration strategy, Astro needs a hint to use the correct renderer.
Did you mean to pass <ComponentName client:only="react|preact" />
```

[The docs](https://docs.astro.build/core-concepts/component-hydration/#mycomponent-clientonly-) still read:

> **If more than one renderer is included** in the Astro config, `client:only` needs a hint to know which renderer to use for the component.

Has this requirement changed? Should the docs now read that the renderer hint is *always* required? Or is this an oversight in the 0.21 release?

I’ve linked to a reproduction that adds `client:only` to the `Counter` component in the basic Preact starter template, which triggers the same error.

### Link to Minimal Reproducible Example

https://codesandbox.io/s/funny-dirac-opquz?file=/src/pages/index.astro:797-825

**Comment by natemoo-re** [comment]
Most likely an oversight! Let me see if I can track down the bug here.

**Comment by natemoo-re** [comment]
Thanks for the report, it was a quick fix! PR here, hope to get it merged soon. https://github.com/snowpackjs/astro/pull/1959

I'm also glad that this error message is much clearer than it has been in the past!

**Comment by delucis** [comment]
Fantastic. Thanks for such a quick PR!
