### ISSUE TITLE
🐛 BUG: Slot tag inside another tag gets added to the end of the body tag and not inside the nested tag.

### ISSUE THREAD

**Issue by MarioC3** [snowpackjs/astro#1974]
### What version of `astro` are you using?

0.21.0

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

 I'm getting a weird bug where a slot inside another tag gets added to the end of the body tag and not inside the nested tag.

This is my page:
```
---
// import About from '../components/home/About.astro'
import Base from '../layouts/Base.astro'
---

<Base title="Home">
  <div>Hello</div>
</Base>
```

And this is the layout component, where I'm trying to use the slot tag inside another tag:
```
---
// import Header from '../components/global/Header.astro'

const { title } = Astro.props
---

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0"
    />
    <link rel="stylesheet" href={Astro.resolve('../styles/main.scss')} />
    <title>{title}</title>
  </head>
  <body>
    <main>
      <slot />
    </main>
  </body>
</html>
```

And this is the result:
![image](https://user-images.githubusercontent.com/17822054/142912363-8b432b6f-ccec-4916-9b69-32e8195b0ecc.png)

As you can see, the slot content is added to the end of the body tag but not inside of the <main>  tag. 

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-dcd3fh?file=src/pages/index.astro

**Comment by natemoo-re** [comment]
Yep, can confirm this issue. I'll take a look at it!

**Comment by natemoo-re** [comment]
Should be fixed in https://github.com/snowpackjs/astro-compiler/pull/162, which I hope to get out in the next patch release. This was a compiler bug due to case-sensitivity, so `<Base>` was being treated as `<base>`, which is a void tag that doesn't accept children.

As a temporary work-around, you can rename your import. `import Layout from '../layouts/Base.astro'` should work.

**Comment by MarioC3** [comment]
Awesome! You guys Rock!
