### ISSUE TITLE
🐛 BUG: Unable to use typescript with svelte

### ISSUE THREAD

**Issue by vineryap** [snowpackjs/astro#1981]
### What version of `astro` are you using?

0.21.2

### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

This issue is reported on discord support channel [[Thread]](https://discord.com/channels/830184174198718474/911513297285689365)
Since v0.21 when using typescript with svelte components will throw errors.
And if `svelte-preprocess` is used, it will throw `ParseError`.

[Link to repo](https://github.com/vineryap/portfolio/tree/dev-astro-0.21)

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-9vhkyk-qj7dlw?devtoolsheight=33&file=src/pages/index.astro

**Comment by 6-000-000** [comment]
Need help with this, too.

**Comment by vineryap** [comment]
This issue will be fixed by this PR 😃
https://github.com/snowpackjs/astro/pull/1982
