### ISSUE TITLE
Default example has horizontal Scroll

### ISSUE THREAD

**Issue by prophet1996** [snowpackjs/astro#209]
![image](https://user-images.githubusercontent.com/16836510/118154363-f50b3580-b3e4-11eb-9d60-b629dc90f870.png)

**Comment by jasikpark** [comment]
Is this still a problem? I cannot replicate on macOS 11 w/ Firefox 89 - if it is, I'm suspicious of `width: 100vw` and that running into the scrollbar: https://destroytoday.com/blog/100vw-and-the-horizontal-overflow-you-probably-didnt-know-about

https://github.com/snowpackjs/astro/blob/262ab69ebaad04173c75199c60e47dc55f950a51/examples/starter/public/style/global.css#L13-L21

Maybe just rewrite to remove the min-height and change width to `100%`?

**Comment by FredKSchott** [comment]
we'd accept any PRs to fix this! I haven't tried reproducing yet

**Comment by Hanawa02** [comment]
I will try to reproduce and fix this tonight then.
