### ISSUE TITLE
💡 RFC: provide hook for custom markdown renderer

### ISSUE THREAD

**Issue by shedali** [snowpackjs/astro#239]
>  since MD is built-into Astro, it would make sense to provide this hook via some Astro config (or: let you provide a custom Astro plugin that takes over responsibility for rendering MD to HTML)

via [discord](https://discord.com/channels/830184174198718474/845430950191038464/846503698557304832)

**Comment by mgrn0** [comment]
If I understand correctly one use case would be to extend markdown files with custom extensions for e.g. integrating html snippets (for design systems) or to wrap some parts of default markdown with additional markup while rendered, adding footnotes and summaries of links, comments which should not be rendered in html but shall stay in markdown etc..?

**Comment by matthewp** [comment]
Yep!

**Comment by akellbl4** [comment]
I didn't found this issue and [tried to implement](https://github.com/snowpackjs/astro/pull/561) one of Remark plugins right in Astro.

I think it's a great idea to provide the hook for custom remark plugins. I would like to work on it because I'm in the process of migrating my site to Astro and I need [remark-code-titles ](https://github.com/mottox2/remark-code-titles#readme). I think it's the only thing that stops me from full migration.

**Comment by natemoo-re** [comment]
@akellbl4 awesome, definitely let us know if you have any questions! The way `renderers` are implemented is probably similar to the way we'll handle this.

**Comment by akellbl4** [comment]
I've played with source code and written rough implementation.
I have two concerns for now:

- Astro has its own plugins that work with headers. 
  What we should do with it?
  - headers collector could conflict with `remark-slug`
  - should preinstalled plugins be removed?
- I haven't found any docs on `mode: 'md' | 'astro-md'` and dropped it for fast implementation.

Would be happy to have comments on my PR.

**Comment by wooorm** [comment]
Btw: I’d strongly suggest to also allow rehype plugins.
Markdown is used a lot to get to HTML. Historically, there was only remark, so a bunch of things were implemented in that space. But there are also many use cases that don’t really care about the input being markdown, or actually don’t have input markdown (e.g., html -> html), which also makes sense for Astro. So integrating with both would be my recommendation!

**Comment by natemoo-re** [comment]
Thanks for chiming in @wooorm! #562 is in progress and adds support for both!
