### ISSUE TITLE
💡 RFC: Global CSS, Scripts, Snippets

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#244]
I just saw that microsite has a `src/global` directory, where anything inside of it is added to every page: 

```
project/
├── public/             // copied to dist/
├── src/
│   ├── global/
│   │   └── index.css   // included in every generated page
│   │   └── index.ts    // shipped entirely to client, if present
```

We've talked about this a bit in terms of theming / shared themes, but I'd love to do something similar for astro! 

- **Global CSS:** Just add a CSS file into `global/`
- **Global JS:** Just add a JS/TS file into `global/`
- **Global HTML:** Support `.astro` files in `global/`, or `.html`?
- **Global CSS Library:** What's the best way to add something like Bootstrap or Bulma? Would it be a global CSS file with an `@import` that we could turn into a `<link>` element in the final HTML? Or, via a `<link>` tag in a global HTML/Astro file instead?

/cc @natemoo-re

**Comment by jasikpark** [comment]
Maybe the best solution is writing clear documentation about how to solve this specific problem with just layouts, in hugo I have a `baseof.html` template that everything else can add bits to and replace slots in it, which has worked great for me.

**Comment by MarcusOtter** [comment]
I found layouts really intuitive to use and it feels like a really good solution for stuff like this.

Is there anything in particular with this suggestion that cannot be accomplished with layouts?
If no, I would prefer that the API is consistent and doesn't give us multiple options that accomplishes the same thing without any notable differences. Related: [535 ways of reloading the page with JavaScript](https://www.phpied.com/files/location-location/location-location.html).

**Comment by matthewp** [comment]
I'm with @MarcusOtter here that layouts seem to solve this problem well enough. I'm also weary if making it too easy to add files to every page. The downside is that files are added to pages that don't need them. The fact that layouts make you at least think about what resources a page needs adds just a little bit of friction.

In either case, this RFC predates the formal RFC format. If you'd still like to pursue this @FredKSchott can you write this up in the modern RFC format? Thanks.

**Comment by FredKSchott** [comment]
I still think there's a great use-case for this, even if layouts already support it. However I'd recommend waiting until the `next` branch settles before we take a look at this. Happy to rewrite this once the `next` branch is merged (or if anyone else wants to take this on, feel free!)
