### ISSUE TITLE
empty data-attribute tags auto populated with ="true"

### ISSUE THREAD

**Issue by James0x57** [snowpackjs/astro#307]
**Astro: 0.12.3
OS: Windows 10**

If the source contains a data-attribute flag with no value or assignment, Astro is altering the data by appending ="true" to it. The expected behavior is to leave the data-attribute as-is, without appending anything at all, so it does not alter the intent or data.

Code Source:
![image](https://user-images.githubusercontent.com/7545075/120910069-418f0d00-c641-11eb-8291-89b60fde7751.png)

Built Source:
![image](https://user-images.githubusercontent.com/7545075/120910114-aea2a280-c641-11eb-93bc-1c201a0e0793.png)

If the code source explicitly says `data-attr=""`, it will remain empty.

**Comment by Zertz** [comment]
This is problematic for `<!DOCTYPE html>`, which becomes `<!DOCTYPE html="true">`

In that particular case, the exclamation mark should be a good indicator that this isn't a component?

**Comment by jasikpark** [comment]
I think having an empty attribute translate to it equaling true is the safe but ugly choice, afaik there's no instance where it would break things for actual attributes as opposed to the above edgecase..

https://html.spec.whatwg.org/multipage/syntax.html#attributes-2 according to the HTML spec a naked attribute is semantically an empty string: `disabled` => `disabled=""`

**Comment by Zertz** [comment]
I'm not an expert but that doesn't seem to be true for doctype? https://html.spec.whatwg.org/multipage/syntax.html#the-doctype

Also, `data-*` should probably be left untouched since they're effectively custom attributes.

> JSX differentiates between components and HTML elements by case: <Component/> v.s. <div> so maybe the parsing should depend on that 😅?

Indeed. I'd expect vanilla HTML nodes to be left as-is.

**Comment by matthewp** [comment]
I don't think we're trying to be that JSX compatible. We are support JSX-like expressions in `{ }`, but for the HTML parts we are trying to be more compatible with HTML (allowing void elements for example). So I think this should definitely behave like HTML. The fix is fairly simple I believe.

**Comment by matthewp** [comment]
PR https://github.com/snowpackjs/astro/pull/422
