### ISSUE TITLE
💡 RFC: allow exports from .astro components

### ISSUE THREAD

**Issue by James0x57** [snowpackjs/astro#309]
Bringing this over from the discord:

I was hoping to be able to export additional data from a .astro component so that when I import it, that data is available

Currently the export behavior is being hijacked for announcing the component's props, at least in part.

(per Nate, this export/prop behavior will be revisited after launch, so exports may be an option after that change)

🍻

**Comment by natemoo-re** [comment]
Hey @James0x57! Just wanted to let you know that #515 won't actually fix this, but it's on our radar to tackle after we are able to discuss it. There are some interesting edge cases for us to consider before we expose this.

**Comment by natemoo-re** [comment]
Putting this "On Hold" because of some complexities with scoping and hoisting `export` from Frontmatter. Will revisit with a more holistic RFC design.

**Comment by FredKSchott** [comment]
Resolution: The resolution on #619 was that this would not be supported. Closing RFC.
