### ISSUE TITLE
💡 RFC: Astro.imageAsset(...)

### ISSUE THREAD

**Issue by James0x57** [snowpackjs/astro#310]
Given this file structure:

```
src/components/my-astro-component
 - /index.astro
 - /image.png
```

and this code in `src/components/my-astro-component/index.astro`:

```
[...]
<style>
  .avatar {
    background: url({ Astro.imageAsset("./image.png") });
  }
[...]
```

I would like the component's image asset copied into a folder in in the final build (similar to adding it to /public manually) and for the `{ Astro.imageAsset("./image.png") }` text to be replaced with the public asset's path: 
`/astro-build-assets/[hash*]-image.png`

* where "hash" is a unique identifier for the image, mapped from the source path to the hash (so multiple references to the same imageAsset result in the same final path)
* Ideally the hash would be something like a quick md5() of the source path, relative to the project's root, so it would result in the same output each build unless the source moved or was renamed

This would allow astro components that contain images to be reused, and even distributed as a package, without the extra step of manually copying the static assets into a path defined by the component every time the component updates.

(currently my assets folder structure looks like a mirror of my component folder structure, which feels like having a nice closet already, but then building another closet off in the garage just for all of my socks)

Other considerations:

* the string passed into could have the caveat that it's a hardcoded path (not from a variable or otherwise constructed) so Astro can just parse it out of the component styles rather than requiring an actual Astro.imageAsset() function
* The implementation would have to limit the source to specific image types so a malicious component doesn't copy executable code into your build.
* any time Astro.imageAsset() is called (especially/only? when the source path contains "node_modules"), output information in the console, perhaps even a warning, so the site owner is aware of the assets being copied over.

I was going to build this myself using .fetchContent as a tour guide of the code and just submit a surprise PR, but the fetchContent feature isn't ready yet. ;( In any case, I'd be happy to build this feature myself given the green light and a tiny bit of guidance 💜

**Comment by jasikpark** [comment]
A different prior art is [Hugo's Page Resources](https://gohugo.io/content-management/page-resources/)

**Comment by FredKSchott** [comment]
What about `Astro.ref('...')`? I think usage will be fairly common, and I'd love for the syntax to feel really concise and almost invisible:

```diff
- <img src="./logo.svg" />
+ <img src={Astro.ref("./logo.svg")} />
```

**Comment by FredKSchott** [comment]
Also we gotta talk about the fact that Next.js definitely seems to be getting a lot out using ESM imports for this. It's familiar and then they can make sure that it returns all of the data that they need for blur assets, image height width, etc.

```
import profilePic from '../public/me.png'
<img src={profilePic} />
```

**Comment by James0x57** [comment]
I love that idea, simply `import` -ing an image local to the component and having info about it + the asset is copied to the build/dev-runtime. They're getting more than just destination path from that import too, which could lead to some really interesting compiled markup in Astro if you wanted to do something iteratively over the dimensions of an image.

```js
import foldPic from './imgs/0.png'
const w = foldPic.width // undefined or number of pixels wide
const h = foldPic.height // undefined or number of pixels high
const src = foldPic.src // dev runtime (or build) location of the asset copied out of the local component folder
```
```html
<div class="fold-img--left" style="--bgImg: url({src}); --bgOffset: 0px; --bgW: {w/2}px; --bgH: {h}px;"></div>
<div class="fold-img--right" style="--bgImg: url({src}); --bgOffset: {w/2}px; --bgW: {w/2}px; --bgH: {h}px;"></div>
```

**Comment by matthewp** [comment]
@FredKSchott We should talk about this at the next RFC meeting. I want to bikeshed on the name `Astro.ref` (my mind goes to React refs), but regardless you could almost do this yourself like this:

```jsx
---
const url = new URL("./logo.svg", import.meta.url);
---
```

However `import.meta.url` is the file url. We could maybe add something like `import.meta.astroUrl` (bikeshed) and then you could do it like:

```jsx
---
const url = new URL("./logo.svg", import.meta.astroUrl);
---

<img src={url.pathname} />
```

And then your Astro.ref idea could essentially just be sugar for this.
