### ISSUE TITLE
empty CSS clause causes Astro to hang

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#340]
In www, I added this to BlogPost.astro accidentally:

```
.author {
}
```

And Astro hung. I couldn't even kill it with Cmd+C.

**Comment by kevinkassimo** [comment]
Quick inspecting shows that for an empty class `.a` we are getting an ever-increasing output that looks like `.a.astro-ldKR6c5M.astro-ldKR6c5M.astro-ldKR6c5M` (repeat). It seems that after a rule application it is just infinitely reapplied, keeping appending the `scopedClass` and thus freezes

**Comment by FredKSchott** [comment]
This is great debugging, thanks! @drwpow I think you're most familiar with our PostCSS implementation at this point, can you take a look?
