### ISSUE TITLE
Fix pnpm/yarn broken renderers

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#342]
Currently, Astro is importing renderers out of your project that are really dependencies of Astro. This is fine in nested node_modules installations but breaks in pnpm/yarn.

Two ways to fix this:
1. Do we want these renderers to be built in to Astro? If so, we should make a special case for these built-in renderers to be imported inside of Astro so that the correct "dependencies" connection is preserved.
2. Do we want zero renderers built in to Astro? If so, then remove them from Astro proper and then invest in a really good error message when you attempt to load a `.svelte`, `.vue`, or `.jsx` file.

Related problem: how do I control the version of React/Vue/etc. that I use? Right now, these are built into the renderer function directly. The ease of use is nice, but I'd imagine most users want to control this themselves. If we move to streaming package imports in Snowpack, then I believe we'll default to latest unless you specify.

**Comment by matthewp** [comment]
The issue goes a little deeper than just renderers. Snowpack does a lot of resolution from the project perspective that won't work with how pnpm installs packages, it has to be resolved from the caller. I'm still scoping out the problem to see if it's fixable without drastic measures, will report back.

**Comment by duncanhealy** [comment]
drastic measures aka adding all the packages to dev dependencies? or changing path resolution in snowpack?
c.f. https://github.com/snowpackjs/snowpack/discussions/2700
The package list below was the list of packages I had to install to get it working locally

but there is a neater solution - I can add a pr with .npmrc forcing shamefully hoist!

```patch
diff --git a/package.json b/package.json
index b14192e..f4d7799 100644
--- a/package.json
+++ b/package.json
@@ -7,7 +7,29 @@
     "build": "astro build"
   },
   "devDependencies": {
-    "astro": "^0.12.10"
+    "@astrojs/renderer-preact": "^0.1.2",
+    "@astrojs/renderer-react": "^0.1.2",
+    "@astrojs/renderer-svelte": "^0.1.1",
+    "@astrojs/renderer-vue": "^0.1.2",
+    "@snowpack/plugin-postcss": "^1.4.1",
+    "@snowpack/plugin-sass": "^1.4.0",
+    "@snowpack/plugin-svelte": "^3.7.0",
+    "@snowpack/plugin-vue": "^2.6.1",
+    "@vue/server-renderer": "^3.1.2",
+    "astring": "^1.7.5",
+    "astro": "^0.14.1",
+    "autoprefixer": "^10.2.6",
+    "estree-util-value-to-estree": "^1.2.0",
+    "node-fetch": "^2.6.1",
+    "node-sass": "^6.0.1",
+    "preact": "^10.5.13",
+    "preact-render-to-string": "^5.1.19",
+    "react": "^17.0.2",
+    "react-dom": "^17.0.2",
+    "shorthash": "^0.0.2",
+    "svelte": "^3.38.2",
+    "svelte-hmr": "^0.14.4",
+    "vue": "^3"
   },

```

**Comment by duncanhealy** [comment]
`pnpm i --shamefully-hoist` works as does adding a .npmrc file with `shamefully-hoist = true`

**Comment by duncanhealy** [comment]
yarn2 aka berry seems to be adding peer dependencies via pr to `https://github.com/yarnpkg/berry/blob/master/packages/plugin-compat/sources/extensions.ts`

**Comment by duncanhealy** [comment]
adding `.npmrc` with `public-hoist-pattern` with just the above packages does **not** seem to work https://pnpm.io/npmrc#hoist-pattern

**Comment by matthewp** [comment]
@duncanhealy Yeah, drastic as in changing path resolution in snowpack. It's not as simple as what our dependency stack looks like in package.json. Snowpack's `knownEntrypoints` seems to be the main cause of our issues here. This config is used to tell snowpack what modules are going to be needed to be built but aren't scannable from the user's source text. However it's a flat list of dependency names. So snowpack resolves them from the user's project folder. So even though many of them are dependencies of dependencies (any snowpack plugin can add to knownEntrypoints) they all get resolved from the top-level.

We could *maybe* overload knownEntrypoints in the future so that you provide a `cwd` to resolve from. However that would be a pretty big change (and not super ergonomic). So I think merging your PR as a stopgap is a good idea.

**Comment by matthewp** [comment]
@duncanhealy can we include one of these `.npmrc`s with the `astro` package and it will work? Or do we need to tell the user to do it themselves?

**Comment by duncanhealy** [comment]
> @duncanhealy can we include one of these `.npmrc`s with the `astro` package and it will work? Or do we need to tell the user to do it themselves?

yes it could be in the root folder as well, it will work for pnpm - for yarn2 I think we need to add a pr

**Comment by matthewp** [comment]
That might work for working in the monorepo, but I'm asking about when people install `astro` themselves. Do they need to add the `.npmrc` to their own project or can we ship one with our package?

**Comment by duncanhealy** [comment]
> That might work for working in the monorepo, but I'm asking about when people install `astro` themselves. Do they need to add the `.npmrc` to their own project or can we ship one with our package?

postinstall script or docs needed in that case, we could detect if pnpm used and issue a warning

**Comment by matthewp** [comment]
Ok, thanks! I'm going to make this a documentation issue for the time being.
