### ISSUE TITLE
Vue version?

### ISSUE THREAD

**Issue by ibdf** [snowpackjs/astro#344]
It's not clear from the documentation which version of Vue is supported. Based on examples, I believe it's Vue 3 only, but would like to confirm.

**Comment by FredKSchott** [comment]
Yup, that's correct. Right now this isn't customizable, but we want it to be. See this related issue: https://github.com/snowpackjs/astro/issues/342

**Comment by ibdf** [comment]
Thanks, that makes sense.

**Comment by FredKSchott** [comment]
Actually, I talked with the team and realized that this is incorrect. Renderers are designed for specific framework major versions, so to support Vue v2 we'd need to use an entirely different version of the vue compiler.

We should support this in another way:
- The version of the framework comes automatically with the renderer
- If you wanted to use a different version of the framework, use a different version of the renderer
- Or, you can pin your dependency using npm/yarn/pnpm resolutions. This would be only for the advanced use-case, but we should make sure that it's possible as a fallthrough.

I'll add some docs on this now
