### ISSUE TITLE
Errors in clean install

### ISSUE THREAD

**Issue by samuelhorn** [snowpackjs/astro#349]
I did a fresh install with `npm init astro`, then ran `yarn dev`. Im on Node 14 if that helps.

**Error message:**

```
Users/username/dev/astrotest/node_modules/astro/dist/cli.js: 1451
import {clearCache} from "snowpack";

SyntaxError: The requested module 'snowpack' is expected to be of type CommonJS, which does not support named exports. CommonJS modules can be imported by importing the default export.
For example:
import pkg from 'snowpack';
const {clearCache} = pkg;
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:97:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:135:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
error Command failed with exit code 1.
```

Let me know if you want me to debug this further somehow.

**Comment by samuelhorn** [comment]
I see that this was maybe a duplicate of #343, but since I'm on Node 14, I'll leave it here for now.

**Comment by matthewp** [comment]
Do you mean `yarn start`? There's not a `dev` script.  Which template did you use? Also which exact version of Node? I just tested with Node `v14.17.0` and the Starter Kit template and didn't run into this.

**Comment by jonbell-lot23** [comment]
I hit the same issue on v14.12.0.

I upgraded node to the latest and it worked.

**Comment by matthewp** [comment]
Thanks! This is now documented in the readme and the minimum version is in the `engines` field, so you should get warnings on install.

**Comment by jonbell-lot23** [comment]
Huzzah, thanks for the quick fix!
