### ISSUE TITLE
Astro is amazing.

### ISSUE THREAD

**Issue by Zertz** [snowpackjs/astro#353]
I switched the landing page for my [MongoDB app](https://spruce.pierluc.io/) to Astro in about an hour last night!

That is all, thanks for listening! 😻

**Comment by matthewp** [comment]
Oh my! That's so awesome to hear!

**Comment by drwpow** [comment]
![YOU’RE BREATHTAKING](https://thumbs.gfycat.com/ShyBewitchedAmericanpainthorse-size_restricted.gif)

**Comment by FredKSchott** [comment]
@Zertz amazing, thanks so much for the kind words! Closing this issue but so happy that you had a great experience
