### ISSUE TITLE
(Short Term) Roadmap

### ISSUE THREAD

**Issue by matthewp** [snowpackjs/astro#354]
This issue is to collect all of the things we have been talking about working on next. These are mostly smallish changes and not the multi-week efforts such as #80 

# Bug fixes
* Get rid of warnings that we are producing inside Snowpack that can be removed. https://github.com/snowpackjs/astro/issues/356
* Provide a method for renderers to define `knownEntrypoints` (a partial solution for the above)
* Fixing pnpm / yarn support (https://github.com/snowpackjs/astro/issues/342)
* Lots of bugs coming from 2 snowpack instances (see below)
* Message Node.js support correctly

# Possible breaking changes
* __Revisit props__ - Should we continue with the Svelte style `export const foo` method of defining props or try something different. https://github.com/snowpackjs/astro/issues/139
* Get rid of the __2 snowpack instances__. Note that this would be breaking as this is how we can support `import.meta.env.astro`. https://github.com/snowpackjs/astro/issues/357
* What does the process look like for contributing an official plugin? How many plugins are official, where do they live, ownership, etc.

# Testing
* __Integration tests__: Test initing an app and making sure dev and build are working. Do this in a way that doesn't hide monorepo issues. https://github.com/snowpackjs/astro/issues/365

# Enhancements
* Docs site
* __Simplified component with markdown use__: Not needing to create an entire .astro file when most of your content is markdown. https://github.com/snowpackjs/astro/issues/364
  *  +1: @FredKSchott @matthewp, Discord User "we're going to the pride parade"
* A way for non-Astro components to get __async data__ before rendering (aka getStaticProps from Next.js). https://github.com/snowpackjs/astro/issues/358
  * +1: @matthewp
* __Named slots__ https://github.com/snowpackjs/astro/issues/360
  * +1: @FredKSchott, Discord User @iksaku
  * Concerns over complexity
* __Router / Animations__ https://github.com/snowpackjs/astro/issues/361
* __Build UI improvements__ - Showing more information about what was bundled and what wasn't. Handling large sites. https://github.com/snowpackjs/astro/issues/362
  * +1: @FredKSchott  
* __Build performance improvements__ https://github.com/snowpackjs/astro/issues/363
  * +1: @FredKSchott  
* __Module exports from .astro files__: https://github.com/snowpackjs/astro/issues/309
* Contributing Instructions / Docs
* Issue templates

**Comment by FredKSchott** [comment]
Migrated to https://github.com/snowpackjs/astro/projects/2
