### ISSUE TITLE
💡 RFC: Async data in non-Astro components

### ISSUE THREAD

**Issue by matthewp** [snowpackjs/astro#358]
Next.js allows for `getStaticProps`. Is there a framework agnostic approach we could take for this?

**Comment by FredKSchott** [comment]
`getStaticProps()` is only for pages, which in our world are only Astro components. So I think we match Next.js support here already.

Can you explain more / use the full RFC template to describe what you want to see here?

**Comment by matthewp** [comment]
That's probably sufficient then. This is really only an issue when we have SSR. Closing for now.
