### ISSUE TITLE
💡 RFC: Named slots

### ISSUE THREAD

**Issue by matthewp** [snowpackjs/astro#360]
Currently Astro components can only have a single slot `<slot></slot>`. It would be nice to support named slots so that a parent component could split where the slotted content goes.

**Comment by FredKSchott** [comment]
RFC Discussion: Still a priority. No design doc needed if this can be implemented matching the `slot` spec.

**Comment by FredKSchott** [comment]
As a workaround for anyone reading this issue: you COULD use a render prop: `renderHeader={() => ...}`
