### ISSUE TITLE
💡 RFC: Router / Animation API

### ISSUE THREAD

**Issue by matthewp** [snowpackjs/astro#361]
@natemoo-re had some ideas he shared on Discord for how to do animations between pages with Astro. This issue is to explore those ideas.

**Comment by natemoo-re** [comment]
No PR yet but some work has been started on this on [`feat/router`](https://github.com/snowpackjs/astro/tree/feat/router).

**Comment by matthewp** [comment]
@natemoo-re Great first pass at this! From the demo you posted on Discord I didn't see animations. I think it would be good to add some, as that is a major feature of the router (imo) so that will help with both selling the feature and understanding the implementation.

My first reaction looking at the code is that is the DOM differ even needed? The important diffing is happening in mergeHead, which you are doing manually. I'm thinking that diffing the body might also prevent animations. Also removing the diffing will remove most of the size.

**Comment by okikio** [comment]
> No PR yet but some work has been started on this on [`feat/router`](https://github.com/snowpackjs/astro/tree/feat/router).
> 
> Also, [`animate-presence`](https://github.com/natemoo-re/animate-presence/tree/master/packages/animate-presence) could be really great prior art for an Astro animation primitive. Thoughts? Hopefully this isn't seen as trying to shoe-horn my own project into Astro—I genuinely think it is a clean solution that fits well with Astro's philosophy.

I don't think we should build a router into `Astro`, I feel `Astro` should remain a build side tool, and [Shared Element Transition](https://css-tricks.com/shared-element-transitions/) could handle transitions with [App History](https://github.com/WICG/app-history) handling routing. 

However, we could use `animate-presence` as an example of non-history-state changing transitions (https://github.com/domenic/close-watcher/blob/main/README.md).

**Comment by FredKSchott** [comment]
FYI: I'd love to discuss in RFC call, but we'll need a proposal to discuss.

**Comment by matthewp** [comment]
I'm going to close this issue as there isn't a current proposal.
