### ISSUE TITLE
Simplified component usage in markdown

### ISSUE THREAD

**Issue by matthewp** [snowpackjs/astro#364]
Some history on markdown and MDX support:

Initially we supported MDX in `.md` files. However it suffered from some issues and didn't support everything you could do in a `.astro` file. 

Then @jonathantneal submitted a PR that created a `.astro.md` format that allowed markdown within Astro files themselves. 

@natemoo-re took over that PR and created a low-level version of the idea, the `<Markdown>` component which is where markdown compilation is handled.

This means you have great power and integration between astro and markdown. However we lost some of the usage simplicity that we had with the previous `.md` implementation.This issue is to consider:

* Should we bring back component usage within `.md` files?
* Should we create a new format (like `.md.astro`) that simplifies how you use markdown in a regular astro component?

**Comment by FredKSchott** [comment]
Very, very strong +1 for having components inside of markdown `.md` files. I would love to hear more about what the issues are with doing this, and whether anything has changed at all since we last looked into it.

**Comment by matthewp** [comment]
There were technical issues which possibly have been overcome, the biggest was that we had to essentially render `.md` files with a bunch of plugins that were redundant with Astro's own parser. Moving markdown parsing inside of Astro's parser/compiler fixed this because Astro gets to parse first.

The new implementation could be used on a `.md` file but as far as I'm aware these issues would still exist with using `.md`:

1. Syntax highlighting breaks pretty quickly.
2. `.md` files used yaml frontmatter which meant imports like this:
   ```yaml
   title: Something
   imports:
     Counter: ../components/Counter.jsx
   ```

    1. This also means you can't do any "setup" type of code such as fetching external data. `.md` was a very limited idea and moving to Astro gave you the full power of JavaScript.

**Comment by jasikpark** [comment]
i was reading https://github.com/snowpackjs/astro/blob/d6cedac38e25fbec8425e020c16393fd70f0adf6/examples/blog/src/layouts/post.astro
i was hoping to be able to choose between `{content.markdown}` and `{content.html}` so that I could choose to pipe the markdown file into a `<Markdown>` component and get mdx style component rendering w/o writing my markdown in astro files... i.e. replace `<slot/>` on that page with `<Markdown>{content.markdown}</Markdown>` so that it gets rendered w/ Astro's renderer :sweat_smile:

**Comment by matthewp** [comment]
For people who are feeling the pain of this, what do you think about this idea?

__.md.astro__ extension. Used like:

```jsx
---
import Something from '../components/Something.jsx'

const data = [ ... ]
---

# My Post

This is a just a normal markdown with [links](./) and whatnot.

And __here__ I'm using a component:

<Component data={data.filter(item => item.color == 'blue')} />

more text here
```

The advantage to this approach over `.md` would be:

* Syntax highlighting will work because its just Astro.
* You can use JavaScript in frontmatter, like any .astro file. 
* You can do setup code (the `data = []` part), which you can't do in `.md` files.

**Comment by georges-gomes** [comment]
+100 for me

**Comment by jasikpark** [comment]
> For people who are feeling the pain of this, what do you think about this idea?
> 
> **.md.astro** extension. Used like:
> 
> ```js
> ---
> import Something from '../components/Something.jsx'
> 
> const data = [ ... ]
> ---
> 
> # My Post
> ```

I like the idea, though I wonder how frontmatter variables are declared, just as local variables or as exports?

```jsx
---
import Something from "../components/Something.jsx"
// actual, regular JS exports from the post after the RFC on Astro props is finalized
export let title :string = "My Post"
export let description :string = "This is an example post about what astro-augmented markdown should look like"
---

This is a just a normal markdown with [links](./) and whatnot.

And __here__ I'm using a component:

<Component data={data.filter(item => item.color == 'blue')} />

more text here
```

**Comment by FredKSchott** [comment]
Hey all, I created a Feature Request issue to discuss a specific proposal to solve this. It's not too far off from @matthewp's post above: https://github.com/snowpackjs/astro/issues/364#issuecomment-859573326. Would love your feedback in that thread

**Comment by FredKSchott** [comment]
Update: we'd like to move forward with https://github.com/snowpackjs/astro/issues/491, will confirm at next RFC call

**Comment by FredKSchott** [comment]
Continuing conversation in #491

**Comment by chadananda** [comment]
Minimal MD functionality is to override tags, support a plugin ecosystem for custom needs and to support Astro components registered elsewhere -- so that content authors are not asked to write code. 

Markdoc addresses the last one but is incompatible with all CMS editors and plugin ecosystems -- and does not work outside of local content collection data.
