### ISSUE TITLE
 [example/docs] SiteSidebar doesn't respect `buildOptions.site`

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#388]
https://github.com/snowpackjs/astro/blob/main/examples/docs/src/components/SiteSidebar.astro

We should use the site value in the link tag here to make sure that links are properly updated when a site is hosted outside of the main root.

@matthewp is this value available via `Astro.site`? As long as its available, this should be an good first issue for anyone to tackle.

**Comment by matthewp** [comment]
Yep! `Astro.site` should be available to all Astro components.
