### ISSUE TITLE
[Bug] Starter template fails to build

### ISSUE THREAD

**Issue by drwpow** [snowpackjs/astro#394]
On Node 16:

Install deps, and build project:
```
yarn
yarn build
```

Then navigate to `examples/starter` and run:

```
yarn build
```

You should see an error:

```
[15:36:01] [snowpack] Build Result Error: There was a problem with a file build result.
[build] Error: Error: Unexpected: Unscanned package import "astro/dist/internal/__astro_component.js" couldn't be built/resolved.
    at file:///Users/drewpowers/Code/snowpackjs/astro/packages/astro/src/build/page.ts:98:44
```

**Comment by matthewp** [comment]
I was able to get it to build in a new `npm init` project. What version of Node are you seeing this on?

**Comment by drwpow** [comment]
Node 16. Run a fresh `yarn && yarn build`, then navigate to `examples/starter` and run `yarn build`. I get an error.

**Comment by duncanhealy** [comment]
snowpack.config.js "workspaceRoot" needs to be set in examples/starter ?

**Comment by duncanhealy** [comment]
if we add to package.json 
```
"snowpack": {
    "workspaceRoot": "../.."
  }
``` 
the error goes away but the starter is being used by `npm init astro` 
?? so should snowpack be stripped from package.json when --template passed into `npm init astro`

**Comment by drwpow** [comment]
@duncanhealy Ah that’s it! OK that’s just a local issue, then.

And yes we are stripping `snowpack` out of `package.json` on `npm init astro` (I don’t think for the current version, but we will in the next release)
