### ISSUE TITLE
💡 RFC: Support partial hydration based on custom media queries

### ISSUE THREAD

**Issue by tony-sull** [snowpackjs/astro#396]
@matthewp and @natemoo-re brought up some ideas related to this in Discord, opening this issue for discussion

The basic idea is to only hydrate custom JS on the client based on a media query, along the lines of

`<MobileMenu:media query="screen and (max-width: 768px)" />`

This would also add feature detection support via media queries level 4, think `@media (hover: hover)` to only load a component that supports hover input

**Comment by matthewp** [comment]
Thinking about this a bit more, maybe instead of putting your media query in an attribute, where you'd have to repeat it for each time you used it, we could provide a way to define "loaders" via config. Maybe like this:

```js
export default {
   // ...
   loaders: {
     mobile: ["media", "screen and (max-width: 768px)"]
   }
}
```

> Note I went with array syntax here in case we wanted to make this pluginnable in the future, but we can bikeshed on the syntax.

Then you'd use like:

```jsx
<MobileMenu:mobile other={props} />
```

**Comment by FredKSchott** [comment]
So I really, REALLY like this idea. First thing that jumps to my mind is, why not leverage JS to solve the reusable, custom media queries?

```
---
import {MOBILE} from '../my-custom-media-queries.js';
---
<MobileMenu:idle media={MOBILE} />
```

Or even better, maybe this is our chance to turn `idle`/`load`/`visible` into something more extendable?


```
// Example interface:
<MobileMenu :idle />
<MobileMenu :load />
<MobileMenu :visible />
<MobileMenu :client={{method: 'idle', media: '...'} />
```

**Comment by natemoo-re** [comment]
@FredKSchott Now we're talking! This was kind of the direction I expected things to go. It would definitely help to have a syntax that allows for more arguments. I think we could go with each one as a keyword? `:` would be the signifier for a loading directive.

```
<Component :load />
<Component :idle />
<Component :visible />
<Component :media="(min-width:40em)" />
<Component :custom={JS_HOOK} />
```

I really like idea of custom JS hooks!
1. It should be separate from a built-in `media` directive. IMO media query is a common enough use case to provide out of the box.
2. I think Matthew's proposal would make syntax highlighting hard to support?

**Comment by tony-sull** [comment]
I'm a big fan of adding optional arguments to the different hydration options!  I was actually thinking that could be helpful at some point for adding a `rootMargin` or `threshold` to `:visible` as well.

This almost feels similar to Svelte's `use:action` syntax, what if the generic hydrate concept was wrapped up into a single syntax?

```js
---
import { idle, media } from "astro/hydrate";
import { myHydrate } from "../utils/hydrate";

import Component from "../components/Header.jsx";
---

<Component hydrate:idle />
<Component hydrate:media="(min-width: 40em)" />
<Component hydrate:myHydrate />
```

**Comment by matthewp** [comment]
I like the direction this is going. One downside I thought of in my idea is that 3rd party packages wouldn't be able to use `:mobile`, etc. since it would have been defined in the app's config. Sharing via JSX expressions fixes that.

---

@tony-sull Your idea interesting here too. One thing with the current implementation is that the hydrators are resolved at compile time and this idea would make them be at runtime. Not sure if that would be a problem or not.

I do think that a media query hydrator should be built in though.

**Comment by matthewp** [comment]
@FredKSchott why remove the label?

**Comment by FredKSchott** [comment]
(As a part of the new board, "enhancement" is now tracked in the project tracker by column.)

@matthewp great point on runtime vs. compile-time. I think that could be an argument for implementing `:media` first, and then having a separate enhancement to add runtime support for custom load logic.

general bikeshed comment: If we're moving `:load` from `Name:load` to `Name :load`, then I'm a strong +1 for putting something before the `:` aka `<Name client:load>` or `<Name hydrate:load>` for some future flexibility (also, more clear).

**Comment by eyelidlessness** [comment]
I am _**all for**_ the proposed move of hydration directives to props, as I was in @natemoo-re’s draft PR introducing that (which I’m having trouble finding now). I will caution that the `:` character has a special meaning in XML (so likely to affect JSX renderers), and in HTML (so likely to affect everyone). If you’re going this way it would be a really good idea to include a namespace defining the attributes so it’s not surprising and plays nice with other tooling.

**Comment by jasikpark** [comment]
A chaotic option for this would be to just allow some sort of way to define custom loading functions, though I think keeping it as magic that is slowly extended makes more sense.

ex:
```jsx
<Component:custom-predicate/>
```

```ts
function custom-predicate() {
  // does it's own fancy math with whatever detection system you want whether that's IntersectionObserver or loading only after some user-input is added...
}
```

I think this is mostly dumb and I can't really think of a usecase, but it's interesting...

**Comment by matthewp** [comment]
I added a proposal for this here: https://github.com/snowpackjs/astro/issues/514
