### ISSUE TITLE
Example: Netlify CMS with Astro

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#401]
@drwpow mentioned that this was blocked because we'd need to load a file out on an npm package without transformation.

```
// not currently supported
<script src="npm:@netlify/cms/dist/netlify.js"></script>
```

**Comment by drwpow** [comment]
Ah sorry I should have updated that. That’d be a nice-to-have, but not blocking. I think one can use this instead in an astro file ([docs](https://www.netlifycms.org/docs/add-to-your-site/)):

```
import CMS from 'netlify-cms-app'
// Initialize the CMS object
CMS.init()
// Now the registry is available via the CMS object.
CMS.registerPreviewTemplate('my-template', MyTemplate)
```

**Comment by jasikpark** [comment]
I've got a mess of netlify cms shortcodes defined exactly like that! https://github.com/jasikpark/jasik-xyz/blob/main/assets/js/admin/index.js

**Comment by tony-navillus** [comment]
I just finished up a Netlify CMS demo - [repo here](https://github.com/Navillus-BV/demo-astro-netlify-cms) and a blog post covering the basics [here](https://navillus.dev/blog/astro-plus-netlify-cms

**Comment by FredKSchott** [comment]
Thanks @tony-navillus !!!
