### ISSUE TITLE
Forward slashes result in build error when used in template strings within inline functions

### ISSUE THREAD

**Issue by tylergaw** [snowpackjs/astro#407]
Here's a Codesandbox demo of the error https://codesandbox.io/s/dreamy-darkness-dd1vi?file=/src/pages/index.astro

The following results in an error `ParseError: <a> was left open`

```
---
let tags = ["dogs", "cats", "birbs"]
---

<body>
  {tags.map(t => <a href={`/tags/${t}`}>{t}</a>)}
</body>
```

### Workaround

As long as you don't create the template string directly in the expression, you can make this work:

```
---
let tags = ["dogs", "cats", "birbs"]
---

<body>
  {tags.map(t => {
    const href = `/tags/${t}`;
    return <a href={href}>{t}</a>
  })}
</body>
```

or if you have a URL creator function somewhere:

```
---
let tags = ["dogs", "cats", "birbs"]
let createUrl = (s) => `/tags/${s}`;
---

<body>
  {tags.map(t => <a href={createUrl(t)}>{t}</a>)}
</body>
```

**Comment by FredKSchott** [comment]
Ah, must be a parser error. Hopefully just something small that was missed in that logic

**Comment by drwpow** [comment]
Fixed! Thank you for filing. This was just a tiny bug in our parser. This will go out in the next release.

**Comment by tylergaw** [comment]
Nice! Thank you @drwpow
