### ISSUE TITLE
💡 RFC: Support fetch() in all JS files, not just Astro files

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#410]
- We've seen multiple users try to use `fetch()` in JS/JSX files
- We encourage this since it's supported in top-level Astro files
- When a user does this, we throw during SSR with `fetch()` is undefined (but would succeed on the client)
- Should we polyfill this in JS/JSX files as well? If not, we should at least expose our fetch polyfill via `import {fetch} from ...` or `Astro.fetch`.

**Comment by matthewp** [comment]
the `Astro` "global" is only available in`.astro` files so that won't work. I think making it available on the globalThis object is the way to go. Cloudflare Workers has it as a global, Deno has it as a global. Node has tried to make it a global I believe, so the world is going this way already.

Is this something we can leverage Snowpack to do for us?

**Comment by FredKSchott** [comment]
I think we could! Especially if "be a better SSR runtime" is a goal for Snowpack going forward

**Comment by eyelidlessness** [comment]
> Deno has it as a global.

I think it’s generally a good idea to follow what Deno is doing wherever possible, as it philosophically aligns well with Snowpack (ESM first) and Skypack (modules are just URLs). And frankly I’d love to see Snowpack and Astro support Deno someday.

**Comment by FredKSchott** [comment]
Okay, is everyone on board with making it global in non-Astro. /cc @natemoo-re @drwpow 

re: leveraging Snowpack for this: Right now, I think you'd have to add a Snowpack transform plugin to inject it in all JS files post-load, using a similar snippet to the one we use in `.astro` files.

**Comment by natemoo-re** [comment]
👍🏻 I'm good with adding it to `globalThis.fetch`. Does that mean we should also add `globalThis.Request`, `globalThis.Response`, `globalThis.Body`, and `globalThis.Headers`? Am I missing any others?

Also this is a release candidate currently, but good to keep an eye on [`undici-fetch`](https://github.com/Ethan-Arrowood/undici-fetch#readme).

**Comment by natemoo-re** [comment]
RFC Discussion: moving forward with `globalThis.fetch`, not adding the additional objects mentioned (until a good use case is introduced).

**Comment by jasikpark** [comment]
Is this just waiting for implementation like in https://github.com/snowpackjs/astro-docs/issues/37#issuecomment-874536881 ?

> in the meantime I came up with this temporary solution:
> 
> ```js
> // astro.config.mjs
> import fetch from 'node-fetch';
> 
> export default {
>     renderers: ['@astrojs/renderer-preact'],
>     injectGlobals: (() => {
>         globalThis.fetch = fetch;
>     })(), //IIFE, the name of the fn is not important but it should not collide with any supported config property
> };
> ```
> @kolodziejczak-sz

**Comment by kolodziejczak-sz** [comment]
> 
> 
> Is this just waiting for implementation like in [snowpackjs/astro-docs#37 (comment)](https://github.com/snowpackjs/astro-docs/issues/37#issuecomment-874536881) ?
> 
> > in the meantime I came up with this temporary solution:
> > ```js
> > // astro.config.mjs
> > import fetch from 'node-fetch';
> > 
> > export default {
> >     renderers: ['@astrojs/renderer-preact'],
> >     injectGlobals: (() => {
> >         globalThis.fetch = fetch;
> >     })(), //IIFE, the name of the fn is not important but it should not collide with any supported config property
> > };
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > @kolodziejczak-sz

that's right, this little hack allowed me to use one service on the backend & client side
