### ISSUE TITLE
💡 RFC: Add simple way to debug output on the client

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#411]
- We've seen multiple users create their own `<pre>` tags to log some variable to the page
- Often this meant also adding custom styles as well so that the pre element didn't overflow past the page
- Overall this took a minute or so to configure each time
- It would be good to have a built-in <Debug ...> component that would do this automatically
- alt: Svelte has an {@debug ...} tag that we could also borrow from. Nice because no `import {Debug}` is needed in addition, but a shame because it's a new syntax to learn

**Comment by jasikpark** [comment]
Could always just make it part of a "prelude" of imported components...

**Comment by jasikpark** [comment]
![Screenshot 2021-07-13 at 02-21-04 Astro](https://user-images.githubusercontent.com/10626596/125408927-05a64080-e381-11eb-9660-64a4501709c2.png)

Tada! I have a very ugly version of this in the works...

https://github.com/jasikpark/astro/astro-debug-component  && https://github.com/jasikpark/astro/example-usage-debug-component

**Comment by jasikpark** [comment]
![Screenshot 2021-07-13 at 02-47-04 Astro](https://user-images.githubusercontent.com/10626596/125412543-f56eb9d2-96d4-45be-ae7b-619dfba680b0.png)

NVM! I think I've got it -- it's just a wrapper around `<Prism>` that pretty prints the props as JSON, then passes that to Prism to syntax highlight as JSON!

**Comment by jasikpark** [comment]
Now just to figure out how I'm meant to write tests for it...
