### ISSUE TITLE
[collections] permalink is too loose, can crash Astro

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#412]
A few issues here:

- [ ] CRITICAL: If permalink ends with `/`, it crashes the process
- [ ] should fail if permalink doesn't match the collection file location in `pages/` (Updated: see https://github.com/snowpackjs/astro/issues/483#issuecomment-864315411)
- [ ] no warning if permalink includes an undefined variable (not critical, can be turned into a separate issue).
- [ ] data seems to be built on top of permalink. It should probably be built on top of routes instead (better source of truth) since bad data like `/tags/undefined` is still a string / hard to detect as broken. Some other redesign could make sense as well.

**Comment by natemoo-re** [comment]
@drwpow can you confirm if 
>  CRITICAL: If permalink ends with /, it crashes the process
was fixed by #469? I assume that's the same issue.

**Comment by FredKSchott** [comment]
(Note: CRITICAL is the only priority here, the rest can be tackled in follow up refactoring)

**Comment by natemoo-re** [comment]
@FredKSchott confirmed that #469 fixed any crash related to trailing `/`. Pasted the other items into #501 to be tackled with the `collections` improvements being discussed there.
