### ISSUE TITLE
Case insensitive <!DOCTYPE html>

### ISSUE THREAD

**Issue by edburtnieks** [snowpackjs/astro#413]
## Issue

I usually prefer my Doctype to be in all uppercase `<!DOCTYPE html>` (it's the case in a lot of example too), but noticed that currently it gets parsed as:

```html
<!DOCTYPE html="true"><!--!DOCTYPE-->
```

## Expected result

The Doctype is case insensitive, so the casing should not matter - https://html.spec.whatwg.org/multipage/syntax.html#the-doctype

**Comment by matthewp** [comment]
Yeah we shouldn't be touching the doctype if it's already in the document, this is a bug.

**Comment by edburtnieks** [comment]
Saying that, I see that emitting doctype completely, we add it automatically to the built html, but yea, in case one leave it and changes casing, it breaks.

**Comment by matthewp** [comment]
PR in #419
