### ISSUE TITLE
[Feature Request] Add Astro file icon to Astro VSCode extension

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#423]
## What is Missing from Astro Today?
- Astro files are missing an icon in VSCode.
- If you have vscode-icons then it does show up, but many users do not.

## Proposed Solution
- Add the astro file icon to the Astro VSCode extension
- See: https://code.visualstudio.com/api/extension-guides/file-icon-theme

## Help Make it Happen!
- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by natemoo-re** [comment]
VS Code doesn't allow an extension to define a _single_ icon for a language, it only allows you to define _all_ icons for _all_ files. This is why we've been taking the approach of adding the [official `astro` icon](https://github.com/snowpackjs/astro/blob/main/assets/brand/file-icon.svg) to popular icon themes.

So far we've added support in:
- [x] [`vscode-icons`](https://marketplace.visualstudio.com/items?itemName=vscode-icons-team.vscode-icons)
- [x] [`material-icon-theme`](https://marketplace.visualstudio.com/items?itemName=PKief.material-icon-theme)

If you'd like to add support to another theme, please open another issue!
