### ISSUE TITLE
🐛 HMR using CSS Modules not refreshing properly

### ISSUE THREAD

**Issue by ewatch** [snowpackjs/astro#435]
### Bug Report: Quick Checklist

- [x] I am on the latest version of Astro & all plugins.
- [x] I am on an ESM Node.js version (`v14.16.1`)
- [x] I use package manager: (npm/yarn).
- [x] I run Astro on OS: (Mac).

### Describe the bug

When using the astro dev server and using a CSS Module which is imported in a React component,
changing the CSS inside the CSS Module leads to generating a new scoped css class.
However the rendered astro component still has the old scoped css class attached to it.
Restarting the dev server fixes it.

### Steps to reproduce

1. `npm init astro` using template <NAME>
2. Create a React Component in the components folder `MyReactComponent.jsx`:
```import React from 'react';
import styles from './MyCSS.module.css';

export default function MyReactComponent() {
    return <h1 className={styles.headlineBackground}>This is my title</h1>;
}
```
3. Create a CSS Module in the component folder `MyCSS.module.css`:
```
.headlineBackground {
    background-color: blue;
}
```
5. Create an astro file in the pages folder `test.astro`:
```
---
import Comp from '../components/MyReactComponent.jsx';
---
<html>
<head>
    <title>bug</title>
</head>
<body>
<p>adfafafa</p>
    <Comp />
</body>
</html>
```
6. `npm start` for the dev server
7.  Change the `background-color` property in the CSS Module
8. The style is not applied anymore to the react component

### Expected behavior

Changes in the CSS Module would be applied through HMR

**Comment by matthewp** [comment]
Fixed in #462
