### ISSUE TITLE
🐛 Misleading error message when component throws

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#442]
### Bug Report: Quick Checklist

- [x] I am on the latest version of Astro & all plugins.
- [x] I am on an ESM Node.js version (`v12.20.0+, v14.13.1+, or v16.0.0+`)
- [x] I use package manager: npm
- [x] I run Astro on OS: Mac

### Describe the bug

When a component fails to render, the error message is misleading and talks about a missing renderer, which is not true.

### Steps to reproduce

1. `npm init astro` using template starter-kit
2. Add a React component like https://github.com/learnwithjason/lets-learn-astro/blob/main/src/components/Button.jsx
3. Remove the `import ... 'react'` line, save, and refresh the page
5. Error! That's expected, but the error itself is misleading and talking about renderers and such.

@natemoo-re mentioned that he had been tracking this before he went out on break.

**Comment by matthewp** [comment]
This was fixed when the JSX renderer `check` was improved. We now report errors properly. In this above case you get this now:

```
ReferenceError: React is not defined
    at Button (/_astro/src/components/Button.js:4:29)
```

Closing.
