### ISSUE TITLE
🐛 Data not updating on save

### ISSUE THREAD

**Issue by mrbrianhinton** [snowpackjs/astro#443]
### Bug Report: Quick Checklist

- [x] I am on the latest version of Astro & all plugins.
- [x] I am on an ESM Node.js version (**v16.0.0+**)
- [x] I use package manager: **npm**
- [x] I run Astro on OS: **Mac**

### Describe the bug

When a local file is updated, and the component is changed Astro is not updating the data without restarting the server.

### Steps to reproduce

1. Create a local .json file populated with data located in src/data/file.json
2. Import the data into a component `import file from '../data/file.json';`
3. Map over the data somehow ie. 
```
{file.data.map((nom) =>
            nom.data === "text"
                ? (<li><a href="{nom.prop1}">{nom.prop2}</a></li>)
                : null
        )}
```
4. Update the data in the json file
5. Next update the component ie. list into a paragraph
6. The data never changes for me no matter how many updates to the component I make. Even rewriting the .map to look for a different piece of data results in the original versions of that data rendering. Meaning if nom.prop3 replaced nom.prop1 in the rewritten .map and the original nom.prop3 = yummy, and I changed nom.prop3 = toast in the json file. Refreshing the browser still says yummy.

### Expected behavior

Ideally when it detects that the local data file has updated it should reload the data into the file variable. I do see Astro detects that the .json file has changed in terminal. Astro should update the output of .map even without a component update.

**Comment by matthewp** [comment]
Can confirm this is happening.
