### ISSUE TITLE
💡 RFC: Trailing slashes

### ISSUE THREAD

**Issue by trustedtomato** [snowpackjs/astro#452]
## What is Missing from Astro Today?

Currently, URLs with trailing slashes result in the "not found" page by default.
There should be a way to serve the page with trailing slashes without changing all of the routes' permalinks.
The reason why I find this important is because both GitHub Pages and Netlify uses trailing slashes and redirects non-trailing-slashed URLs to trailing-slashed ones, which means that all of the links which were working in development result in an avoidable redirect when using the mentioned services.

## Proposed Solution

There could be a config option similar to SvelteKit's: `trailingSlash: 'must-exist' | 'can-exist' | 'cannot-exist'`. (I find this API a bit more intuitive than SvelteKit's `trailingSlash: 'never' | 'always' | 'ignore'`), but it doesn't really matter.

## Help Make it Happen!

- [ ] I am willing to submit a PR to implement this change.
- [x] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by natemoo-re** [comment]
We currently emit `src/pages/name.astro` as `/page/name/index.html`, which would line up with the default behavior of GitHub Page and Netlify. Is our dev server doing the opposite and redirecting trailing-slashed to non-trailing-slashed? If so, I agree that we should fix that.

Would `must-exist`, `can-exist`, and `cannot-exist` modify the `build` output? Would you mind clearly defining how the output would differ between each of those options?

**Comment by FredKSchott** [comment]
I'll just add that since SvelteKit is building a Node.js server, they need to build that `trailingSlash` logic into their production server.

Because Astro is building a static site, it's up to the host how it handles these things. We could have an option like this to define dev server behavior, but I'd almost rather just be flexible (this is a dev server, after all) and support all of them in dev.

**Comment by trustedtomato** [comment]
Yeah, being flexible seems to be a very good resolution to my problem.
I think that the deployment and the dev version could behave the same way using this option, which might help catching bugs in development, but being flexible (`trailingSlash: 'can-exist'`) would definitely be a very nice default option since it would enable both trailing-slashed and not-trailing-slashed URLs to work.

**Comment by radiosilence** [comment]
Yeah, we're using a trailing slash for all of our internal links, and whilst serving it works fine, the dev server says not found if you use trailing slashes.

**Comment by FredKSchott** [comment]
RFC Discussion: +1 to move forward on this feature.

**Comment by FredKSchott** [comment]
FYI we have a PR out to fix this!
