### ISSUE TITLE
[Feature Request]  Config option to allow dot files to be copied on build

### ISSUE THREAD

**Issue by theZieger** [snowpackjs/astro#453]
## What is Missing from Astro Today?

`astro build` is not copying some files over to `/dist` e.g. in my case astro is not copying my `.htaccess` over to `/dist`

## Proposed Solution

I guess by default astro is ignoring files prefixed with a dot. A allowlist to support specifc files via `astro.config.mjs` would be nice I guess.

## Help Make it Happen!

- [ ] I am willing to submit a PR to implement this change.
- [x] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
This is coming from Snowpack: we ignore all dotfiles by default in your final build.

I think that we'd continue to ignore dotfiles in your `src` directory, but I do agree that all dotfiles in the public directory should be included. I think this means that we need a feature request to add `dot` support to Snowpack's mount config. I'll get a PR up there, and then if there's anything else needed here it should be fairly straighforward to enable.

**Comment by theZieger** [comment]
Sounds great! Thanks for the fast feedback and even a PR against snowpack. 💯

**Comment by FredKSchott** [comment]
This wasn't meant to be closed by that issue! Following up in https://github.com/snowpackjs/astro/issues/689
