### ISSUE TITLE
🐛 global.css from /public is copied to /dist but unused

### ISSUE THREAD

**Issue by theZieger** [snowpackjs/astro#454]
### Bug Report: Quick Checklist

- [x] I am on the latest version of Astro & all plugins.
- [x] I am on an ESM Node.js version v14.13.1+
- [x] I use package manager: npm
- [x] I run Astro on OS: Linux Ubuntu 20.10

### Describe the bug

On `astro build` global.css is copied to `/dist` but inside the website/app itself it is unused.
Unused in the sense that the file itself is never referenced inside any HTML file since it is bundled into the final CSS files (common-xyz.css)

Edit as stated by @Hanawa02:
I reference global.css directly inside a component via link and would therefore either expect that global.css stays global and is simply referenced in the final build HTML file via link or that it is bundled into the _astro scoped css files and is not part of the final build (as dist/global.css)

### Steps to reproduce

1. `npm init astro` using template blog
2. `npm run build`
3. discover global.css in `/dist`
5. Error!? global.css inside `/dist` but never referenced from any HTML file

### Expected behavior

I guess it should not be copied to /dist after the build if it is bundled into _astro/common-xyz.css
Since /dist would be my final build and shipping that file is not needed.

**Comment by theZieger** [comment]
Hey @Hanawa02 thanks for the quick response. From what I read in #445 I think they are different issues.
I reference global.css directly inside a component via <link /> and would therefore either expect that global.css stays global and is simply referenced in the final build HTML file via link or that it is bundled into the _astro scoped css files and is not part of the final build (as dist/global.css)
But since I don't know the inner workings I might be wrong here and those issues are connected but at least separate cases a test might cover?

**Comment by Hanawa02** [comment]
@theZieger Sorry, I misunderstood your scenario then. Would say they are probably related (I also don't understand the work behind the scenes as well), but not duplicated.

I would recommend adding this information about the global.css being referenced within a component and not the layout or as an HTML link inside the <head> tag to help on debugging.

**Comment by FredKSchott** [comment]
This is actually a limitation of Snowpack, but one that we can remove now that we have a better idea of your application structure in Astro. 

**Rough outline of what I'd like to see:**
- `public/` is for raw assets, maybe built (scss -> css) and minified but not tree-shaken or bundled. We'll never be able to know 100% if these are safe to remove if not found (maybe they're referenced from somewhere completely outside of your application) so we always leave this in the final build.
- `src/` is for your application, and any JS/CSS inside of it is bundled, tree-shaken, optimized to the max, etc.

**Comment by theZieger** [comment]
Hey @FredKSchott thanks for the explanation.
You are totally right. I guess your expectation would also match with people coming from other frameworks, boilerplates, etc.

**Comment by matthewp** [comment]
So can this issue be closed? Seems like `src/` is copied only when used, and `public/` is always copied and that's the way we want it.  Btw, you can use something from `/src` (such as CSS) like so:

```html
<link rel="stylesheet" href="/_astro/src/whatever/global.css">
```

**Comment by FredKSchott** [comment]
If we're already doing this then that's great! I guess the the action item here becomes:
1. Document this behavior
2. Add some tests to make sure it doesn't break later
3. confirm and add test the non-standard behavior seen in #445



---
_copied from #445: (`_astro/common-rk2vf.css` is what shouldn't exist following this plan)_
In resume: 
Before build:
`public/index.css`
`public/theme.css` (imported in the index.css as `@import './theme';`)
`public/theme.css` (imported in the index.css as `@import './code';`)

After build:

`_astro/common-rk2vf.css`
`theme.css` (imported in the common-rk2vf.css as `@import './theme';`)
`theme.css` (imported in the common-rk2vf.css as `@import './code';`)

**Comment by FredKSchott** [comment]
I'll remove the "needs discussion" label if all @snowpackjs/maintainers are in alignment on this

**Comment by theZieger** [comment]
Maybe I got this wrong but I see a slight difference here between #445 and my issue.
@FredKSchott you stated that:

> `public/` is for raw assets, maybe built (scss -> css) and minified but not tree-shaken or bundled

But in my case it was bundled into a css file under  `/dist/_astro/`.
Which makes sense since I reference it from my MainHead.astro component like in the blog example.

I guess the usage of assets in combination with `/public` is just a bit confusing.
I should probably just move my css file into `/src` and boom "problem" solved.
Anyway I guess docs and some of the examples need some love then.
At least the blog example is doing it the same way I did and the result is probably the same (`/public/global.css` is bundled into `/dist/_astro/xyz.css` but alos remains as "raw" asset file and is copied to the `/dist` folder )

Also that's the way shown on how to use tailwind with astro. straight from the styling.md docs file:

```css
/* public/global.css */
@tailwind base;
@tailwind components;
@tailwind utilities;```

**Comment by natemoo-re** [comment]
cc @matthewp I do think we should update the Tailwind docs or example based on @theZieger's comment above!

**Comment by matthewp** [comment]
What do you think we should change them to? The `/_astro/src` thing is kind of a hack. These docs were intended to give people a workaround. `Astro.ref()` or Astro.relative()` or whatever is the ultimate solution. We might need to change the mountpoint in the future in which case `/_astro` will stop working. I don't think we want to overencourage that pattern.

**Comment by matthewp** [comment]
Talked this over in standup and we don't want to overdocument `/_astro` since it's an internal implementation detail. It's documented as a workaround for people today. In the future we'll have something like: https://github.com/snowpackjs/astro/issues/310 to load relative to the sort folder.

**Comment by brycewray** [comment]
If one uses PostCSS as per the docs and adds the `postcss-import` plugin, should things like `@import 'filename.css` not also work? Getting 'UnhandledPromiseRejectionWarning` errors when I try that from `/public/assets/style/index.css` (I prefer to bring in Tailwind in that fashion — mentioned as an alternative in [TWCSS docs](https://tailwindcss.com/docs/installation) — so I can mix and match my own CSS files accordingly, control the order of importation, etc.)
