### ISSUE TITLE
🐛 Build fails unless `astro dev` is run first

### ISSUE THREAD

**Issue by tony-navillus** [snowpackjs/astro#468]
### Bug Report: Quick Checklist

- [x] I am on the latest version of Astro & all plugins.
- [x] I am on an ESM Node.js version (`v12.20.0+, v14.13.1+, or v16.0.0+`)
- [x] I use package manager: (Fill in: npm, yarn, pnpm, etc).
- [x] I run Astro on OS: (Fill in: Windows, Mac, Linux, etc).

### Describe the bug

This is a strange one...

When building locally the project handles both `dev` and `production` builds just fine.  Deployed to Netlify and it failed with errors related to mixing CommonJS and ES modules.

Turns out the build works fine **only if** `astro dev` was already run and a route has been loaded.  Maybe the dev build is doing some CJS -> ESM conversion that allows `astro build` to find pre-converted modules?

### Steps to reproduce

Full repo that reproduces this bug can be found [here](https://github.com/Navillus-BV/demo-astro-netlify-cms)

1. clone [Github repo](https://github.com/Navillus-BV/demo-astro-netlify-cms)
2. `cd demo-astro-netlify-cms`
3. `npm i && npm run build` // build will fail with multiple ES Module errors
4. `npm start`
5. load `localhost:3000` in a browser and allow the page to render
6. kill the local dev server and run `npm run build`
7. Magic!  The build now works without issue

### Expected behavior

Building after a clean NPM install should succeed.

### Anything else?

Node version: v14.16.1
NPM version: 6.14.12
Astro version: 0.13.8  (tried a few versions back and hit the same error)
OS: Pop!_OS 20.10

**Comment by natemoo-re** [comment]
@matthewp reopening as this isn't fixed in Astro quite yet

**Comment by matthewp** [comment]
Fixed by #477
