### ISSUE TITLE
Remove unused classnames 

### ISSUE THREAD

**Issue by mrbrianhinton** [snowpackjs/astro#472]
## What is Missing from Astro Today?

Remove unused classnames (ie. astro-feHumnd) as a final optimization step on build. 

## Proposed Solution

Noted by: @drwpow these will probably stay in dev no matter what because there are a lot of weird behaviors when you try and treeshake something almost as a race condition with other stuff happening on-the-fly.

But as a **final** build step when we know what the final HTML & CSS is only necessary classnames should persist.

**Comment by natemoo-re** [comment]
One straight-forward optimization here would be to _not_ apply the `astro-xxxxx` class if the component has not `<style>` block. But I definitely agree that we could try to purge the classes as a final `build` optimization.

**Comment by FredKSchott** [comment]
tbh #497 is plenty for where we are at right now. Anything more I think would require the ability to really parse your CSS, which I know @drwpow had mentioned wanting to avoid for now.

A reminder for anyone concerned about perf: a reused classname gzips REALLY well. This probably has less affect on loading perf than you'd think, especially once #497 is merged.
