### ISSUE TITLE
🐛 BUG: Prettier Plugin eats my astro component body on save

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro#478]
### Bug Report: Quick Checklist

- [x] I am on the latest version of Astro & all plugins.
- [x] I am on an ESM Node.js version (`v12.20.0+, v14.13.1+, or v16.0.0+`)
- [x] I use package manager: (Fill in: npm, yarn, pnpm, etc).
- [x] I run Astro on OS: macOS.

### Describe the bug

When saving an astro file, the prettier plugin removes the entire body of the component, leaving only the frontmatter.

### Steps to reproduce

before: 

```jsx
---
export let post;
export let author;

console.log({post})

function formatDate(date) {
  return new Date(date).toUTCString().replace(/(\d\d\d\d) .*/, '$1'); // remove everything after YYYY
}
---

<style lang="scss">
.post {
  padding-top: 6rem;
  padding-bottom: 6rem;
  border-bottom: 1px solid rgba(black, 0.25);
  text-align: center;
}

.author {
  text-transform: uppercase;
}

.date {
  font-style: italic;
}

.description {
  font-size: 1.25em;
}

.link {
  text-transform: uppercase;
  font-size: 0.8em;
  margin-left: 1em;
}

h1 {
  font-weight: 700;
  font-size: 2.75em;
  line-height: 1;
  letter-spacing: -0.04em;
  margin-top: 0;
  margin-bottom: 0;
}

time {
  display: block;
  margin-top: 0.25rem;
  margin-bottom: 0.5em;
}
</style>

<article class="post">

  <div class="data">
    <h1>{post.title}</h1>
    <a class="author" href={`/author/${post.author}`}>{author.name}</a>
    <time class="date" datetime={post.date}>{formatDate(post.date)}</time>
    <p class="description">
      {post.description}
      <a class="link" href={post.url}>Read</a>
    </p>
  </div>
</article>
```
after:
```jsx
---
export let post;
export let author;

console.log({ post });

function formatDate(date) {
  return new Date(date).toUTCString().replace(/(\d\d\d\d) .*/, '$1'); // remove everything after YYYY
}
---

```

**Comment by FredKSchott** [comment]
I think we have some known work to do on the prettier plugin. I'm not familiar enough with Prettier to work on this. Maybe someone from the community can take a look at this?

**Comment by natemoo-re** [comment]
While there are some serious issues with the prettier plugin at the moment, I don't think it's possible that _this_ is being caused by the Prettier plugin. It is not published anywhere! See [npm.im/prettier-plugin-astro](https://npm.im/prettier-plugin-astro).

Any chance this is caused by VS Code's built-in formatter or a plugin that you have enabled?

**Comment by jasikpark** [comment]
Yes, I have the VS Code prettier extension setup to format on save, and the prettier package is detecting .prettierrc in the root directory of snowpackjs/astro and using the astro prettier plugin it found within the workspace I believe xD

**Comment by tmayr** [comment]
Using `prettier-plugin-astro` from `astro@b2a72cc`, ´prettier@2.3.1´ and the vscode extension with ´defaultFormatter: prettier´ seems to trigger the issue, using a vanilla install, 100% sure.

It seems like

`<a class="author" href={`/author/${post.author}`}>{author.name}</a>`

Is tripping something, the `href` definition to be exact.

**Comment by FredKSchott** [comment]
Assigning @natemoo-re just to take a look at this, but @tmayr or @jasikpark if you can keep digging to find out what's wrong in the plugin, that would definitely be helpful

**Comment by FredKSchott** [comment]
Failing test added in #508: "can format an Astro file with a JSX expression in an attribute"
unskip that test to run it locally against a fix

**Comment by akellbl4** [comment]
I'm not an expert in Prettier. I've taken a look and found out that the Prettier HTML parser throws an error. It happens on an attempt to parse the HTML tag with a dynamic attribute. At this line: https://github.com/snowpackjs/astro/blob/11cf22999d9eeb45d25596af481d8bc27fa931ec/tools/prettier-plugin-astro/index.js#L147
Hope it helps.

**Comment by jasikpark** [comment]
> I'm not an expert in Prettier. I've taken a look and found out that the Prettier HTML parser throws an error. It happens on an attempt to parse the HTML tag with a dynamic attribute. At this line:
> 
> https://github.com/snowpackjs/astro/blob/11cf22999d9eeb45d25596af481d8bc27fa931ec/tools/prettier-plugin-astro/index.js#L147
> 
> Hope it helps.

How did you discover that? I don't see that when running the failing tests...

**Comment by jasikpark** [comment]
The `html` variable is set to `html: '<a class="author" href={`/author/${post.author}`}>\n{author.name}\n</a>'` when that error with the HTML parser happens, I'm not totally sure I understand the `embed` function, but it sounds like it pulls out all of the js embeds so that only valid HTML remains? And then that string is not valid HTML, right? So that's why it complains, maybe because it gets confused by `/a`uthor and thinks that is a closing `</a>`

**Comment by jasikpark** [comment]
I'm not sure if this is important for this, but `concat` is deprecated: https://github.com/prettier/prettier/blob/main/commands.md#deprecated-concat

**Comment by akellbl4** [comment]
> How did you discover that? 

I wrapped up the function in `try...catch` :)
Then I tried to parse with babel and it worked better but added `;` after  `</a>`

**Comment by jasikpark** [comment]
This project has been moved to https://github.com/snowpackjs/prettier-plugin-astro while we work on a rewrite via a hard fork of https://github.com/sveltejs/prettier-plugin-sveltejs
