### ISSUE TITLE
💡 RFC: <Markdown> should not apply recursively within block-level components

### ISSUE THREAD

**Issue by telic** [snowpackjs/astro#495]
### Bug Report: Quick Checklist

- [x] I am on the latest version of Astro (0.13.10) & all plugins
- [x] I am on an ESM Node.js version 16.2.0
- [x] I use package manager: npm
- [x] I run Astro on MacOS

### Describe the bug

The `<Markdown>` component "recursively" renders markdown syntax inside of block-level HTML and components when provided as direct content\*. This is not expected behavior according to the [CommonMark spec](https://spec.commonmark.org/0.29/#html-blocks).

> \* Note that the markdown content *is* rendered according to spec if it is provided through the `content` prop. This bug *only* affects content provided as child text nodes.

HTML blocks are leaves and their content should be preserved verbatim. That is, nothing inside an element used in a "block-level" context should be parsed as markdown. Since component tags are indistinguishable from regular HTML according to the parser rules, I would expect that they should be treated identically.

### Steps to reproduce

Render the following .astro component:
```astro
---
import { Markdown } from 'astro/components';
---
<Markdown>
  Markdown content, *parsed* as expected.

  <div>
    Inner content should **not** be parsed.
  </div>
</Markdown>
```

### Expected behavior

A CommonMark-compliant processor would convert that markdown source content to:

```html
<p>Markdown content, <em>parsed</em> as expected.</p>
<div>
  Inner content **not** parsed.
</div>
```

Similarly, when the `<Markdown>` component processes this content, the `<div>` should have a text node child with the literal text `Inner content **not** parsed`.

If using a custom component (eg. `<MyComponent>`) instead of `<div>` in this example, the result should be similar -- the literal text content should be provided to the component's default slot.

### Anything else?

@natemoo-re mentioned that MDX has similar behaviour. I haven't used MDX in a build system before, but it doesn't appear to currently work this way in their [online playground](https://mdxjs.com/playground) (try adding some markdown inside the \<Button>). Perhaps this was bug or an implementation limitation that they later fixed? In either case, I would suggest that consistency with how markdown normally works is a better goalpost for Astro than how it works in MDX. I believe Astro already diverges from MDX in other ways that make porting old MDX code over directly already problematic.

Note that this is only divergent from CommonMark for **block-level** elements. The content of inline elements *should* be parsed.

**Comment by FredKSchott** [comment]
Thanks for kicking this off, I do think it's worth revisiting this decision now that we have users, who have feedback.

> HTML blocks are leaves and their content should be preserved verbatim. That is, nothing inside an element used in a "block-level" context should be parsed as markdown. Since component tags are indistinguishable from regular HTML according to the parser rules, I would expect that they should be treated identically.

This actually may be the most compelling reason not to be recursive. I hadn't considered this as actually breaking markdown spec, but you're right.

**Comment by matthewp** [comment]
Thanks @telic, we are talking about adding a way to opt-out of recursion here. Until that happens if there is markdown that you want to not be rendered you can also make it a string like so:

```jsx
---
import { Markdown } from 'astro/components';
---
<Markdown>
  Markdown content, *parsed* as expected.

  <div>
    {`Inner content should **not** be parsed.`}
  </div>
</Markdown>
```

**Comment by FredKSchott** [comment]
This has been rolled into the `next` branch work in Astro v0.21.

**Comment by jasikpark** [comment]
I would say that GFM has support for recursive markdown btw!

```md
<details>
<summary>hello world</summary>

```js
console.log("hello world")
```

</details>
```

produces


<details>
<summary>hello world</summary>

```js
console.log("hello world")
```

</details>

**Comment by aFuzzyBear** [comment]
Posting this from the [discord thread](https://discord.com/channels/830184174198718474/871832088263933973/899765952818855946) discussing this feature within the `astro-next` branch

``` html
<Layout>
  <Markdown>
    ## Interesting Topic

    <Hello name={`world`} />
    <Counter client:load />
  </Markdown>
</Layout>
```
