### ISSUE TITLE
🐛 BUG: Recursive markdown example not rendering

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#496]
_From twitter:_ https://twitter.com/SteveALee/status/1405938897348145152

> sorry for flyby comment but the Markdown example the "🤯 It's also _recursive_!" does not render. FFx on WIndows

**Comment by natemoo-re** [comment]
Haha, whoops! This _is_ a bug but also worth discussing if we should fix it in relation to #495.
