### ISSUE TITLE
💡 RFC: Improving handling of `:root` in CSS (or warn users)

### ISSUE THREAD

**Issue by natemoo-re** [snowpackjs/astro#503]
## What is Missing from Astro Today?

I've noticed that quite a few people (myself included) have been tripped up when trying to write styles selecting `:root`. Our current suggestion is to use `:global(:root)`, but is there a better solution here?

See the definition of `:root` in the [CSS Selectors 4 Spec](https://drafts.csswg.org/selectors-4/#the-root-pseudo). Are there other pseudo-selectors that we need to consider?

https://discord.com/channels/830184174198718474/845451724738265138/856553773329154070

## Proposed Solution

- Improve our scoping logic to handle pseudo-selectors. Should selectors like `:root` never be scoped?
- Warn users that they probably meant to use `:global(:root)`

## Help Make it Happen!

- [ ] I am willing to submit a PR to implement this change.
- [x] I am willing to submit a PR to implement this change, but would need some guidance (cc @drwpow)
- [ ] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
Solved with the addition of `<style global>`. Should we add docs for this to make it clear?
