### ISSUE TITLE
💡 RFC: Introduce `<style global>` to opt out of scoped-styles

### ISSUE THREAD

**Issue by natemoo-re** [snowpackjs/astro#507]
## What is Missing from Astro Today?

It would be nice to be able to opt-out of scoped styles for an entire set of styles. Scoped is the right default, but there are cases where global styles are totally valid.

## Proposed Solution

Introduce a `global` attribute for `<style>` blocks inside of `.astro` files. This would bypass our `scoping` features and emit plain old unscoped selectors.

```html
<style global>
:root {
  color: red;
}
</style>
```

## Help Make it Happen!

- [x] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
The two tricky questions here are:
1. Can I do `<style>...</style><style global>...</style>` in the same component.
2. If so, is this more ergonomic than `:global{}`? Do we want to support two ways to do the same thing?

**Comment by georges-gomes** [comment]
FWIW

`<style>...</style><style global>...</style>` I do use this in Vue from time to time.

I like the fact that my global/scoped css are separated and nothing else is in my css.

**Comment by natemoo-re** [comment]
RFC Call: 

1. Yes, support `<style global>`.
2. Still support `:global` inside of default `<style>`, but document _why_ you'd use one over the other.
3. Yes, support more than one style tag in an `.astro`. Dev server can concat styles into a single `.css` file.

**Comment by tony-sull** [comment]
Working on this one in #824 - just need to add a few extra tests and update the docs

**Comment by FredKSchott** [comment]
@tony-navillus amazing!!

**Comment by jasikpark** [comment]
Closed by #824 😆
