### ISSUE TITLE
💡 RFC: Add the media hydration directive and move hydration directives to special attributes

### ISSUE THREAD

**Issue by matthewp** [snowpackjs/astro#514]
## What is Missing from Astro Today?

Some times you have code that should only run in browsers of certain screen sizes, such as mobile side navigation. There is not a good way to say in Astro "only load this in mobile".

## Proposed Solution

Add a new `:media="query"` hydrator that allows you to define a media query and have that query be used to lazy-load a component only when/if needed. Proposed syntax:

```jsx
---
import Nav from '../components/Nav.jsx';
---

<Nav :media="(max-width: 768px)" />
```

This also will allow you to put all of your queries in a common place to aid with reusability for example:

__src/queries.js__
```js
export const PHONE = '(max-width: 768px)';
```

__src/pages/index.astro__

```jsx
---
import Nav from '../components/Nav.jsx';
import {PHONE} from '../queries.js';
---

<Nav :media={PHONE} />
```

To achieve this 2 steps are needed:

### Move Hydrators to an attribute

For this proposal we need a hydrators to be an attribute instead of part of the tag name so that we can provide a value. This will solve another issue we have in that currently you need to include the hydrator in the end tag (🤮). So:

```jsx
---
import DatePicker from '../components/DatePicker.svelte';
---

<DatePicker:load>
  <div>some children content here...</div>
</DatePicker:load>
```

Would become:

```jsx
---
import DatePicker from '../components/DatePicker.svelte';
---

<DatePicker :load>
  <div>some children content here...</div>
</DatePicker>
```

### Add the `:media` hydrator

After the hydrators have been moved to attributes we can add the `:media` hydrator.

One implementation note here: we need for the value to be dynamic. This means that the hydrator needs to be dynamic and accept the media query. The way that __astro_component works, this should be straightforward to make possible.

## Help Make it Happen!

- [✅] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by natemoo-re** [comment]
We decided on our RFC call to move forward with a media hydration directive. We also decided to move forward with a special prop syntax for hydration directions. We need to iron out the exact syntax.

**Comment by eyelidlessness** [comment]
I was about to mention namespacing but it appears I [already did](https://github.com/snowpackjs/astro/issues/396#issuecomment-861096986).

**Comment by natemoo-re** [comment]
Thanks for the reminder! There has been discussion on this in a few different places. 

See [the original `media` issue](https://github.com/snowpackjs/astro/issues/396) and [an early PR](https://github.com/snowpackjs/astro/pull/73) where we discussed this.

**Comment by matthewp** [comment]
I'm ready to start implementing this. The last thing blocking was bikeshedding on the prefix. The candidates are:

* `client:`
* `hydrate:`

In the future there are likely other prefixes we might have such as `server:` for hydration mixins like `server:only`.
