### ISSUE TITLE
🐛 BUG: Error compiling `.tsx` in Astro 

### ISSUE THREAD

**Issue by aFuzzyBear** [snowpackjs/astro#518]
### Bug Report: Quick Checklist

- [x] I am on the latest version of Astro & all plugins.("astro": "^0.14.0")
- [x] I am on an ESM Node.js version (` v16.0.0+`)
- [x] I use package manager: (yarn).
- [x] I run Astro on OS: (WSL2:Ubuntu-20.04).

### Describe the bug

Trying to compile `.tsx` files in astro and I am receiving the following error,

```bash
[executing astro] CompileError: Could not find "/src/components/islands/Counter/Counter.js"
    at load (file:///home/peter/dev/Astro/astro-lessons/node_modules/astro/src/runtime.ts:276:16)
    at Server.<anonymous> (file:///home/peter/dev/Astro/astro-lessons/node_modules/astro/src/dev.ts:33:20) {
  start: { line: 1, column: 0, character: 0 },
  end: { line: 1, column: 0, character: 0 },
  filename: '/home/peter/dev/Astro/astro-lessons/src/pages/index.astro',
  frame: '1: ---\n' +
    '   ^\n' +
    "2: import Tour from '../components/Tour.astro';\n" +
    "3: import Counter from '../components/islands/Counter/Counter.tsx'"
}
[access] /500
```

Here is my astro.config.mjs

```js
export default {
  // projectRoot: '.',     // Where to resolve all URLs relative to. Useful if you have a monorepo project.
  pages: './src/pages',   // Path to Astro components, pages, and data
  dist: './dist',       // When running `astro build`, path to final static output
  public: './public',   // A folder of static files Astro will copy to the root. Useful for favicons, images, and other files that don’t need processing.
  buildOptions: {
    // site: 'http://example.com',           // Your public domain, e.g.: https://my-site.dev/. Used to generate sitemaps and canonical URLs.
    // sitemap: true,      // Generate sitemap (set to "false" to disable)
  },
  devOptions: {
    // port: 3000,         // The port to run the dev server on.
    // tailwindConfig: '', // Path to tailwind.config.js if used, e.g. './tailwind.config.js'
  },
  renderers:{'@astrojs/renderer-react'}
};
```
`package.json` is the same as a fresh install. 

This works fine if the file is a `.jsx` however when its turned into `.tsx` it gets angry. 

@FredKSchott mentioned on the discord support room, that this might pertain to a render not registering the extension. thought I would mention that to save some stress,

### Steps to reproduce

1. `npm init astro` using template <NAME>
2. created a Counter, like in the kitchen-sink example, wrote it as a `.jsx` file first, imported to `index.astro` and applied the hydrate `:load` method on the Counter component, and it works fine
3. change the file extension to `.tsx` and all hell breaks loose

### Expected behavior

The expected behaviour would be for the `.tsx` file to compile normally, without the demon stare.

Thank you for looking into this, If you wish I could share the repo,

**Comment by natemoo-re** [comment]
Hey @aFuzzyBear! Just getting to this, but I wonder if the issue is the error in your config file? 

Try switching the renderers from an object (`{` and `}`, currently invalid) to an array (`[` and `]`). 

```diff
- renderers:{'@astrojs/renderer-react'}
+ renderers: ['@astrojs/renderer-react']
```

**Comment by aFuzzyBear** [comment]
Hi @natemoo-re im sorry bud that was my fault when i was typing up the bug report, I was still getting the error when it was written properly 🙈

**Comment by matthewp** [comment]
Hey @aFuzzyBear, I haven't been able to recreate this bug. I set up a project here: https://github.com/matthewp/astro-tsx-test-example that is using a tsx component. Can you tell me what is different about your project? Thanks!

**Comment by aFuzzyBear** [comment]
This bug came and went like a ghost, my aplogies for leaving this open, next time I see the poltergeist I'll let you know,
