### ISSUE TITLE
🐛: Astro should not blanket-swallow warn messges

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro#528]
I think that was removed in 0.14.0, we shouldn't be swallowing anything anymore.

err... looks like we are doing some `console.warn` trapping in `build()`. If you don't mind filing an issue for that, I think that's worth fixing (we could just silence the exact warnings coming from vue, instead of a blanket "swallow all")

_Originally posted by @FredKSchott in https://github.com/snowpackjs/astro-docs/issues/17#issuecomment-867302585_

**Comment by matthewp** [comment]
Easy fix for anyone that wants it, you can add a callback here: https://github.com/snowpackjs/astro/blob/d6dfff6000b39f0eecb220214569aec48ff26aeb/packages/astro/src/build.ts#L74

And check for the Vue warning, otherwise call our own logging mechanism. Pseudo-code:

```js
const release = trapWarn((...args) => {
  if(!args[0].includes('some vue message')) {
    warn(logging, 'build', ...args);
  }
})
```

**Comment by natemoo-re** [comment]
I think we fixed the Vue warning upstream, actually! We should be able to remove this.
