### ISSUE TITLE
🐛 PostCSS `from` option is not set correctly in some cases

### ISSUE THREAD

**Issue by bradlc** [snowpackjs/astro#546]
### What package manager are you using?

npm

### What operating system are you using?

macOS

### Describe the Bug

The PostCSS `from` option is not set correctly in some cases. The setup I am seeing this in looks something like this:

- A CSS file (`src/global.css`), referenced in a component
- Two components with `<style>` elements
- A page that uses all three components

### Expected Behavior

The `from` option should be set to the file that contains the CSS that is being processed.

### Link to Minimal Reproducible Example

https://github.com/bradlc/astro-postcss-from

### Steps to reproduce

I have created a minimal project that shows this behaviour. There is a simple PostCSS plugin that replaces `@from` with a `content` declaration containing the `from` option that PostCSS received. `@from` is used in the `src/global.css` file, so the `content` value should be `{projectRoot}/src/global.css`, but instead it is `{projectRoot}/src/components/One.astro` or `{projectRoot}/src/components/Two.astro` (it varies between builds)

1. Clone https://github.com/bradlc/astro-postcss-from
2. Run `npm install`
3. Run `npm start`
4. Notice that the text does not read `{projectRoot}/src/global.css` as it should

**Comment by matthewp** [comment]
It's a bug in our snowpack postcss plugin: https://github.com/snowpackjs/snowpack/issues/3490. Fixing.
