### ISSUE TITLE
🐛 BUG: React SSR can’t use `window` object

### ISSUE THREAD

**Issue by drwpow** [snowpackjs/astro#551]
Referencing `window` in a React component errs with:

```
Error: ReferenceError: window is not defined
```

The error comes from ReactDOM itself. What should we do in Astro? Should we mock `window` using something like [window-mock](https://www.npmjs.com/package/window-mock)?

**Comment by FredKSchott** [comment]
Really? Every Astro file is wrapped in an async function call, which was why this wasn't originally an issue. Maybe something changed there?

**Comment by FredKSchott** [comment]
Oh you know what... It may be that that async wrapper only happens on pages and not components? That could explain it

**Comment by drwpow** [comment]
Oh yes it seems to happen for components and layouts. Which is tricky, because this means you couldn’t use `fetch()` for a markdown page with an Astro layout, either (or for any Astro components)

**Comment by drwpow** [comment]
Update—it’s not `fetch()`! It’s using [window in React SSR](https://stackoverflow.com/questions/38951721/react-js-server-side-issue-window-not-found) that throws the error. I had just assumed it was `fetch()` because the error messages thrown in the renderers currently don’t show any code frame so you’re unsure which page it even is.

Will open up a draft PR with a test.
