### ISSUE TITLE
🐛 BUG: Odd behavior when markdown page is empty

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#554]
### What package manager are you using?

yarn

### What operating system are you using?

mac

### Describe the Bug

See title, i'm seeing a broken page when the markdown body is empty.

### Expected Behavior

see steps below

### Steps to reproduce

```bash
1. Check out and run astro-docs
2. visit a page with an empty contents (or remove some contents)
3. change some styles across the site
4. come back to this page, see the styles still outdated / broken
5. add some page contents, and the page is magically up to date in the browser
```

**Comment by matthewp** [comment]
I think this one is finally fixed! I'm unable to get a problem with testing this in `next`: https://stackblitz.com/edit/github-cck9y2?file=src%2Fpages%2Findex.md
