### ISSUE TITLE
🐛 BUG: confusing error when I build astro-docs

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#555]
### What package manager are you using?

yarn

### What operating system are you using?

mac

### Describe the Bug

When I build astro-docs, I see this error a lot:

```

You might not have "SNOWPACK_PUBLIC_GITHUB_TOKEN added for escaping rate-limiting.
Error: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
You might not have "SNOWPACK_PUBLIC_GITHUB_TOKEN added for escaping rate-limiting.
Error: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
You might not have "SNOWPACK_PUBLIC_GITHUB_TOKEN added for escaping rate-limiting.
Error: TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
```

I'm sure there's something happening in the project (I think the fetch() call to GitHub is returning a 404 once rate-limited, inside of AvatarList). However, this issue is impossible to debug during the build, and I have no idea how to resolve as a user.

### Steps to Reproduce

1. run `yarn build` on astro-docs
2. See this error

**Comment by matthewp** [comment]
That error is from within one of the astro-docs components: https://github.com/snowpackjs/astro-docs/blob/main/src/components/AvatarList.astro#L10

**Comment by jasikpark** [comment]
This was hopefully fixed via https://github.com/snowpackjs/astro-docs/pull/49 though I suppose adding an explanation for which component is calling `console.error` might be helpful...

**Comment by jasikpark** [comment]
Ok, I added a link to the component that is creating the warning within the warning:

```ts
} catch (e) {
    console.warn(`[error]  /src/components/AvatarList.astro 
    ${e?.message ?? e}`);
    return new Array();
}
```

https://github.com/snowpackjs/astro-docs/pull/67
