### ISSUE TITLE
💡 RFC: Get date from file or folder names 

### ISSUE THREAD

**Issue by Brixy** [snowpackjs/astro#556]
### Motivation

It would be great if Astro could get a post’s date not only from `date` in front matter but also/alternatively from the file or folder name.

This way Astro would support folder structures commonly used by other SSGs.

(Sorry if this is already possible. I did not find any information.)

## Possible solutions

```
/src/pages/blog/2021-06-26-my-post.astro

# Date ist set to 2021-06-26
# URL could be
# /my-post/
```

or

```
/src/pages/blog/2021-06-26-another-post/index.astro

# With assets living in the same folder
# Date is set to 2021-06-26
# URL could be
# /another-post/
```

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by natemoo-re** [comment]
Related to https://github.com/snowpackjs/astro/issues/439, we'll prioritize 439 and circle back to this in the future.

**Comment by FredKSchott** [comment]
Superseded by #439
