### ISSUE TITLE
💡 RFC: create-astro support community repos/examples

### ISSUE THREAD

**Issue by colbyfayock** [snowpackjs/astro#558]
### Motivation

A lot of site building tools provide a mechanism for creating a new project based off of a template.

Probably most commonly are the two big ones Next.js and Gatsby:

```
// Next.js
yarn create next-app -e [repo] my-next-project

// Gatsby
gatsby new [repo] my-gatsby-project
```

While Astro has the ability to select a template, the ones available must be pre-configured.

Ideally there would be a way for developers to create "starter" templates, where Astro can provide a way to set up a new project from a repo similar to other tools.

RE convo https://discord.com/channels/830184174198718474/830184175176122389/858361793327136828

### Possible solutions

@FredKSchott:

> I like the idea of the “author/repo” format, we could just have create-astro-app pass the string directly to degit if it detects a slash
> (Currently, I think we add “astro/examples/“ to everything that you pass)

https://discord.com/channels/830184174198718474/830184175176122389/858376686747648030

I think the "create-app" pattern is a nice way to handle these kinds of things, it's already a common pattern hooking into either npm or yarn without requiring an additional command line tool on its own.

### Alternatives considered

Currently you can use degit without any additional work, though it still isn't necessarily "first  class" Astro support:

Me:

> actually didnt realize degit was that easy to use :exploding_head: could just reference npx degit cassidoo/shopify-react-astro my-new-project

https://discord.com/channels/830184174198718474/830184175176122389/858359964585951233

### Open Questions

I think a big question would be what would be included in the creation process. Most of the starter tools include dependency installation as well as creating a fresh git history, which I believe these 2 things are important to help newcomers get up and running really quickly.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
If everyones on board with my suggestion above, it would be as easy a fix as:

```diff
-  const emitter = degit(`snowpackjs/astro/examples/${options.template}${hash}`, {
+  const templateTarget = options.template.includes('/') ? options.template : `snowpackjs/astro/examples/${options.template}`;
+  const emitter = degit(`${templateTarget}${hash}`, {
```

Then we should just add a test for this, I think `--template cassidoo/shopify-react-astro` would be fine as our test.

**Comment by FredKSchott** [comment]
There's the other question of "do we want to add some community templates to the interactive project selector?"  that shows up when you don't use `--template`. But I would suggest that we tackle that later/separately, since 90% of the value here for me is that this gives community templates an easy command to add to their readme.

**Comment by colbyfayock** [comment]
> There's the other question of "do we want to add some community templates to the interactive project selector?"

only thoughts here from a UX perspective is avoiding overwhelming someone with too many options. i like the idea of having carefully crafted options to pick from, even if that means a few more to the list, but moreso Astro-supported templates, where they go through the workflow here to get added and such (and limit how many)
