### ISSUE TITLE
💡 Add ability to add filename to code blocks 

### ISSUE THREAD

**Issue by akellbl4** [snowpackjs/astro#560]
Hi there
I'm [trying to migrate](https://github.com/akellbl4/pavel.mineev.me/pull/5) my site to Astro. I haven't found this ability and decided to implement it.
I provided a draft implementation and would be happy to see any feedback on it.
Sorry if I've done something wrong.

### Motivation

An idea is pretty simple. It could be great to add the ability to name code blocks in markdown.
While using [remark](https://github.com/remarkjs/remark) you can plugin [remark-code-titles](https://github.com/mottox2/remark-code-titles#readme) and it gives you the ability.

### Possible solutions

The syntax could look like this:
<pre>
```${lang}:${filename}

function myFn() {}

```
</pre>

It's easy to implement by splitting parsed `lang` by `:`

### Risks, downsides, and/or tradeoffs

- I can't see any risks for this feature.

### Open Questions

- What class name the filename element should have?

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.

**Comment by natemoo-re** [comment]
Thanks for opening this issue _and providing a draft implementation_! That's super helpful.

We're tracking allowing users to extend Markdown in [239](https://github.com/snowpackjs/astro/issues/239). We are using `remark` so ideally you could just add the plugin you mentioned. 

I think this request would make sense under that umbrella because you'd be able to totally customize how your code blocks render. What do you think?

**Comment by akellbl4** [comment]
@natemoo-re oh, really nice. I agree with you. Can I try to implement it?

**Comment by natemoo-re** [comment]
> @natemoo-re oh, really nice. I agree with you. Can I try to implement it? 

Of course, feel free to give it a try! 

I can't remember if we have `markdownOptions` in the `astro.config.mjs` file yet, but we'd probably do this through `markdownOptions.remarkPlugins`. Take a look at how the `renderers` are implemented for reference.
