### ISSUE TITLE
💡 Expose rendered `html` when using `Astro.fetchContent`

### ISSUE THREAD

**Issue by natemoo-re** [snowpackjs/astro#571]
### Motivation

We've had quite a number of people ask how to get the rendered HTML from a post pulled in using `Astro.fetchContent`.

### Proposed Solution

On the returned posts, we already have the `astro` metadata which includes `headers` and the raw `source`.

### Alternatives considered

Is `rendered` a better name than `html`? 

### Risks, downsides, and/or tradeoffs

No risks I can see of, we already allow this if you pipe `astro.source` to `<Markdown>`, it's just an annoying extra step.

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
RFC Discussion: +1 for merging with the one callout for the performance cost risk of rendering everything vs. as requested.

Current Workaround: Passing the `content.source` value to the `<Markdown content={content.astro.source}>` component.

**Comment by kaleidawave** [comment]
🎉 🎉  Thanks @natemoo-re . Very quick 🏎
