### ISSUE TITLE
💡 RFC: Astro.context

### ISSUE THREAD

**Issue by matthewp** [snowpackjs/astro#577]
### Motivation

Currently there isn't a great way to track globalish data about a single request. There is `Astro.request` which is specific to the request, but it's only available on pages, because it does not get passed down to child components.

There is a use-case for having request-contextual information about a render. This allows for higher-level components such as Theme components to add information to a context object. Frameworks such as React have such a feature.

One use-case I have in mind: I want to track how many times I've rendered something in a component, to avoid rendering more than once. This is what is desired in #370. Such a feature could use this API to do that.

### Possible solutions

We add an `Astro.context` object. It is an object containing, to start:

```js
Astro.context = {
  request
};
```

This context will be passed down to child pages automatically. This will allow a child component to do something like:

```js
Astro.context.theme = 'dark';
```

And have that information be shared. Additionally the `request` will be part of this object (but still aliased to Astro.request, at least for a time for backwards compatibility).

Here's how you might use this feature to prevent rendering a script more than once:

```jsx
---
const hasRenderedPolyfill = Astro.context.hasRenderedPolyfill;

if(!hasRenderedPolyfill) {
  Astro.context.hasRenderedPolyfill = true;
}
---
{hasRenderedPolyfill ? '' : (
  <script src="/scripts/polyfill.js"></script>
)}
```

### Alternatives considered

None, since there is existing precedent for using the `Astro` object for contextual information.

### Risks, downsides, and/or tradeoffs

Unknown.

### Detailed Design

This should be implemented by adding a symbol to the props object that will automatically be passed down to child components in the compiler. We already do this to some degree with the "astro.internal" symbol. This would be a separate symbol that is always passed to child components.

Pseudo-code of what the compiler is already doing and how we can add the context:

```js
function render(props) {
  const Astro = {
    context: props[Symbol.for('astro.context')],
    // More stuff here
  };

  // JSX is here
}
```

### Open Questions

The `Astro` object has a number of things on it and we should reconsider what belongs there, what doesn't, and how its organized. That's the point of #506. 

Redesigning that object is out-of-scope for this feature request. 

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by natemoo-re** [comment]
I really like the idea of moving `request` to a namespace, but maybe it would be something like `Astro.page` and `Astro.context` would be reserved for user-provided context? Inspired by [Svelte Kit's `load` handlers](https://kit.svelte.dev/docs#loading-input).

**Comment by eyelidlessness** [comment]
This is a good idea, but I’m cautious about the proposed solution.

Glomming magic onto `Astro` carries a lot of risk, and essentially reproduces global state in a different form. This is quite similar to the risk of stateful “middleware” in Node. In both cases, you have no way to statically ensure that your dependencies are present, correct, or without conflict.

I suspect that this would benefit from functions with a clear API. React or other context-providing frameworks can be a good frame of reference. Astro already knows what context it’s operating in, but Astro files don’t. If a template wants data about its context it would help to call functions that actually provide it.

**Comment by matthewp** [comment]
Going to close this, as I don't think it's quite right. In other frameworks a context is contained within a subtree, but this Astro.context idea is specific to the full tree. There isn't a way to contain. the context to a subtree and that's not desired. The primary use-case I have is to solve the #370 issue, but that be doable in another way.
