### ISSUE TITLE
🐛 BUG: Confusing error message when using the Fragment global

### ISSUE THREAD

**Issue by matthewp** [snowpackjs/astro#582]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

If you try to use the global `Fragment` in a component it throws:

```jsx
<Fragment>anything</Fragment>
```

This error: 

```
Error: Parse error @:1:0
    at parse$n (/Users/matthew/dev/astro/node_modules/snowpack/lib/index.js:113453:379)
    at scanCodeImportsExports (/Users/matthew/dev/astro/node_modules/snowpack/lib/index.js:114680:29)
```

We should have a better error message 

### Steps to Reproduce

See above

**Comment by natemoo-re** [comment]
This was intentional. We removed the magic `Fragment` global for the `<>anything</>` syntax in #433.

**Comment by matthewp** [comment]
Reopening to improve the error message here.

**Comment by matthewp** [comment]
I didn't realize that #433 intended to remove Fragment. It doesn't mention doing so in the PR and it's labeled as a patch change. I wish we had discussed this before because I think the explicitness of Fragment is a bit better than the `<>` syntax (which isn't valid HTML anyways). I thought #433 was about having a bridge for React/JSX users.

**Comment by matthewp** [comment]
Just looking at the code for #433 it doesn't appear to remove support for Fragment. Are you sure it was done so there? Those code changes are minimal and seem to be additive for `<>`.

**Comment by natemoo-re** [comment]
> Just looking at the code for #433 it doesn't appear to remove support for Fragment. Are you sure it was done so there? Those code changes are minimal and seem to be additive for `<>`.

I think this is actually correct, #433 _is_ purely additive.

Pretty sure this was an unrelated regression and I was just mistaken about it being intentional.

**Comment by natemoo-re** [comment]
@matthewp IMO we should expose `Fragment` on `globalThis` for `.astro` files

**Comment by matthewp** [comment]
Fragment is already in the scope because its imported from the h module, so it doesn't need to be on the global object. It's used a lot internally. The bug here is the compiler which strips out Fragment in some cases, I guess.

**Comment by jasikpark** [comment]
The docs should be updated to reflect that you can use both syntax in `.astro` files, right?

**Comment by FredKSchott** [comment]
@matthewp bump! What's needed to resolve this issue?

**Comment by matthewp** [comment]
Just fix the bug, I'll take a crack at it now.

**Comment by virtualitems** [comment]
how am I supposed to do this with <> syntax !?

<Fragment slot="scripts"></Fragment>
