### ISSUE TITLE
🐛 BUG: Class names used for scoping styles can leak into Astro.props

### ISSUE THREAD

**Issue by tony-navillus** [snowpackjs/astro#604]
### What package manager are you using?

npm

### What operating system are you using?

Linux (Ubuntu 20.10)

### Describe the Bug

An Astro component can expect a property named `class` in Astro.props to avoid the `className` type of workaround used in React.  This worked for passing in my own class name to be used in a component, but the component also received one of Astro's internal class names used to scope styles

### Steps to Reproduce

1. Clone https://github.com/tony-navillus/astro-classname-repro
2. npm init && npm build
3. The repo is logging the `<Heading>` components `Astro.props.class` value to console, it should only include "hero"
4. You can also see the issue if you start the dev server and inspect the `<h1>` in the DOM

### Link to Minimal Reproducible Example (Optional)

https://github.com/tony-navillus/astro-classname-repro

**Comment by tony-navillus** [comment]
[Looks like](https://discord.com/channels/830184174198718474/845451724738265138/860851525113610241) I may have jumped the gun assuming this was a bug!

I pushed a tweak to the repro code that may be a bit more clear on what could be going on

```html
<main class="astro-ldKR6c5M">
  <header class="astro-ldKR6c5M">...</header>
  <!-- start Heading.astro -->
  <div class="hero astro-ldKR6c5M heading">
    <h1>Astro App</h1>
  </div>
  <!-- end Heading.astro -->
  ...
</main>
```

Basically, an Astro class is being handed down to `<Heading>` which really wouldn't be a problem, but it's actually reusing the same class that was used in the page's inline `<heading>` element.

I think there's a chance this could lead to CSS scope creep if selectors applied to the page's `<header>` happen to match elements that were rendered inside `Heading.astro`

**Comment by natemoo-re** [comment]
Can @drwpow and/or @matthewp weigh in here? I know passing the scoped class to components was something @matthewp implemented but the potential for scope leaking may have been the reason @drwpow didn't do this originally.

**Comment by matthewp** [comment]
Yeah we talked about this on discord and @tony-navillus thought this was leaking by accident and didn't realize the use case. I think they're ok with it now: https://discord.com/channels/830184174198718474/845451724738265138/860865604924080138
