### ISSUE TITLE
🐛 BUG: createCollection handles additional route

### ISSUE THREAD

**Issue by kolodziejczak-sz** [snowpackjs/astro#606]
### What package manager are you using?

yarn

### What operating system are you using?

Windows

### Describe the Bug

`$[collectionName].astro` always handles the `/[collectionName]/` route

Let's take a moment to look at the code example. Below I have simple `$post.astro` page where I specified the `routes` and `permalink`  props:

```javascript
// pages/$post.astro
---
import BaseLayout from '../layouts/Base';

export async function createCollection () {
    const allPosts =[
      { title: 'first post', slug: 'first-post' },
      { title: 'second post', slug: 'second-post' }
    ]

    return {
        routes: allPosts,
        permalink: ({ params: post }) => `/post/${post.slug}`,
        data: ({ params: post }) => post,
    }
};

const { collection } = Astro.props;
const post = collection.data[0];
---
<BaseLayout>
  <h1>{post.title}</h1>
</BaseLayout>
```
I would expect this code to generate the following pages:

```
dist/post/first-post/index.html
dist/post/second-post/index.html
```

But Astro generates also the `dist/post/index.html`.
This output is forcing me to handle the empty data, even though I explicitly passed only 2 routes.

Changing the createCollection.data implementation to smth like this:

`data: ({ params: post }) => allPosts.find(p => p.slug === post.slug)`

Would end up with the following build error: `Error: Error: [createCollection] data() returned nothing (empty data)`, since the params will be a plain, empty object `{}`.

Btw the `dist` directory is being cleaned before starting the new build. If build command fail, I will lose my `dist` folder. That kinda leaves me empty handed.

Btw2 In that example, a permalink has to contain the substring `/post/` otherwise it won't work right? If so, I wonder why it is necessary to provide it manually at first place

Btw3 my createCollection.data returns object and the Astro.props.collection.data is an array

Btw4 I can't create the `export const createCollection = ...` because it gives me an error that the 'svelte-way' of declaring props is deprecated.

I know this bug description might look like just grumbling about the collections API, but I really admire your product and I'm amazed by the simplicity of Astro concepts. Keep up the good work!

### Steps to Reproduce

1. Create a collection with routes & permalink, f.e pages/$post.astro
2. Run dev or build command
3. The localhost:{port}/post or dist/post/index.html cases are being handled

**Comment by matthewp** [comment]
Fixed by #703
