### ISSUE TITLE
💡 RFC: Absolute imports

### ISSUE THREAD

**Issue by JakubKoralewski** [snowpackjs/astro#607]
### Motivation

It's kinda boring to write '../../../' everywhere while making imports.

### Possible solutions

Resolve imports that don't start with a `.` as if they were relative to the project directory. 

### Alternatives considered

I tried using snowpacks `alias` feature but it didn't work. Same errors.

### Open Questions

Whether the `.` root directory or `./src` should be the root of the project I don't know.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by natemoo-re** [comment]
We'd like to avoid introducing any sort of custom import resolution logic to Astro. It's a very deep rabbit hole that has led to a ton of unnecessary complexity in Node. That's the main reason ESM requires imports to be as explicit as possible.

That being said, we know relative paths are irritating. We recently fixed a bug with Snowpack aliases! Can you try out aliases again on `astro@0.16.2` and see if it fixes your problem?

**Comment by JakubKoralewski** [comment]
Looks to be working! Awesome! Thanks.
