### ISSUE TITLE
🐛 BUG: HMR Not Working on http://127.0.0.1:3000/

### ISSUE THREAD

**Issue by alteredorange** [snowpackjs/astro#611]
### What package manager are you using?

pnpm

### What operating system are you using?

WSL

### Describe the Bug

`pnpm run start` produces:
```
[dev server] Server started in 1019ms.
[dev server] Local: http://127.0.0.1:3000/
```
Clicking on the link opens up http://127.0.0.1:3000 in the browser. Changing files are noticed by the command line, but the browser does not update. Opening http://localhost:3000, Hot Module Reload works just fine.

### Steps to Reproduce

1. `npm init astro` 
3. `npm run start`
4. open http://127.0.0.1:3000
5. Edit and save some files, browser will not reload the page.
5. Expected browser to refresh the page and show latest changes.

A quick fix would be to have the CLI print out:
```
[dev server] Server started in 1019ms.
[dev server] Local: http://localhost:3000/  // instead of http://127.0.0.1:3000/
```

**Comment by jasikpark** [comment]
There might have been some changes to HMR that updated

**Comment by alteredorange** [comment]
Yes still happening to me as well, might be WSL specific, since I'm on WSL2 as well. Does Localhost & HMR work on mac, or does it only work on 127.0.0.1?

**Comment by jasikpark** [comment]
> Yes still happening to me as well, might be WSL specific, since I'm on WSL2 as well. Does Localhost & HMR work on mac, or does it only work on 127.0.0.1?

HMR works for me both when loading `127.0.0.1:3000` and when loading `localhost:3000` in my browser on macOS

**Comment by alteredorange** [comment]
@jasikpark odd! I guess the question is, is there another system where only `127.0.0.1:3000` works for HMR and not `localhost:3000`. If there's not, defaulting to `localhost:3000` would fix the issue.

**Comment by jdbr99** [comment]
Hey there, @alteredorange !
I also had this problem with WSL2, but I solved it by recreating the proyect within wsl2 Ubuntu's home folder (`~`). It also makes the whole thing work MUCH faster (before doing that the dev server was taking on average 27s to start up, now it takes a few ms).
Hope this can help you too.

**Comment by matthewp** [comment]
Started using `localhost` as of 0e761b9bdf7606693298956b021886a3470f0cc2, let us know if this is still an issue and we can reopen.
