### ISSUE TITLE
🐛 BUG: link to discord is not working

### ISSUE THREAD

**Issue by JakubKoralewski** [snowpackjs/astro#615]
### What package manager are you using?

--

### What operating system are you using?

--

### Describe the Bug

https://astro.build/chat returns 404

![obraz](https://user-images.githubusercontent.com/43069023/124713000-4117b980-df00-11eb-8859-b7a79e2cb744.png)

### Steps to Reproduce

--

**Comment by starchildluke** [comment]
I noticed that too. Had to use Wayback Machine to retrieve the original Discord link (if anyone wanted it):

https://discord.com/invite/grF4GTXXYm

**Comment by matthewp** [comment]
Fixing it, thanks for the notice!
