### ISSUE TITLE
🐛 BUG: Unable to render <Component:visible /> on the server

### ISSUE THREAD

**Issue by alexbruno** [snowpackjs/astro#628]
### What package manager are you using?

NPM

### What operating system are you using?

WSL2 Ubuntu 20.04

### Describe the Bug

README says that Partial Hydration can build interactive component in the client output: https://github.com/snowpackjs/astro#-partial-hydration
But `<Component:visible />` isn't working as expected with Svelte components when `<script>` block contains browser global scope references.
It raises an error 500.

### Steps to Reproduce

1. `npm init astro` using any template
2. Create a Svelte component that contains some browser global reference at `<script>` block, like `window.something`
3. Import that component into an `.astro` page with `<Component:visible />` modifier 
4. Load the page at the browser
5. Error:

![image](https://user-images.githubusercontent.com/2638399/124941854-81029d80-dfe1-11eb-83ec-21c17c966c49.png)

**Comment by natemoo-re** [comment]
Since Astro renders every component _on the server_, you can't access `window` unconditionally. You should be able to use the following code in your Svelte script. This will only access `window` on the client (where it exists).

```
if (!import.meta.env.SSR) {
  // code that accesses `window` here
}
```

**Comment by alexbruno** [comment]
Hello @natemoo-re, thanks!
You are right, using `import.meta.env.SSR` in my script fixed the component. Great!
But conceptually, maybe it woudn't must be required, since docs suggest `:load` and `:visible` modifiers will render the component only client side.
Or maybe docs must be more clear about this.

**Comment by natemoo-re** [comment]
Thanks for the feedback, I agree that the docs could have been more clear about this.

I updated the docs to clarify that _every component is rendered on the server at build time_, and hydration directives additionally _add_ rendering on the client at runtime rather than using _only_ clientside rendering.
