### ISSUE TITLE
🐛 BUG: Astro class hash scoping breaks on frontmatter components

### ISSUE THREAD

**Issue by kaleidawave** [snowpackjs/astro#631]
### What package manager are you using?

npm

### What operating system are you using?

windows

### Describe the Bug

Astro adds class hashes (I think for scoping reasons) but this breaks dynamic content (Including the `<Markdown>` component)

### Steps to Reproduce

If I have the following including scss with nested rules:
```html
---
let myHtml = "<h1>Hello World</h1>";
---
<div>
    {myHtml}
</div>

<style lang="scss">
    div {
        h1 {
            color: red;
        }
    }
    /* or even */
    div h1 {
        color: red;
    }
</style>
```

The resultant css output is:
```css
div.astro-BT3XpR40 h1.astro-BT3XpR40 {
    color: red;
}
```

Yes where the class hashes are the exact same.

The interpolated `h1` won't be red because it doesn't have the `astro-BT3XpR40` class

**Comment by natemoo-re** [comment]
This is pretty tricky because we're doing all this scoping work at compile time, but the static values aren't available until (server) runtime. Not positive we'd be able to do scoping at runtime in a performant manner.

You can use `div :global(h1) { color: red; }` to opt out of scoping as a workaround.

**Comment by kaleidawave** [comment]
Thanks, the `:global` tag works 👍 Is good for now. Maybe if others run into this issue then this could be mentioned in the docs

**Comment by jasikpark** [comment]
> This is pretty tricky because we're doing all this scoping work at compile time, but the static values aren't available until (server) runtime. Not positive we'd be able to do scoping at runtime in a performant manner.
> 
> You can use `div :global(h1) { color: red; }` to opt out of scoping as a workaround.

I guess this is a slight problem with the `components defined in frontmatter` bit, no?

**Comment by FredKSchott** [comment]
We've removed frontmatter components temporarily in v0.21. We hope to add these back soon, and in a way that solves this problem!
