### ISSUE TITLE
🐛 BUG: Can't bind client side events in Svelte components with client:*

### ISSUE THREAD

**Issue by alexbruno** [snowpackjs/astro#640]
### What package manager are you using?

NPM

### What operating system are you using?

WSL2 Ubuntu 20.04

### Describe the Bug

I have a Svelte component with `client:load` modifier that tries to bind a client click event on a button, but it doesn't work.

### Steps to Reproduce

1. `npm init astro` using any template
2. Create a Svelte component with a button
3. Code a `handler` function at `<script>` block
4. Try to bind a click event at the button with `on:click={handler}`
5. Error! Event binding doesn't work.

**Comment by FredKSchott** [comment]
Sorry, we'll need more info in the steps to reproduce: I don't know enough about svelte to do this myself and know that we're talking about the same thing.

Can you copy an full example Svelte component file that isn't working in Astro?

**Comment by alexbruno** [comment]
Oh, sorry for the late response!

I'm talking about components like this:

```html
<script>
  import Feather from '../elements/Feather.svelte'

  function toggle() {
    const html = window.document.head.parentElement
    const dark = html.classList.toggle('dark')
    const theme = dark ? 'dark' : 'light'
    localStorage.setItem('theme', theme)
  }

  if (!import.meta.env.SSR) {
    const theme = localStorage.getItem('theme')
    if (theme === 'dark') toggle()
  }
</script>

<button id="theme-switch" aria-label="Trocar tema" on:click={toggle}>
  <Feather name="sun" classes="sun text-2xl" />
  <Feather name="moon" classes="moon text-2xl" />
</button>
```

I need to intereact with root DOM elements, so this action binding must happens only client side.

But it doesn't work and I can't put the `toggle` function into the `if` condition, neither its content code, because the component raises an error about undefined method or simply do nothing.

**Comment by matthewp** [comment]
@alexbruno When you say it doesn't work, do you mean that the `toggle` function doesn't get called in the client?

**Comment by alexbruno** [comment]
Yup, it is it!

**Comment by jasikpark** [comment]
> But it doesn't work and I can't put the toggle function into the if condition, neither its content code, because the component raises an error about undefined method or simply do nothing.

How about 

```html
<script>
  import Feather from '../elements/Feather.svelte'

  function toggle() {
	if (!import.meta.env.SSR) {
  	  const html = window.document.head.parentElement
   	  const dark = html.classList.toggle('dark')
   	  const theme = dark ? 'dark' : 'light'
  	  localStorage.setItem('theme', theme)
	} else { 
	  console.log(`toggle() called in SSR mode`); 
	}
  }

  if (!import.meta.env.SSR) {
    const theme = localStorage.getItem('theme')
    if (theme === 'dark') toggle()
  }
</script>

<button id="theme-switch" aria-label="Trocar tema" on:click={toggle}>
  <Feather name="sun" classes="sun text-2xl" />
  <Feather name="moon" classes="moon text-2xl" />
</button>
```

**Comment by jasikpark** [comment]
Hmmm I can't actually get Astro to even render a Svelte component D: now I'm confused.. https://codesandbox.io/s/astro-614-reproduction-nyipy?file=/package.json

**Comment by matthewp** [comment]
I'm able to create this in codesandbox: https://codesandbox.io/s/happy-wind-q0p1v?file=/src/pages/index.astro

Pretty strange! I'm going to take a closer look locally.

**Comment by matthewp** [comment]
Ok, I've been able to get it working locally: https://github.com/matthewp/astro-issue-640

Maybe something weird is up with Codesandbox. Going to close, please use the above as a starting point if you'd like.

**Comment by FredKSchott** [comment]
@matthewp should this be reported to code sandbox?
