### ISSUE TITLE
💡 RFC: Provide an _app.js replacement like next.js

### ISSUE THREAD

**Issue by L1lith** [snowpackjs/astro#643]
### Motivation

Something like [Next.js's _app.js feature](https://nextjs.org/docs/advanced-features/custom-app) would be really useful to reduce the redundancy of global site code. It would save a lot of time with things like automatic titling, importing global css, head metadata, html lang, \<header\> components, etc. 

[Next Seo](https://github.com/garmeeh/next-seo) is another tool that is really useful, and it also requires an _app.js to set the default title and title format so laying the groundwork to build something like this for Astro would be really nice for me as a developer

### Possible solutions
Implement some kind of page or component equivalent to next.js's _app.js where it could be loaded on every page by default

### Alternatives considered
The way I'm currently implementing it is by creating an component called `Head.astro` then importing it and using it in every page. This creates a lot imports and component usages that seem to be mostly boilerplate.

### Risks, downsides, and/or tradeoffs
There could be components where you don't want to use the global code. While you could simply not use the _app.js, you could also provide something like a <NoGlobals/> component to use on a page-to-page basis.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
I agree, I really want this. We have an existing RFC for #244. Lets keep the convo going in one place over on that issue, but I'd love if you could copy paste the relevant info from this issue into a comment in that issue.
