### ISSUE TITLE
Failed to build on netlify/cloudflare pages

### ISSUE THREAD

**Issue by xeroticikot** [snowpackjs/astro#645]
### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Setup the starter kit project on my local machine. npm start/run build works fine on local, but tried to deploy both on netlify and cloudflare pages, but the npm build command getting failed with the same error. Here's the image of the failed build log-

![deploy-error](https://user-images.githubusercontent.com/11814742/125094591-370adc00-e0f5-11eb-8724-70ed7d9084f2.png)

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. ...
3. ...
4. ...
5. Error! Describe what went wrong (and what was expected instead)...

**Comment by natemoo-re** [comment]
Hello there! This error can happen on unsupported Node versions. Can you make sure that Netlify is using at least `v14.15.1`?

See https://github.com/cassidoo/astro-netlify-starter for instructions.

**Comment by xeroticikot** [comment]
You're absolutely right. Changing the NODE_VERSION env var to 14 solved the issue. Thank you so much.

**Comment by natemoo-re** [comment]
@xeroticikot This issue has actually come up quite a few times, so I just opened a PR to make it more obvious what's going on here. Hopefully you are the last person to be confused by this! 😉 

https://github.com/snowpackjs/astro/pull/649

**Comment by xeroticikot** [comment]
That's awesome! Great work brada! I'm a very lazy person actually, started this awesome Astro just today, looked so promising to me. Didn't want to waste time on searching, instead opened an issue here! 🥰
