### ISSUE TITLE
🐛 BUG: `create-astro` throws `zlib: unexpected end of file`

### ISSUE THREAD

**Issue by gabrielreisn** [snowpackjs/astro#655]
### What package manager are you using?

npm

### What operating system are you using?

MacOS (M1)

### Describe the Bug

Unable to start a new astro project

```
zlib: unexpected end of file
```

Node version: 14.17.1
npm version: 6.14.13

### Steps to Reproduce

```
λ gabriels-MacBook-Air astro-blog → npm init astro
npx: installed 11 in 1.239s

Welcome to Astro! (create-astro v0.5.0)
If you encounter a problem, visit https://github.com/snowpackjs/astro/issues to search or file a new issue.

> Prepare for liftoff.
> Gathering mission details...
✔ Which app template would you like to use? › Blog
✔ Using template's default renderers › Preact
> Copying project files...
zlib: unexpected end of file
```

**Comment by natemoo-re** [comment]
We've heard a few reports of this but I haven't been able to reproduce. Intuitively this seems like a problem with `degit` which powers `create-astro`.

I wonder if this similar issue for Sapper has any clues...? https://github.com/sveltejs/sapper/issues/924

**Comment by natemoo-re** [comment]
I think I found a fix! Can you try running the following?

```
rm -rf ~/.degit/github/snowpackjs
```

I still have to dig into the underlying cause, but the gist is that `degit`'s local cache is corrupted for some reason... we might be able to sidestep the cache entirely.

<details>

> **nate (he/him)** — Today at 3:52 PM
> Does running `rm -rf ~/.degit/github/snowpackjs` fix it?
> :red_circle:D A N G E R:red_circle: running rm -rf, obviously

> **madah** — Today at 3:53 PM
> It did work actually
> good job
> Any idea how to prevent it from happening?

> **nate (he/him)** — Today at 3:53 PM
> Ugh, wild. No idea what the underlying issue there is, but I'm glad this fixes it. 

<summary>
<a href="https://discord.com/channels/830184174198718474/845451724738265138/864247422003183646">Relevant discussion on Discord</a>
</summary>
</details>

**Comment by MatsDahlin** [comment]
The suggestion from @natemoo-re above solved the issue for me, thanks!

**Comment by gabrielreisn** [comment]
> but the gist is that degit's local cache is corrupted for some reason

yeah, following the other issues you'd mentioned deleting npm cache worked for me. Thanks for the help mate!

**Comment by yikaus** [comment]
Thanks @natemoo-re  point out the cause, running into a same issue and found out it 's due to impatience of  first init command  (ctrl c quit),  didn't expect degit is so slow downloading the tar file , and once tar file is broken it showing issue above.

**Comment by calvo-jp** [comment]
Thanks, @natemoo-re.

**Comment by natemoo-re** [comment]
> Thanks @natemoo-re  point out the cause, running into a same issue and found out it 's due to impatience of  first init command  (ctrl c quit),  didn't expect degit is so slow downloading the tar file , and once tar file is broken it showing issue above. 

Ahhh that makes sense! We might be able to clean up the partially cached download if you quit early, then. Thanks for pointing me in the right direction!

**Comment by FredKSchott** [comment]
If anyone is interested in helping, we have an idea for a semi-fix here: https://github.com/snowpackjs/astro/issues/835#issuecomment-885994107

**Comment by lloydjatkinson** [comment]
Just hit this now, so the problem still exists


```
> Copying project files...
zlib: unexpected end of file
This seems to be a cache related problem. Remove the folder '~/.degit/github/snowpackjs' to fix this error.
For more information check out this issue: https://github.com/withastro/astro/issues/655
```

**Comment by raph5** [comment]
because of the astro's repo changing (astro's repo was `snowpack/astro` but now it's `withastro/astro`) the command to fix this issue is :
```
rm -rf ~/.degit/github/withastro
```

**Comment by victor0x16** [comment]
I run into it on Windows:

```
This seems to be a cache related problem. Remove the folder '~/.degit/github/withastro' to fix this error.
For more information check out this issue: https://github.com/withastro/astro/issues/655
```
and

`rmdir /s %HOME%/.degit/github/withastro` or `rm -r  ~/.degit/github/withastro` (powershell)

It seems to fix it.

**Comment by Psypher1** [comment]
I got this error today after running `pnpm create astro@latest`

**Comment by M4rteaga** [comment]
```pnpm --global update astro```  works for me

**Comment by nguyenhuyquang** [comment]
Thanks so much @natemoo-re . That works for me.
