### ISSUE TITLE
💡 RFC: Allow .astro files to employ child components

### ISSUE THREAD

**Issue by L1lith** [snowpackjs/astro#657]
### Motivation

I was trying to create a standard .astro file to wrap all of my page components so that I could have a standardized layout for the \<head\> and <\html> components. Here's what that looks like:

StandardizedLayout.astro
```
---
// Component Imports
import Head from '../components/Head.astro';
---
<html lang="en">
<Head/>
<body>
    <main>
        <header>
            <div>
                <img width="60" height="80" src="/assets/logo.svg" alt="Astro logo">
                <h1>My Website</h1>
            </div>
        </header>
        CHILDREN NEED TO GO HERE
    </main>
</body>
</html>
```
Here's what the page looks like

index.astro
```
---
// Component Imports
import Tour from '../components/Tour.astro';
import Head from '../components/Head.astro';
import StandardizedLayout from '../components/StandardizedLayout.astro';
---
<StandardizedLayout>
    <h3>Welcome to my page</h3>
    <p>Lorem Ipsum</p>
</StandardizedLayout>
```

This is just an example of what the feature might look like, at the moment it's impossible to do this with astro files. It's also impossible to do with JSX components from my testing, as html tags are not allowed in JSX. 

This feature would also go hand-in-hand with the _app.js replacement feature I proposed [here](https://github.com/snowpackjs/astro/issues/643), as it would be really cool to have one astro file wrapping your whole project.

### Possible solutions
Make .astro files accept children

### Alternatives considered
You could somehow try to make the JSX accept HTML tags

### Risks, downsides, and/or tradeoffs
It could be a little difficult to figure out how to implement with your build process, but I believe it shouldn't be too hard or messy if an effective recursive rendering process is implemented.

### Detailed Design

In my project [Sandhands](https://github.com/L1lith/Sandhands) you can see how I implemented the library as a recursive function in order to support the sanitation of arbitrarily nested data. In order to handle nested component trees there would most likely need to be recursion.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by akellbl4** [comment]
If I understand your problem right, you can replace `CHILDREN NEED TO GO HERE` with `<slot/>` and It should work.

**Comment by L1lith** [comment]
@akellbl4 your solution appears to be working thank you!

Perhaps I missed it but I didn't see this mentioned in the docs? If I didn't miss it then perhaps it needs to be documented?

**Comment by akellbl4** [comment]
You can see docs on it [here](https://github.com/snowpackjs/astro-docs/blob/main/src/pages/core-concepts/astro-components.md#slots) in section Slots
