### ISSUE TITLE
🐛 BUG: Style tags are not used in layouts specified by markdown files

### ISSUE THREAD

**Issue by JoelHobson** [snowpackjs/astro#670]
### What package manager are you using?

npm

### What operating system are you using?

Windows 10

### Describe the Bug

Styles aren't being applied to the page for me if the layout that includes the style tag is chosen by the `layout` field in the frontmatter of a markdown file. 
This seems similar to the [previous bug](https://github.com/snowpackjs/astro/issues/605) I found, so hopefully, the solution is similar too.

### Steps to Reproduce

1. `npm init astro` using template Starter Kit (Generic) - No frameworks selected
2. In the pages directory, create a file named `test.md` with this content:

```
---
layout: "../layouts/layout.astro"
---

Here's some content
```

3. Create a folder named `layouts` and a file called `layout.astro` with this content:
```
---
import { Markdown } from 'astro/components'; 

const { content } = Astro.props;
---

<style>
    div {
        width: 500;
        height: 500;
        background-color: red;
    }
</style>

<html>
    <head></head>
    <body>
        <div>
            <Markdown content={content.astro.source} />
        </div>
    </body>
</html>
```
4. Start Astro with `npm start`, and go to `localhost:3000/test`

Expected behaviour: The text "This is some content" appears on a red square.
Actual behaviour: The text "This is some content" appears on a blank white page.

**Comment by jasikpark** [comment]
I wasn't able to reproduce w/ astro 20.0.4 https://codesandbox.io/s/admiring-carson-w5ivn?file=/src/layouts/layout.astro - so hopefully it's been fixed in the meantime! If not feel free to reopen!
