### ISSUE TITLE
🐛 BUG: Cannot rename `src` folder

### ISSUE THREAD

**Issue by Nixinova** [snowpackjs/astro#674]
### Description
*npm on Windows 10*
I would have expected the `pages` config option allow me to change the pages directory to path other than a subfolder of `src`. However if I do so the build crashes complaining about a missing corresponding js file (`Error: Could not find "`[file]`.js"`).

<details>
<summary>Build using <code>pages: './src/pagecontent'</code></summary>

```cmd
$> astro build
[20:14:04] [snowpack] Ready!
[build] ! building pages...
[build] ✔ pages built.
[build] ! optimizing css...
[build] ✔ css optimized.
[build] ! creating sitemap...
[build] ✔ sitemap built.
[build] ! copying public folder...
[build] ✔ public folder copied.
[build] ! bundling...

   Pages                                                     Page Weight (GZip)
 ┌ /index.html                                               0.68 kB
[build] ▶ Build Complete!
```

</details>

<details>
<summary>Build using <code>pages: './pages/pagecontent'</code></summary>

```cmd
$> astro build
[20:14:12] [snowpack] config.mount[C:\Users\user\Documents\GitHub\astro-test\src]: mounted directory does not exist.
[20:14:13] [snowpack] Ready!
[build] ! building pages...
[build] Unable to render pages\pagecontent\index.astro

Error: Could not find "/pages/pagecontent/index.astro.js"
    at file://C:\Users\user\Documents\GitHub\astro-test\pages\pagecontent\index.astro
    at load (file:///C:/Users/user/AppData/Roaming/npm/node_modules/astro/src/runtime.ts:295:16)
    at buildStaticPage (file:///C:/Users/user/AppData/Roaming/npm/node_modules/astro/src/build/page.ts:95:18)
    at async Promise.all (index 0)
    at build (file:///C:/Users/user/AppData/Roaming/npm/node_modules/astro/src/build.ts:77:7)
    at buildAndExit (file:///C:/Users/user/AppData/Roaming/npm/node_modules/astro/src/cli.ts:16:15)

[build] ✕ building pages failed!
```

</details>

### Steps to Reproduce

1. `npm init astro`
2. Run `astro build`
   - Build succeeds
3. Rename `src` to `foo`
4. Change `pages` option in `astro.config.mjs` to `'./foo/pages'`
6. Run `astro build`
   - Build fails

**Comment by matthewp** [comment]
There's also a `src` option in the config. This is admittedly confusing. They both need to be set though.

**Comment by Nixinova** [comment]
`src` isn't given by default in the config file

**Comment by Nixinova** [comment]
> They both need to be set though.

This doesnt work:
```js
// astro.config.mjs
src: './content',
pages: './content/pages',
```
```cmd
$> astro build
[build] Unable to render content\pages\index.astro
Error: Could not find "/content/pages/index.astro.js"
```

**Comment by rebelchris** [comment]
Can confirm this looks like a bug.

Even when using:
```
src: './docs',
pages: './docs/pages', /
```

And changing the `src` to `docs` it states:
Error: Could not find "/docs/pages/index.astro.js"

**Comment by FredKSchott** [comment]
I believe that this is still a bug. For now I'd really recommend leaving `src` folder as is, and we might just remove this config for now to prevent user errors and frustration.

**Comment by FredKSchott** [comment]
Reported here that any change to the pages config doesn't work: https://github.com/snowpackjs/astro/issues/1174
