### ISSUE TITLE
💡 RFC: Astro Browser Devtools / Debug Extension

### ISSUE THREAD

**Issue by L1lith** [snowpackjs/astro#682]
### Motivation

It would make a lot more sense for debugging purposes if Astro had it's own debugging browser extension like React.
In this issue here there is discussion about changing the composition of the page, and while I think that could be a really handy tool it does seem like something that would be very confusing and jarring to a developer who didn't realize the dev tools were in play, and it could on occasion clash with their site. It would make a lot more sense I believe if these kinds of features could be toggled on and off from inside of the browser extension.

### Possible solutions
Implement a browser extension
### Alternatives considered
Implement a similar solution but in the JS of the page

### Risks, downsides, and/or tradeoffs
Not really much downsides that I can think of

### Detailed Design

I wrote a Webpack environment to build a browser extension I think is really cool [here](https://github.com/L1lith/Showdown-Stats). You could just strip the guts of that project but change the source contents. Likely a websocket connection would need to be formed between the dev server and the browser extension in order to give live updates.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by jasikpark** [comment]
I love this idea! I've definitely made plenty of use of this for projects like React and AlpineJS, it's definitely helpful.

**Comment by FredKSchott** [comment]
Related to https://github.com/snowpackjs/astro/issues/598

**Comment by aFuzzyBear** [comment]
This would be cool, but i do wonder how would the dev tool work with different frameworks, state management tools, hmr etc, but the idea of having an astro dev tool is pretty powerful.

**Comment by FredKSchott** [comment]
RFC Call: We're going to pursue https://github.com/snowpackjs/astro/issues/598 for now.
