### ISSUE TITLE
🐛 BUG: npm init astro fails with existing subdirectory

### ISSUE THREAD

**Issue by BryanPan342** [snowpackjs/astro#690]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Running `npm init astro` in a directory that has a subdirectory (`.git/`, `foobar/`) fails with nondescript error message. 

### Steps to Reproduce

1. `mkdir test && cd test`
2. `git init`
3. `npm init astro`
4. Fails with the following message:
    ```
    node:internal/process/promises:245
              triggerUncaughtException(err, true /* fromPromise */);
              ^
    
    [Error: EINVAL: invalid argument, rmdir '.'] {
      errno: -22,
      code: 'EINVAL',
      syscall: 'rmdir',
      path: '.'
    }
    npm ERR! code 1
    npm ERR! path /Users/path
    npm ERR! command failed
    npm ERR! command sh -c create-astro
    ```

As a new user of astro, I felt like I could create a directory with an existing git library and then run `npm init astro` (I actually have a python script to create git projects through the cli). Not sure if other people follow this pattern, but I think it would be nice at least to have some **documentation** noting this, or adding this as part of the `create-astro` script to either support existing subdirectories OR error out with something more descriptive.

**Comment by FredKSchott** [comment]
Fixed in #700
