### ISSUE TITLE
💡 RFC: Static tweet parser

### ISSUE THREAD

**Issue by rebelchris** [snowpackjs/astro#691]
### Motivation

I want to be able to have a markdown shortcode for instance: `{{ tweet 34343443 }}` or have full link to a tweet like: `https://twitter.com/user/22332` which then should convert to a static tweet.

The origin of this is Astro is build to be fast, static and no-js.
However one big struggle for my site is Tweet embeds inside Markdown.

These use a lot of resource and slow the rendering down.

A solution for instance is this vercel next.js example:
https://static-tweet.vercel.app/

I got the gist working in Astro as a component on it's own
However that doesn't work on build and it can't work on markdown parsed files (which often a blog are)

### Possible solutions

A rehype plugin that can do this?

### Alternatives considered

A Astro component that can render over Markdown slot?

### Risks, downsides, and/or tradeoffs

You will miss the live like update, or this can be fetched on build time?

### Detailed Design

The output can look like this:
https://static-tweet.vercel.app/

Benefit, people can style the tweets anyway they like to fit the website.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by okikio** [comment]
You should be able to use `.astro` together with the Markdown component https://github.com/snowpackjs/astro/blob/main/docs/guides/markdown-content.md#astros-markdown-component

**Comment by jasikpark** [comment]
Once #207 drops you should be able to use the tweet component in your markdown, akin to a shortcode. Until then, I'd do like @okikio suggests above!

**Comment by jasikpark** [comment]
https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/shortcodes/twitter.html and https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/shortcodes/twitter_simple.html are good places to pull from for implementing one of these as well.

**Comment by rebelchris** [comment]
@okikio Yes and no actually, I have 500+ articles in .md files.
I can't really go and wrap them in a <Markdown> structure to have the option for dynamic elements.

Unless it would work, by passing the <Markdown content="md"> but have it parse the markdown first?
Don't think that will work actually.

From what I can see #491 would solve this same issue!
As for the examples thanks @jasikpark, the twitter_simple has a nice implementation for the json endpoint, didn't know about that one yet.

**Comment by rebelchris** [comment]
To clarify even more:

I have the following `.md` file:

```md
<Avatar name="Chris" />

# Heading one

Some random content
```

I now would like this Avatar component to render as is

Using the following in my `BlogPost.astro` (Layout file) will work:

```
<Markdown>
        <Avatar name="chris" />
        
        # Heading one
        
        Some content
  </Markdown>
  ```
  
  However I can't use it like that since the markdown is a seperate md file.
  So I can at most do this:
  
  ```
  <Markdown content="content.astro.source" />
  ```
  
  Which in return won't render my custom component.
  
  But maybe I'm using this wrong now?

**Comment by okikio** [comment]
Yeah # 491 is going to be required

**Comment by natemoo-re** [comment]
Correct me if I'm wrong but this seems like two issues:
 - [x] Support components in Markdown. Covered by #491.
 - [ ] Build static tweet rendering into an official Astro component, `import { Tweet } from 'astro/components'`

Is that right? We've definitely talked about an official Tweet component before and _I think_ would be in favor of this.

**Comment by rebelchris** [comment]
@natemoo-re Yes correct!

I'm already working on this static tweet component in Astro
Ofcourse, happy to share once it's done to see if it can become an official Tweet component.

**Comment by okikio** [comment]
If we are talking a native tweet component I think it would be better as a separate npm package, what do you think?

**Comment by jasikpark** [comment]
I definitely like the idea of `yarn add astro-tweet` 😆

**Comment by rebelchris** [comment]
@jasikpark @okikio def like this idea.
Could you just guide me to an example way of achieving this?

Since it will need to be something that can run on runtime, but render statically?

**Comment by jasikpark** [comment]
> https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/shortcodes/twitter.html and https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/shortcodes/twitter_simple.html are good places to pull from for implementing one of these as well.

I would just translate this into an Astro component! Fetch the data the same way, etc..

**Comment by okikio** [comment]
Yeah, something similar to what @jasikpark said, e.g. 
![image](https://user-images.githubusercontent.com/17222836/126361605-08665f8a-fde3-4f62-9574-0735a62beaa2.png)

The example above is from my [Hashnode blog](https://blog.okikio.dev/psa-add-dark-mode-to-your-sites-or-at-least-let-the-browsers-do-it-for-you), you can check out how Hashnode did theirs from one of my articles.

**Comment by okikio** [comment]
From what I understand [dev.to](https://dev.to) also has a Twitter component, I suggest checking out [`Forem`](https://github.com/forem/forem) (the open source project dev.to is built from) for the tweet component, e.g.
* https://github.com/forem/forem/blob/c842d1a0c6718f319f167e9ec13d4d7d5d6b6d39/app/views/liquids/_tweet.html.erb
* https://github.com/forem/forem/blob/c842d1a0c6718f319f167e9ec13d4d7d5d6b6d39/app/assets/stylesheets/ltags/TweetTag.scss
* etc...

**Comment by rebelchris** [comment]
Thanks for that, the hashnode one just renders the iframe, so no immediate win there.
However the forem one is a good find, it uses the API and that code I already got working, so will be working on that later today.

**Comment by rebelchris** [comment]
Update on this,

Almost have the astro component done and it works great in build and dev!
this is a fully static tweet.

Still need to do some testing with different types of tweets, anyone keen to help testing or perhaps help converting it so we can make it it's own module? (Astro plugin)
 
<img width="611" alt="Screenshot 2021-07-21 at 16 14 42" src="https://user-images.githubusercontent.com/554874/126503754-5999e306-5f1f-4be3-8b1a-6914efd3f409.png">

**Comment by rebelchris** [comment]
@natemoo-re I've just published my very first Astro plugin:
https://www.npmjs.com/package/@rebelchris/astro-static-tweet

However i'm still testing and it seems like the CSS (inline in astro) is not working, any idea how I can fix that?

**Comment by natemoo-re** [comment]
@rebelchris this is awesome!! I will take a look sometime today and see if I can debug the CSS. 👍

**Comment by aFuzzyBear** [comment]
I think what @rebelchris has done here is brilliant, could this be opened further to incorporate other forms of social embed's like facebook, insta etc?

**Comment by okikio** [comment]
@rebelchris Would it be possible to have a default Twitter like style, but then allow the user to build their own custom style to supplement their sites?

**Comment by okikio** [comment]
> I think what @rebelchris has done here is brilliant, could this be opened further to incorporate other forms of social embed's like facebook, insta etc?

We could create a `astro-social` packages, that functions as a way to import a bunch of social components with the ability to use only the components you need.

**Comment by jasikpark** [comment]
Instagram would be *fun* to implement because each user would need to aign up for their own app auth key, but it'd be pretty simple otherwise https://github.com/gohugoio/hugo/issues/7879

**Comment by jasikpark** [comment]
> @rebelchris Would it be possible to have a default Twitter like style, but then allow the user to build their own custom style to supplement their sites?

Maybe `<Tweet type="unstyled || default"/>`?

**Comment by okikio** [comment]
I created a repo from `astro-social`, it's still a massive WIP, but it's a starting point. https://github.com/okikio/astro-social

**Comment by rebelchris** [comment]
> @rebelchris Would it be possible to have a default Twitter like style, but then allow the user to build their own custom style to supplement their sites?

It is actually styled by default, but there is still and issue where this CSS is not loading from the Astro file.
My plan was it would take that as a basis, and I write the classes out so people can overwrite them.

Good idea on making a social repo, think we can easily add other socials.
If indeed we use the API credentials.

**Comment by okikio** [comment]
@rebelchris yeah, my main problem is the api endpoints for each service, if anyone has experience with those that would be much appreciated. The repo is https://github.com/okikio/astro-social

**Comment by rebelchris** [comment]
I'll have a look, we might not even have to use API's for each service, that's mainly a Twitter downside as they don't have a public way of getting all the info needed (They do have those JSON endpoints, but they are very limited) ~ Could possibly add those as callback for when user doesn't set the keys.

**Comment by okikio** [comment]
> I'll have a look, we might not even have to use API's for each service, that's mainly a Twitter downside as they don't have a public way of getting all the info needed (They do have those JSON endpoints, but they are very limited) ~ Could possibly add those as callback for when user doesn't set the keys.

Possibly, but I remember seeing somewhere that instagram requires API Access Key.

**Comment by jasikpark** [comment]
> Instagram would be _fun_ to implement because each user would need to aign up for their own app auth key, but it'd be pretty simple otherwise [gohugoio/hugo#7879](https://github.com/gohugoio/hugo/issues/7879)

yep you do need a key for instagram

**Comment by aFuzzyBear** [comment]
This is exciting, ☺

**Comment by jasikpark** [comment]
Looks like this has been fulfilled via https://docs.astro.build/themes#featured-packages - the astro static tweet package, right? I definitely feel like this is something that works best external to astro!

Hugo has had an [issue](https://github.com/gohugoio/hugo/issues/7893) discussing whether social media shortcodes should be w/in the main project, and they have a much bigger ask since there's no real way to import hugo shortcodes from a package manager, whereas Astro is built for it! 

I'm excited to see how we get Components in Markdown w/ `astro-next-compiler` :D

lmk if I'm wrong about closing this 😅
