### ISSUE TITLE
💡 RFC: Dev Server does not recognize public ".html" extensions files

### ISSUE THREAD

**Issue by johnhenry** [snowpackjs/astro#697]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Running 'astro dev' does not mount files in the 'public/' directory ending in ".html".

### Steps to Reproduce

1. `npm init astro` using template Generic
1. Add empty "default.htm" and "default.html" (note the additional "l") files to the "public/"  directory
1. Tun dev server with `npm start`
1. Visit http://localhost:3000/default.htm and observe empty page.
1. Error! visit http://localhost:3000/default.html and observe "Not Found" error.
1. Note: building the application with `npm run build` appears to work properly.

**Comment by natemoo-re** [comment]
Thanks for opening an issue! This is a good point.

Would it be worth supporting plain `.html` files in the `pages` directory as well? We should definitely support `public` but `pages` would be less prone to accidental overwrites.

**Comment by johnhenry** [comment]
I support this in the pages directory as well, though I struggle to understand what this would accomplish?

**Comment by johnhenry** [comment]
> Thanks for opening an issue! This is a good point.
> 
> Would it be worth supporting plain `.html` files in the `pages` directory as well? We should definitely support `public` but `pages` would be less prone to accidental overlap.

I support this in the pages directory as well, though I struggle to understand what this would accomplish?

**Comment by johnhenry** [comment]
This appears to be working now. Thanks all!

**Comment by johnhenry** [comment]
I closed this pre-maturely. This still appears to be an issue.

**Comment by matthewp** [comment]
Going to move this to the RFC board as this is a requested new feature.

**Comment by johnhenry** [comment]
Does it make sense to close this in favor of https://github.com/snowpackjs/astro/issues/749?

Ideally, any files that appears within `/public` should be served un-modified and this should apply to `.html` files as well?

**Comment by jasikpark** [comment]
I think that makes sense - you can also add the context from this issue as a comment on the more general issue
