### ISSUE TITLE
🐛 BUG: HTML entities are being evaluated, e.g. &copy; -> © instead of keeping them as-is

### ISSUE THREAD

**Issue by Janne252** [snowpackjs/astro#704]
### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

HTML entities are being evaluated, e.g. `&copy;` -> © instead of keeping them as-is.

### Steps to Reproduce

1. Clone the minimal reproducible example repository
2. `npm install`
3. `npm run build`
4. Check the contents of `dist/index.html`. The `<body>` tag should contain `©` character instead of the original `&copy;`
5. Expected to retain `&copy;` as-is.

### Link to Minimal Reproducible Example (Optional)

https://github.com/Janne252/-snowpackjs-astro-issue-704-HTML-entities-are-being-evaluated

**Comment by natemoo-re** [comment]
Thanks for opening an issue! I signaled on Discord that leaving these as is seems like the desired behavior.

For context, this is inherited from the parser we forked. I'd be in favor of at least _exploring_ what it means to remove this.

**Comment by jasikpark** [comment]
> Thanks for opening an issue! I signaled on Discord that leaving these as is seems like the desired behavior.
> 
> 
> 
> For context, this is inherited from the parser we forked. I'd be in favor of at least _exploring_ what it means to remove this feature, because I think it's unexpected in the vast majority of cases.

I'd be curious to go back through the issues and PRs to find why they decided to do it in the parser that was forked?

**Comment by natemoo-re** [comment]
@jasikpark feel free to peruse [the upstream issues](https://github.com/sveltejs/svelte/issues?q=is%3Aissue+decode) ☺️ . Might date back to the very beginning of the parser, I'm not sure.

**Comment by FredKSchott** [comment]
Isn't this behaving correctly? My only personal experience is that I used to use `&nbsp;` all the time to create a non-breaking space. In HTML, I expected that to be evaluated instead of left as text. 

```
<p>Word1&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Word2</p>
// copied from: https://stackoverflow.com/questions/1357078/whats-the-difference-between-nbsp-and
```

**Comment by jasikpark** [comment]
I do believe that is the bug

**Comment by sno2** [comment]
Alright, it seems there is more going wrong here.  Here are all of the instances of Astro escaping html entities that I could find:

https://github.com/snowpackjs/astro/blob/9c7f07aebdd7d762f2f86dd3752773ce851cde65/packages/markdown-support/src/codeblock.ts#L24

`escape` function
https://github.com/snowpackjs/astro/blob/9c7f07aebdd7d762f2f86dd3752773ce851cde65/packages/astro/src/compiler/transform/prism.ts#L9-L13
used:
- https://github.com/snowpackjs/astro/blob/9c7f07aebdd7d762f2f86dd3752773ce851cde65/packages/astro/src/compiler/transform/prism.ts#L20
- https://github.com/snowpackjs/astro/blob/9c7f07aebdd7d762f2f86dd3752773ce851cde65/packages/astro/src/compiler/transform/prism.ts#L85

**Comment by FredKSchott** [comment]
Makes sense. Would love to see you take another stab at this in a new PR, if you're able!

**Comment by sno2** [comment]
> Makes sense. Would love to see you take another stab at this in a new PR, if you're able!

Hoping to get one in tonight without breaking the entire docs again😅

**Comment by jasikpark** [comment]
> Alright, it seems there is more going wrong here.  Here are all of the instances of Astro escaping html entities that I could find:
> 
> 
> 
> https://github.com/snowpackjs/astro/blob/9c7f07aebdd7d762f2f86dd3752773ce851cde65/packages/markdown-support/src/codeblock.ts#L24
> 
> 
> 
> `escape` function
> 
> https://github.com/snowpackjs/astro/blob/9c7f07aebdd7d762f2f86dd3752773ce851cde65/packages/astro/src/compiler/transform/prism.ts#L9-L13
> 
> used:
> 
> - https://github.com/snowpackjs/astro/blob/9c7f07aebdd7d762f2f86dd3752773ce851cde65/packages/astro/src/compiler/transform/prism.ts#L20
> 
> - https://github.com/snowpackjs/astro/blob/9c7f07aebdd7d762f2f86dd3752773ce851cde65/packages/astro/src/compiler/transform/prism.ts#L85
> 
> 
> 
> Edit: This might also be causing the problem within the `Markdown` component:
> 
> https://github.com/snowpackjs/astro/blob/1bbe98ae54eb6018184fdc3875fe689775510ad6/packages/markdown-support/src/index.ts#L70
> 
> 

I believe this was talking about the left brace error, which was fixed! :D
