### ISSUE TITLE
🐛 BUG: npm init astro fails

### ISSUE THREAD

**Issue by ga-fleury** [snowpackjs/astro#709]
### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

Can't start a new project, when using npm init astro I just get an error

λ npm init astro

Welcome to Astro! (create-astro v0.5.0)
If you encounter a problem, visit https://github.com/snowpackjs/astro/issues to search or file a new issue.

> Prepare for liftoff.
> Gathering mission details...
√ Which app template would you like to use? » Portfolio
✔ Using template's default renderers › Preact
> Copying project files...
zlib: unexpected end of file
npm ERR! code 1
npm ERR! path D:\astro
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c create-astro

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\gabri\AppData\Local\npm-cache\_logs\2021-07-15T21_27_03_379Z-debug.log

### Steps to Reproduce

1. `npm init astro` using any template

5. Error! Describe what went wrong (and what was expected instead)...

**Comment by ga-fleury** [comment]
as found in #655, running rm -rf ~/.degit/github/snowpackjs solved the issue.

**Comment by Fil** [comment]
I had the same crash after I ctrl-C my first test install, but had to run rm -rf ~/.degit/github/ instead — the error message should certainly be updated?

**Comment by weakish** [comment]
> error message should certainly be updated?

#2400 updated the error message
