### ISSUE TITLE
💡 RFC: Git pre-commit hook for lint and code format.

### ISSUE THREAD

**Issue by devsmitra** [snowpackjs/astro#713]
### Background & Motivation
Can be used to lint commit messages, run tests, lint code, etc. at the time of commit or push. 
This can be done using CI as well but using hook developers will be informed before pushing their code to the git.

### Possible solutions
I have already suggested a solution for this here https://github.com/snowpackjs/astro/pull/698

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [X] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
Thanks for creating the issue! Copying my response from the PR here: I

 personally don't love Husky, and would rather automate these things via CI instead outside of the PR flow on each contributors machine. For example, we automatically format the codebase after every commit, so there's no need for a husky format precommit check.

**Comment by devsmitra** [comment]
@FredKSchott I agree, We can do this using CI but if we use git hooks developer will know before commit/push. Instead of going and checking GitHub action or CI.

**Comment by jasikpark** [comment]
> @FredKSchott I agree, We can do this using CI but if we use git hooks developer will know before commit/push. Instead of going and checking lint issue GitHub action or CI, It'll help us to fix common issues then and there.

The prettier CI doesn't work as a lint though, it works as a codemod - every commit to main is formatted automatically just like if we had git hooks setup.

**Comment by devsmitra** [comment]
@jasikpark I think we can skip the format, but can we do it for lint checks. because I see some lint issue and warning is main. We avoid these issues in the future.  


Just for reference
```
✖ 27 problems (4 errors, 23 warnings)
 1 error and 0 warnings potentially fixable with the `--fix` option.
  ```

**Comment by jthegedus** [comment]
You could probably just add `eslint --fix` to the auto format as well? Would fix a bunch of the issues.

**Comment by jasikpark** [comment]
It looks like #802 added running the lint commands to the CI, so hopefully we can just PR a commit that makes those improvements now that they're visible... while we're still figuring this out, want to submit a PR that does just that?

**Comment by devsmitra** [comment]
@jthegedus I have added `eslint --fix` in the pre-commit check.

**Comment by FredKSchott** [comment]
I'd like to close this because I'm strongly -1 on adding husky at this stage in the project (for the reasons outlined above and in that PR). 

If there's interest from other L2+ contributors I'm happy to reopen and discuss more, but otherwise I'd like to push us to improving CI to better surface these issues instead, and then revisit this once we've hit v1.0 release.
