### ISSUE TITLE
🐛 BUG: "index" in markdown filename breaks build

### ISSUE THREAD

**Issue by stenehall** [snowpackjs/astro#722]
### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

Having a markdown file named `no-index.md` in posts will crash `yarn build` with the following error `Error: Not Found (/posts/some-)`

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. Create a markdown post named `no-index.md`
3. `yarn build`
5. `Error: Not Found (/posts/some-)`

**Comment by FredKSchott** [comment]
fixed in #722
