### ISSUE TITLE
📘 DOC: Add Progressive Enhancement section

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro#724]
It'd be nice if the docs had a section that describes how to use progressive enhancement for your components, so that they render with something useful at build time, and are then hydrated in a useful way.

**Comment by L1lith** [comment]
@jasikpark Isn't that what [this](https://docs.astro.build/core-concepts/component-hydration) is? Although I do think that it could be titled more clearly than "partial hydration". Although it does make sense it might not be intuitive to someone who's looking to attach the load listeners

**Comment by jasikpark** [comment]
My point is more of showing an example of how to make a component that works well both when loaded with JS and on a browser that doesn't have JS, so that page describes some of the tools you might use, but not how to effectively make that happen?

**Comment by FredKSchott** [comment]
We explored this in #1440 but I don't think there's currently a way to do this well on our docs site. Closing until we can redesign the docs site to include more blog post-type narrative content.
