### ISSUE TITLE
📘 DOC: Opening Curly Brace shows as HTML Encoded Value ("Built-In Components")

### ISSUE THREAD

**Issue by sno2** [snowpackjs/astro#727]
![image](https://user-images.githubusercontent.com/43641633/126021769-1c28e6b4-5286-4ccf-aa93-992144e207fe.png)

[Website Reference](https://docs.astro.build/reference/builtin-components)

If you look at the [source file](https://github.com/snowpackjs/astro/blob/main/docs/src/pages/reference/builtin-components.md), then you will notice that it does not look incorrect as shown in the screenshot.  I actually can't figure out why it is happening so this might also be a bug within Astro SSR.

**Comment by jasikpark** [comment]
From what I've seen it seems to be a bug from Astro escaping `{` to an html entity, which is fine sometimes, but not when it is rendered in a `<code>` block. Astro shouldn't auto-escape characters... I might be suspicious of remark as well tho...

**Comment by benborgers** [comment]
I'm running into this issue with code blocks in the `<Markdown />` component too. Looks like this line is responsible: 

https://github.com/snowpackjs/astro/blob/f33c775b93d2998d8da8a4f71a5ee4fb6abdd949/packages/markdown-support/src/codeblock.ts#L24

There might be a good reason to escape `{` though, so I'm not sure if it could just be removed.

**Comment by jasikpark** [comment]
I imagine it was added to deal with something about the astro file allowing you to embed TS with `<button aria-pressed={buttonIsActive}></button>`, so it makes sense to replace it to not trip up the compiler, but I imagine this might need to be done differently somehow.

**Comment by FredKSchott** [comment]
Had to revert #738, this is still not fixed!

**Comment by IanVS** [comment]
It took me a sec to find this issue, and I almost opened another, so I'll add this as a search term for anyone else who might be looking: &#123;

**Comment by eallenOP** [comment]
+1 
I was going to report this one too. It renders fine on GitHub https://github.com/snowpackjs/astro/blob/main/docs/src/pages/core-concepts/astro-components.md but makes docs pages with lots of inline code snippets rather confusing to read! (Seems fine in code blocks.)

<img width="747" alt="Screenshot 2021-07-29 at 10 58 21 AM" src="https://user-images.githubusercontent.com/10552518/127406822-3e91f1d3-4d55-442e-8cbb-886ebe702224.png">

**Comment by sno2** [comment]
I couldn't fix these issues without breaking other things within Astro after 4 long sprees on them.  If anyone else would like to give this a try, then you are welcome.

**Comment by jasikpark** [comment]
Fixed in #1094 

`#&123;` is dead. long live `#&123;`!
