### ISSUE TITLE
🐛 BUG: npm init astro --template does not use requested template

### ISSUE THREAD

**Issue by alex-drocks** [snowpackjs/astro#737]
### What package manager are you using?

npm

### What operating system are you using?

Windows 10 x64 latest public available version

### Describe the Bug

![image](https://user-images.githubusercontent.com/69808183/126072023-8321a739-57c0-4671-bc1c-6588e9393263.png)

using --template with **npm init astro does not use the requested template**. Instead the initializer asks for which template I want to use even if I provided it beforehand.

I tried with --template portfolio and --template framework-react and the result was the same as seen in the screenshot above.
I'm using Node 16.4.0 and npm 7.19.0. 

Good news is when I select the template with the console prompt, it will work with that. But it of course won't be the template I requested with the cli command --template ...

### Steps to Reproduce

1.  npm init astro --template framework-react
2. Error: npm ignores request --template command and prompts which template I would like to use.
3.  Expected: npm should init with the --template requested instead of asking which one I would like to use.

**Comment by FredKSchott** [comment]
I can't reproduce on mac:

```
~/Code/test/foaa npm init astro --template framework-react
npx: installed 11 in 2.227s

Welcome to Astro! (create-astro v0.5.0)
If you encounter a problem, visit https://github.com/snowpackjs/astro/issues to search or file a new issue.

> Prepare for liftoff.
> Gathering mission details...
> Copying project files...
✔ Done!
```

I think this is a windows issue but I'm not sure why that is. Can anyone else reproduce on windows?

If anyone could add some `console.log` debugging info to `packages/create-astro/src/index.ts` to see what's going on here, that would be helpful. My guess is maybe something in the prompts.override call?

**Comment by alex-drocks** [comment]
> I can't reproduce on mac:

I just tried on MacBook Air and it did same problem as on my Windows machine. That's weird. Probably a npm thing with my version ? 

My Mac and windows machines are running npm 7.19.1, I'll try with latest 7.20.0 and confirm back here

**Comment by jasikpark** [comment]
https://user-images.githubusercontent.com/10626596/126406205-45682c64-4a9c-42f6-b98c-936301310baf.mov

Reproduced on macOS 11.4, node v16.5.0, create-astro v0.5.0 (this is b/c `yarn create` installs `create-astro` as a global command, and then I guess npm init just grabs that???

**Comment by natemoo-re** [comment]
Doesn't `npm@7` require an additional `--` to pass arguments through? I know we had this in the docs at one point.

```
npm init astro -- --template framework-react
```

**Comment by jasikpark** [comment]
<img width="1027" alt="image" src="https://user-images.githubusercontent.com/10626596/126411593-abefc061-2017-4214-a8c8-795cd6da4f25.png">

It looks like that's it. I'll update the docs + examples directories.

**Comment by FredKSchott** [comment]
Ah dang, I may have run “yarn create” when I was testing and not even realized it
