### ISSUE TITLE
🐛 BUG: npm init astro fails - "could not find commit hash for HEAD"

### ISSUE THREAD

**Issue by tomasmendes01** [snowpackjs/astro#746]
### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

could not find commit hash for HEAD
npm ERR! code 1
npm ERR! path C:\laragon\www\Portfolio
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c create-astro

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Admin\AppData\Local\npm-cache\_logs\2021-07-19T00_34_19_517Z-debug.log

### Steps to Reproduce

1. `npm init astro`
2. Select anything (in my case i'm selecting `Portfolio` but i've already tested all the remaining options)
3. Error after `> Copying project files...`!

**Comment by jgil-r** [comment]
do you have git installed?

**Comment by jasikpark** [comment]
If I'm not wrong, `degit` shouldn't require git, no?

**Comment by jgil-r** [comment]
It is my understanding that it does. I could be wrong, was reading through this [issue](https://github.com/Rich-Harris/degit/issues/37)

**Comment by jasikpark** [comment]
Wack. I honestly would have thought there was something like `libgit2` but for JS

**Comment by FredKSchott** [comment]
I think it uses the Github API and not git. In either case, this is out of scope for us and a problem in degit (that may be related to your machine).  Sorry about that! In that case, you can clone (or download as a tarball) the example yourself from Github.
