### ISSUE TITLE
📘 DOC: Toggle light/dark theme makes screen flashing

### ISSUE THREAD

**Issue by vuhoanglinh1123** [snowpackjs/astro#747]
When navigating to a different route or reloading after selecting the light/dark theme, the page keeps switching back and forth between the default system theme and the selected theme. This is very noticable when the system theme has an opposite color compare to the selected light or dark theme, as it makes the screen seems to be flashing everytime the user changes route.

**Comment by tony-sull** [comment]
Thanks for catching this!  Just submitted PR #748 with a fix

**Comment by FredKSchott** [comment]
Fixed in #748 !
