### ISSUE TITLE
🐛 BUG: Error `zlib: unexpected end of file` when running `npm init astro`. Fails out.

### ISSUE THREAD

**Issue by rrsai** [snowpackjs/astro#750]
### What package manager are you using?

npm 7.19.1

### What operating system are you using?

Linux Ubuntu 20.04

### Describe the Bug

When running npm init astro, it errors out (on all app templates)

$ npm init astro

Welcome to Astro! (create-astro v0.5.0)
If you encounter a problem, visit https://github.com/snowpackjs/astro/issues to search or file a new issue.

> Prepare for liftoff.
> Gathering mission details...
✔ Which app template would you like to use? › Starter Kit (Generic)
✔ Which frameworks would you like to use? › 
> Copying project files...
zlib: unexpected end of file
npm ERR! code 1
npm ERR! path /src/project
npm ERR! command failed
npm ERR! command sh -c create-astro

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/username/.npm/_logs/2021-07-19T19_12_09_515Z-debug.log
username:/src/project$ e /home/username/.npm/_logs/2021-07-19T19_12_09_515Z-debug.log
username:/src/project$ tail -60 /home/username/.npm/_logs/2021-07-19T19_12_09_515Z-debug.log
0 verbose cli [
0 verbose cli   '/home/username/.nvm/versions/node/v14.17.0/bin/node',
0 verbose cli   '/home/username/.nvm/versions/node/v14.17.0/bin/npm',
0 verbose cli   'init',
0 verbose cli   'astro'
0 verbose cli ]
1 info using npm@7.19.1
2 info using node@v14.17.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:/home/username/.nvm/versions/node/v14.17.0/lib/node_modules/npm/npmrc Completed in 2ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/src/project/.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/home/username/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/username/.nvm/versions/node/v14.17.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 0ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 10ms
19 timing npm:load:configload Completed in 10ms
20 timing npm:load:setTitle Completed in 0ms
21 timing npm:load:setupLog Completed in 1ms
22 timing npm:load:cleanupLog Completed in 2ms
23 timing npm:load:configScope Completed in 0ms
24 timing npm:load:projectScope Completed in 0ms
25 timing npm:load Completed in 14ms
26 timing config:load:flatten Completed in 2ms
27 http fetch GET 200 https://registry.npmjs.org/create-astro 228ms (cache revalidated)
28 timing arborist:ctor Completed in 1ms
29 timing arborist:ctor Completed in 0ms
30 timing arborist:ctor Completed in 0ms
31 timing command:init Completed in 4058ms
32 verbose stack Error: command failed
32 verbose stack     at ChildProcess.<anonymous> (/home/username/.nvm/versions/node/v14.17.0/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
32 verbose stack     at ChildProcess.emit (events.js:376:20)
32 verbose stack     at maybeClose (internal/child_process.js:1055:16)
32 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
33 verbose cwd /src/project
34 verbose Linux 5.8.0-59-generic
35 verbose argv "/home/username/.nvm/versions/node/v14.17.0/bin/node" "/home/username/.nvm/versions/node/v14.17.0/bin/npm" "init" "astro"
36 verbose node v14.17.0
37 verbose npm  v7.19.1
38 error code 1
39 error path /src/project
40 error command failed
41 error command sh -c create-astro
42 verbose exit 1
username:/src/project$ 

### Steps to Reproduce

1. `npm init astro` using template blog/generic or any other
2. use dependency node version: deps:
```
node -v
v14.17.0
npm -v
7.19.1
```

2. The init process will error out `zlib: unexpected end of file`

**Comment by rrsai** [comment]
Ah, I searched about that specific error and it's related to download usage of gzip compression, and `npm init astro` is now working again as of 11 pm tonight, so I believe this was actually related to a obscured network download error, something along the line was unavailable and this was the output.

I can only suggest that since the install is such a high profile area, it might be beneficial to wrap the process in error/exception handling, to clarify that it's a likely error with the network in this stage, and then just pass through that additional helpful error along with the more specific error.

**Comment by jasikpark** [comment]
+1 we need a better error message for this!
