### ISSUE TITLE
💡 RFC: Compiler API

### ISSUE THREAD

**Issue by georges-gomes** [snowpackjs/astro#76]
We would like to add .astro components support to our products (divriots.com)
Do you have an API already I can use ? in browser ?

If this helps: We just need the raw translation to js/ts. We already have TS/babel/JSX/CSS/SASS/CSSModules processing in the build pipeline... which would require less dependencies on your end if we can pull this off.

Cheers

**Comment by jasikpark** [comment]
https://play.astro.build could be very cool -- akin to https://play.tailwindcss.com

**Comment by tony-sull** [comment]
> https://play.astro.build could be very cool -- akin to https://play.tailwindcss.com

I'm a big fan of [Svelte's REPL](https://svelte.dev/repl/hello-world?version=3.38.3) as well.  It's even tied in to GitHub so you can save sessions as gists

**Comment by mash-graz** [comment]
stackblitz [webcontainers](https://github.com/stackblitz/webcontainer-core) and [next.js live](https://nextjs.org/live) look like very promising solutions concerning this feature request.

**Comment by natemoo-re** [comment]
We've made some huge progress on this front! Will keep this issue open until all of this lands as stable, but...

https://github.com/snowpackjs/astro-compiler-next will be a stand-alone package published as `@astrojs/compiler` and https://astro.build/play is running it in the browser!

**Comment by FredKSchott** [comment]
Awesome work @natemoo-re !!!

I feel like this is safe to close now, with work continuing in the https://github.com/snowpackjs/astro-compiler-next repo. We'll keep making improvements to the API as we get closer to v1.0. Cheers yall! 🥳
