### ISSUE TITLE
📘 DOC: Codeblock with no specified lang renders with small font-size

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro#760]
<details><summary>Screenshot showing an `astro` codeblock, but the author forgot to specify a language, so the text was rendered smaller due to CSS selection.</summary><img width="1032" alt="image" src="https://user-images.githubusercontent.com/10626596/126245600-039a070b-2852-4a0a-b581-08e3da5b4990.png">
</details>

I'm going to submit a PR to fix this small inconsistency in the docs, by adding the `astro` lang to the codeblock, but should the CSS select based on whether the codeblock has a language or not for font size?

**Comment by FredKSchott** [comment]
@natemoo-re I see a lot of `:not([class*='language'])` in the new CSS. Was that meant to match against an inline code style vs. a full code block?

If so, then it would be better to style `code` for inline and `pre > code` for code blocks to avoid the bug that @jasikpark is mentioning. I've always used that in the past as the way to style inline vs block.

**Comment by jasikpark** [comment]
I might try to refactor that code into 
```css
code {
}

pre {
}

pre > code {
}
```

If that's the case.

**Comment by FredKSchott** [comment]
Fixed in #948
