### ISSUE TITLE
📘 DOC: iOS Safari does not fully support `aspect-ratio: 16 / 9`

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro#762]
The Youtube video at https://docs.astro.build/quick-start does not render in 16/9 aspect ratio because iOS Safari does not have fully support for the feature: https://caniuse.com/mdn-css_properties_aspect-ratio

I would say we should keep the `aspect-ratio: 16 / 9` while still depending on the padding-bottom hack.

**Comment by FredKSchott** [comment]
sgtm! @natemoo-re any objections?

**Comment by jasikpark** [comment]
This is less important since I believe the immediate youtube video is now in `www` not `docs`, but it's probably still something to update the docs styles with at some point?

**Comment by jasikpark** [comment]
Closing for the above comment
