### ISSUE TITLE
🐛 BUG: Components output with extra space preventing them rendering inline in `<Markdown/>`

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro#764]
### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

I wanted to show off https://github.com/jasikpark/astro-katex/ using `<Markdown/>` but when I tried to show a component used inline, it inserted extra paragraph tags.

```md
Hello <Component/>.
```
turned into

```tsx
<p>Hello</p>
<Component/>
<p>.</p>
```

### Steps to Reproduce

Try to use a component that outputs a `<span>` or other inline element from within the `<Markdown/>` component

**Comment by FredKSchott** [comment]
@natemoo-re this feels familair, is this a duplicate? If not, can you tackle as a part of your Markdown + Components work?

**Comment by natemoo-re** [comment]
Confirming that this is fixed in the `astro@next` preview! See [working reproduction](https://stackblitz.com/edit/github-fwb523?file=src%2Fpages%2Findex.astro).

Will put this in our milestone to be closed when that release is stable.
