### ISSUE TITLE
💡 RFC: Add `snowpack.config.mjs` and `astro.config.mjs` schemas to https://www.schemastore.org/json/

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro#765]
### Background & Motivation

I want my editor to be able to provide feedback about whether I have invalid configs for these files.

### Possible solutions
Submit a schema to https://www.schemastore.org/json/ via https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md
### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
How does this work with versioning? This config will probably go through a few more iterations as it grows.

Also, I don't believe that the schema works for JS, only JSON. 

Instead, you can add a comment above your config, which works in VSCode and any TS-enabled editors (even if you are just using JS):

```diff
+/** @type {import("snowpack").SnowpackUserConfig } */
export default {
  plugins: [
    /* ... */
  ],
};
```

**Comment by jasikpark** [comment]
:0 true I totally forgot that this is meant for `json` and that we don't use `json` whoops

**Comment by jasikpark** [comment]
Maybe an RFC for adding that line to the examples? 🤔 Probably not though...
