### ISSUE TITLE
🐛 BUG: `snowpack.config.mjs` is referred to as `snowpack.config.js` but complains if you use a regular js file

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro#766]
### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

If you follow the reccomendation of using `snowpack.config.js` for your config, Snowpack will complain at you, saying that ESM exports are not allowed in a regular js file.

I think just searching a replacing the `snowpack.config.js` -> `snowpack.config.mjs` would be a good fix, unless `snowpack.config.js` is meant to work.

### Steps to Reproduce

1. `npm init astro`
2. Add a `snowpack.config.js` file at the root.
3. `npm start`
4. Warning!

**Comment by jasikpark** [comment]
<details><summary>Screenshot of error:
<pre>
Failed to load "/Users/calebjasik/Github/astro/docs/snowpack.config.js"!
ESM format is not natively supported in "node@v16.5.0".
Please use CommonJS or upgrade to an LTS version of node above "node@12.17.0".
</pre>
etc...
</summary>
 <img width="860" alt="image" src="https://user-images.githubusercontent.com/10626596/126250292-68142108-4259-4b1e-ad6a-ba14302f2500.png">
</details>

I can get this error by changing `astro/docs/snowpack.config.mjs` to `astro/docs/snowpack.config.js`

**Comment by FredKSchott** [comment]
I think the `set type: module` note in that error message is correct, based on Node.js behavior. I think this is behaving as expected. I'll do a quick PR to update `snowpack.config.js` to `snowpack.config.mjs` in the docs.

**Comment by FredKSchott** [comment]
Fixed: 225baf1

**Comment by jasikpark** [comment]
This is also needed elsewhere in the `astro` package btw! I'll see if I can make a PR at some point...

**Comment by FredKSchott** [comment]
Thanks!

**Comment by FredKSchott** [comment]
I believe that this has been fixed, but happy to reopen if you see any more references to `astro.config.js` or `snowpack.config.js`

**Comment by jasikpark** [comment]
Is `snowpack.config.json` valid? I've seen that in the docs and such...

**Comment by jasikpark** [comment]
Ah it looks like all of those references are in `examples/snowpackjs` so they shouldn't be too much of a problem...
https://github.com/snowpackjs/astro/blob/3b51f4b5e21a1ae1a49826664a525d6b3ee49aea/examples/snowpack/src/pages/posts/2020-05-26-snowpack-2-0-release.md#L78-L78

```markdown
snowpack.config.json
```

**Comment by FredKSchott** [comment]
Right, and that's just a test fixture at this point / its documentation for snowpack.dev. Should still be good to close
