### ISSUE TITLE
📘 DOC: There is little issue with the scroll on https://astro.build/ , it doesn't work on clicking the scrollbar

### ISSUE THREAD

**Issue by shubhamsoni2617** [snowpackjs/astro#777]
### Background & Motivation

NA

### Possible solutions

The first div inside the body has position fixed and width is 10vw, so it's overlapping the scrollbar. I am not sure if this a feature to keep the UI this way such the planet animates from right end of the screen. In case if this is not intended, we can make the width as 98vw which will fix the issue.

### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
Sorry, I'm not sure that I'm following. Can you give a link to where you're seeing this and a screenshot?

**Comment by markpinero** [comment]
When you enable `Show scroll bars` in System Preferences, you can't click on the scrollbar to scroll up or down. This is an issue with `.space` since it's `width: 100vw`, it overlaps the scrollbar. You can add `pointer-events: none` to fix this.

**Comment by jasikpark** [comment]
I believe this was fixed, though I can't find the pertinent pr - lmk if I'm wrong to close this!
