### ISSUE TITLE
💡 RFC: Custom CSS Prefixes

### ISSUE THREAD

**Issue by markpinero** [snowpackjs/astro#787]
### Background & Motivation

Since Astro is supposed to be "webby," I think we should have more control over our outputs. Every scoped class gets printed as `astro-********` and we should add an option for project-based customizations for it like `project-********`.

### Possible solutions

add to `buildOptions` a `cssPrefix` key value to replace the existing CSS prefix.

eg:
```
{
  buildOptions: {
    cssPrefix: 'project'
  }
}
```

### Open Questions

I have a branch with the proposed changes but don't know how to handle testing for this. As well as validating the string used.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
I'm -1 on this change, or at least I don't understand what problem this solves / what you mean by "webby" 

FYI Svelte has similar support and as far as I know only supports the "svelte-" prefix (you can see it here by going to the "CSS Output" tab: https://svelte.dev/repl/aff6159730694c7eb6e768093073a693?version=3.38.3)

**Comment by markpinero** [comment]
I guess my intention is to have full control of the output.

I know in Eleventy, there are some that take pride in the fact you can't tell at they're using Eleventy. And with Nuxt, you're able to change the global name.

**Comment by FredKSchott** [comment]
I think we'll hold off for now, The benefit to users is unclear and we have a lot of high-priority things to get to before v1.0. Post v1.0, I'd be open to revisiting.

**Comment by arimgibson** [comment]
I personally see this feature as being useful for performance aspects, as those longer class names could add a significant amount to a website's bundle size. Being able to set a much smaller class name would reduce the negatives associated with this tradeoff

**Comment by jylin** [comment]
General minimalism is another argument for supporting this.

**Comment by arimgibson** [comment]
Hehe @jylin submitting right after they hit v1.0.0 😛 depending on my capacity, I could probably PR this within a couple weeks with your approval @FredKSchott (if that takes some burden off you)

**Comment by timfee** [comment]
I was just looking at the docs to see if this function existed, +1!

**Comment by arimgibson** [comment]
Looks like this conversation has been migrated to this recent discussion ☺️

https://github.com/withastro/rfcs/discussions/243
