### ISSUE TITLE
💡 RFC: Command Line argument for specifying `site`

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro#788]
### Background & Motivation

I want to be able to specify what the base URL of my astro site is at build invocation, so that I can for example run:

```shell
yarn build --site $DEPLOY_PRIME_URL
```

on Netlify and get a site that has all of the tags that require fully-qualified URLs built correctly.

### Possible solutions
Allow the `--site` argument to override the setting in `astro.config.mjs`
### Help make it happen!

- [X] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by FredKSchott** [comment]
+1, this use-case makes sense to me
