### ISSUE TITLE
📘 DOC: Add community plugins

### ISSUE THREAD

**Issue by rebelchris** [snowpackjs/astro#798]
It would be cool to have a reference on the [plugin](https://docs.astro.build/guides/publish-to-npm) page where it links to community build plugins.

Will make a start on adding this in my own fork and open a PR.

**Comment by jasikpark** [comment]
Wouldn't those be community components, not plugins?

**Comment by rebelchris** [comment]
@jasikpark You're right

Also added a PR for this:
https://github.com/snowpackjs/astro/pull/799

Let me know what you guys think.

**Comment by FredKSchott** [comment]
Fixed in #799
