### ISSUE TITLE
💡 RFC: SSR

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#80]
Our current intention is to launch Astro as a static site builder. That means all pages are built to static HTML, and no support for dynamic server-side routes. 

But, there seems to be a lot of community interest in supporting dynamic routes & pages. If there's enough interest and anyone willing to help us with an implementation, then I'd love to start putting together an RFC for experimental support. If we put this behind an experimental flag to start, then I don't think it interferes with our "static site builder" launch story.

Anyone interested in helping spec out an RFC? 

#### Some pieces that need discussion / fleshing out:
- Dynamic pages: can we borrow from Next.js's file based routing? `/pages/[id].js`, `/pages/[...id].ks`, etc.
- Dynamic props: how does a page register as dynamic? Something like `getServerSideProps`?
- Deploy targets: In addition to a Node.js server deployment, I really want us to have a good Cloudflare Workers story. SvelteKit too the approach of having different "adapters" for Node, Deno, etc. Could we do the same?

**Comment by philippe-elsass-deltatre** [comment]
I would like to +1 here that, as with many SSR solutions, routing is again "static":

- How do I make a multilingual website with translated routes?
- can I bring my own routing logic? our projects use a dynamic routing mapping logic that we load server-side and client-side

**Comment by rebelchris** [comment]
+1 from my side, I realised this actually works on dev build.
So I would indeed think it could work something like Next.js JIT rendering?

I think all we would need is the params variable not?

file: `$tweets.astro`
builds: tweets/:tweet (singular)?
on page: $tweet is the ID?

I would hope there we can use this dynamic ID as a JIT rendering to retrieve some API details.

**Comment by askeyt** [comment]
Hi all,

Very new to Astro and apologies if this is not the right place for this. But bear with me and please consider the following:

```astro
---
// $pages.astro
export async function createCollection() {

  // Flattened page list
  const items = [
    {
      name: 'My Title',
      slug: 'my-title',
      fullSlug: 'my-title',
    },
    {
      name: 'My Child',
      slug: 'my-child',
      fullSlug: 'my-title/my-child',
    },
    {
      name: 'My Child 2',
      slug: 'my-child-2',
      fullSlug: 'my-title/my-child-2',
    },
  ];

  return {
    route: `/pages/:fullSlug`,
    paths() {
      return items.map((page, i) => ({params: {fullSlug: page.fullSlug}}));
    },
    async props({ params }) {
      return {item: items.find((page) => page.fullSlug === params.fullSlug)};
    },
  };
}
const {item} = Astro.props;
---
```

1. `http://localhost:3000/pages/my-title` works :)
2. `http://localhost:3000/pages/my-title/my-child` doesn't work :(

The error I get for 2 is:

`Error: [createCollection] route pattern does not match request: "/pages/:fullSlug". (/pages/my-title/my-child)`

Now, coming from a Vue background which uses `path-to-regexp` (as do you?).. I tried changing the returned `route` property in `createCollection` to `route: /pages/:fullSlug+` (see here: https://github.com/pillarjs/path-to-regexp/tree/v1.7.0#one-or-more)

Now I get the following error:

`TypeError: Expected "fullSlug" to match "[^\/#\?]+?", but got "my-title/my-child"`

**Now for the reason of my post** 

By extending the behaviour of the `route` param to follow all the rules of path-to-regexp, does this not solve the problem of "dynamic routing" ? Everything comes down to mapping the collections and the props with the route.

There would need to be rules around which takes precedence, static files vs regex patterns, and I'm sure I'm not taking into account a lot of things – but no one has mentioned this here yet and I thought it was worth doing so.

**Comment by matthewp** [comment]
This is out! https://docs.astro.build/core-concepts/routing#dynamic-routes Closing

**Comment by FredKSchott** [comment]
I got confused by this too! But I think this issue was originally designed to track what we now just call SSR. Reopening to keep gathering feedback

**Comment by askeyt** [comment]
> This is out! https://docs.astro.build/core-concepts/routing#dynamic-routes Closing

This sorts me out! Thanks

**Comment by CEbbinghaus** [comment]
This would be a wonderful feature. Ideally allowing for things like Catchall Routes that result in an Error404 page and allowing for content to update dynamically as it gets added.

> What's the reason for compiling a static page to HTML? Perf? As we've discussed previously, if we change the compilation to strings we're talking about a "dynamic" page module for a static page as being something like this:
> 
> ```js
> function __render() {
>   return "<html><head><title>My app</title></head><body><h1>My app</h1></body><html>"
> }
> ```
> 
> You can't get much better than that in terms of perf. So if that's the reason I don't think it's worth the added complexity of having 2 different modes and forcing the user to decorate their pages (which they might do incorrectly).

I feel like this or something akin to it would be a great compromise. Having half static and half dynamic pages would require whatever SSR code is running to do additional checks when having to retrieve static content.

I think Astro and in particular, `.astro` files lend themselves uniquely to SSR being logically split into the "build" and "render" steps. Allowing the "build" step to happen when the request fires with top-level await would make for some very elegant solutions to pathing and similar.

**Comment by tbeseda** [comment]
**Wild idea:** what if Astro wasn't a full server framework? Not all of one, anyway. Just[^1] make it mountable in existing frameworks. 

If Astro's runtime could be mounted, it wouldn't need to worry about higher level routing, middleware (like auth), static assets (including .html pages generated by Astro at build time), sessions, etc. Astro's theoretical server runtime could accept the standard request/response args and return HTML

Astro would exist somewhere between a full web framework and a view engine. It could "route" the request in that Astro would pick which `.astro` file to load up and render. But it would do this after the framework in charge has already handled the rest.

**Hypothetical:** "ΛstroLive"
I set up my main `server.js` with the framework du jour. The framework parses the request, auths the user, populates the session from the db, etc. Then it also mounts ΛstroLive: `myApp.use('/app', Astro.live('./path-to/astro-views', options))`[^2]
Now I can write most of the fun parts of my app in Astro files! They have access to the original request object with things like session already populated by my framework. And the Astro files always return HTML.

I have no idea how this works for things like partial hydration. But Astro could be responsible for setting up internal paths for those resources at the root I set in the framework (`/app` in the example above).

A key advantage, aside from not having to build and maintain a full JS web framework: it would be great for serverless.

🤔 Maybe this is a separate idea. or a convenient half way step to the ultimate goal.[^3]

[^4]

[^1]: I say "Just", but I realize it's still a huge effort.
[^2]: I made up `Λ.live()` -- but I bet there's a cool space-y name someone more clever than I can come up with.
[^3]: If this is not in line with the goals of Astro, I won't mind. just something I've been thinking about.
[^4]: [GitHub Markdown footnotes](https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/) are awesome, btw.

**Comment by jasikpark** [comment]
> **Wild idea:** what if Astro wasn't a full server framework? Not all of one, anyway. Just[^1] make it mountable in existing frameworks. 
> 
> 
> 
> If Astro's runtime could be mounted, it wouldn't need to worry about higher level routing, middleware (like auth), static assets (including .html pages generated by Astro at build time), sessions, etc. Astro's theoretical server runtime could accept the standard request/response args and return HTML
> 
> 
> 
> Astro would exist somewhere between a full web framework and a view engine. It could "route" the request in that Astro would pick which `.astro` file to load up and render. But it would do this after the framework in charge has already handled the rest.
> 
> 
> 
> **Hypothetical:** "ΛstroLive"
> 
> I set up my main `server.js` with the framework du jour. The framework parses the request, auths the user, populates the session from the db, etc. Then it also mounts ΛstroLive: `myApp.use('/app', Astro.live('./path-to/astro-views', options))`[^2]
> 
> Now I can write most of the fun parts of my app in Astro files! They have access to the original request object with things like session already populated by my framework. And the Astro files always return HTML.
> 
> 
> 
> I have no idea how this works for things like partial hydration. But Astro could be responsible for setting up internal paths for those resources at the root I set in the framework (`/app` in the example above).
> 
> 
> 
> A key advantage, aside from not having to build and maintain a full JS web framework: it would be great for serverless.
> 
> 
> 
> 🤔 Maybe this is a separate idea. or a convenient half way step to the ultimate goal.[^3]
> 
> 
> 
> [^4]
> 
> 
> 
> [^1]: I say "Just", but I realize it's still a huge effort.
> 
> [^2]: I made up `Λ.live()` -- but I bet there's a cool space-y name someone more clever than I can come up with.
> 
> [^3]: If this is not in line with the goals of Astro, I won't mind. just something I've been thinking about.
> 
> [^4]: [GitHub Markdown footnotes](https://github.blog/changelog/2021-09-30-footnotes-now-supported-in-markdown-fields/) are awesome, btw.

So something with the similar energy of https://tokio.rs/blog/2021-07-announcing-axum where all the middleware is just express or ember or something?

**Comment by may17** [comment]
@chriscalo see here https://docs.astro.build/de/guides/server-side-rendering/
