### ISSUE TITLE
🐛 BUG: Remark should generate unique header id's

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro#805]
### What package manager are you using?

yarn

### What operating system are you using?

Mac

### Describe the Bug

When you have two sections with the same titles, they get the same element id, but that is not permitted in HTML and also breaks links as well.

This also breaks the table of content links on the docs site.

### Steps to Reproduce

1. Look at the header id's at https://docs.astro.build/comparing-astro-vs-other-tools

**Comment by mmarkelov** [comment]
@jasikpark @FredKSchott shouldn't we add [remark-slug](https://github.com/remarkjs/remark-slug) to handle it?
