### ISSUE TITLE
📘 DOC: 'touch .nojekyll' in deploy.sh for github pages

### ISSUE THREAD

**Issue by danny-burrows** [snowpackjs/astro#816]
Sorry in advance if I break any conventions, this is my first time opening an issue on a big project.

In the Github Pages section of [Deploy a Website](https://docs.astro.build/guides/deploy) I wondered if it would be possible to add `touch .nojekyll` to deploy.sh under `cd dist` as I've found that `npm run build` doesn't pull through the .nojekyll file from /public. 

I hope this helps. Thank you for your time.

**Comment by FredKSchott** [comment]
Done in #819
