### ISSUE TITLE
🐛 BUG: Lit Web Component Example Not Running

### ISSUE THREAD

**Issue by jaydanurwin** [snowpackjs/astro#825]
### What package manager are you using?

npm

### What operating system are you using?

Linux Pop! OS

### Describe the Bug

I tried setting up a demo project using the Lit example (https://github.com/snowpackjs/astro/tree/main/examples/framework-lit) and I'm running into 2 issues, 1 is easily fixable. The dependency for @astrojs/renderer-lit is missing from `package.json` so it errors out right away. I installed the renderer but now I'm getting the error below. I know this is a brand new renderer just by looking at the code but it seems like this is supposed to be an officially supported use case for Astro so I figured I'd file an issue.

```
Error: Cannot find module ''@webcomponents/template-shadowroot/template-shadowroot.js'' from '[project-directory]/astro-lit/node_modules/@astrojs/renderer-lit/client-shim.js'
```

### Steps to Reproduce

1. `npm init astro -- --template framework-lit`
2. `npm i`
3. `npm start`
4. Error that @astrojs/renderer-lit is missing
5. `npm i @astrojs/renderer-lit`
6. `npm start`
7. Error below

```
Error: Cannot find module ''@webcomponents/template-shadowroot/template-shadowroot.js'' from '[project-directory]/astro-lit/node_modules/@astrojs/renderer-lit/client-shim.js'
```

**Comment by FredKSchott** [comment]
I'm actually getting a different error trying to run this: `ReferenceError: Cannot access 'LitElementRenderer' before initialization`

@matthewp mind taking a look at this?

**Comment by FredKSchott** [comment]
FYI solving the missing render dependency in #826

**Comment by jasikpark** [comment]
This should be sorted now that #826 is merged, right?

**Comment by FredKSchott** [comment]
Yes! I can no longer reproduce on `next` versions of astro. Made a quick fix to the package.jsons just to get those working: 353bc89f. Should be safe to close now

**Comment by jaydanurwin** [comment]
Wow, super impressed to see this closed in less than 24 hours! Now I don't have any excuses to wait to test Astro out. Keep up the good work!

**Comment by matthewp** [comment]
@jaydanurwin I also created another Lit demo which you can see here: https://github.com/matthewp/astro-lit-demo
