### ISSUE TITLE
🐛 BUG: Nesting Vue components is not working 

### ISSUE THREAD

**Issue by Igloczek** [snowpackjs/astro#828]
### What package manager are you using?

yarn and npm

### What operating system are you using?

Mac

### Describe the Bug

While trying to nest Vue components, in consoe it prints `[Vue warn]: resolveComponent can only be used in render() or setup().` followed by error 500 `TypeError: Invalid value used as weak map key`

I narrowed down the problem to a single function, that in Snowpack environment behaves differently than in for example Vite (and others where SSR works properly), which was my reference setup for debugging.

Vue SSR process is using the [`renderComponentSubTree` ](https://github.com/vuejs/vue-next/blob/1c7f5d3fce9a8bad5b023fea99915b6b3d25ec4d/packages/server-renderer/src/render.ts#L108) function, that utilizes the [`setCurrentRenderingInstance` ](https://github.com/vuejs/vue-next/blob/1c7f5d3fce9a8bad5b023fea99915b6b3d25ec4d/packages/server-renderer/src/render.ts#L164) method that comes from [`ssrUtils`](https://github.com/vuejs/vue-next/blob/1c7f5d3fce9a8bad5b023fea99915b6b3d25ec4d/packages/server-renderer/src/render.ts#L31-L37) that comes from [`vue`](https://github.com/vuejs/vue-next/blob/1c7f5d3fce9a8bad5b023fea99915b6b3d25ec4d/packages/server-renderer/src/render.ts#L8) package, precisely a [`runtime-core`](https://github.com/vuejs/vue-next/blob/4e3f82f6835472650741896e19fbdc116d86d1eb/packages/runtime-core/src/index.ts#L283) part of it.

The problem is that calling that method in Snowpack compiled code, does not properly set the underlying [`currentRenderingInstance` ](https://github.com/vuejs/vue-next/blob/4e3f82f6835472650741896e19fbdc116d86d1eb/packages/runtime-core/src/componentRenderContext.ts#L9) value, because this code is not a singleton, depends on a initiator it runs from `node_modules/@vue/runtime-core/dist/runtime-core.cjs.js` or `node_modules/.cache/snowpack/build/@vue/runtime-core@3.1.5/@vue/runtime-core.js`, and it works only if expect to this value be empty, so only if there is just one component.

So the question is, how to prevent Snowpack from coping the Vue stuff to `node_modules/.cache` or how to adjust Vue, to not break when Snowpack copies that stuff. But...it works everywhere but there, so I guess it should be addressed in Snowpack/Astro first.

<details>
<summary>Full stack trace</summary>
<pre><code>
[Vue warn]: resolveComponent can only be used in render() or setup().
TypeError: Invalid value used as weak map key
    at WeakMap.set (<anonymous>)
    at normalizePropsOptions (/Users/igloczek/Sites/temp/astro-vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:3580:15)
    at createComponentInstance (/Users/igloczek/Sites/temp/astro-vue/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:6973:23)
    at renderComponentVNode (/Users/igloczek/Sites/temp/astro-vue/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:184:22)
    at Object.ssrRenderComponent (/Users/igloczek/Sites/temp/astro-vue/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:520:12)
    at ssrRender (/_astro/src/components/Counter.vue.js:31:19)
    at renderComponentSubTree (/Users/igloczek/Sites/temp/astro-vue/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:250:13)
    at renderComponentVNode (/Users/igloczek/Sites/temp/astro-vue/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:201:16)
    at renderVNode (/Users/igloczek/Sites/temp/astro-vue/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:291:22)
    at renderComponentSubTree (/Users/igloczek/Sites/temp/astro-vue/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:256:13)
    at renderComponentVNode (/Users/igloczek/Sites/temp/astro-vue/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:201:16)
    at Object.<anonymous> (/Users/igloczek/Sites/temp/astro-vue/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:443:30)
    at Generator.next (<anonymous>)
    at /Users/igloczek/Sites/temp/astro-vue/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/igloczek/Sites/temp/astro-vue/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:27:12)
    at Object.renderToString (/Users/igloczek/Sites/temp/astro-vue/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:433:12)
    at Object.renderToStaticMarkup (/_snowpack/pkg/@astrojs.renderer-vue.server.v0.1.3.js:13:32)
    at eval (/_snowpack/pkg/astro.dist.internal.__astro_component.v0.17.3.js:189:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
</code></pre>
</details>

### Steps to Reproduce

I've prepared a slightly modified version of [the official example](https://github.com/snowpackjs/astro/tree/main/examples/framework-vue). Instead of using slot and passing text from `index.astro`, it's importing a Vue component with text inside the `Counter.vue`.

If you comment out line 8 of `src/components/Counter.vue` error will be gone.

### Link to Minimal Reproducible Example (Optional)

https://github.com/Igloczek/astro-vue-nested-components

**Comment by Igloczek** [comment]
I just slightly updated the description, because missed the part with `Vue warn`.

**Comment by Igloczek** [comment]
After some investigation, I guess I got to the point where I understand the issue, but don't know where to fix it in Astro.

https://github.com/snowpackjs/astro/blob/main/packages/renderers/renderer-vue/server.js#L9 the `Component` prop, which is an object, come there with `components` object, and `ssrRender` function, with is causing the issue, because instead of using components passed in `components` object, it calls `resolveComponent` method from Vue, which is looking for globally registered components, which not exist and this is where the error is thrown.

So right now we have:

```js
    components: { child },
    ssrRender: (ctx, push, parent, attrs) => {
      const childComponent = resolveComponent('child')
      push('<div>A parent')
      push(ssrRenderComponent(childComponent))
      push('</div>')
    }
```

but we need

```js
    components: { child },
    ssrRender: (ctx, push, parent, attrs) => {
      push('<div>A parent')
      push(ssrRenderComponent(child))
      push('</div>')
    }
```

**Comment by Igloczek** [comment]
I narrowed down the problem to a single function, that in Snowpack environment behaves differently than in for example Vite (and others where SSR works properly), which was my reference setup for debugging.

Vue SSR process is using the [`renderComponentSubTree` ](https://github.com/vuejs/vue-next/blob/1c7f5d3fce9a8bad5b023fea99915b6b3d25ec4d/packages/server-renderer/src/render.ts#L108) function, that utilizes the [`setCurrentRenderingInstance` ](https://github.com/vuejs/vue-next/blob/1c7f5d3fce9a8bad5b023fea99915b6b3d25ec4d/packages/server-renderer/src/render.ts#L164) method that comes from `ssrUtils`(https://github.com/vuejs/vue-next/blob/1c7f5d3fce9a8bad5b023fea99915b6b3d25ec4d/packages/server-renderer/src/render.ts#L31-L37) that comes from [`vue`](https://github.com/vuejs/vue-next/blob/1c7f5d3fce9a8bad5b023fea99915b6b3d25ec4d/packages/server-renderer/src/render.ts#L8) package, precisely a [`runtime-core`](https://github.com/vuejs/vue-next/blob/4e3f82f6835472650741896e19fbdc116d86d1eb/packages/runtime-core/src/index.ts#L283) part of it.

The problem is that calling that metod in Snowpack compiled code, does not properly set the underlying [`currentRenderingInstance` ](https://github.com/vuejs/vue-next/blob/4e3f82f6835472650741896e19fbdc116d86d1eb/packages/runtime-core/src/componentRenderContext.ts#L9) value, and the rendering process fails, because it is lacking the rendering context.

My hypothesis is that due to `setCurrentRenderingInstance`, nor `ssrUtils` not being a directly included into `vue` package, there is some ES Modules specific config missing, and due to that Snowpack can't statically analyze those imports properly, and fails to compile them in a same way as other tools.

**Comment by matthewp** [comment]
Thanks so much for working on this @Igloczek! Is this the same as #182 then?

**Comment by matthewp** [comment]
Fixed in https://github.com/snowpackjs/astro/pull/858
