### ISSUE TITLE
🐛 BUG: relative pathing deployment

### ISSUE THREAD

**Issue by FriendlyUser** [snowpackjs/astro#833]
### What package manager are you using?

npm

### What operating system are you using?

Windows

### Describe the Bug

I want to deploy the astro site to https://friendlyuser.github.io/astro-blog/

`/astro-blog`

I cannot figure how to deploy to the astro site to `/astro-blog` 

### Steps to Reproduce

1. `npm init astro` using template preact
2. attempt to deploy to github pages subdirectory `/astro-blog`

### Link to Minimal Reproducible Example (Optional)

https://github.com/FriendlyUser/astro-blog

**Comment by FredKSchott** [comment]
Does editing `buildOptions.site` in your `astro.config.js` file work?

**Comment by FriendlyUser** [comment]
I tried adding buildOptions.site in the astro.config.mjs file, didn't seem to fix the issue.

**Comment by FredKSchott** [comment]
Interesting! Okay, Someone should take a look at your repo and attempt to reproduce

**Comment by simonwiles** [comment]
Same problem here -- seems to be a duplicate of #688 ?

**Comment by matthewp** [comment]
Fix in #856
