### ISSUE TITLE
🐛 BUG:  zlib: unexpected end of file

### ISSUE THREAD

**Issue by dlakhiani** [snowpackjs/astro#835]
### What package manager are you using?

npm 

### What operating system are you using?

WSL (Debian 10)

### Describe the Bug

after ```npm init astro```, when asked what framework I would like to use (I chose React), it begins copying project files and then ends abruptly with -- 
**zlib: unexpected end of file**

I am using npm v14.13.1

![image](https://user-images.githubusercontent.com/68260043/126821346-e7e8740d-cc39-4261-92a6-a2402eac7a6d.png)

### Steps to Reproduce

1. `npm init astro` using template <NAME>
2. Starter Kit (Generic)
3. React
4. Error! zlib: unexpected end of file, expected it to just build the dir

**Comment by Mravuri96** [comment]
Solved in #655

**Comment by FredKSchott** [comment]
You know what, we can actually help with this on our end:
- add a catch for errors in debit and look for this specific error 
- console.log a warning that includes the code snippet to clear your cache + a link to the issue/comment Nate mentioned.

Leaving this issue open to represent that fix. Would love if someone could help with a PR here!

**Comment by matthewp** [comment]
Fixed in #889
