### ISSUE TITLE
🐛 BUG: Pages with a certain name can not be found

### ISSUE THREAD

**Issue by fools-mate** [snowpackjs/astro#840]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

I've run into a strange bug that sometimes certain namings cause Astro to not be able to find them. But it also seems that my folder structure plays a big role.

Strangely enough, as soon as I remove just one letter from the name or a folder, it works. It also works if I create an extra folder and rename the md/astro file to index.md/astro.

### Steps to Reproduce

1. clone the repo
2. check out the index page '/projects/graphic-design'
3. try out the links

### Link to Minimal Reproducible Example (Optional)

https://github.com/fools-mate/astro-bug

**Comment by FredKSchott** [comment]
Can you try this with the latest `npm install astro@next`? We improved the search algorithm a bit and may have fixed this bug for you already

**Comment by fools-mate** [comment]
Sorry, I forgot to mention that I already have astro@next installed.

**Comment by matthewp** [comment]
Thanks @fools-mate, do you see this issue in dev or only in the build output?

**Comment by fools-mate** [comment]
Ok, I have checked it. This only appears in the 'dev' output.

**Comment by FredKSchott** [comment]
Thanks for the report! We believe that this has been fixed in astro v0.21, going out today. Let us know if you can still reproduce the issue after updating to v0.21 and we'll be happy to take a look.
