### ISSUE TITLE
📘 DOC: Search in docs?

### ISSUE THREAD

**Issue by zvikasdongre** [snowpackjs/astro#841]
### Background & Motivation

The docs are great and simple. But it doesn't have is a `search` functionality, however this is not a big deal but by not having it makes finding things a little more time consuming. It would be nice to have something like that.

### Possible solutions
Maybe we can use something like algolia or something that other sites implemented?

Thanks.

**Comment by jasikpark** [comment]
One option that I was interested in looking into for search was https://stork-search.net/ which is a statically generated search that runs based off an index generated from your pages + a WASM search script

**Comment by jasikpark** [comment]
https://diff.wikimedia.org/2010/06/15/usability-why-did-we-move-the-search-box/ Is a pretty good casestudy for search!

**Comment by tony-sull** [comment]
Algolia is another pretty common option for search on static sites

11ty's doc site actually just opens a new tab with a DuckDuckGo search, but thats always felt a little wrong to me for some reason 😁

**Comment by jasikpark** [comment]
> Algolia is another pretty common option for search on static sites
> 
> 11ty's doc site actually just opens a new tab with a DuckDuckGo search, but thats always felt a little wrong to me for some reason 😁

Algolia definitely seems pretty solid, I think if I remember to I'm gonna try and see how hard it'd be to setup Stork just cause I'm interested in it, even if it's not the right choice for these docs 😆

**Comment by zvikasdongre** [comment]
In my opinion algolia will fit the best in the docs, see [Doks](https://getdoks.org/docs/prologue/introduction/) generated by a static side generator. There search is also powered by algolia.

**Comment by zvikasdongre** [comment]
Or [Flexsearch](https://github.com/nextapps-de/flexsearch) can be a better alternative.

**Comment by FredKSchott** [comment]
I'd like to stick with Algolia. We could borrow almost all of the code from https://www.snowpack.dev/ and we already have a relationship with them to get us added to the free open-source plan.

**Comment by zvikasdongre** [comment]
## 🎉🥳 You guys did it!! 🥳🎉

Thank y'all for making this possible, And taking this request seriously. 

Thanks again, have a great day!
