### ISSUE TITLE
🐛 BUG: two instances of the same React component taking different props on an .astro page both render with the same props

### ISSUE THREAD

**Issue by sarah11918** [snowpackjs/astro#844]
### What package manager are you using?

npm (on CodeSandbox)

### What operating system are you using?

ChromeOS

### Describe the Bug

Two separate instances of a component (each with different props) that displays a user's most recent tweet on the same Astro page end up rendering two individual tweet displays (as expected) however they are both of the same (second) user (unexpected). 

(NB: When the HTML is inspected, both components' astro-root uid are identical.)

### Steps to Reproduce

1. install react-twitter-widgets
2. Create a React component that accepts props.
eg:
`import React from "react";
import { Timeline } from "react-twitter-widgets";

const RecentTweet = ({ user }) => (
  <>
    <div className="tweet">
      <Timeline
        dataSource={{
          sourceType: "profile",
          screenName: user
        }}
        options={{
          width: "100",
          tweetLimit: "1"
        }}
      />
    </div>
  </>
);

export default RecentTweet;`

2. on an Astro page, import, render multiple instances of that component, using different props for each component
eg 
`
<RecentTweet user="user1" client:load />
<RecentTweet user="user2" client:load />
`
3. Error! Instead of the .astro page rendering two different Tweets, one from each user... two identical Tweets are rendered, both from user2's Twitter profile.

![Screenshot 2021-07-24 18 15 20](https://user-images.githubusercontent.com/5098874/126882618-b7690323-2b89-4584-b088-4d53cf8eafda.png)

![Screenshot 2021-07-24 19 11 06](https://user-images.githubusercontent.com/5098874/126882722-833b2fee-df6e-4774-a414-d66dc173d77e.png)

**Comment by matthewp** [comment]
Thanks, someone submitted a fix in #846.

**Comment by Kilian** [comment]
I'm currently running into this issues with Astro 0.22.2 on this site: https://tender-carson-79d420.netlify.app/ the three tickers on this page all get instantiated with different props, yet they all end up with the same uid and props (According to the react dev tools)

Is this fix in Astro 0.22.2?
