### ISSUE TITLE
🐛 BUG: All content copied to all slots

### ISSUE THREAD

**Issue by johnhenry** [snowpackjs/astro#849]
### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

When using multiple slots within a componens, rather that forwarding components to specific named slots,
all content is copied to all available slots.

(Version: 0.17.3)

### Steps to Reproduce

1.  Clone repository [here](https://github.com/johnhenry/astro-issue-slots).
2.  Install and build (`npm install && npm run build`).
3. Error! Content from component appears 3 times within `dist/actual/index.html`. (As opposed to once within `dist/expected.htm`.)

### Link to Minimal Reproducible Example (Optional)

https://github.com/johnhenry/astro-issue-slots

**Comment by FredKSchott** [comment]
@matthewp can you take a look at this?

**Comment by taniki** [comment]
I ran into the same issue. I figured out that named slots are a `0.18` feature. I rembember that being written in the documentation but it is not anymore.

**Comment by taniki** [comment]
cf https://github.com/snowpackjs/astro/pull/661

**Comment by matthewp** [comment]
Yep, this feature is only available by installing `next`. Please try using 0.18-next and let us know if you still have the problem and we can reopen @johnhenry
