### ISSUE TITLE
🐛 BUG: `lang="sass"` on a <style> uses `scss` istead

### ISSUE THREAD

**Issue by Tc-001** [snowpackjs/astro#851]
### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Docs give an example of using both `sass` and `scss`
>👓 Sass
>Astro also supports Sass out-of-the-box. To enable for each framework:
 >> Astro: <style lang="scss"> or <style lang="sass">

https://docs.astro.build/guides/styling#frameworks-and-libraries

But Astro uses `scss` to compile in both cases (even if told to use `sass`)

### Steps to Reproduce

1. `npm init astro` using template `Starter Kit (Generic)`
2. Replace `index.astro` with:
```html
<head>
    <style lang="sass">
        span
            color: red
    </style>
</head>
<body>
    <span>Test</span>
</body>
```
3. Run `npm start`
4.  Observe error:
```
Error: expected "{".
  ╷
3 │             color: red
  │                       ^
  ╵
  stdin 3:23  root stylesheet
````

5. Format it like an `scss` stylesheet (keeping lang as `sass`):
```html
<head>
    <style lang="sass">
        span {
            color: red;
        }
    </style>
</head>
<body>
    <span>Test</span>
</body>
```
6. See it working without any issues

**Comment by Tc-001** [comment]
It seems that I have found the issue
https://github.com/snowpackjs/astro/blob/84e8779faab399022eac64847cc6fe25c717fc3e/packages/astro/src/compiler/transform/styles.ts#L110-L114
Both `sass` and `scss` use the same compile function, but for `sass` to compile correctly, [indentedSyntax](https://github.com/sass/node-sass#indentedsyntax) needs to be set true.

I will probably open a pull request later today if the fix doesn't break anything else

**Comment by matthewp** [comment]
I'm not sure if we intended to support sass as isn't it deprecated? Pinging @drwpow who worked on this part.

**Comment by Tc-001** [comment]
I believe you are talking about https://www.npmjs.com/package/node-sass. 

It was deprecated in favor of https://www.npmjs.com/package/sass (dart-sass), which is maintained and used by Astro.

**Comment by drwpow** [comment]
@Tc-001 is correct, and this is a bug! Yes we should be passing `indentedSyntax` for `lang="sass"`. And also it is not deprecated 🙂
