### ISSUE TITLE
📘 DOC: Homepage - broken scrollbar 

### ISSUE THREAD

**Issue by RyanFarrah67** [snowpackjs/astro#852]
Hi,

in the homepage of the Astro website : https://astro.build/, the scrollbar can't be selected to move the bar inside it and therefore scroll the page by this way. The other ways of scrolling work well.

Tested under Google Chrome 92 and Firefox 90 on Windows 10.

**Comment by FredKSchott** [comment]
Thanks! I think I fixed this with 84e8779f

**Comment by RyanFarrah67** [comment]
Yes, it works now with the the same 2 browsers.
