### ISSUE TITLE
💡 RFC: Allow dev port to be set via environment variable

### ISSUE THREAD

**Issue by stramel** [snowpackjs/astro#872]
### Background & Motivation

This is stemming from a conversation on adding Astro as a supported framework on Vercel. 
https://github.com/vercel/vercel/pull/6477#discussion_r676880529

### Possible solutions
Allow the use of the `$PORT` environment variable to dictate the dev port.
`PORT=3200 astro dev`

### Alternatives considered
Utilize the current workaround by passing the CLI flag,
`PORT=3200 astro dev --port $PORT`

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by matthewp** [comment]
Sounds reasonable 👍

**Comment by jasikpark** [comment]
This could be solve similarly to PR https://github.com/snowpackjs/astro/pull/838 which added `--site` for a similar reason of wanting Netlify Deploy Previews to work

**Comment by jasikpark** [comment]
Oh wait I'm wrong ig.. does it make sense to also overload the site config like that or no?
