### ISSUE TITLE
📘 DOC: Missing docs on environment variable usages

### ISSUE THREAD

**Issue by stramel** [snowpackjs/astro#873]
Currently, there is no documentation around how to use environment variables within Astro and nothing noting the limitation of client-side usage.

Currently, `SNOWPACK_PUBLIC_` is the required prefix for client-side usage. 

Side Question: Should this be aliased to `ASTRO_PUBLIC`?

**Comment by markpinero** [comment]
There is documentation but it's currently not linked to on the docs site: https://github.com/snowpackjs/astro/blob/main/examples/snowpack/src/pages/reference/environment-variables.md

**Comment by drwpow** [comment]
+1 to this!

**Comment by stramel** [comment]
Thanks! 🙏
