### ISSUE TITLE
💡 RFC: Include file paths in fetchContent output

### ISSUE THREAD

**Issue by bearror** [snowpackjs/astro#883]
### Background & Motivation

I'm looking to connect my [Foam Knowledge Base](https://foambubble.github.io/foam/) to Astro. This boils down to rendering Markdown content with internal [wikilinks](https://foambubble.github.io/foam/wikilinks). Without utilizing any Markdown plugins on the Astro-side, these can be expanded to e.g.
```md
[[2021-07-27]]

[2021-07-27]: journal/2021-07-27 "Tuesday, July 27, 2021"
```
... where _"Tuesday, July 27, 2021"_ is the `h1` of the journal entry `journal/2021-07-27`. Using `Astro.fetchContent`, the headings for that entry are as follows:
```json
{
  "headers": [
    {
      "depth": 1,
      "slug": "tuesday-july-27-2021",
      "text": "Tuesday, July 27, 2021"
    }
  ]
}
```
**The problem is that there is insufficient information to build a page with a path that matches up with the links to it.** (`journal/2021-07-27` ⟷ `tuesday-july-27-2021`) Resolving each wikilink, e.g. `[[2021-07-27]]`, from the source also relies on the name of the file that is being linked to, which can rarely be derived from the title.

### Possible solutions

Include the file path (and perhaps the file name for convenience?) for each entry returned by `Astro.fetchContent`. With that, the user has the necessary context to ensure that internal links in the content can be resolved.

### Alternatives considered

- The necessary information could be manually included in the frontmatter. In the case of wikilinks that'd mean duplicating the file name and keeping that in sync.
- A Markdown plugin could probably be used to resolve wikilinks directly on the Astro-side without expanding the links in the content.
- The user could write any custom mapping logic in `createCollection` to resolve links and/or paths as needed.

### Risks, downsides, and/or tradeoffs

Having access to another set of (externally defined) paths might add confusion as to when to use the file-system routing for `/pages`, when to use [dynamic routes](https://github.com/snowpackjs/astro/issues/80), and when to take a DIY approach with `Astro.fetchContent` and `createCollection`.

Using frontmatter is a fair option, although I would argue that including the file path does not bloat the output enough to warrant having to duplicate the file name in the content.

### Open Questions

Perhaps the bigger question would be: _"Should Astro handle internal links in fetched Markdown content, and if so, how?"_ (Likely no?) I imagine that this isn't trivial, as the content returned from `Astro.fetchContent` doesn't have a 1:1 relation with the pages that one might render. IMO that's really powerful, as I like being able to compose multiple pieces of content together at build-time.

### Help make it happen!

- [x] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by bearror** [comment]
For additional context that I failed to mention; **This is relevant for content that isn't included under the `/pages` directory.** That is, Markdown content that is to be transformed / composed _into pages_, rather than pages that are expressed as Markdown.

---

Looking at the current implementation of `fetchContent`, there's already a distinction between content that is fetched from within `/pages` and content that is external to it. The `url` property is provided for the first case, and omitted from the second case. Makes sense, since there isn't a page to point to when the content isn't in `/pages`.

To provide the user with the most flexibility and context when dealing with external content, I'd suggest that a `path` would be included instead. (Perhaps by utilizing `urlSpec`?) https://github.com/snowpackjs/astro/blob/cb7c9d5f82c9b557665299b2ec5f08e3da8606c5/packages/astro/src/internal/fetch-content.ts#L15
Depending on the desired return type, `path` could be omitted from the later return that has `url`, or it could be included there as well. If this isn't a super niche use-case, a discriminator might be useful as well, to signify whether or not we are dealing with content under `/pages` or external content.

**Comment by matthewp** [comment]
Thanks! I'm not sure if you're in the discord or not, but we are having a meeting tomorrow and would love to discuss this idea if you are interested in joining.

**Comment by bearror** [comment]
Sure thing, I'll be there.

**Comment by matthewp** [comment]
There is a `file` property that is a URL which you should be able to use for this. We should document this if it's not already documented.

**Comment by bearror** [comment]
Can confirm that `file` solves the issue. Looks like the solution snuck in as a part of the file-based-routing changes. Works for me — an indirect fix is the best kind of fix. 😄

Definitely recommend taking another look at https://docs.astro.build/reference/api-reference now that the output is different.
