### ISSUE TITLE
RFC Call: August 3rd, 2021

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#888]
## When/Where

- 11am PST, August 3 2021
- On Discord, #rfc-call channel

## Agenda

https://github.com/snowpackjs/astro/issues?q=is%3Aopen+is%3Aissue+label%3Arfc-discuss

- #958
- #918
- #914
- #901
- #745
- #708
- #691
- #495
- #492
- #310
- #244

**Comment by jasikpark** [comment]
I think the time should be "August 3rd" in the body, right?
