### ISSUE TITLE
🐛 BUG: Svelte complains about being passed attributes it doesn't understand from Astro

### ISSUE THREAD

**Issue by VodnikAngus** [snowpackjs/astro#890]
### What package manager are you using?

npm

### What operating system are you using?

Linux (Fedora 34)

### Describe the Bug

Svelte complains about being passed attributes it doesn't understand from Astro
![image](https://user-images.githubusercontent.com/5102074/127216770-1059719e-81cc-416e-a1f2-53ae7ca9989f.png)

### Steps to Reproduce

1. `npm init astro`
2. Install TypeScript (I am sure this has nothing to do with it I just haven't checked before installing ts)
3. Wrong warnings

**Comment by FredKSchott** [comment]
From Discord: https://discord.com/channels/830184174198718474/830184175176122389/869663433379942400
