### ISSUE TITLE
📘 DOC: Add a description of how to use `.env` and regular env variables with Astro

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro#892]
Currently I think we link out to the Snowpack docs, but I want to write some more thorough docs we can point people towards.

**Comment by drwpow** [comment]
+1 to this!

**Comment by drwpow** [comment]
Just noticed this is a dupe of https://github.com/snowpackjs/astro/issues/873. Sorry, but first one to open wins! :P
