### ISSUE TITLE
💡 RFC: alternative `.astro` file formats

### ISSUE THREAD

**Issue by kosich** [snowpackjs/astro#903]
### Background & Motivation

With current `---` code fences (frontmatter) style IDE support is a bit limited (at least, in the types department) and requires specialised plugins (that also need to be up-to-date with Astro version) to properly highlight, format and lint it. Typing (or inferring types) would probably require some ad-hoc solutions too. So why inventing something new if we can re-use existing solutions that have huge communities behind it?

_I bet you've discussed this a thousand times, but I've not found neither such a discussion, nor a document w/ motivation behind this syntax. So I'm sorry if this is repetitive. #139 has a related discussion, but seems to go only around frontmatter format_

### Possible solutions

We could have two astro filetypes:

A template-only pure html `.astro`, e.g:

```html
<div>
  <h1>Hello</h1>
  <slot />
</div>
```

And a logic-full `.astrox` (React-like function components w/ JSX-like syntax) e.g.:

```tsx
import { fetchContent } from 'astro';

export default ComponentName(props: { title: string }) {
  let posts = fetchContent('./*.md');

  return <div>
    <h2>{ props.title }</h2>
    { posts.map(p => <a href={p.url}>{ p.title }</a>) }
  </div>
}
```

We would get all the types support out of the box (thanks for previous work to support react-like syntaxes), and no magical `Astro.props` needed.

If two file-types is too much, we could have a single filetype w/ jsx. In this case the first template-only example would look like:

```jsx
export default <div>
  <h1>Hello</h1>
  <slot />
</div>
```

Supporting a standalone syntax wont be cheap. And JSX is here to stay, so it seems like a good long-term bet.

### Alternatives considered

Vue has it's single file component w/ the `<template>`/`<script>` tags, though the typings there aren't so good and if astro needs to export client-side `<script>` — the nesting might be confusing. Thought this path is also worth exploring, imho.

### Risks, downsides, and/or tradeoffs

This, admittedly, is a big change and is not backwards compatible.

Risks I can think of now:

-  JSX would probably complain about `Component:visible` syntax, which is absolutely required for astro
   _One way to fix that is to use global jsx types and allow `visible` `lazy` `load` attributes on any component, e.g.: `<Component visible title="Hello />`_ 
   _Another not-that-good way to quick-fix this would be to export a `visible` function and do `ComponentOnVisible = visible(Component)` and use that in JSX_

- returning multiple children might require a `<></>` fragment

- returning `<script>` and `<style>` from the components might require special handling (but I guess, Astro already does that)

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by kosich** [comment]
I'd even go one step further and suggest using `astro` suffix for Astro component filenames, e.g. `Component.astro.jsx`. With `.js/jsx` and `.ts/.tsx` extensions to distinguish syntaxes. While regular `.jsx/tsx` remaining for React-like components.

This allows following features:

**Regular page:**

```tsx
// src/pages/index.astro.tsx

import { fetchContent } from 'astro';

let content = await fetchContent('./*.md');

export default function Index () {
  return <html>
    <body>
      <ul>
        { content.map(p => <li>{ p.title }</li> ) }
      </ul>
    </body>
  </html>
}
```

**Regular component:**

```tsx
// src/Posts/PostPage.astro.tsx

import { Markdown } from 'astro';

export default function PostPage (props: { title: string, body: string }) {
  return <>
    <h1>{ props.title }</h1>
    <Markdown>{ props.body }</Markdown>

    <style>...</style>
  </>
}
```

---

**No need for special syntax hacks for collections:**

```ts
// src/pages/$tag.ts

import { ICollection } from 'astro';
import TagPage from './TagPage.astro.tsx';

// typed export
export default const collection: ICollection = {
  data() {
    return await fetch('...')
  },
  // render can be a function or an imported component
  // that would have to match it's props type with the return type of data()
  render: TagPage
}
```

---

**Maybe even with custom plugins applied**

```tsx
// src/pages/blog/index.astro.tsx

export default const component = CustomRouting(props => {
  return <div>
    ...
  </div>
})
```

**Comment by radiosilence** [comment]
I mean if this is the case why not just support TSX as a top level page component?

I think the point of `.astro` is that it is more simple and less nested.

**Comment by kosich** [comment]
> I mean if this is the case why not just support TSX as a top level page component?

That's my argument in the second comment. But afau the build system distinguishes component types by file extension, therefore the `.astro.tsx` suffix

And the suffix looks awesome in terms of React's upcoming server components, with the `server` - `astro` - `client` component type trio!

---

> I think the point of `.astro` is that it is more simple and less nested.

Well, if thats for the cost of not having tooling and type safety — those 1-2 levels of nesting are not worth it, imho. I guess, there are other, build-related reasons authors initially chose a custom syntax.

Here I wanted to point out that using a more industry-friendly (and code-transparent) format would give multiple instant benefits:
- refactoring
- linting
- intelli-sense
- type safety
- maybe additional JSX pre/post-processors
- and probably more

On top of that, the Astro API receives a native JS form: `(props) => ...` and `import { fetchContent } from 'astro'` instead of a bit magical `Astro.props` and `Astro.fetchContent`.

---

This is my opinion, while I currently know close to nothing about Astro core, so maybe there are some serious blocker to this approach.

**Comment by matthewp** [comment]
No problem with bring up the discussion! But I can safety say that we're not going to drop our file format. At this point it's established and improving. The downsides will be improved over time.

The main reason we went with the astro file format was so that we could precompile the astro module and provide support for stuff like `<MyComponent client:load>` which turns that code into a script tag. This would likely be impossible in JavaScript since JavaScript is completely dynamic. 

I think there was also a style preference; we wanted astro to be *mostly* HTML and to defer out logic to components. I think this is a fair compromise. If you prefer JSX then you can use JSX in components and don't need to work inside of .astro files very much.

**Comment by kosich** [comment]
@matthewp , hi!

> The main reason we went with the astro file format was so that we could precompile the astro module and provide support for stuff like <MyComponent client:load> which turns that code into a script tag. This would likely be impossible in JavaScript since JavaScript is completely dynamic.

Well, Astro already supports dynamic JSX-like expressions, doesn't it? This is already as dynamic as it can get for a site generator:

```tsx
<div>
{ Math.random() > 0.5 ? <h1>Hi</h1> : <h1>Bye</h1> }
</div>
```

Yes, Astro's current JSX-like compiler would allow this.

There's no issue in JS flexibility, since Astro already supports all JS there is in the code fences part.
Let me show you this in an example. Imagine we have a regular `.astro` component:

`src/components/Header.astro`

```astro
---
let { title, subtitle } = Astro.props;

---

<div>
  <h1>{ title }</h1>
  <h2>{ subtitle || 'lorem ipsum' }</h2>
</div>
```

I'm saying that it's equivalent to following JSX:

`src/components/Header.astro.jsx`

```jsx
export default function (props) {
  let { title, subtitle } = props;

  return <div>
    <h1>{ title }</h1>
    <h2>{ subtitle || 'lorem ipsum' }</h2>
  </div>
}
```

See, there's almost no difference!

Only with JSX we get all the tooling there is around JSX. And the ecosystem is **huge**! To stress again that it's as dynamic as Astro's current format: as soon as function returns JSX — we have our static vDOM tree that can be analysed and rendered to `div`s and `script`s.

```js
JSX !== dynamic

JSX === { type: 'div', props: { style: 'color: red' }, children: [ 'a', 'b', 'c' ] }
```

I assume, current svelte-forked compiler does a similar thing: compiles `.astro` syntax into a function that would receive current component props/context and returns some form of a virtual DOM. With JSX that whole module can be dropped. All the parsing would be done by 3rd party libraries, Astro would only need to traverse a JS object and build html output.

> I think there was also a style preference; we wanted astro to be mostly HTML and to defer out logic to components. I think this is a fair compromise. 

Astro already supports `.astro` components with server-side **logic**. JS logic is something Astro uses both in components and in special case pages (like Collections). I'm just saying that these cases would only win if we were to expose them either in pure JS or JSX.

> If you prefer JSX then you can use JSX in components and don't need to work inside of .astro files very much.

Currently this is not an equal exchange, as client framework side doesn't support the `:visible` triggers.

---

I understand that it's a huge change. Especially this far into development it's a huge uncomfortable step.
My point is that supporting custom format has a big cost to it, w/o bringing any benefit.

Simply defining astro component as a function `(props) => vDOM` would unlock all the community super powers. Not only for JSX, but for any other syntax in the future.

Please, think of it a bit more. I truly believe this change would be beneficial to the project.

**Comment by matthewp** [comment]
Anything's possible given enough effort, but Astro is mostly static with dynamic parts where as JS is truly dynamic. A core thing we do is find `client:load` attrs and turn those into scripts. It would be almost impossible to do this in JavaScript: https://codesandbox.io/s/currying-cdn-zsr3c?file=/src/App.js

> I assume, current svelte-forked compiler does a similar thing: compiles .astro syntax into a function that would receive current component props/context and returns some form of a virtual DOM. With JSX that whole module can be dropped. All the parsing would be done by 3rd party libraries, Astro would only need to traverse a JS object and build html output.

Our compiler does quite a lot, there's a current PR out there that will actually remove import statements:

```jsx
---
import Component from './some/place.jsx'
---

<Component client:only />
```

This will make that component only render in the client and remove the the import statement so that it doesn't throw due to not being Node compatible. This wouldn't happen with JSX unless we completely took over JavaScript parsing which I don't have the stomach to attempt.

**Comment by kosich** [comment]
>  It would be almost impossible to do this in JavaScript: https://codesandbox.io/s/currying-cdn-zsr3c?file=/src/App.js

That's a great example, I haven't thought of this too dynamic case 🙂

> Our compiler does quite a lot, there's a current PR out there that will actually remove import statements

Here's a naive thought: would it be possible for the builder to override component imports (`.jsx` or others) with importing file path instead?

So that:

```js
import Component from './some/place.jsx';
// becomes
const Component = './some/place.jsx';
```

_I suppose, there's already some heavy AST work in the PR you mentioned, so this one should not be a very heavy operation_

With that in place, we can now run our component function and get the result:

```tsx
const Component = './some/place.jsx';

export default Parent(props) {
  return <Component client-only />
}
```

And then we'll see which components are used to either dynamically import them for SSR, or register as client-only. This also easily allows syntax like `<Component client-only={ props.value > 0.5 } />` to dynamically define load conditions.

The only convention here is that one can use load triggering attributes only on file components.

WDYT?
