### ISSUE TITLE
🐛 BUG: Errors @vue/runtime-core

### ISSUE THREAD

**Issue by Enteleform** [snowpackjs/astro#905]
# What package manager are you using?

yarn

# What operating system are you using?

Windows

# Describe the Bug

### `start`
- `VueCounter` is unresponsive.
- `console.error`:
```log
visible.ts:15 Uncaught (in promise) TypeError: Failed to resolve module specifier "@vue/runtime-core". Relative references must start with either "/", "./", or "../".
async function (async)
cb @ visible.ts:13
(anonymous) @ visible.ts:23
```

### `build`
- `snowpack` Error
```log
[10:59:54] [snowpack] (/_snowpack/pkg/@vue/runtime-core) Deprecated manual package import. Please use snowpack.getUrlForPackage() to create package URLs instead.
[build] Could not load /_snowpack/pkg/@vue/runtime-core (imported by ..\..\..\_snowpack\pkg\@vue.runtime-dom.v3.1.5.js): ENOENT: no such file or directory, open 'D:\_snowpack\pkg\@vue\runtime-core'
```

# Steps to Reproduce

## Common
1. `npm init astro` using template `Starter Kit (Generic)` with `Vue` framework.
2. `yarn install`

## `start`
3. `yarn start`

## `build`
3. `yarn build`

**Comment by Igloczek** [comment]
It's related to changes I made in #858, didn't test it properly on client side, sorry about that 😞

**Comment by matthewp** [comment]
@Igloczek does this mean that Vue doesn't work client-side at all? If so we probably will need to temporarily revert that change until we can figure something else.

**Comment by Igloczek** [comment]
@matthewp unfortunately that's true, even not nested are broken on client side

**Comment by Igloczek** [comment]
Kinda wonder why this change even do anything to SSR, since this package was already marked as external in Astro, and was part of the Snowpack config 🤔 
https://github.com/snowpackjs/astro/blob/main/packages/astro/src/external.ts#L21

**Comment by matthewp** [comment]
Closed by https://github.com/snowpackjs/astro/pull/913
