### ISSUE TITLE
🐛 BUG: `could not find [library]` when doing `client:load` on imported React components from other projects

### ISSUE THREAD

**Issue by radiosilence** [snowpackjs/astro#906]
**Note this is using astro 0.17.x due to https://github.com/snowpackjs/astro/issues/904 **

### What package manager are you using?

yarn

### What operating system are you using?

MacOS

### Describe the Bug

If I have a library from a workspace and import a component in such fashion:

```astro
import { HiMan } from 'test-ui';
```

It renders fine, but when I add `client:load` like so:

```
---
<html lang="en">
<head>
    <HiMan client:load />
</html>
```

It breaks with an error like so:

```
[build] Error: file://xx/my-astro-project/web/src/pages/index.astro: could not find "test-ui"
    at file:///xx/my-astro-project/node_modules/astro/src/build.ts:140:25
    at async Promise.all (index 1)
    at build (file:///xx/my-astro-project/node_modules/astro/src/build.ts:154:5)
    at buildAndExit (file:///xx/my-astro-project/node_modules/astro/src/cli.ts:16:15)
```

### Link to Minimal Reproducible Example (Optional)

https://github.com/radiosilence/astro-bug-906

**Comment by matthewp** [comment]
Closing in favor of https://github.com/snowpackjs/astro/issues/908 which describes the more generic problem that's happening here.
