### ISSUE TITLE
🐛 BUG: Bare-module specifiers cannot be islands

### ISSUE THREAD

**Issue by matthewp** [snowpackjs/astro#908]
### What package manager are you using?

nopm

### What operating system are you using?

Mac

### Describe the Bug

If you attempt to hydrate a third party component using `client:load`, etc. it is unable to load in the browser. This is because the compiler resolves relative to the current file and doesn't account for bare module specifiers.

### Steps to Reproduce

The following does not work:

```astro
---
import Something from 'some-package';
---

<Something client:load />
```

**Comment by natemoo-re** [comment]
The fact that we're not running specifiers through Snowpack is tracked in https://github.com/snowpackjs/astro/issues/574. Closing as a duplicate.

Spolier: it's fixed in #1406!
