### ISSUE TITLE
🐛 BUG: Markdown heading slugs are duplicated

### ISSUE THREAD

**Issue by IanVS** [snowpackjs/astro#910]
### What package manager are you using?

npm

### What operating system are you using?

mac

### Describe the Bug

The `content.astro.headers` generated from a markdown file can have duplicate slugs for different headings, as well as the generated html having duplicate `id` values for different elements.  I believe the normal approach here is to append a `-1`, `-2` etc to the ids and slugs in this situation, but Astro does not seem to do that. 

### Steps to Reproduce

See codesandbox.

### Link to Minimal Reproducible Example (Optional)

https://codesandbox.io/s/mystifying-leftpad-uxj53?file=/src/layouts/Main.astro

**Comment by matthewp** [comment]
This might fix it: https://github.com/snowpackjs/astro/pull/862

**Comment by IanVS** [comment]
Ah, thanks, this indeed looks like a duplicate of https://github.com/snowpackjs/astro/issues/805.

**Comment by IanVS** [comment]
In the meantime, using [`rehype-slug`](https://github.com/rehypejs/rehype-slug) solves my problem nicely!

**Comment by jasikpark** [comment]
I think the latest version of Astro has that integrated - maybe test on 0.18.5?

**Comment by IanVS** [comment]
I'm also using another rehype plugin, so I have to add it manually anyway.  It would be nice if those plugin configs were functions and the existing plugins could be spread in, so they aren't lost.

**Comment by jasikpark** [comment]
hmm 
```

import defaultRemarkConfig from "astro"; 

export default {
  remarkConfig: {
    remark-plugin-x,
    ...defaultRemarkConfig
  }
};
```

Could be an interesting way to do that, though I'm not sure how you'd configure a default plugin - I guess if you specified it before the default spread, the spread wouldn't override it?
