### ISSUE TITLE
🐛 BUG: Lit Renderer @customElement Typescript decorator not working

### ISSUE THREAD

**Issue by jaydanurwin** [snowpackjs/astro#921]
### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

I created a repo that reproduces the issue at https://github.com/jaydanurwin/astro-lit-test

The `my-counter` component uses the manual `export const tagName = 'my-counter';` line and the project builds successfully. However, the `my-counter-2` component uses Lit's `@customElement` decorator and when I use that component the build breaks with the following error:

```
(node:413485) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./directives/" in the "exports" field module resolution of the package at .../astro-lit-test/node_modules/@lit-labs/ssr-client/package.json imported from .../astro-lit-test/node_modules/@lit-labs/ssr/lib/render-lit-html.js.
Update this package.json to use a subpath pattern like "./directives/*".
(Use `node --trace-deprecation ...` to show where the warning was created)
[build] ✔ pages built.
[build] file:///.../astro-lit-test/src/pages/index.astro: could not find "undefined" 
```

I think other Lit users would expect the built in decorator for declaring the tag name to work which I why I felt I should file an issue. Thank you for all of your hard work on this great framework!

### Steps to Reproduce

1. clone reproducible repo
2. use the my-counter-2 component in the `index.astro` page
3. `npm run build`
4. See the error mentioned above

### Link to Minimal Reproducible Example (Optional)

https://github.com/jaydanurwin/astro-lit-test

**Comment by matthewp** [comment]
@jaydanurwin You still need to export the tagName. Does adding that fix it?

**Comment by jaydanurwin** [comment]
Yes, that seems to fix it for my own Lit components. However, I am seeing issues while trying to use the [mwc-button](https://github.com/material-components/material-components-web-components/tree/master/packages/button) component inside of that component and/or imported directly into the Astro page. This might be a dumb question but if I try to import a Lit component from NPM and it doesn't export the tagName will it not work?

Let me know if you want me to file a separate issue for this.

**Comment by matthewp** [comment]
Right, if you import it into an Astro file it needs the tagName export. That's how it knows what module to load in the browser.

What I would do is create a wrapper module. In that module import (side-effect import) your 3rd party element and then export a tagName from that file.

**Comment by jaydanurwin** [comment]
Are you able to provide a minimal example? You'll have to bear with me as I'm pretty new to web components. I think I know what you mean by wrapping the 3rd party component. I [added a new file to my repo](https://github.com/jaydanurwin/astro-lit-test/blob/main/src/components/mwc-button/mwc-button.js) and then I'm importing it into the my-counter-2 component but I am still getting the following error:

```
[executing astro] TypeError: document.addEventListener is not a function
at eval (/_snowpack/pkg/@material.mwc-base.base-element.v0.22.1.js:27:10)
```

**Comment by matthewp** [comment]
Lit uses a DOM shim so not all web components can run with it. Which package are you trying to use?

**Comment by jaydanurwin** [comment]
In this particular example I'm trying to use the material web component button package (https://www.npmjs.com/package/@material/mwc-button) which I think still uses Lit Element.

**Comment by matthewp** [comment]
Ah yeah, that's because Lit's DOM shim doesn't have `addEventListener`: https://github.com/lit/lit/blob/main/packages/labs/ssr/src/lib/dom-shim.ts#L79-L92

It look like MWC is using that to do some feature detection here: https://github.com/material-components/material-components-web-components/blob/9e41cb2e16883609b757bc0e8127343ac17c24d1/packages/base/utils.ts#L42-L43

I would raise this with either the Lit or MWC team. Probably the latter to start. Just let them know that it's not working with Lit SSR.

**Comment by matthewp** [comment]
I'm going to close as I don't think there's a bug here, but happy to continue discussing here.

**Comment by jaydanurwin** [comment]
Thank you for the replies Matthew. That makes sense, I guess the only thing I'm hung up on is that I'm able to use vite with this same setup of Lit and the MWC web components and it will build to a static site with no issue. Is snowpack not able to bundle components to static files in the same way? To give more context I was planning on possibly migrating one of my biggest projects to Astro but this would be a deal breaker if I **have** to use SSR for all of my UI components.

Thank you again I really appreciate you taking the time to help

**Comment by jaydanurwin** [comment]
Here's a repo using the same my-counter-2 component from my astro repo (https://github.com/jaydanurwin/vite-lit-test). It runs locally and builds to a static file I could host on netlify or firebase hosting.

**Comment by matthewp** [comment]
Hi @jaydanurwin, you definitely don't have to use SSR for your components. If you don't want to SSR a component (or any code), just omit the import statement from the frontmatter and add a `<script>` tag instead.

**Comment by jaydanurwin** [comment]
Got it! I guess I just missed the fact that import was me saying I wanted to use SSR. I'm coming from most of my web dev experience being in Gatsby (based on React) where everything has to be imported then it builds to static. 

Thanks again!
