### ISSUE TITLE
[BUG] Grammar source contains incompatible syntax

### ISSUE THREAD

**Issue by Nixinova** [snowpackjs/astro#925]
### Describe the Bug

The [tmlanguage file](https://github.com/snowpackjs/astro/blob/main/tools/vscode/syntaxes/astro.tmLanguage.json) for this repository contains syntax that is incompatible with GitHub Linguist. **This is blocking Astro from being added to GitHub's list of languages.** https://github.com/github/linguist/pull/5460#issuecomment-888249909

The issue lies in how some capture groups are formatted. The indices should be integer strings in an object, not an array.

### ❌ Wrong

```json
"captures": [
  {"name": "..."}
]
```

### ✔️ Right

```json
"captures": {
  "0": {"name": "..."}
}
```

**Comment by matthewp** [comment]
Thanks! We'll prioritize getting this fixed before their deadline.

**Comment by jasikpark** [comment]
Should every Array be rewritten as a Object with number keys? I'm not sure where to fix this..

**Comment by matthewp** [comment]
@jasikpark looking at the error message it seems like this is specifically about the capture ones, so `captures`, `beginCaptures` and `endCaptures`
