### ISSUE TITLE
💡 RFC: Auto-numbered footnotes (like remark-numbered-footnotes)

### ISSUE THREAD

**Issue by brycewray** [snowpackjs/astro#929]
### Background & Motivation

Part of Astro’s built-in Remark-based handling of Markdown — which includes items that would otherwise require plugins — is footnote support. However, the resulting HTML doesn’t auto-number footnotes — specifically, through creation of an ordered list — as is possible with either the [remark-numbered-footnotes plugin](https://github.com/remarkjs/remark-footnotes) or the [remark-numbered-footnote-labels plugin](https://github.com/jackfletch/remark-numbered-footnote-labels). Since using a separate plugin means giving up (and, thus, having to self-replace) the built-in Remark functionality, it would be preferable if, instead, Astro had this one additional Remark capability just as it already has those others.

Ideally (this comes from an Eleventy test page I made, and the returns are for easier reading here), the following Markdown...

```md
This is an example of how footnotes work in 
Eleventy[^Eleventy]. It illustrates how I would 
like them to work in Astro[^AstroDef].

[^Eleventy]: [Eleventy](https://11ty.dev) is a popular 
static site generator.

[^AstroDef]: [Astro](https://astro.build) is 
[self-defined](https://docs.astro.build/getting-started) 
as a "modern static site builder." 

While editing one's Markdown files in an editor 
like Ulysses[^bigU]---which not only auto-numbers 
footnotes but also places them at the bottom of 
the Markdown---would resolve this issue, it's highly 
unlikely more than a small fraction of Astro's likely 
user base would be willing to go that route. Instead, 
given that Astro already has several Markdown-related 
features[^MDfeats] that apparently come from Remark 
plugins, it just makes sense to add one more such feature, 
in the form of auto-numbered footnotes.

[^bigU]: [Ulysses](https://ulysses.app) is a writing app 
for macOS and iOS.

[^MDfeats]: These Remark-specific features, as noted in the [Astro 
documentation](https://docs.astro.build/guides/markdown-content), 
include a limited form of footnotes support, "Smartypants" for better 
typography, and Remark-slug for adding anchor links to headings. 
Astro also supports [Prism](https://prismjs.com)-based syntax 
highlighting, although it's not mentioned whether this also involves 
a Remark plugin.
```

...would produce HTML **similar to** the following (I say “similar to” because the following comes from Eleventy’s [Markdown-It](https://github.com/markdown-it/markdown-it) parser, not Remark, but those familiar with HTML from the previously mentioned Remark plugins will be able to extrapolate from this):

```html
<p>This is an example of how footnotes work in Eleventy<sup class="footnote-ref"><a href="#fn1" id="fnref1">1</a></sup>. It illustrates how I would like them to work in Astro<sup class="footnote-ref"><a href="#fn2" id="fnref2">2</a></sup>.</p>

<p>While editing one’s Markdown files in an editor like Ulysses<sup class="footnote-ref"><a href="#fn3" id="fnref3">3</a></sup>—which not only auto-numbers footnotes but also places them at the bottom of the Markdown—would resolve this issue, it’s highly unlikely more than a small fraction of Astro’s likely user base would be willing to go that route. Instead, given that Astro already has several Markdown-related features<sup class="footnote-ref"><a href="#fn4" id="fnref4">4</a></sup> that apparently come from Remark plugins, it just makes sense to add one more such feature, in the form of auto-numbered footnotes.</p>

<hr class="footnotes-sep">
<section class="footnotes">
  <ol class="footnotes-list">
    <li id="fn1" class="footnote-item">
      <p><a href="https://11ty.dev" target="_blank" rel="noreferrer noopener">Eleventy</a> is a popular static site generator. <a href="#fnref1" class="footnote-backref">↩︎</a></p>
    </li>
    <li id="fn2" class="footnote-item">
      <p><a href="https://astro.build" target="_blank" rel="noreferrer noopener">Astro</a> is <a href="https://docs.astro.build/getting-started" target="_blank" rel="noreferrer noopener">self-defined</a> as a “modern static site builder.” <a href="#fnref2" class="footnote-backref">↩︎</a></p>
    </li>
    <li id="fn3" class="footnote-item">
      <p><a href="https://ulysses.app" target="_blank" rel="noreferrer noopener">Ulysses</a> is a writing app for macOS and iOS. <a href="#fnref3" class="footnote-backref">↩︎</a></p>
    </li>
    <li id="fn4" class="footnote-item">
      <p>These Remark-specific features, as noted in the <a href="https://docs.astro.build/guides/markdown-content" target="_blank" rel="noreferrer noopener">Astro documentation</a>, include a limited form of footnotes support, “Smartypants” for better typography, and Remark-slug for adding anchor links to headings. Astro also supports <a href="https://prismjs.com" target="_blank" rel="noreferrer noopener">Prism</a>-based syntax highlighting, although it’s not mentioned whether this also involves a Remark plugin. <a href="#fnref4" class="footnote-backref">↩︎</a></p>
    </li>
  </ol>
</section>
```

### Possible solutions

Just as Astro already includes functionality apparently derived from other Remark plugins, it should also include the functionality of one of the footnote-related plugins mentioned above.

### Alternatives considered

Assuming Remark is the choice for Astro’s Markdown parser, there isn’t one. IMHO, [Markdown-It](https://github.com/markdown-it/markdown-it) is a better parser and doesn’t present the problems of Remark, but I assume that ship has sailed.

### Risks, downsides, and/or tradeoffs

I don’t know how to answer this part, but I do know that anyone who depends on auto-numbered footnoting couldn’t use Astro unless this functionality is there. I haven’t yet tried to add the functionality through a plugin because then, as the documentation says, I lose the already-provided Remark features and would have to recreate them all. This seems to be a choice that won’t go over well with those who need normal footnoting.

### Open Questions

Unknown.

**Note**: I do see the note saying that “RFCs with contributing authors are much more likely to get done!” However, I am not a (real) coder and thus couldn’t be of use with a PR. I am certainly willing to **test** one if someone wishes my help in that regard.

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [ ] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by jasikpark** [comment]
You should be able to simply use the remark footnotes plugins in your config: https://docs.astro.build/guides/markdown-content#add-a-markdown-plugin-in-astro

**Comment by brycewray** [comment]
@jasikpark Yes but, as I noted:

> Since using a separate plugin means giving up (and, thus, having to self-replace) the built-in Remark functionality, it would be preferable if, instead, Astro had this one additional Remark capability just as it already has those others.

This is based on the **Note** in [Remark and Rehype Plugins](https://docs.astro.build/guides/markdown-content#remark-and-rehype-plugins).

**Comment by jasikpark** [comment]
Ah, yeah I can see that! I feel like a pain point of this would be to make copy and pasting the default values for the plugins easier, no?

Also maybe this is a case where we should allow extending the plugin config

**Comment by jasikpark** [comment]
Added #941 for that, though that might not be the full solution you want.

**Comment by brycewray** [comment]
> Added #941 for that, though that might not be the full solution you want.

Thanks! Still think it'd be better if they just added that one thing. It's really the only missing piece for footnotes.

**Comment by brycewray** [comment]
@jasikpark Given that it appears there is a need to provide options to the built-in Remark/SmartyPants functionality (see https://github.com/snowpackjs/astro/issues/720#issuecomment-890112036), is there a way to do that without breaking the built-in Remark stuff and, thus, being forced to manually add it all (as was my previously stated fear)?

**Comment by jasikpark** [comment]
Not that I can tell you about. 

I imagine it might be a good idea to either allow "extends @astro/remark-default-config" or something else for this usecase at somepoint. 

Today I'm pretty confident you just need to duplicate the default config if you want to edit it though.

**Comment by brycewray** [comment]
> Not that I can tell you about.
> 
> I imagine it might be a good idea to either allow "extends @astro/remark-default-config" or something else for this usecase at somepoint.
> 
> Today I'm pretty confident you just need to duplicate the default config if you want to edit it though.

And that's what I decided to do. Not so bad after all. 😄 Thanks again.
