### ISSUE TITLE
🐛 BUG: Directory not empty... on npm init astro 

### ISSUE THREAD

**Issue by mash-graz** [snowpackjs/astro#931]
### What package manager are you using?

npm

### What operating system are you using?

linux + gitpod

### Describe the Bug

IMHO it's really annoying, that astro requires an empty current directory for the initialization.

wouldn't it be sufficient, to just look for conflicting files ('package.json', 'astro.config.mjs'), which have to be created by the init routine, and ignore all other files and directories instead of  wiping out everything as the only option?

the present behavior is simply incompatible with many tools (e.g. `gitlab` and `gitpod`), which require some kind of already existing dot-files or -dirs (and `.git` in particular!) in the working directory. sure, it's possible to workaround this flaw by various ways of manual installation, but the instructions given in the documentation will not work anymore in this case. 

see also: #690 #700 #729

### Steps to Reproduce

```
gitpod /workspace/webpage $ ls -a
.  ..  .git  .gitpod.yml  README.md

gitpod /workspace/webpage $ npm init astro
npx: installed 18 in 1.373s

Welcome to Astro! (create-astro v0.5.2)
If you encounter a problem, visit https://github.com/snowpackjs/astro/issues to search or file a new issue.

> Prepare for liftoff.
> Gathering mission details...
? Directory not empty. Delete . to continue? › (y/N)
```

**Comment by mash-graz** [comment]
while reading the git history to find a solution for this issue, i found:

- the remove procedure resp. requiring an  empty directory was already present in the first PR of  the create-astro redesign (#301)
- it was already criticized in #332 

`degit` provides the rather useful `force` option for this kind of conflicts. why shouldn't we use it?

perhaps it could make sense, to reuse the present empty-dir-check for some kind of warning dialog, but simply overwrite by `degit  --force` instead of removing any files, if the user accepts the possible troubles of just adding the template content instead of a clean init. if someone doesn't want to go this way, he is still able to stop the installation at this point and wipe out all existing stuff manually after this warning dialog.

**Comment by matthewp** [comment]
This is as intended, you can do `npm init astro new-folder` and it will create a subfolder. Does that work for you?

**Comment by mash-graz** [comment]
yes -- that's one of the more or less obvious ways to workaround this limitation. 
but why should we introduce this kind of crazy obstacles?

but perhaps there is good reason, why a simple `degit --force` resp. warning dialog doesn't to the job in a much more transparent manner. please just explain it me!

**Comment by matthewp** [comment]
Because it's not obvious when you run `npm init astro` if that will install the current directory or create a new directory. Since it's the former we don't want to trash someone's folder because they were unaware of this.

If we had an option to proceed without deleting the files in the current folder would that work?

**Comment by mash-graz** [comment]
> Because it's not obvious when you run npm init astro if that will install the current directory or create a new directory.

no -- that's IMHO no convincing argument. for a good reason we use the term "current working directrory".
when i use the `git init` command, i also expect, that it will affect the local directory and not remove anything.

and i really like tools, which try coexist with other utilities without unnecessary interference resp. don't force the user to handle everything in very opinionatedmanar or command order. 

> Since it's the former we don't want to trash someone's folder because they were unaware of this.

yes -- the explicit warning dialog makes sense. but this prevention mechanism was already present in the initial commit of the redesigned create-astro command.

> If we had an option to proceed without deleting the files in the current folder would that work?

that's indeed the point, which i also don't understand.

we are using `degit --forced` anyway, and the variable of the relevant dialog is also called 'forceOverwrite' -- so: why do we still need this additional file removal efforts?

that's why i just removed this single line of code in #937
