### ISSUE TITLE
📘 DOC: Add Language Selector - Design Review

### ISSUE THREAD

**Issue by FredKSchott** [snowpackjs/astro#942]
## Options:

<img width="1336" alt="Screen Shot 2021-07-29 at 5 00 18 PM" src="https://user-images.githubusercontent.com/622227/127580748-bb56c100-65d4-4f4d-a376-ff6dc8d65f94.png">
<img width="1336" alt="Screen Shot 2021-07-29 at 4 59 56 PM" src="https://user-images.githubusercontent.com/622227/127580689-3c77cfda-d5a9-480c-9805-212cad045e5a.png">
<img width="1336" alt="Screen Shot 2021-07-29 at 5 03 17 PM" src="https://user-images.githubusercontent.com/622227/127580686-86f96f36-44e9-4057-941b-3ec25ff67bec.png">
<img width="1336" alt="Screen Shot 2021-07-29 at 5 05 50 PM" src="https://user-images.githubusercontent.com/622227/127580684-46358a2a-7c11-4da4-81af-3b347031dbcc.png">
<img width="1336" alt="Screen Shot 2021-07-29 at 5 06 24 PM" src="https://user-images.githubusercontent.com/622227/127580682-a3a09aa8-a8a4-4be2-ac17-6c274eb3188a.png">
<img width="1336" alt="Screen Shot 2021-07-29 at 5 07 42 PM" src="https://user-images.githubusercontent.com/622227/127580675-0559313f-c056-4fb8-ad27-8fbf2665505c.png">

/cc @snowpackjs/docs thoughts?

**Comment by FredKSchott** [comment]
If we went the "sidebar link" route instead of the "sidebar dropdown" route, then we'd need a popup like this: 

<img width="1336" alt="Screen Shot 2021-07-29 at 5 19 46 PM" src="https://user-images.githubusercontent.com/622227/127581427-f65dfeaa-07d6-43dc-ad06-dbdd778103eb.png">

**Comment by jasikpark** [comment]
I'm in favor of 4/5 (obviously with a good darkmode style) since that surfaces the selector easily.. I would say that it could go in the same place on mobile above the table of contents.

**Comment by FredKSchott** [comment]
Moving forward with this in #945
