### ISSUE TITLE
📘 DOC: Search modal does not have dark mode

### ISSUE THREAD

**Issue by jasikpark** [snowpackjs/astro#943]
The algolia search modal should use dark styles in dark mode, though currently it is always white. Maybe it could use similar styles to the SiteSidebar in terms of background and selection background transparency?

**Comment by FredKSchott** [comment]
It should be possible! If you check out devtools, you'll see what CSS rules are being used to set those colors. We already override one or two to get the orange color

**Comment by jasikpark** [comment]
Closed by #1041
