### ISSUE TITLE
🐛 BUG: Snowpack plugin results in the incorrect mime type

### ISSUE THREAD

**Issue by jonathantneal** [snowpackjs/astro#944]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

When using the following Snowpack plugin in Astro, which processes a `.module.html` file into a `.js` file, the resulting component has an incorrect mime type (`text/html` instead of `application/javascript`).

```js
module.exports = (snowpackConfig, pluginOptions) => ({
	name: 'snowpack-module-html',
	resolve: {
		input: ['.module.html'],
		output: ['.js', '.module.html'], // <- dunno why, but this produces the desired extension (`.module.html.js`)
	},
	async load() {
		return {
			'.js': 'export default class extends HTMLElement {}',
		}
	},
})
```

### Steps to Reproduce

1. Create an astro project (`npx create-astro`).
2. Add the snowpack plugin as described in the report (and linking to it within `snowpack.config.json`).
3. Create a file like `components/Hello.module.html`.
4. Start Astro and visit `http://localhost:3000/_astro/src/components/Hello.module.html.js`.
5. Wrong mime type! Expected `text/html` but get `application/javascript`.

### Link to Minimal Reproducible Example (Optional)

https://github.com/jonathantneal/astro-snowpack-mime-issue

**Comment by matthewp** [comment]
This was fixed in Snowpack, closing.
