### ISSUE TITLE
📘 DOC: Add PostCSS configuration

### ISSUE THREAD

**Issue by onlurking** [snowpackjs/astro#946]
I'd like to use PostCSS plugins instead of Sass, so I have this `postcss.config.js` in my root folder:

```js
module.exports = {
  plugins: [
    require('autoprefixer'),
    require('postcss-import'),
    require('postcss-nested')
  ]
}
```

But Astro did not load the `postcss-nested` plugin, so, I had to create a `snowpack.config.js` file and configure the plugins section with:

```js
module.exports = {
  plugins: [
    '@snowpack/plugin-postcss',
  ],
};
```

Is this worth to document under the [Styling & CSS](https://docs.astro.build/guides/styling) page, or there is a better way to enable this functionality?

**Comment by onlurking** [comment]
Just came across this [PostCSS Guide](https://github.com/snowpackjs/astro/blob/9c7f07aebdd7d762f2f86dd3752773ce851cde65/examples/snowpack/src/pages/guides/postcss.md) under `examples/snowpack/src/pages/guides`, would be cool to be a section under the Astro Styling page.

**Comment by jasikpark** [comment]
There might be some sections where it A. makes sense to link out to https://snowpack.dev and B. makes sense to duplicate the docs on snowpack.dev w/in the astro docs site!
