### ISSUE TITLE
💡 RFC: Log full snowpack errors to command line

### ISSUE THREAD

**Issue by kaleidawave** [snowpackjs/astro#950]
### Background & Motivation

Spent a while trying to figure out why my site wasn't building (from `astro build`). Was getting this error message: `[static] Not found /styles.css`.

Turns out I should have looked at the line above `[snowpack] Build Result Error: There was a problem with a file build result.` to realise there was a issue building *some part of the site*.

The issue was the `public/styles.css` stylesheet was malformed and wasn't being transpiled/compiled, thus the server could not *get* it. 

The error is thrown by snowpack's server and is displayed in the browser console logs. But for building there is no way to see this issue. This is especially important when on a CI server.

It would be good for snowpack errors like this to come through in the CLI logs! 

### Possible solutions

Astro should be able to intercept these kind of issues from snowpack. But I understand snowpack does not expose full issues yet:

https://github.com/snowpackjs/snowpack/blob/ab4ddec39c02dbd126e420e510fbda694408a3c5/snowpack/src/commands/dev.ts#L709-L719

It would be good to add *some* way for snowpack to expose full error messages. Probably through a CLI flag.

Then some receiver on the astro side could repeat these out.  

### Help make it happen!

- [ ] I am willing to submit a PR to implement this change.
- [X] I am willing to submit a PR to implement this change, but would need some guidance.
- [ ] I am not willing to submit a PR to implement this change.

**Comment by matthewp** [comment]
Did you run `astro --verbose`? It should log everything that snowpack does.

**Comment by jasikpark** [comment]
I think maybe their point is that Snowpack isn't providing descriptive enough errors regardless of whether they're in verbose mode, though I might be wrong.

**Comment by kaleidawave** [comment]
Hmm even with `--verbose` it still doesn't explain the problem in the same details as is coming through from snowpack's hmr-client script.

From CLI:

```
[17:24:53] [@snowpack/postcss-transform] transform() starting… [public\styles.css]
[access] /_snowpack/hmr-client.js
[dev] loaded /_snowpack/hmr-client.js [2ms]
[17:24:53] [snowpack] Build Result Error: There was a problem with a file build result.
[dev] loaded /styles.css [136ms]
[static] Not found /styles.css
```

From browser console:

```
[ESM-HMR] ...\styles.css
 Build Result Error: There was a problem with a file build result.
CssSyntaxError: ...\styles.css:4568:20: Unclosed string
```

**Comment by drwpow** [comment]
This is a known issue with Snowpack, and there are other bugs/RFCs here and in Snowpack dealing with errors that get swallowed. I know this doesn’t address your problem today, but this issue is front-of-mind for us and we’re fixing it right now with the [new compiler](https://twitter.com/astrodotbuild/status/1426219847671681024?s=20) (which we’ll have more details on soon!)

**Comment by jasikpark** [comment]
`astro build --super-duper-verbose` 😆

**Comment by natemoo-re** [comment]
I'm going to close this as `astro@next` (now in preview) will be moving from Snowpack to Vite and this issue focused on Snowpack behavior.

I think we'll likely still have to work on improving Vite error handling, but you're welcome to open a new issue for any problems you see there!
