### ISSUE TITLE
🐛 BUG: Built Astro site cannot be hosted at a subpath

### ISSUE THREAD

**Issue by simonwiles** [snowpackjs/astro#968]
### What package manager are you using?

npm

### What operating system are you using?

Linux

### Describe the Bug

Following up on #688 and #833, the fix in #856 means that `Astro.site` is now looking as expected, but hrefs in `index.html` are still written as `/_astro`, `/_astro_frontend`, and `/_snowpack`, so the built site can't be deployed in a subfolder (e.g. a `gh-pages` repo).  I would say #856 has fixed #688 but not #833.  (It's easy to fix by running `sed` over the generated `index.html`, of course).

### Steps to Reproduce

1. `npm init astro`
2. configure `buildOptions.site` in `astro.config.mjs` to an address with a subfolder (e.g. https://gh-user.github.io/repo-name)
3. ` astro build`
4. `grep --color=always /_{astro,snowpack} dist/index.html`

**Comment by matthewp** [comment]
Thanks! I think this is a relatively easy fix.

**Comment by simonwiles** [comment]
Thank you -- I'd hoped it would be (I did take a very quick look to see if I might fix it myself, but I just don't have the bandwidth at the moment).

**Comment by johanbook** [comment]
I am very excited about using Astro for Github pages but waiting for this issue to be resolved

**Comment by jasikpark** [comment]
> I am very excited about using Astro for Github pages but waiting for this issue to be resolved

I feel like it should work with a fully-qualified url? like `site: "https://hello.github.io/astro-site"` would probably work right? since this issue is for specifying `site: "/astro-site"` with no hostname attached?

**Comment by johanbook** [comment]
When specifying the site as a full url the `/_astro/` files do not respect the relative path so it's not possible to serve over say `https://hello.github.io/astro-site`

**Comment by FriendlyUser** [comment]
I would also like this issue to be resolved so I can use astro with github pages :D

**Comment by Bloodyaugust** [comment]
Bumping this as still an existing issue. I'd argue that #856 doesn't actually resolve #688, but I'll let it slide this time. 😉 I would love to be able to remove the `sed` step from my CI scripts when deploying to github pages!

**Comment by matthewp** [comment]
Renaming this to capture the larger issue here, as a lot of people run into similar problems.

**Comment by IanVS** [comment]
Seems like this could be closed by https://github.com/snowpackjs/astro/pull/1801, right?

**Comment by matthewp** [comment]
Yes! This is supported as of `next.5`. Please file new issues if you find problems there.
