### ISSUE TITLE
🐛 BUG: Cant import in svelte "ts" files. "ReferenceError: exports is not defined"

### ISSUE THREAD

**Issue by allanvobraun** [snowpackjs/astro#969]
### What package manager are you using?

yarn

### What operating system are you using?

linux ubuntu

### Describe the Bug

I'm using svelte with typescript in astro and this error appears when I try to import something. It only happens when I put lang='ts'.
![image](https://user-images.githubusercontent.com/52121195/127750478-a5cd1ab3-e7d1-485c-9d3f-444dd27dc333.png)
NavBar.svelte
![image](https://user-images.githubusercontent.com/52121195/127750482-5a839be8-09a3-420b-821f-2cef1c52307f.png)

### Steps to Reproduce

1. `git clone https://github.com/allanvobraun/pernonal-site.git`
2. `cd pernonal-site`
2. `git checkout bug-astrojs` 
3. `cd frontend`
4. `yarn install`
5. `yarn run build`
6. ERROR IN CONSOLE

### Link to Minimal Reproducible Example (Optional)

https://github.com/allanvobraun/pernonal-site.git

BRANCH: bug-astrojs

**Comment by allanvobraun** [comment]
Same as #403 
I think the setup should be done out of the box by astro

**Comment by jasikpark** [comment]
I would comment there to open that issue up again, I think

**Comment by matthewp** [comment]
Let's use #403 then.
