### ISSUE TITLE
🐛 BUG: Web font behavior is inconsistent with settings

### ISSUE THREAD

**Issue by brycewray** [snowpackjs/astro#970]
### What package manager are you using?

npm

### What operating system are you using?

macOS 11.5.1

### Describe the Bug

I have a font (Inter VF) in `/public/assets/fonts/` and it's getting seen OK by my SCSS, gets included in builds, etc. However, its visibility on the actual displayed page comes and goes. At initial launch of a page, only the system fonts appear. If I go into the browser inspector and toggle the `font-family` setting off and on, suddenly the desired font appears. A refresh makes it go away again. Thought maybe this was an oddity with my local setup, so I pushed it to a Vercel build and am seeing the same behavior there. The repo is [https://github.com/brycewray/astro-site](https://github.com/brycewray/astro-site) and a **very** rough-looking demo is up at [https://astro-site.vercel.app/](https://astro-site.vercel.app/). (I figured I'd try to get this sorted out before doing more on it.) Any help or advice appreciated!

### Steps to Reproduce

1. Put a web font file in `/public/assets/fonts/`.
2. Edit the appropriate CSS or SCSS to point to the font.
3. `npm run start`. 
4. In the resulting page, note that the font isn't being displayed.
5. Open the browser inspector and toggle the site's `font-family` off and on. This will cause the desired font to appear. But reload the page and it will go away again. 
6. `npm run build` to confirm that the font is getting built to `dist/assets/fonts/` and that the HTML build's CSS includes the proper `link` to the font.

This behavior appears in both dev and production modes.

### Link to Minimal Reproducible Example (Optional)

https://github.com/brycewray/astro-site

**Comment by jasikpark** [comment]
Would you mind adding a title to the issue?

**Comment by brycewray** [comment]
@jasikpark Sorry, forgot. Done.

**Comment by matthewp** [comment]
Hi @brycewray, I notice in your demo that the common.css is being played after the index.css file in the build output. I don't know if that's the issue or not, but would you mind try reordering those so that the common.css is first and see if that helps?

**Comment by brycewray** [comment]
@matthewp If you'd let me know how, sure. Right now, the layout for the home page (`/src/layouts/Base.astro`) has only the one link to `/style/index.css`, so how would I control it otherwise? Sorry for what I'm sure is a really dumb question.

**Comment by jasikpark** [comment]
Not a dumb question! (I don't know the answer tho)

**Comment by brycewray** [comment]
@matthewp @jasikpark Looking at the Vercel version I'm guessing it's because I'm using `@use` with my SCSS to bring in multiple SCSS files' content, based on what I see in the respective CSS outputs. Perhaps I should go down to just one SCSS file for testing purposes re this bug? Let me know if that sounds like it would help.

**Comment by matthewp** [comment]
@brycewray The common.css file is generated from the build I imagine. So in order to test if this is your issue you'll need to reorder the built HTML, not your source file. This would be an Astro bug if this is the problem, just trying to confirm that.

**Comment by jasikpark** [comment]
@matthewp is saying can you re-order the CSS `<link rel="stylesheet"/>`'s in the /dist folder to see if your problem is simply a bug in Astro

**Comment by brycewray** [comment]
I understand that part, but how do I keep Astro from undoing it at build time? Is there an undocumented `astro serve` command or something like that, or do you want me to install (e.g.) BrowserSync and run it on a manually re-ordered `/dist` folder?

**Comment by matthewp** [comment]
@brycewray Run it manually, yeah. You can use something like this: https://www.npmjs.com/package/serve. I'm assuming this problem is seeable locally and not just hosted.

**Comment by brycewray** [comment]
@matthewp OK, will do ASAP and let you know the results. Thanks.

**Comment by brycewray** [comment]
@matthewp Tried but now the output from `astro build` is showing only the common CSS in the resulting three HTML files, not the index.css as well, so not sure how to recreate.

(I removed my attempted collection-display page at `/src/pages/$posts.astro` because it would always crash the build due to other problems apparently of my own making. Uncertain if removing that page has changed anything about the CSS and ordering thereof.)

**Comment by brycewray** [comment]
Now running Astro 0.18.8 and am no longer seeing this odd behavior. Closing.
