### ISSUE TITLE
🐛 BUG: 'secure' option does not appear to enable https

### ISSUE THREAD

**Issue by jayphelps** [snowpackjs/astro#975]
### What package manager are you using?

npm (node v16.3.0)

### What operating system are you using?

Mac

### Describe the Bug

After generating a cert using [mkcert described in the docs](https://github.com/snowpackjs/astro/blob/9c7f07aebdd7d762f2f86dd3752773ce851cde65/examples/snowpack/src/pages/guides/https-ssl-certificates.md) I tried both the [`--secure` flag](https://github.com/snowpackjs/astro/blob/9c7f07aebdd7d762f2f86dd3752773ce851cde65/examples/snowpack/src/pages/reference/configuration.md) and the [`devOptions.secure` options](https://github.com/snowpackjs/astro/blob/9c7f07aebdd7d762f2f86dd3752773ce851cde65/examples/snowpack/src/pages/reference/configuration.md#devoptionssecure) but both do not appear to enable https (they appear inert.)

I do not receive any errors from the CLI. The browser is unable to connect via https: `This site can’t provide a secure connection.` However, the non-https does work, suggesting that indeed the options are just inert.

Apologies if this is user-error.

### Steps to Reproduce

1. `npm init astro` using template @example/framework-preact
2. `mkcert -install && mkcert -key-file snowpack.key -cert-file snowpack.crt localhost`
3. `npm start -- --secure` (or add `devOptions.secure` option to either `snowpack.config.js` or `astro.config.js`, neither do anything) Note that the CLI still says `http://localhost` not https
```
➜  astro-preact npm start -- --secure


> @example/framework-preact@0.0.1 start
> astro dev "--secure"

[11:36:21] [snowpack] Ready!
[dev server] Server started in 706ms.
[dev server] Local: http://localhost:3000/
[11:36:21] [snowpack] watching for file changes...
```
4. Navigate to `https://localhost:3000/` (or your configured port)
5. ???
6. Profit! (errrr I mean...see connection error in browser: `This site can’t provide a secure connection`)

**Comment by jayphelps** [comment]
Nevermind, I just realized those docs were specific to snowpack, but doing some digging astro appears to set up its down dev server manually and doesn't (yet) support https. 🚀

**Comment by benjaminwy** [comment]
I just went through the same steps myself before finding this issue. Is there any update on HTTPS support in dev? Or any recommendation on how to proceed?

**Comment by kitschpatrol** [comment]
I was able to get TLS working on `astro dev` via [vite-plugin-mkcert](https://github.com/liuweiGL/vite-plugin-mkcert) and some additions to the Astro config.

Steps involved in a fresh Astro project:

1. Add vite-plugin-mxcert

```sh
npm i -D vite-plugin-mkcert
```

2. Add the plugin to your Astro config, minimal functional example below:

```js
import { defineConfig } from "astro/config";
import mkcert from "vite-plugin-mkcert";

export default defineConfig({
  vite: {
    plugins: [mkcert()],
    server: {
      https: true,
    },
  },
});
```
