### ISSUE TITLE
🐛 BUG: Remote srcset are not ignored for getDistPath

### ISSUE THREAD

**Issue by vanhoofmaarten** [snowpackjs/astro#985]
### What package manager are you using?

npm

### What operating system are you using?

Mac

### Describe the Bug

Remote URLs in `srcset` aren't excluded from `getDistPath`
https://github.com/snowpackjs/astro/blob/c2d8cea41fc6209d7153d0f0c731fb5daddddbcf/packages/astro/src/build.ts#L301-L308

Unlike `src` remote URLs:

https://github.com/snowpackjs/astro/blob/main/packages/astro/src/build.ts#L296

This results in build error: 
`[build] /src/pages/index.astro: could not find "photo-1469854523086-cc02fe5d8800"`

### Steps to Reproduce

1. `npm init astro` using template portfolio
2. `cd portfolio`
3. `npm install`
4. (Optional) Currently, the SVGs in `src/components/Nav/index.jsx` are causing the following error: `SyntaxError: ... Namespace tags are not supported by default. React's JSX doesn't support namespace tags.` Place those SVGs between comments to work around this issue.

5. `npm run build`
6. `[build] /src/pages/index.astro: could not find "photo-1469854523086-cc02fe5d8800"`

**Comment by mmarkelov** [comment]
@vanhoofmaarten not sure that your PR fix this error. As I can see there is wrong attribute for last svg:
https://github.com/snowpackjs/astro/blob/c2d8cea41fc6209d7153d0f0c731fb5daddddbcf/examples/portfolio/src/components/Nav/index.jsx#L27

As it is react component it should be `xmlSpace` instead of `xml:space`

**Comment by vanhoofmaarten** [comment]
@mmarkelov I can confirm that the PR fixes the failing portfolio example build, apart from the `xml:space` error.
